- go.mod
- go.sum
- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/version.go
- pkg/p2p/p2p.go
- pkg/p2p/p2p_test.go
- pkg/p2p/streamtest/streamtest.go
- pkg/p2p/streamtest/streamtest_test.go
- pkg/pingpong/pingpong.go
- pkg/pingpong/pingpong_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
This PR is addressing a [comment](https://github.com/ethersphere/bee/pull/11#discussion_r376245337) by @acud about protocol and stream versioning . The simplification is beneficial, but it requires a special version matcher, which is very similar to libp2p's MultistreamSemverMatcher, but checks for the second to last element in the stream id instead, and also adds a debug log line in case of version parsing error, which is silently ignored in MultistreamSemverMatcher, resulting a lack of information while debugging.
This PR influences the implementation of https://github.com/ethersphere/bee/pull/11 and if merged, https://github.com/ethersphere/bee/pull/11 should be updated to reflect these changes.
> declare version per protocol, not per stream

- go.mod
- pkg/p2p/libp2p/libp2p.go
This PR changes which libp2p peerstore is used when constructing new libp2p Service. By default the DefaultPeerstore is called creating a new peerstore implicitly, which is never closed creating goroutine leaks in tests. Here, a dedicated peerstore is created and closed on Service.Close.
> add dedicated peerstore for every libp2p host

- go.mod
- go.sum
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/libp2p_test.go
This PR addresses a data race achieved when multiple websocket listeners are created, with websockets and tls security enabled.
Data race is on github.com/gorilla/websocket when multiple connects and disconnects are performed while using tls security. The default security in go-libp2p is secio, so this PR is suing only it to avoid data race.
Additionally, a few changes to options handling is added to libp2p.New constructor.
Data race
```
==================
WARNING: DATA RACE
Read at 0x00c0006b1be0 by goroutine 205:
github.com/gorilla/websocket.(*messageWriter).flushFrame()
/Users/janos/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:614 +0x7cd
github.com/gorilla/websocket.(*messageWriter).Close()
/Users/janos/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:724 +0xba …
```
> use only libp2p default security to avoid websockets data race

- pkg/p2p/libp2p/internal/handshake/handshake_test.go
- pkg/p2p/libp2p/internal/handshake/mock/peer.go
- pkg/p2p/libp2p/internal/handshake/mock/stream.go
TODO: 
- implement peer registry mocks insted of `PeerFinder`, move them to `libp2p/mock` and use them in `handshake_test`
- try to re-implement handshake tests to use `streamtest`
> Rename handshake mocks

- pkg/p2p/libp2p/connections_test.go
- pkg/topology/full/full.go
It looks to me that there was a small bug here. In the `AddPeer` function, the new was added to the map right away, which was making broadcast sending it to itself.
Also, I believe there was no need for disconnect in the tests because of the deferred cleanup function.
> Fix full connectivity add peer and test

- README.md
- cmd/bee/cmd/start.go
- pkg/addressbook/addressbook.go
- pkg/addressbook/inmem/inmem.go
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/peer.go
- pkg/debugapi/peer_test.go
- pkg/debugapi/status_test.go
- pkg/discovery/discovery.go
- pkg/discovery/mock/mock.go
- pkg/hive/hive.go
- pkg/hive/hive_test.go
- pkg/node/node.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/libp2p_test.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
- pkg/topology/full/full.go
- pkg/topology/full/full_test.go
- pkg/topology/mock/mock.go
- pkg/topology/topology.go
Points I tried to achieve:
1. `Discovery`, `Topology` interfaces not to know about multiaddr, the `addressbook` is used to fetch multiaddress in concrete implementations if needed
2. Extract business logic from `Hive` to rest of the system
3. Don't put specific logic into `libp2p`
4. Cover both known and connected peer added with/without connect 
I decided to do on a bit of a handler heavy approach, as I tried to do it with subscription and channels, and this seems much more simple. Wanted to cover full connectivity simple case, we can expand if needed.
Also, unrelated to the hive,  I did a few renaming along the way, @acud I renamed `GetterPutter` per Janoses comment on your PR that came a bit late, and I was guilty for the name  `GetterPutter`, I think `GetPutter` is more Go idiomatic. …
> Hive - Topology driver

- cmd/bee/cmd/start.go
- pkg/node/node.go
This PR removes libp2p.Options from node.Options in order to decouple them as libp2p.Options has to be changed (added depndencies) in node.NewBee. This makes node initialisation cleaner and completely independent on libp2p implementation.
> remove libp2p Options type from node Bee Options

- pkg/api/pingpong.go
- pkg/logging/logging.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/tracing_test.go
- pkg/pingpong/pingpong.go
- pkg/tracing/tracing.go
- pkg/tracing/tracing_test.go
This PR extends tracing package to add traceid to log messages if tracing context is available.
The usage example is in the pingpong package as well as in the newly added tests.
This change will allow correlation between logs and traces and their integration.
> add traceid log field if tracing context if available

- pkg/api/metrics.go
- pkg/debugapi/metrics.go
- pkg/logging/metrics.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/p2p/libp2p/metrics.go
- pkg/pingpong/metrics.go
This PR improves how metrics names are specified:
- adds a global Namespace which is currently `bee` as the prefix to all service metrics
- adds package local subsystem variable
This PR is not implementing an option to override Namespace variable, as it is not required now.
This PR is mostly related to easier metrics management with prefixes, by the infrastructure.
> add metrics namespace

- pkg/debugapi/debugapi_test.go
- pkg/debugapi/export_test.go
- pkg/debugapi/p2p.go
- pkg/debugapi/p2p_test.go
- pkg/debugapi/router.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
This PR is adding a new endpoint to debug api to expose LibP2P MultiAddresses. This is mainly needed for infrastructure automation to provide addresses that other nodes can connect to.
If the debug api is enabled a GET request to `http://localhost:6060/addresses` should return a list of addresses that node is listening to, for example:
```json
{
"addresses": [
"/ip4/127.0.0.1/tcp/7071/p2p/16Uiu2HAmTBuJT9LvNmBiQiNoTsxE5mtNy6YG3paw79m94CRa9sRb",
"/ip4/192.168.0.101/tcp/7071/p2p/16Uiu2HAmTBuJT9LvNmBiQiNoTsxE5mtNy6YG3paw79m94CRa9sRb",
"/ip4/127.0.0.1/udp/7071/quic/p2p/16Uiu2HAmTBuJT9LvNmBiQiNoTsxE5mtNy6YG3paw79m94CRa9sRb",
"/ip4/192.168.0.101/udp/7071/quic/p2p/16Uiu2HAmTBuJT9LvNmBiQiNoTsxE5mtNy6YG3paw79m94CRa9sRb",
"/ip6/::1/tcp/7071/p2p/16Uiu2HAmTBuJT9LvNmBiQiNoTsxE5mtNy6YG3paw79m94CRa9sRb", …
```
> add debugapi /addresses endpoint to expose libp2p mutiaddresses

- pkg/addressbook/inmem/inmem.go
- pkg/hive/hive.go
- pkg/node/node.go
- pkg/p2p/libp2p/libp2p.go
- pkg/topology/full/full.go
* Bootnodes init in parallel, and does not fail if bootnode connect fails
* multiaddr creation fix in incoming connection in `libp2p`
@acud, @janos  
When testing I believe I found a problematic behavior which I believe is because the `AddPeer` handler is not async, or at least part of it. Imagine a scenario where you have nodes 0..10, and node 1 nodes about all other nodes. This can happen:
1. Node 2 connects to node 1
2. Node 1 will start to broadcast this node to all other nodes waiting for them to finish connect in order to finish the handle
3. Also, other nodes, will broadcast to other known nodes, in the handler, after connect
Every broadcast hive message is waiting for other side to close the stream, to finish communication, and this could result in lots of waits and timeouts. 
I …
> bootnode init improvement + libp2p incoming connection addr fix

- go.mod
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bzzchunk.go
- pkg/api/bzzchunk_test.go
- pkg/api/router.go
- pkg/node/node.go
- pkg/storage/mock/storer.go
- pkg/storage/mock/storer_test.go
- pkg/storage/store.go
This PR adds functionality to upload and download a chunk from `bee`.
Right now chunks are stored in-memory using a mock `storage.Storer` implementation.
Chunks are "verified" only through the test harness - i.e. it is ready to accept flows that would be generated from errors while putting the chunk, but does not expose which errors occurred (this will be done once the necessity will be shown).
Once localstore gets imported we can switch to that as storage engine. Same for BMT and chunk verification.
cc @jmozah @nolash
> api, storage: add http interface to accept chunks

- .golangci.yml
This PR is raising golangci-lint timeout from 1m to 10m since it is timing out on github actions.
> set golangci-lint timeout to 10m

- pkg/logging/metrics.go
- pkg/pingpong/metrics.go
This PR fixes to metrics names that were incorrectly changed in previous PR.
> fix metrics names in logging and pingpong

- pkg/p2p/p2p.go
This PR makes Debug API /peers endpoint response a bit prettier by using not capitalised json object key.
> add p2p.Peer json tag to Address field as it is returned by debug api

- pkg/p2p/libp2p/headers_test.go
- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/p2p/libp2p/libp2p.go
I believe this one is caused by https://github.com/ethersphere/bee/pull/65. I did not put peer registry synchronization in the right place. It was after the stream was already closed, resulting in possibly late addition to peer registry in retrospect to the other side of the stream.
To reproduce add  `time.Sleep` of 1s before ln 195 in `libp2p.go` on the code from master. What happens iis that stream handler returns not found from peer registry, and this error log is not visible in tests.  This should result in:
```
--- FAIL: TestHeaders (0.35s)
headers_test.go:57: send headers: read message: stream reset
--- FAIL: TestHeaders_empty (0.31s)
headers_test.go:106: send headers: read message: Application error 0x0
--- FAIL: TestHeadler (0.15s)
headers_test.go:170: send headers: read message: …
```
> Flacky tests - NewStream

- pkg/hive/hive_test.go
- pkg/p2p/libp2p/libp2p_test.go
- pkg/p2p/protobuf/protobuf_test.go
This is an attempt of an easy fix, and should have some performance improvement. On my computer, around 2x for libp2p and 5x for protobuf. The approach was to not change tests too much, but keep same  kind of tests and reduce timeouts, and granularity. If we want more improvements, I think we would need to go to different kinds of tests, or simply remove some tests.
Maybe we could reduce number of tests with timeouts.
Also, I changed a bit protobuf tests, as I believe this to be more accurate so it works a bit better with lesser values.
@acud Regarding your question for additional bug you found, I could not reproduce it locally or on github so far, maybe that timeout is less likely now.
> Tests time improvement

- pkg/addressbook/addressbook.go
- pkg/hive/hive_test.go
- pkg/node/node.go
The different way would be to try to connect to some `limit` amount of nodes, and add them to a topology driver already connected. This makes sense if we don't want to let topology driver choose which and amount of nodes connected when node is starting.
> Init topology driver

- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
- pkg/topology/full/full.go
- pkg/topology/full/full_test.go
- pkg/topology/topology.go
As a requirement of #49, we need to request a chunk from the closest peer that we're connected to.
This functionality was already implemented as part of #97, but since the functionalities are overlapping and are exactly the same - I am getting rid of the separate `ChunkPeerer` and `SyncPeerer` interfaces  in favor of just one `ClosestPeerer` interface.
> [bee #49]: get closest peer

- .github/workflows/go.yml
- Makefile
This PR is reintroducing race detector in tests in github actions but only for ubuntu and macos, and windows is running tests without the race detector. This is due to issue explained in the commend in workflow file.
> disable race detector on windows github actions

- pkg/localstore/migration_test.go
a minor nuisance, but when searching the build log for failures when something breaks, we look for the `fail` keyword and these tests always come up first. now they won't.
> rename migration tests

- pkg/debugapi/chunk.go
- pkg/debugapi/chunk_test.go
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/router.go
- pkg/node/node.go
- pkg/storage/mock/storer.go
- pkg/storage/mock/storer_test.go
this PR adds a debug api endpoint to query whether a node has a chunk. returns `404`, `200`, or `400` if the address was corrupt.
needed for syncing integration testing
> add debug api to expose localstore Has

- pkg/p2p/libp2p/internal/breaker/breaker.go
- pkg/p2p/libp2p/internal/breaker/breaker_test.go
- pkg/p2p/libp2p/internal/breaker/export_test.go
- pkg/p2p/libp2p/libp2p.go
Please check linked issue for spec. 
This is a "basic" implementation of connection breaker with exponential back-off. Basically, it is tracking down consequent failed calls in a provided time interval. When the limit is reached, the breaker closes for some time in exponential back-off manner. 
The current implementation treats all errors in the same way. We can add specific error matching, if needed, in the future.
The implementation is very opinionated and I am aware that  it can be done in many different ways, so feel free to LMNWYT :)
TODO: 
1. I have added only dummy usage to `libp2p` as I would like to test it and add some `libp2p` tests in another PR 
2. Use `Breaker` in connectivity driver as well, also in another PR
> Connection Breaker

- .github/workflows/beekeper.yaml
Sometimes it happens that kube-system ns needs more time to bootstrap and tests to fail.
Added checks for kube-system ns
> fix k3d initialization

- pkg/api/bzz.go
- pkg/api/bzz_test.go
- pkg/api/router.go
This PR fixes the issue described in https://github.com/ethersphere/bee/issues/151.
The problem is in expected chunk data that needs to be passed to the storer. A chunk should be put with its span data prepended in bzzUploadHandler, and returned without it in bzzGetHandler. Current implementation assumes that span should not be stored in localstore and with that assumption validator panics on data that are less than 8 bytes long, as it does not do bounds check.
This PR also removes the need to have a trailing slash on /bzz endpoint.
To reproduce the error do on master code `curl --data-binary '12345' localhost:8080/bzz/`, it will produce a panic.
To validate the fix in this branch `curl --data-binary '12345' localhost:8080/bzz`, it should return a valid response with a hash value.
fixes …
> fix api /bzz post endpoint

- .github/workflows/coverage.yml
- .github/workflows/go.yml
Make github actions execution time faster, only test for go1.14 and on pull_request event
> remove push trigger and go1.x from actions

- .githooks/pre-push.bash
- .github/workflows/go.yml
- .golangci.yml
- Makefile
- pkg/p2p/libp2p/internal/breaker/breaker.go
- pkg/pushsync/metrics.go
- pkg/pushsync/pushsync.go
- pkg/swarm/swarm.go
- pkg/validator/validator_test.go
This PR adds more linters to golangci-lint suite to improve automatic static checking.
This PR also fixes some minor the problems found by new linters.
It updates the Go GitHub Actions workflow not to use autocrlf to avoid false positive gofmt errors on windows when gofmt is changing line endings.
It adds `linter` Makefile rule to install a specific version of golangci-lint as its master appears not to be stable.
It changes pre-push githook to use `linter` rule.
> add misspell, gofmt and unconvert linters

- pkg/node/node.go
- pkg/pusher/metrics.go
- pkg/pusher/pusher.go
- pkg/pusher/pusher_test.go
- pkg/pushsync/metrics.go
- pkg/pushsync/mock/mock.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
- pkg/storage/store.go
- Moved chunksWorker in to pusher package
- Made pushsync protocol dummy and it handles only one put chunk using a restricted storer interface
- Added pushed to node start and shutdown
Refer https://github.com/ethersphere/bee/issues/159
> Pusher: Move push sync logic in to pusher

- pkg/kademlia/pslice/export_test.go
- pkg/kademlia/pslice/pslice.go
- pkg/kademlia/pslice/pslice_test.go
- pkg/topology/test/helper.go
- pkg/topology/test/helper_test.go
- pkg/topology/topology.go
this PR introduces a basic data structure (therein called `pslice`) which is essentially a slice which maintains indexes for POs, that is to index the different proximity order of peers that we populate in the main `peers` slice.
needed by #155 
inadvertently related to #47
> kademlia, topology: introduce pslice

- .github/workflows/go.yml
- Makefile
This is a temporary solution to fix build failures in golangci-ling version >= 1.25.0 doe to breaking changes in gomodguard v1.1.0:
```
go/pkg/mod/github.com/golangci/golangci-lint@v1.26.0/pkg/golinters/gomodguard.go:47:36: unknown field 'k' in struct literal of type gomodguard.BlockedModule
go/pkg/mod/github.com/golangci/golangci-lint@v1.26.0/pkg/golinters/gomodguard.go:51:43: cannot use m (type gomodguard.BlockedModule) as type map[string]gomodguard.BlockedModule in append
```
> downgrade golangci-lint to v1.24.0

- pkg/debugapi/router.go
This PR fixes the issue with DebugAPI router serving pprof profiles. Currently profiles such as goroutines is not accessible as gorilla mux Handle was used incorrectly (expecting the behaviour as http.ServeMux). Here, pprof.Index is configured correctly to serve index and also profiles under it.
> fix debugapi pprof profiles router

- pkg/p2p/error.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/protocols_test.go
Added missing `DisconnectError` handling test case to `libp2p`.
> libp2p: DisconnectError test

- pkg/intervalstore/intervals.go
- pkg/intervalstore/intervals_test.go
- pkg/intervalstore/store_test.go
as a preparation step for commencing work on pull sync, we need to import the interval store code from old swarm.
test cases are not ideal since some of them inject some initial state into the interval by changing the field and not by constructor. @janos should we change this?
> import interval store code from swarm

- Makefile
- README.md
This PR adds a convenient Makefile rule to generate Go code from protobuf files and also to half-automate tools installation.
> add protobuf Makefile rule

- pkg/debugapi/export_test.go
- pkg/debugapi/topology.go
- pkg/debugapi/topology_test.go
- pkg/discovery/mock/mock.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/node/node.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/peer.go
continued work on kademlia following #155.
this PR:
- implement `ClosestPeer` so that retrievals and push sync will work on kademlia
- improve debug api for topology, so that the actual kadmlia json string is a native JSON, not an escaped string
- hook up kademlia to be the default topology, instead of `full`
- clean up some of the connect logic in kademlia and pull it to a separate method, to clean up the `manage` loop logic
- add peer broadcasting functionality upon connecting to a peer
- add `Connected` hook on kademlia
- add peer announcement on dial-in
related to #47 #56 usw..
> [bee #47, #56] integrate kademlia instead of full driver

- Dockerfile
Download modules in separate layer for later reuse if modules didn't updated
> enable modules caching in separate layer during docker build

- pkg/localstore/gc_test.go
- pkg/localstore/localstore.go
- pkg/localstore/localstore_test.go
- pkg/localstore/mode_get.go
- pkg/localstore/mode_get_multi.go
- pkg/localstore/mode_get_multi_test.go
- pkg/localstore/mode_put.go
- pkg/localstore/mode_set.go
- pkg/localstore/mode_set_test.go
- pkg/localstore/pin.go
- pkg/localstore/pin_test.go
- pkg/localstore/subscription_pull.go
- pkg/shed/db.go
- pkg/shed/db_test.go
- pkg/shed/example_store_test.go
- pkg/shed/field_string.go
- pkg/shed/field_struct.go
- pkg/shed/field_uint64.go
- pkg/shed/index.go
- pkg/shed/index_test.go
- pkg/shed/schema.go
- pkg/shed/vector_uint64.go
This PR removes extensive logging next to returning the error in shed and properly annotates these errors so that their path is known. The consequence is that error checking has to be done with errors.Is function, which is also changed in this PR. This PR is based on the bad user experience when uploading and downloading chunks results with error messages that are not clear and not needed. There is no need to log errors in shed as they are all returned, so logger is removed, just as it does not exist in the swarm project code.
> annotate errors in shed

- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/p2p/libp2p/internal/handshake/handshake_test.go
- pkg/p2p/libp2p/libp2p.go
@zelig 's comments from: https://github.com/ethersphere/bee/pull/196.
Moved handshake tests to single function to re-use data init.
> Binary encoding of networkID

- pkg/localstore/export_test.go
- pkg/localstore/gc_test.go
- pkg/localstore/index_test.go
- pkg/localstore/localstore_test.go
- pkg/localstore/mode_get_multi_test.go
- pkg/localstore/mode_get_test.go
- pkg/localstore/mode_has_test.go
- pkg/localstore/mode_put_test.go
- pkg/localstore/mode_set_test.go
- pkg/localstore/pin_test.go
- pkg/localstore/retrieval_index_test.go
- pkg/localstore/subscription_pull_test.go
- pkg/localstore/subscription_push_test.go
Use testing.Cleanup function in localstore tests to simplify cleanups. It includes slight changes in respect to defer statements and new Cleanup function calls to ensure the right order of test hooks related calls to avoid data races.
> use testing.Cleanup in localstore tests

- pkg/addressbook/addressbook_test.go
- pkg/api/api_test.go
- pkg/api/bzz_test.go
- pkg/api/bzzchunk_test.go
- pkg/api/pingpong_test.go
- pkg/debugapi/chunk_test.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/p2p_test.go
- pkg/debugapi/peer_test.go
- pkg/debugapi/pin_test.go
- pkg/debugapi/status_test.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/headers_test.go
- pkg/p2p/libp2p/libp2p_test.go
- pkg/p2p/libp2p/protocols_test.go
- pkg/p2p/libp2p/tracing_test.go
- pkg/shed/db_test.go
- pkg/shed/field_string_test.go
- pkg/shed/field_struct_test.go
- pkg/shed/field_uint64_test.go
- pkg/shed/index_test.go
- pkg/shed/schema_test.go
- pkg/shed/vector_uint64_test.go
- pkg/statestore/leveldb/leveldb_test.go
- pkg/statestore/mock/store_test.go
- pkg/statestore/test/store.go
This PR is a continuation of https://github.com/ethersphere/bee/pull/203 where testing.Cleanup is used, but only in localstore packag. Here, other cases are addressed.
> use testing.Cleanup in test instead deferred explicit cleanup function

- .github/workflows/beekeeper.yaml
bee-debug endpoint needed to check when service is up missing from /etc/hosts
> add bee-debug endpoint to /etc/hosts for beekeeper test

- pkg/debugapi/export_test.go
- pkg/debugapi/router.go
- pkg/debugapi/topology.go
- pkg/debugapi/topology_test.go
- pkg/discovery/mock/mock.go
- pkg/kademlia/doc.go
- pkg/kademlia/export_test.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/kademlia/pslice/pslice.go
- pkg/kademlia/pslice/pslice_test.go
- pkg/node/node.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/libp2p_test.go
- pkg/p2p/libp2p/peer.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
- pkg/topology/full/full.go
- pkg/topology/mock/mock.go
- pkg/topology/topology.go
This PR aims to introduce a simple kademlia implementation into the codebase.
It wires in the `PSlice` type that was merged previously (#169), as a type that manages and indexes a slice of peers by their proximity order.
This PR handles:
1. Implementation of depth calculation for kademlia
2. Implementation of basic connection management that bootstraps a kademlia topology
3. Debug API endpoint for retrieving a JSON output of the current topology
4. Integration into libp2p abstraction layer for peer connect/disconnect notification
5. Dummy `binSaturated` implementation. Right now checks for a constant bin size, but is built to accommodate for more complex operations, such as check square address gaps and so on.
6. implement `ClosestPeer` so that retrievals and push sync will work on …
> [bee #47, #56]: kademlia phase 0+1

- pkg/debugapi/topology.go
This PR adds a content type header that some clients may relay on. Currently beekeeper requires it.
> add content-type header to debug api /topology endpoint

- pkg/p2p/streamtest/streamtest.go
- pkg/pushsync/pushsync_test.go
Adding a noop middleware to recorder makes the usage of empty middleware definitions unnecessary, this cleans up some of the tests that use this component actively.
> streamtest: add noop middleware to recorder

- pkg/netstore/netstore.go
- pkg/retrieval/retrieval.go
This PR adds more informative information to errors in the netstore and retrieve protocol so that we can debug retrievals.
related to https://github.com/ethersphere/bee/issues/230
> netstore, retrieval: wrap errors

- pkg/swarm/swarm.go
adding a const for hash size in bytes so we can reuse across packages
> swarm: add address hash size

- pkg/kademlia/kademlia.go
This PR prevents disconnects with peers when a second connection try is attempted. This error should not disconnect peer. This fix is addressing the problem described in https://github.com/ethersphere/bee/issues/219 by not disconnecting them.
But there is still problem with false reports on disconnections in the topology endpoint. Some peers (only bootnode noticed so far by me) are listed as disconnected even they are not, according to the /peers endpoint list and also according to the lack of logs that disconnection happened, and also pingpong protocol works with the peer listed as disconnected in bins. This is another problem related to the kademlia, not connectivity.
This fix can be tested by creating a cluster with multiple nodes and validating that there are no disconnected peers in …
> handle already connected peer gracefully in kadmelia connect

- pkg/debugapi/debugapi.go
- pkg/debugapi/peer.go
- pkg/kademlia/kademlia.go
- pkg/node/node.go
This PR fixes some bugs that were observed on the clusters and on local testing, namely inconsistencies of peers shown as disconnected while being in fact connected.
A short explanation of the changeset with its repercussions:
- `debugapi/peer.go` - the `AddPeer` method on kademlia was called _after connecting to the peer_. this is legacy from the full topology implementation and is incorrect in this case. The resulting behavior would be that the peer would be connected to, then would be added to the _known_ peers list, instead of both _known and connect_ lists. So the kademlia would try to iterate in `manage` but the peer would never show up in the known peers list, so would never show up in the iterator.
- it could be, that under certain circumstances that this peer would be gossiped to …
> kademlia, debugapi, node: fix connection issues

- pkg/debugapi/export_test.go
- pkg/debugapi/pin.go
- pkg/debugapi/pin_test.go
- pkg/debugapi/router.go
- pkg/jsonhttp/jsonhttptest/jsonhttptest.go
- pkg/localstore/pin.go
- pkg/localstore/pin_test.go
- pkg/storage/mock/storer.go
This PR addresses some of the issues that were discovered during the Debug API review that I did with @metacertain.
- listPinnedChunks hander is exposing types that are outside of the debugapi package making it possible that a struct changed in different package can result in the api response change
- listPinnedChunks is changed to return the json object, instead the list, making it more extensible in the future without the need for breaking changes
- some of the bad request responses are change to internal server error as they are not related to the user input
- getPinnedChunk is added to properly check if the chunk is pinned, as the current implementation did not use the address parameter at all
- tests are adjusted to explicitly check for types, not json strings
- an explicit and …
> improve list and get pinned chunks api endpoints and tests

- pkg/debugapi/router.go
- pkg/logging/http_access.go
This PR implements a handler that allows setting log level explicitly for http endpoints and uses that to suppress log messages for debug api /metrics, /readiness and /health endpoints.
> suppress log messages for debug api metrics, health and readiness

- pkg/debugapi/peer.go
- pkg/debugapi/peer_test.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/node/node.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
- pkg/topology/full/full_test.go
While reverting changes in bzz address PR I forgot to fix `debugapi` part as well, which needed a slight change of `p2p.Connect` method as well.
> Fix bzz addr in debugapi

- pkg/validator/validator.go
Validator attempted to re-use same hasher in concurrent operations. That was silly. Who would write such a silly thing? Oh, wait. It was me.
Resolves https://github.com/ethersphere/bee/issues/241
> Fix deadlock in concurrent uploads

- pkg/pusher/pusher.go
- pkg/pusher/pusher_test.go
bzz api does not implement splitter and tags yet, but pusher assumed that tags are present for all addresses and fails because of this. This PR put skips this condition until the bzz api implements splitter and then tags.
fixes https://github.com/ethersphere/bee/issues/258
Note: This should be temporary to make cluster tests pass... after bzz api implements splutter and tags, we should remove this guard fix.
> Guard pusher against tags that are not present

- .github/workflows/beekeeper.yaml
- pkg/api/bzzchunk.go
- pkg/api/bzzchunk_test.go
- pkg/api/tag_test.go
- pkg/debugapi/pin_test.go
This PR is fixing /bzz-chunk endpoint in relation with the validator. Similar as the previous fix for /bzz endpoint, it puts the chunk data with span, as required by validator, and serves it without the span on download. This issue was discovered while developing beekeeper test that uploads the chunk by calculating it hash as required for this endpoint.
> Fix bzz chunk api

- pkg/localstore/localstore.go
In the PR that introduced db capacity an error was made to call `Info` instead `Infof` resulting badly formatted log message `INFO[2020-06-05T15:55:32+02:00] setting db capacity to: %v5000000`. I have also adjusted the log message to a statement.
> fix db capacity log message

- pkg/api/tag_test.go
also, a mistake in one of the comparators of the test was discovered (in the condition that is failing/flaking)
> api: more info for failing test

- pkg/p2p/libp2p/libp2p_test.go
We have experienced slowdowns on CI and timeouts on connectivity tests in libp2p packages. Most frequently timeouts in TestConnectDisconnectOnAllAddresses. After some profiling, I have found that the default RSA key generation is the slowest part of that test and by using Secp256k1 the test is ~2x faster in average. This is an attempt to see if the test will not timeout, but in general the speedup is beneficial.
> set Secp256k1 private key in libp2p test services instead temp RSA

- pkg/pusher/pusher.go
- removed continuous printing of pusher log when there is only one connected node
> fixed redundent debug statements

- pkg/api/bzzchunk.go
- pkg/api/router.go
- pkg/api/tag.go
- pkg/api/tag_test.go
- pkg/pusher/mock/mock.go
In bzz-api tag.address field is set to the chunk that arrives. It is usually used to represent the root chunk in tagging. since this does not fit here, i have removed assigning the received address to the ta.address field.
Also removed the api which gets the tag address and gives back the tag details.
> remove tag address field for bzz-chunk api

- pkg/localstore/gc.go
- pkg/localstore/gc_test.go
- pkg/localstore/localstore_test.go
- pkg/localstore/mode_get.go
- pkg/localstore/mode_put.go
- pkg/localstore/mode_set.go
**Problem**: Sometime a pinned chunk gets GCd and is not available in `localstore`. This was not simulatable. It once occurred in FairData setup and now in @santicomp2014 's setup in global pinning. 
**Fix**: Even though we don't know the exact scenario when this happens, a code walk through found out that we are not checking for `pinIndex` presence when a chunk is added in `gcIndex`. We found 4 such places that are missed out and fixing it in this PR.
> Local pinning fix

- .github/workflows/beekeeper.yaml
- cmd/internal/file/io.go
- pkg/api/bytes.go
- pkg/api/bytes_test.go
- pkg/api/chunk.go
- pkg/api/chunk_test.go
- pkg/api/export_test.go
- pkg/api/router.go
- pkg/api/tag_test.go
- pkg/debugapi/pin_test.go
This PR addresses some of the points discussed about API design for the alpha release.
- [renames](https://hackmd.io/fGoeV1n2QficZwuHnYmb-g#Chunk-proposal-by-Louis) `bzz-chunk` endpoint to `chunks`
- [renames](https://hackmd.io/fGoeV1n2QficZwuHnYmb-g#Raw-content) `bzz-raw` endpoint to `bytes`
- adds support for `/v1` [prefix to endpoints](https://hackmd.io/fGoeV1n2QficZwuHnYmb-g#Translation-of-versioned-paths)
- [renames](https://hackmd.io/fGoeV1n2QficZwuHnYmb-g#POST-v1bytes) `bzz-raw` (now `bytes`) POST json response field from `hash` to `reference`
- updates log message accordingly with the changes above
- updates tests to work with the new endpoints
This PR does not address points in [Other section](https://hackmd.io/fGoeV1n2QficZwuHnYmb-g#Other). That will be done in the followup PR. …
> api bzz-chunk and bzz-raw rename

- pkg/kademlia/kademlia.go
- pkg/kademlia/pslice/pslice_test.go
- pkg/localstore/localstore.go
- pkg/localstore/subscription_pull_test.go
- pkg/swarm/proximity.go
- pkg/swarm/proximity_test.go
- pkg/swarm/swarm.go
This PR adjusts the Proximity function so that there is a total number of 16 bins, not 17, which is kind of odd. This goes inline with the current kademlia implementation. Also the return value is set to uint8 to avoid unnecessary type conversions, and the test is now using explicit binary notation which were added after this test have been written.
> proximity function adjustments

- pkg/localstore/gc_test.go
Local pinning fix introduced a testcase TestPinSyncAndAccessPutSetChunkMultipleTimes. Some times in coverage report the test fails because few chunks that we are bombarding might have been GC'd before they are accessed . 
This fix is to ignore those errors which are valid cases.
> Fix one of the test case in local pinning

- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/protocols_test.go
wrong handlers are called when multiple stream descriptors are defined
> shadow stream descriptor in libp2p

- cmd/bee-join/main.go
- cmd/internal/file/io.go
This small feature add makes it possible to `bee-join` from the same on-disk format of chunk that `bee-split` creates.
> Add join from chunks on disk (symmetric to bee-split)

- pkg/api/file.go
This is a suggestion how to handle the case where multipart part does not contain Content-Length value. It is the same approach as we have in the Swarm https://github.com/ethersphere/swarm/blob/master/api/http/server.go#L493.
> handle no content-length in multipart part bzzFileUploadHandler

- pkg/api/export_test.go
- pkg/api/router.go
- pkg/debugapi/export_test.go
- pkg/debugapi/router.go
- pkg/debugapi/tag.go
- pkg/debugapi/tag_test.go
- pkg/tags/tag.go
- pkg/tags/tags.go
This PR moves /bzz-tag endpoints to Debug API /tags as noted in https://hackmd.io/fGoeV1n2QficZwuHnYmb-g?view#Other, and updated per https://hackmd.io/fGoeV1n2QficZwuHnYmb-g?view#new-tags-api-design-after-alpha. Total increment feature is not implemented as it would require more changes (a separate i), but some improvements to the code is done.
The purpose of this change is not to expose the tags api for alpha release. It will be moved to the main API for next releases.
> move tags endpoints to debug api

- pkg/logging/http_access.go
This PR fixes the panic observed on making a request to debug api pprof /debug/pprof/profile endpoint.
responseLogger needs to implement a CloseNotifier interface as required by github.com/gorilla/handlers.compressResponseWriter.
It adds a linter ignore as http.CloseNotifier is considered deprecated.
```
http: panic serving [::1]:63564: runtime error: invalid memory address or nil pointer dereference
goroutine 41 [running]:                      
net/http.(*conn).serve.func1(0xc0002defa0)   
net/http/server.go:1772 +0x139              
panic(0x1a16940, 0x25360e0)                  
runtime/panic.go:975 +0x3e3                 
github.com/gorilla/handlers.(*compressResponseWriter).CloseNotify(0xc0000c6e10, 0x1de1de0) 
<autogenerated>:1 +0x2f …
```
> implement http.CloseNotifier to responseLogger for gorilla compress

- pkg/pusher/pusher.go
This PR fixes a name for tags.ErrNotFound which changed between to PRs tested on CI, both passed, but when merged the error type name change form one to another.
> fix the reference to tags.ErrNotFound error type

- pkg/api/chunk.go
This PR removes "X-" prefix in served http headers. This was suggested by @metacertain as no longer suggested practice. https://hackmd.io/fGoeV1n2QficZwuHnYmb-g#Other
> remove experimental -x http header prefix

- pkg/api/bytes.go
- pkg/api/export_test.go
- pkg/api/file.go
- pkg/api/file_test.go
- pkg/api/router.go
This PR adds a support to upload a file in its binary form, get its `content-type` from request header and name from `name` query parameter. This is done beside the regular multipart/form-data upload.
https://hackmd.io/fGoeV1n2QficZwuHnYmb-g?both#POST-v1files-typestringamp-namestring
- fileUploadHandler is reorganized to support binary data uploads, content type detection from header and filename detection from query parameter (Content-Disposition is only response header and is not used in requests)
- splitUpload returns only address to simplify its usage
- splitUpload removes requirement for io.ReadCloser as Close is never used, just io.Reader is required
- bytesUploadHandler structure is more consistent with other handlers
- minor adjustments to exported variables
- existing tests are …
> support binary upload to api files endpoint

- cmd/bee/cmd/start.go
- pkg/localstore/localstore.go
I believe that we should never use the metric "chunks" when we communicate about database size to our users, however I can image that doing such a change is debated (as @mortelli convincingly argued, in some tests it is good to have fine-grained control over the gc with chunks as metric) and it might be too big of a change for now. 
At a minimum, we should give the user a translation from db capacity (as measured in chunks) to db capacity (measured in bytes).
> Added translation from chunks to bytes in help and log

- cmd/bee/cmd/start.go
- pkg/node/node.go
- pkg/p2p/libp2p/export_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/static_resolver.go
- pkg/p2p/libp2p/static_resolver_test.go
This PR adds the option to specify a specific nat IP and/or port. This option is needed for setups like our kubernetes cluster. This option has similar functionality as --nat option in swarm, just it works with multiaddresses.
> add option to specify static nat address

- pkg/kademlia/kademlia.go
- pkg/kademlia/pslice/pslice.go
Change `pslice` to use `RWMutex` for read operations as `kademlia.connectedPeer` is used across different components and the `manage` loop might slow other components down.
> kademlia: pslice rwmutex

- pkg/addressbook/addressbook.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
The basic idea is to stop infinitely retrying  and/or clean `addressbook` from the non-connectable nodes. This is not a full solution, as we would probably like to implement some kind of connection service/component to be used to make the code more reusable and less error prone, as we discussed when talking about handlers as well. This is just a quick fix, and if it works well, we can extract it to this kind of component and use it across  bee in a uniform way.
Please check  linked issue for additional details
> Clean addressbook after failed connection attempts

- pkg/node/node.go
- pkg/p2p/discover.go
This PR improves logs when calling dns discover and logs correct address, not the provided bootnode.
> improve discover log messages and errors

- pkg/kademlia/kademlia.go
- pkg/node/node.go
This is just a cleanup of the not so useful log messages.
I also included one log fix in kademlia.
> suppress p2p.ErrAlreadyConnected log when connecting to bootnodes

- pkg/hive/hive.go
- pkg/kademlia/kademlia.go
- pkg/p2p/libp2p/libp2p.go
- pkg/topology/full/full.go
This PR properly disconnects peers on errors and propagates context instead creating a new ones.
> full close timeout handle

- pkg/addressbook/addressbook.go
- pkg/addressbook/addressbook_test.go
- pkg/debugapi/peer_test.go
- pkg/hive/hive.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/topology/full/full.go
This PR addresses 2 minor issues:
1. In order to check the result of `addressbook.Get()` one must compare received error with `storage.NotFound` error, which is not in the same package and should not be used to check the result of the addressbook get function.
2. The returned `BzzAddress` is copied creating minor, but unnecessary overhead.
3. Makes the user of fetched `BzzAddress` pay attention to pass the address of BzzAddress on many places where it is convenient, such where  `Equal(), String()` methods are used and their appropriate interfaces
> Addressbook get  - not found

- pkg/p2p/libp2p/headers.go
Some nodes may not behave well and not send data back while waiting for them. This PR adds a timeout for that case:
```
goroutine 4195 [select, 17 minutes]:
github.com/ethersphere/bee/pkg/p2p/protobuf.Reader.ReadMsgWithContext(0x7f3b38de6b70, 0xc001c68f80, 0x127fee0, 0xc000198300, 0x127a620, 0xc001d08280, 0x0, 0x0)
github.com/ethersphere/bee/pkg/p2p/protobuf/protobuf.go:65 +0x13b
github.com/ethersphere/bee/pkg/p2p/libp2p.sendHeaders(0x127fee0, 0xc000198300, 0xc0017a7838, 0xc001d08240, 0x1266301, 0xc000083870)
github.com/ethersphere/bee/pkg/p2p/libp2p/headers.go:25 +0x19c
github.com/ethersphere/bee/pkg/p2p/libp2p.(*Service).NewStream(0xc0001fa1c0, 0x127fee0, 0xc000198300, 0xc000c758e0, 0x20, 0x20, 0xc0017a7838, 0xfcd0dc, 0x4, 0xfcd650, ...) …
```
> add send headers timeout

- pkg/p2p/libp2p/peer.go
Move peer registry lock on disconnect before handler so it does not block for long and to be uniform with remove() method.
> Peer registry minor fix

- pkg/kademlia/kademlia.go
The ordering of announce seems a bit different to me in the case of connect from manage and connected handler. @acud Could you pls take a look and verify if this is more correct? 
It seems to me that in manage it is first announced and then clean-ed up from maps, and in connected is vice versa + there is a manageC triggered in between, but I might be wrong 🙈
> Announce order

- pkg/api/bytes.go
- pkg/api/file.go
- pkg/file/error.go
- pkg/file/file.go
- pkg/file/splitter/splitter.go
There are not really big changes here in this PR, more or less just:
* removing the loglines in the goroutine, replacing them with errors (that we perhaps could just drop is what I asked, simplifying quite a bit)
* moving the splitUpload to files a method SplitWriteAll, which mirrors the already existing facilitator JoinReadAll.
* ~~typed error from splitter~~
> Improve code in api/bytes.go

- pkg/p2p/libp2p/libp2p.go
Currently, it seems that we are relying on headers logic timeout when errors happen in sending headers on both sending and receiving side (read will probably timeout). This is not a huge problem, but probably it's better to handle this explicitly as it will not wait for the whole timeout and we have a bit more control.
The solution is disconnect for now, as this is how we are handling most of errors of this kind, assuming that something is wrong with the peer in this case. Other solution could be closing or resetting the stream.
> Disconnect on headers error

- pkg/p2p/libp2p/libp2p.go
This PR reverts the change from https://github.com/ethersphere/bee/pull/333 as it creates a deadlock by calling pslice Remove on disconnect in kademlia.go:446 from the inside of pslice EachBinRev.
This can be seen in the goroutine:
```
goroutine 151 [semacquire]:
sync.runtime_SemacquireMutex(0xc00243f618, 0xc002243400, 0x0)
runtime/sema.go:71 +0x47
sync.(*RWMutex).Lock(0xc00243f610)
sync/rwmutex.go:103 +0x88
github.com/ethersphere/bee/pkg/kademlia/pslice.(*PSlice).Remove(0xc00243f5e0, 0xc0002b59e0, 0x20, 0x20, 0x0)
github.com/ethersphere/bee/pkg/kademlia/pslice/pslice.go:162 +0x5e
github.com/ethersphere/bee/pkg/kademlia.(*Kad).Disconnected(0xc000e22000, 0xc0002b59e0, 0x20, 0x20)
github.com/ethersphere/bee/pkg/kademlia/kademlia.go:371 +0xb3 …
```
> Revert "Disconnect on headers error (#333)"

- pkg/kademlia/kademlia.go
this PR tries to solve a problem where libp2p connect might block for a significant amount of time, possibly slowing down kademlia iterations.
Therefore a timeout has been added to `connect` method.
The problem was noticed when shutting down nodes, a goroutine trying to connect to a peer would always write to the log at the edge of the log stream.
> kademlia: add timeout to connect

- pkg/pusher/pusher.go
Tags are not working correctly and are polluting the terminal output.
Also, pusher pushes every chunk synchronously to NN, making the process painstakingly slow.
This PR adds some parallelism to the push process, therefore speeding it up.
> pusher: disable broken tags and make pusher push chunks in parallel

- pkg/puller/puller.go
this logs too much information by default when running on debug/trace. change the flag to true to enable more logging if that is needed
> puller: make logging toggleable

- pkg/p2p/libp2p/libp2p.go
The both incoming and sending side should wait for each other after adding the node to the peer registry, so we have a consistent situation when initiating protocols.
> Fullclose on incoming connection

- pkg/kademlia/kademlia.go
- pkg/node/node.go
We decided to change these to warnings as they can be part of a normal workflow of the app.
> Error -> warnings on connect calls

- pkg/kademlia/kademlia.go
- pkg/node/node.go
We decided that this should be warnings instead of errors cuz they are mostly the normal flow of the app.
> error -> warning in connect calls

- pkg/kademlia/kademlia.go
We should not try to connect to the same peer over and over again, since iterator on pslice does not prioritize peers, it might get stuck on the same problematic peer over and over again, causing other bins not to optimize correctly
> kademlia: dont connect to the same peer again in short interval

- pkg/p2p/libp2p/libp2p.go
- The both incoming and sending side should wait for each other after adding the node to the peer registry, so we have a consistent situation when initiating protocols.
- handle/send headers stream close per https://github.com/ethersphere/bee/pull/354
> Fullclose on incoming connection + stream close on send/handle headers

- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/libp2p_test.go
This PR cleans up kademlia when the peer is not found in peer registry. This PR is dependent on https://github.com/ethersphere/bee/pull/350, as it currently creates a deadlock on pslice lock.
> remove peer from kademlia on peer not found in peer registry

- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/p2p/libp2p/libp2p.go
- pkg/puller/puller.go
- pkg/pusher/pusher.go
this PR adds more information to errors in `libp2p` package.
also, it changes `pusher` to print the trace which indicates that a chunk has been successfully pushed only in those cases (right now it would print it even if there's an error).
It also changes the pusher to retry only ten seconds after a full run over the index has been completed, instead of just one second before. in the future we should detect when there's a significant amount of errors (i.e. a node is not connected, etc), reset the timer and break out of the iterator subscription, allowing it to wait for the next timer interval (which should probably be higher too).
> instrument libp2p errors, print pusher trace only when successful

- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/peer.go
As libp2p Stream does not provide context and no context is passed to handlers, we are keeping the registry of all of active streams for a particular peer in order to cancel them when the peer disconnects. This prevents blocking indefinitely in parts of the code that do not relay on reading from the stream to detect that the stream is closed.
> cancel stream contexts

- pkg/api/file.go
As we are using gzip compressor for our responses. I am adding a custom header as suggested in this comment https://stackoverflow.com/questions/15097712/how-can-i-use-deflated-gzipped-content-with-an-xhr-onprogress-function/32799706#32799706 for progress bar support.
> add decompressed-content-length header to be used for progress bar

- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
This fixes a bug where a peer would be connected to correctly, but due to a slow peer in announce, the root context in `kademlia.connect` would expire, resulting in an error at the announce method, causing the peer to be wrongly disconnected.
> kademlia: announce in a separate goroutine

- pkg/p2p/libp2p/protocols_test.go
Test was not waiting for handler to be finished, so I have added fullclose and closing the stream in the handlers.
> Multistream test fix

- pkg/p2p/libp2p/libp2p.go
This was a very old todo message. This can actually happen when the node is disconnected or something similar, so it is not valid anymore. So, I removed the todo and added this as a debug, cuz I think it pollutes the user output. We will watch this case and guard against it more if needed.
> Remove error log from add protocol

- pkg/kademlia/export_test.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/p2p/libp2p/peer.go
- pkg/pullsync/pullsync.go
This PR changes the saturation function to use both known and connected peers for depth calculation, avoiding piling up peers in shallow bins when initially bootstrapping the topology. This results in much more stable topology. We also after some experimentation raised the number of peers needed to saturate a bin to `4`, referred to as `saturationPeers` thereafter in kademlia.
> kademlia: saturate based on known peers

- cmd/bee/cmd/start.go
- pkg/node/node.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
This PR makes QUIC and WS transports disabled by default. It was observed that quic may introduce problems, and it is still an experimental feature. We should keep the transport on tcp only as the safest one, and enable other transports if needed and for testing.
This PR is important for infrastructure and documentation also as it changes command line parameters:
- `--p2p-disable-quic` to `--p2p-enable-quic`
- `--p2p-disable-ws` to `--p2p-enable-ws`
> Disable QUIC and WS libp2p transports by default

- pkg/p2p/libp2p/libp2p.go
- pkg/pingpong/pingpong.go
As @acud found, libp2p appears not to clean-up streams unless the stream is closed for both write and read: https://github.com/libp2p/go-libp2p/blob/master/NEWS.md. 
We are currently relying on `stream.Close()` to close one side of the stream, but don't check if the other side is closed, always. This can result in a half-closed stream in a case of an error. The quick fix is to use `FullClose` which will reset the stream on timeout, if other side did not close the stream.
This means that in order for stream to be cleaned up, one of the following must happen:
1. Stream must be closed by both sending and receiving side. There is no way to know this unless we wait for other side to close the stream,
2. If any error appears the stream should be reset, so it is closed for both writing and …
> Handle zombie streams with fullclose - pingpong

- pkg/p2p/libp2p/internal/handshake/mock/stream.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/p2p.go
- pkg/p2p/protobuf/protobuf_test.go
- pkg/p2p/streamtest/streamtest.go
This is a first PR in the set of PRs that will introduce usage of `stream.Reset()` into the protocols in order to:
1. Signalize errors between both sides of the stream instead of silencing them with `stream.Close()`
2. Not to timeout on `awaitEOF` in the case of an errors
Together with the usage of `FullClose` it should attempt to solve: https://github.com/ethersphere/bee/issues/403.
In order to have completely valid unit-test we would need to update `streamtest` to support `Reset` in a valid way. However, this would require us to change all the protocols at once. In order to avoid this, me and @janos have decided to dummy implement `Reset()` in `streamtest` for now, and test protocols behavior on the clusters. If everything goes well `streamtest` will be updated as well.
> Stream reset initial implementation

- pkg/node/node.go
- pkg/puller/export_test.go
- pkg/puller/puller.go
- pkg/puller/puller_test.go
- pkg/swarm/swarm.go
extract the max bins from puller to be easily injected from tests.
tried to also refactor `kademlia` to use `swarm.MaxBins` but I'm getting tests to hang for some reason.
as part of #329
> puller: extract maxpo and shallow bin peers

- pkg/node/node.go
- pkg/pusher/pusher.go
- pkg/pusher/pusher_test.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
tags are fetched by address in pusher which is wrong. They should be fetched by the uid in the chunk (if present, /bytes & /files api's don't have tags) and stored in a local map. When a receipt is received, the state in the local store should be synced and the tag counter for synced should be incremented.
> Fix getting tags by address in pusher

- pkg/node/node.go
This is a small update on handling some errors in node shutdown.
> group pull errors in node shutdown

- pkg/puller/metrics.go
- pkg/puller/puller.go
- pkg/pullsync/metrics.go
- pkg/pullsync/pullsync.go
This PR adds some prometheus metrics to the `puller` and `pullsync` packages.
These are very minimal metrics, and they should reflect some basic information as to the operation of these components.
One important note to the error counters is that due to the fact that context is being used to cancel the syncing jobs on depth change/peer disconnect, it in fact means that not all errors that are being returned from certain function calls should be accounted as actual protocol errors (or errors that we as developers would like to be notified about). 
This is due to the fact that once a sync job's underlying context is cancelled, the current function call will return an error `context.ErrContextCancelled`, which is not really an error in this case. This is why only certain branches of the code …
> pullsync, puller: add metrics

- Makefile
This PR adds the build for  `bee-file`,`bee-split` and `bee-file`
Makefile adds a command for
- `make binaries`
This will compile and generate the binaries in the dist folder for:
- `bee`
- `bee-file`
- `bee-split`
- `bee-file`
> Makefile: Added build for other binaries in BEE

- pkg/retrieval/retrieval_test.go
The retrieval protocol test is broken. `RetrieveChunk` returns an error (which is ignored, the test returns instead of fataling) because `EachPeer` was implemented on the mock instead of `EachPeerRev`. This PR changes this to `EachPeerRev` being implemented and failing in the test on error.
> fix broken retrieval test to implement EachPeerRev instead of EachPeer

- pkg/crypto/crypto.go
- pkg/file/file.go
- pkg/file/splitter/internal/job.go
- pkg/puller/puller.go
- pkg/swarm/swarm.go
- pkg/trojan/error.go
- pkg/trojan/export_test.go
- pkg/trojan/message.go
- pkg/trojan/message_test.go
Implements the trojan structures as described in the Book of Swarm.
The purpose of deploying trojan messages is to message another node in obscurity; hence they are embedded into trojan chunks, which are indistinguishable from regular data chunks.
This is pulled from the old swarm code base and refitted for the bee
#445 Add unsealing and sealing
#444 optimize trojan chunk mining
#443 make trojan chunks work as a bit vector
> Trojan chunk support

- cmd/bee/cmd/start.go
- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/accounting/mock/accounting.go
- pkg/accounting/mock/pricer.go
- pkg/accounting/pricer.go
- pkg/node/node.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
This PR adds an initial accounting implementation.
It includes
* `Credit` and `Debit` functions to modify a peers balance (replacing the `Add` function from earlier accounting implementation) 
* `Reserve` / `Release` functionality to prevent overspending
* Returning a p2p disconnect error in `Debit` if the disconnect threshold is crossed
* A `Balances` function to query balances used for testing (and later APIs)
* Writing and loading balances from a state store (this version writes to the store on every request which is not good if there is a lot of traffic, debouncing should be added to the db writes)
* Integration with retrieval protocol using a simple fixed price strategy based on proximity
* Option for setting the disconnect threshold
It does not include integration with settlement.
> add initial accounting for retrieval

- .github/workflows/beekeeper.yaml
K3d did two things, renamed master to main and released new version, new version is still not feature complete for our usecase, setting previous version.
DNS infra tests already [passed](https://github.com/ethersphere/bee/runs/896990514).
> k3d set v1.7.0 version

- .github/workflows/go.yml
this pr tries to shorten workflow time and reduce false positives
quite often lint is failing on windows and it can take too much time
for vet and linting it doesn't matter what base os we are using
> run lint and vet only for ubuntu

- pkg/soc/validator_test.go
This PR fixes the `TestSocValidator` test which fails sometimes.
The test attempts to manipulate a randomly generated address by xoring the first byte with itself. This always sets the first byte to zero which causes the test to fail if the first byte of the address was already zero. This PR replaces the xor with `255 - val` which guarantees that `wrongAddress` will always be different.
> fix TestSocValidator test

- pkg/file/testing/vector.go
the last two test vectors in `TestSplitThenJoin` take `t=eternity+1` to execute, which very often sends the CI to a halt, causing the test suite to fail, resulting in a slower feedback loop and a general slow-down of the workflow.
example dump observed yesterday:
```
2020-07-27T13:39:58.1569660Z === RUN   TestSplitThenJoin
2020-07-27T13:39:58.1603830Z === RUN   TestSplitThenJoin/0
2020-07-27T13:39:58.1703740Z === RUN   TestSplitThenJoin/1
2020-07-27T13:39:58.1733370Z === RUN   TestSplitThenJoin/2
2020-07-27T13:39:58.1740340Z === RUN   TestSplitThenJoin/3
2020-07-27T13:39:58.1845580Z === RUN   TestSplitThenJoin/4
2020-07-27T13:39:58.1849340Z === RUN   TestSplitThenJoin/5
2020-07-27T13:39:58.1854880Z === RUN   TestSplitThenJoin/6
2020-07-27T13:39:58.1883860Z === RUN   TestSplitThenJoin/7 …
```
> file: disable hanging tests

- pkg/netstore/netstore.go
Removes `INVOKE RECOVERY PROCESS` log from `netstore.get` until global pinning is correctly implemented and recovery process is initiated.
> netstore: removed log from get

- pkg/api/bytes.go
- pkg/api/file.go
- pkg/file/splitter/internal/job.go
- pkg/node/node.go
When the debug api is enabled,  /tags and /tags/{uid} api panic.
This is because the tag is not initialized in the debug server.
This was not caught in the unit tests as the test cases uses mock server and in real world we use the debug server which is initialized in "node" package
> Fix panic in tags debug api

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bzz.go
- pkg/api/bzz_test.go
- pkg/api/dirs.go
- pkg/api/dirs_test.go
- pkg/manifest/jsonmanifest/entry.go
- pkg/manifest/jsonmanifest/json.go
- pkg/manifest/jsonmanifest/manifest.go
- pkg/manifest/manifest.go
- pkg/node/node.go
This PR removes the `manifest` parser-related structures, interfaces and functions and embeds the `encoding` binary marshaller and unmarshaller interfaces in its stead.
It also:
- updates the `jsonmanifest` implementation to comply with the new interface.
- piggybacks the splitting of `jsonmanifest/manifest.go` into 2 files (one for `jsonmanifest.Entry`) for easier maintainability.
- removes the word `Get` from `manifest.Entry` func names
- as a result, `jsonmanifest.JSONEntry` fields had to be unexported, a constructor added, and custom marshalling/unmarshalling funcs were added as well. this struct now uses pointer semantics
- updates some `manifest` and `jsonmanifest` comments.
We are still eventually migrating all of this out of the codebase, through #476.
closes #494
> manifest, jsonmanifest, api, node: add encoding marshaling to manifest interface

- pkg/api/chunk.go
- pkg/api/router.go
- pkg/jsonhttp/handlers.go
- pkg/jsonhttp/handlers_test.go
This PR adds a simple http middleware constructor NewMaxBodyBytesHandler that can be chained on various router paths to limit the maximal allowed body size. Since the error is returned by reading from the body it has to be handled in the handler where it happens so a helper function is added HandleBodyReadError, which can be used to serve an appropriate Request Entity Too Large response.
This handler is integrated into the chunks api endpoint and should be used in other handlers where the protection from large response bodies is required, like in https://github.com/ethersphere/bee/pull/439.
> limit max http body size and detect it

- pkg/debugapi/debugapi.go
- pkg/debugapi/export_test.go
- pkg/debugapi/router.go
- pkg/debugapi/welcome_message.go
- pkg/debugapi/welcome_message_test.go
- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/p2p/libp2p/internal/handshake/handshake_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/welcome_message_test.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
The purpose of this PR is twofold:
- One: to enable runtime changes of the welcome message for the handshake
- Two: to establish a pattern for runtime change of select configuration parameters through the debug API
> Dynamic welcome message

- .github/workflows/go.yml
- Makefile
Some of the previous releases had problems with compilation, this one works fine.
> update golangci-lint to the latest release

- pkg/debugapi/pin_test.go
- pkg/localstore/pin.go
- pkg/storage/mock/storer.go
When /chunks-pin (list pinned addresses) API is called and if nothing is pinned, the response is 
`{ "message": "get first pin: leveldb: not found", "code": 500 }`
Instead it would be good if an empty response is returned, like
`{"chunks":[]}`
This fixes the issue https://github.com/ethersphere/bee/issues/478
> return empty response when nothing is pinned

- pkg/content/mock/validator.go
- pkg/content/validator.go
- pkg/netstore/netstore.go
- pkg/netstore/netstore_test.go
- pkg/node/node.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
- pkg/soc/validator.go
- pkg/storage/mock/storer.go
- pkg/swarm/swarm.go
In order to account only for valid chunks that are returned by others (i.e. not paying for junk) we need to check for chunk validity before we would change the account balance of the serving peer. 
As we want to do the accounting in for example retrieval, this required us to do the check before the end of retrieval, while the preexisting code only checked after retrieve returned. 
This also brought our attention to another possible issue, that if we were to recieve garbage chunk, we would not retrieve from another peer, as the verification takes place after the peer queries, so then we would probably fail, even if the valid chunk would be available from the next tried peer.
So we created the chunk in retrieve, and passed a validation function as an argument to retrieve that can do the …
> Check for validity before concluding retrieving chunk

- pkg/netstore/netstore_test.go
- pkg/p2p/streamtest/streamtest.go
This PR fixes the problem found as flaky test in https://github.com/ethersphere/bee/issues/513. The problem is not with the test but within goroutine synchronization in stream test. The handler is returned allowing the test to continue while the hander goroutine may still did not set the error. This PR adds a done channel so that all goroutines are done before the records are returned by the Records method.
I was able to reproduce the error on master locally with:
```
go test github.com/ethersphere/bee/pkg/p2p/streamtest -failfast -count=100000 -race -run TestRecorder_recordErr
```
It is very rare, hence the large count value.
Unrelated to this fix, this error is removing unused `mockValidator` to avoid linter errors.
fixes: #513
> streamtest record err flaky test fix

- pkg/trojan/message.go
- pkg/trojan/message_test.go
When a wrap takes time (race test) or is supplied a longer target, it gets stuck in a forever loop mining the trojan chunk.
This had a timeout which was inside the longest target loop (i.e. timeout will be checked after trojan reaches 255 bytes long ).
Now it is fixed to check the timeout every few(256) iterations.
The solution is to increase the timeout and bring down the target length from 2 bytes to 1 bytes in tests. 
Fixes https://github.com/ethersphere/bee/issues/509
> fix forever loop timeout issue

- pkg/retrieval/retrieval_test.go
This PR reintroduces the check in the server accounting in retrieval test which was removed from the first accounting PR due to being flaky. Due to the changes in #514 this check can now run reliably.
> readd server accounting check in retrieval test

- pkg/netstore/netstore_test.go
- pkg/swarm/proximity.go
- pkg/swarm/proximity_test.go
This PR is a proposal how to handle the symptom of the problem described in https://github.com/ethersphere/bee/issues/515. This changes the behaviour for proximity function to handle shorter second argument than the first one instead to panic. This behaviour would hide the root cause of the issue https://github.com/ethersphere/bee/issues/515, but the current implementation is not commutative binary function as it would handle shorter first argument, but not the second one.
The root cause of https://github.com/ethersphere/bee/issues/515 should be found, regardless of this PR being merged or not.
Additionally, mockValidator is removed in order to make the linter pass.
> prevent panic in proximity function with shorter second argument

- pkg/retrieval/retrieval.go
This PR fixes the problem when maxPeers is reached while retrieving the chunk. In that case the error that is returned is nil, as well as the chunk, resulting in type assertion panic.
fixes: https://github.com/ethersphere/bee/issues/523
> retrieval: return chunk not found if max peers reached

- pkg/node/node.go
Removes the variable declaration for `storer` as it is increases indirection when reading the code.
> node: remove var declaration for storer

- pkg/hive/hive_test.go
The discovery test was flaking on a timeout to reach the correct number of entries in the address book. The timeout of the helper function was 1 second, however, it can be that the timeout was reached since the golang test suite is significantly slower with race detector on. I have added more verbose logging and goroutine printouts in case this flakes again, to see if some specific handler goroutine is taking too long due to whatever reason. Also, responses are now checked without constraint of ordering.
hopefully fixes #485
> hive: clean up tests, allow for unordered response

- .github/workflows/go.yml
This change fixes the problem with CI configuration where Lint and Vet steps were disabled on all targets.
> fix lint and vet go github workflow condition

- pkg/node/node.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/libp2p_test.go
- pkg/p2p/libp2p/peer.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
Renamed existing method `SetNotifier` to `AddNotifier`, and added support for adding multiple notifiers, all of which will be invoked during appropriate changes.
Issue: #541
> Support multiple notifiers in 'libp2p.Service'

- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/peer.go
During investigation of https://github.com/ethersphere/bee/pull/new/disconncted-calls-fix I noticed that disconnected is called sometimes on the value that is not found in peer registry. 
The new change that @zbiljic added is calling registry disconnect which is a bit more guarded. 
The original code was calling `peers.disconnecter.Disconnected` handler explicitly,  and could actually pass the address that is not in a peer registry.
Anywayz, since the `peerregistry.remove` is used to signal disconnection, there is not need to call disconnected explicitly if the peer is not found in peer registry. If this signal is needed in this case for some reason, then the receiver of disconncted event should always parse overlay address and check if it is valid.
> Remove invalid disconnected call

- pkg/debugapi/chunk.go
- pkg/debugapi/chunk_test.go
- pkg/debugapi/router.go
- pkg/storage/mock/storer.go
This PR adds a debug API to remove a chunk from the local store and its associated indexes.
This will be useful to test global pinning in cluster setting.
the API is 
curl -X DELETE http://127.0.0.1:6060/chunks/<chunk reference>
Fixes https://github.com/ethersphere/bee/issues/555
> expose remove chunk debug API

- .github/workflows/go.yml
- Makefile
This PR fixes a problem when building golangci-lint fails with some of its linters create a breaking change. The solution is to install the prebuilt binary using the official install script. The unneeded step to setup golangci-lint is removed as it is done by the `lint` Makefile rule.
> golangci-lint binary install

- pkg/hive/hive.go
- pkg/kademlia/doc.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/kademlia/mock/kademlia.go
- pkg/node/node.go
- pkg/puller/puller.go
- pkg/topology/full/full.go
- pkg/topology/full/full_test.go
- pkg/topology/mock/mock.go
- pkg/topology/topology.go
https://github.com/ethersphere/bee/issues/521
I have left `Start()` method only on kademlia for now, so I did not extract any extra interfaces. This is probably ok, as there is no other implementation of topology driver at the moment, and full connectivity does not need it.
> Fallback to bootnodes

- cmd/bee-file/main.go
- cmd/bee-split/main.go
- pkg/api/api.go
- pkg/api/bytes.go
- pkg/api/bzz_test.go
- pkg/api/chunk.go
- pkg/api/chunk_test.go
- pkg/api/dirs.go
- pkg/api/file.go
- pkg/debugapi/pin_test.go
- pkg/debugapi/tag_test.go
- pkg/file/file_test.go
- pkg/file/joiner/joiner_test.go
- pkg/file/splitter/internal/job.go
- pkg/file/splitter/internal/job_test.go
- pkg/file/splitter/splitter.go
- pkg/file/splitter/splitter_test.go
- pkg/localstore/localstore_test.go
- pkg/localstore/mode_put.go
- pkg/localstore/mode_put_test.go
- pkg/localstore/pin.go
- pkg/storage/mock/storer.go
- pkg/storage/mock/storer_test.go
- pkg/storage/store.go
This PR adds a `ModePutUploadPin` which allows to upload and pin content simultaneously in one atomic operation. `Swarm-Pin` header is also added to the API to enable pinning on all the relevant endpoints.
> api: add pin on upload

- cmd/bee/cmd/start.go
- pkg/node/node.go
This PR removes the `--disconnect-treshold` command line argument which seems to have been reintroduced by mistake in the unrelated #479.
> remove disconnect threshold argument

- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
adds the `/balances` and `/balances/{peer}` calls to the openapi spec.
> add balance debug api to openapi

- pkg/accounting/accounting.go
This PR removes the in-memory copy of accounting balances (as suggested by @janos). Balances are always loaded from disk when needed. The `balances` struct has been renamed to `accountingPeer` as it no longer holds the balance. Instead it is only for in-memory data (such as the reserved balance and the payment threshold). The accounting logic itself remains unchanged.
> Always load balance from store

- pkg/accounting/accounting_test.go
The `TestAccountingAddBalance` test called `Reserve` with the wrong argument (`booking.price` instead of `-booking.price`). Due to the `uint64` cast this leads to a very big booking (which should work but is not what we want to test here).
> call reserve in booking test correctly

- pkg/statestore/test/store.go
This pr fixes an error from Go 1.15 vet tool:
```
go vet ./...
pkg/statestore/test/store.go:163:17: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```
This change is related to the correctness. No functional problems exist.
> fix int conversion to string in statestore test

- pkg/api/bytes_test.go
- pkg/api/bzz_test.go
- pkg/api/chunk_test.go
- pkg/api/dirs_test.go
- pkg/api/file_test.go
- pkg/api/tag_test.go
- pkg/debugapi/balances_test.go
- pkg/debugapi/chunk_test.go
- pkg/debugapi/p2p_test.go
- pkg/debugapi/peer_test.go
- pkg/debugapi/pin_test.go
- pkg/debugapi/pingpong_test.go
- pkg/debugapi/status_test.go
- pkg/debugapi/topology_test.go
- pkg/debugapi/welcome_message_test.go
- pkg/jsonhttp/jsonhttptest/jsonhttptest.go
- pkg/jsonhttp/jsonhttptest/jsonhttptest_test.go
- pkg/jsonhttp/jsonhttptest/testing_mock_test.go
This PR consolidates all functions in jsonhttptest package that piled up over time bloating its api. Unfortunately, only the initial two functions were tested, non of the followup were, so new tests are added and existing one improved. Also the package is better documented.
Tests in api and debugapi packages are adjusted.
fixes: #477
> cleanup jsonhttptest package

- pkg/api/router.go
A minor change to use the versioned `handle` function in api package router for recently put back tags endpoints.
> support api version path for tags api endpoints

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/configurateoptions.go
- cmd/bee/cmd/start.go
- go.mod
#522 
To achieve a greater degree of configuration overviewability, we are introducing the bee config command.
Behavior of the command is to show all options and default values of configuration used without a provided configuration file, 
Or - in presence of a configuration file provided to bee - to show all of the options and the actual values used with that configuration file loaded.
The aim is to display the output formatted as valid yaml
> Config command

- pkg/node/node.go
- pkg/settlement/pseudosettle/metrics.go
- pkg/settlement/pseudosettle/pseudosettle.go
The aim of this PR is to introduce some monitoring opportunity to sent / recieved pseudosettlements through the /metrics endpoint of the debug API
> Add basic metrics counters for total sent/recieved pseudosettle amounts

- go.mod
- go.sum
- pkg/resolver/doc.go
- pkg/resolver/mock/resolver.go
- pkg/resolver/multi.go
- pkg/resolver/multi_test.go
- pkg/resolver/resolver.go
Multiresolver allows a registered resolver chain to be selected based on a TLD in a name (eg. "name.eth" -> ENS resolver chain).
A resolver chain attempts to resolve a name using all resolvers in a chain, returning an error if all resolvers fail.
> Add multiresolver

- pkg/node/node.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
This PR integrates push sync with accounting. Nodes pay their peers after receiving the receipt.
The accounting flow is as follows:
During handling a chunk delivery:
* if we are the closest we debit the pushing peer with our price after sending the receipt (in `handleDeliveryResponse`)
* if we need to forward we credit (with the corresponding reserve/release calls) the closest peer with their chunk price after receiving the receipt . after sending back the receipt to the pusher we debit it with our price (at the end of the `handler`) 
During initiating a push:
* if we are not the closest node, the closest node is credited with their price for the chunk after receiving the receipt (with the corresponding reserve/release calls before sending any messages).
> accounting in push sync

- go.mod
- go.sum
- pkg/api/dirs_test.go
- pkg/api/file_test.go
- pkg/api/tag_test.go
- pkg/manifest/manifest.go
- pkg/manifest/mantaray.go
This change adds `mantaray` manifest implementation for `bee`.
Externally from `pkg/manifest` package there are no changes, expect to some test, where some edits were required.
Since the `mantaray` implementation contains `obfuscationKey`, which is generated randomly for new manifest, each time collection is uploaded, new hash will be returned by the service.
> Add support for 'mantaray' manifest, and make it default

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- pkg/kademlia/kademlia.go
- pkg/node/node.go
- pkg/p2p/libp2p/libp2p.go
fixes #536 
The --standalone flag's intended behaviour is to:
- inhibit bootstrapping connections to bootnodes
- inhibit connecting to known peers
- disable listen addresses so incoming connections are not accepted
> Standalone flag option for bee

- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
When connecting to bootnodes, put a max bootnode count to 3. There is no theoretical limit to a number of bootnodes, but this is limiting a number of bootnodes the kademlia will try to connect to at once.
In order to keep the limit strict, I have made connecting to bootnodes sequential. I don't think there is a way to be strict when there are concurrent parallel connection  attempts without doing disconnects etc...
fixes #635
> Connect to max 3 bootnodes at startup

- pkg/debugapi/debugapi.go
- pkg/debugapi/peer.go
- pkg/debugapi/peer_test.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/p2p/discover.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
Potentially remove connect notify from toplogy driver as a cleanup, as it is used only in debugapi.
TODO:
Polish up the p2pMock a little bit and check toplogy notifier in `peer_tests` in debugapi.
> Remove connect notify

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- cmd/internal/file/io_test.go
- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/gatewaymode_test.go
- pkg/api/router.go
- pkg/node/node.go
This PR ads a single api and cli option to disable some features, most useful when exposing the api in public.
Gateway mode disables in the API level:
- tags endpoints
- pinning chunks endpoints
- encryption on upload endpoints
- pinning on upload endpoints
Additionally, this PR adds api.Options with the new Gateway option and already existing cors headers as both being optional features.
fixes: #668
> api gateway mode

- Makefile
- pkg/debugapi/status.go
- pkg/debugapi/status_test.go
This is a simple change to include the git commit when building with Makefile and .git directory is available very similar to what we had before https://github.com/ethersphere/bee/commit/dc1951843baeebbe7dc417216e86cc5ab6cd9fc4#diff-b67911656ef5d18c4ae36cb6741b7965L4, but if the COMMIT environment variable is provided, the git command will not be executed. When building a docker image COMMIT environment must be provided as .git directory is in .dockerignore, this is not changed.
fixes: #683
> add git commit to version and expose version in debugapi

- pkg/accounting/accounting_test.go
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/export_test.go
- pkg/debugapi/router.go
- pkg/debugapi/settlements.go
- pkg/debugapi/settlements_test.go
- pkg/node/node.go
- pkg/settlement/interface.go
- pkg/settlement/pseudosettle/mock/pseudosettle.go
- pkg/settlement/pseudosettle/pseudosettle.go
- pkg/settlement/pseudosettle/pseudosettle_test.go
The aim of this pull request is to create the
`/settlements`
`/settlements/{peer}`
endpoints in the debug api that return the swap settlements associated with all peers or a specified peer in json format
> settlement persistence and debug api

- pkg/node/node.go
- pkg/p2p/p2p.go
- pkg/p2p/streamtest/streamtest.go
- pkg/recovery/repair_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
This PR is an attempt to improve chunk retrieval.
- block peer for some short time if the retrieval times out (since it forwards, maybe to extend the timeout from 10s to 30s)
- decouple netstore from the retrieval protocol, avoiding circular dependency between these two services
- small improvements to logging
Changes were also tested with beekeeper retrieval check.
> blocklist peer on retrieval timeout

- pkg/pushsync/pushsync.go
Log errors from the pss delivery handler instead of returning them to the push sync handler. This is to avoid them causing a stream reset which sometimes prevents the receiving of the receipt by the other peer.
The loglevel was chosen as `DEBUG` because this is how it would be logged before this PR (as an `error handle protocol`).
> log pss error instead of stream reset

- openapi/Swarm.yaml
- pkg/api/api.go
- pkg/api/bzz.go
- pkg/api/dirs.go
- pkg/api/dirs_test.go
- pkg/api/router.go
This PR is a proposal on how to support default path (index) for serving web sites. If Swarm-Index is specified, directories in manifests will be referenced with the entry of the filename in that directory if that file exists.
fixes: #647 #658
> implement swarm-index dirs api option as default path

- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
This PR blocks peers instead of just disconnecting if the threshold is reached to prevent them from reconnecting.
The time period for the block has been chosen arbitrarily. Better suggestions are welcome.
> block peers on disconnect threshold

- pkg/accounting/accounting.go
- pkg/debugapi/balances.go
- pkg/debugapi/balances_test.go
- pkg/debugapi/export_test.go
The aim of this change is to return "No balance for peer" instead of 0 in case there is no balance associated with the peer key in storage.
> Distinguish no balance for peer

- pkg/pss/pss.go
- pkg/pss/pss_test.go
- pkg/trojan/error.go
- pkg/trojan/export_test.go
- pkg/trojan/message.go
- pkg/trojan/message_test.go
- pkg/trojan/mining_test.go
closes #444 
- introduce context to Wrap and eliminate MinerTimeout
- simplify Wrap
- add mine function that finds a nonce that makes a function true
- introduce mining benchmarks
BEFORE
```
:) go test -v -run None -bench .
goos: darwin
goarch: amd64
pkg: github.com/ethersphere/bee/pkg/trojan
BenchmarkWrap
BenchmarkWrap/length:1,depth:1
BenchmarkWrap/length:1,depth:1-8         	     100	  25259359 ns/op
BenchmarkWrap/length:4,depth:1
BenchmarkWrap/length:4,depth:1-8         	     211	   5987303 ns/op
BenchmarkWrap/length:16,depth:1
BenchmarkWrap/length:16,depth:1-8        	     662	   1601796 ns/op
BenchmarkWrap/length:64,depth:2
BenchmarkWrap/length:64,depth:2-8        	      15	 118159956 ns/op
BenchmarkWrap/length:256,depth:2
BenchmarkWrap/length:256,depth:2-8       	      44 …
```
> trojan,pss: optimise trojan mining

- .github/workflows/beekeeper.yaml
Here is the workflow that will be trigger after build and all tests passed -> [bee-argo](https://github.com/ethersphere/bee-argo/blob/master/.github/workflows/update.yaml)
That workflow will generate k8s yamls for deployment and self-commit to edge folder, argocd running on staging cluster will detect repo folder's change and update the cluster.
> add trigger for argocd deploy

- .github/workflows/beekeeper.yaml
Too often beekeeper tests are failing, mostly retrieval related, this should start [Tunshell](https://github.com/TimeToogo/tunshell) debug session that should last for max timeout for github actions (6 hours I think)
If pipeline hangs with executed Tunshell action ping @svetomir or me for access.
> add tunshell installation if workflow failed

- pkg/kademlia/kademlia_test.go
In `TestClosestPeer`, there was a possibility for a race condition where the `conns` counter that was used has been incremented, but the peer was not yet added to the backing `pslice` data structure.
This is possible since the `conns` counter was incremented in the mock p2p connect function, meaning that kademlia initiated a dial, but the actual addition to `connectedPeers` is done some lines of code after the connection is done on the p2p level, resulting in a data race where indeed 3 connections were initiated, but not all 3 peers are in `connectedPeers`.
This is also evident, since the test was flaking on the first test case:
```
=== RUN   TestClosestPeer
##[error]    kademlia_test.go:509: peers not equal. got 4000000000000000000000000000000000000000000000000000000000000000 expected …
```
> kademlia: TestClosestPeer wait for peers to be added to the backing data structure

- pkg/node/node.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
- pkg/recovery/repair_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
Add tracing to pushsync and retrieval
> retrieval, pushsync: add tracing

- cmd/bee/cmd/start.go
- pkg/crypto/clef/clef.go
- pkg/crypto/clef/clef_test.go
- pkg/crypto/eip712/typeddata.go
- pkg/crypto/signer.go
- pkg/crypto/signer_test.go
- pkg/node/node.go
- pkg/settlement/swap/chequebook/cheque.go
- pkg/settlement/swap/chequebook/cheque_test.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/chequebook_test.go
- pkg/settlement/swap/chequebook/common_test.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/chequebook/init.go
- pkg/settlement/swap/chequebook/mock/chequebook.go
- pkg/settlement/swap/chequebook/transaction.go
- pkg/settlement/swap/chequebook/transaction_test.go
adds cheque signing functionality
a few remarks:
* unfortunately the clef wrapper from go-ethereum does not expose `account_signTypedData`. therefore a lower-level `rpc.Client` is also passed into the signer. in the future we could either use the rpc directly for everything (as it is just a very thin wrapper), or try to get a `SignedTypedData` function in the go-ethereum abstraction.
* the package which defines the `TypedData` structures (with the correct json encoding) is unfortunately called `core` (from `signer/core`) on the go-ethereum side. To avoid having to have `core` everywhere or resort to import aliasing I created type aliases for the relevant stuff in a `eip712` package which also has some additional helpers.
* `IssueCheque` might change in the next PR depending on the needs …
> add cheque signing

- pkg/crypto/dh.go
- pkg/crypto/dh_test.go
- pkg/encryption/encryption.go
- pkg/encryption/encryption_test.go
a prerequisite to pss encryption #663 submitted seperately for easier review
> crypto: add ECDH shared secret support, in memory variant

- go.mod
- go.sum
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bzz.go
- pkg/api/bzz_test.go
- pkg/api/dirs.go
- pkg/api/dirs_test.go
- pkg/api/export_test.go
- pkg/manifest/manifest.go
- pkg/manifest/mantaray.go
- pkg/manifest/simple.go
Includes support for metadata that can be stored in manifest.
Initially it i used to store `index-document` and `error-document` in the manifest.
These two are stored in root path (`/`) entry metadata.
During serving files from paths, on the `bzz` endpoint, if some of these documents are configured, attempt will be made to redirect to some of them (based on the actual state of the request).
Some naming changes are done by this PR (headers), which should be open for discussion.
One additional change was made to `api_test.go`, where additional option was added, that allows caller to disable client redirect. This was done to support some additional tests related to redirection to these mentioned (optional) documents.
> Add support for manifest metadata

- pkg/retrieval/retrieval.go
This PR changes slightly the logic of retrieval. It allows the upstream chunk request by the requester node. All forwarded requests are still only downstream. This change improves the situation where the requester node is the closest to he chunk of all its peers. By allowing the first request to be upstream, retrieval is more efficient and forwarding loops are still not possible.
> allow first retrieval request to be upstream

- pkg/encryption/elgamal/encryption.go
- pkg/encryption/elgamal/encryption_test.go
- pkg/encryption/encryption.go
- pkg/encryption/mock/mock.go
a prerequisite to  pss encryption #663 
builds on #727 
This PR implements el-Gamal encryption using  symmetric encryption of the `encryption` package and `ECDH` secret key generation in  the `crypto` package
> simple El-Gamal encryption for trojan chunks

- go.mod
- go.sum
There was an issue with the bytecode in the old bindings. This updates master to use the last version of the contracts, so that devops can already work with the latest contracts for the integration testing.
> update smart contract bindings to latest version

- cmd/bee/cmd/cmd.go
- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/node/node.go
This changes accounting to trigger payment a bit earlier than the peers payment threshold. This is to avoid needlessly blocking reserve request if already near the payment threshold when several concurrent request occur.
> trigger settlement before expected debt hits payment threshold

- pkg/node/node.go
- pkg/pusher/pusher.go
- pkg/pusher/pusher_test.go
adds a main trace to the pusher under which all the chunks in the snapshot will be visible on jaeger.
> pusher: add tracing

- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/file.go
- pkg/netstore/netstore.go
- pkg/netstore/netstore_test.go
- pkg/recovery/repair_test.go
- pkg/sctx/sctx.go
We are constantly rewriting errors with chunk repair and trojan errors and this must be changes so that netstore returns the correct errors when failing to retrieve a chunk. Also, since targets are not a mandatory argument when doing requests, it should not be considered an error when one does not have any targets set.
> api, netstore: dont set empty targets, return correct errors from netstore

- pkg/debugapi/chequebook.go
- pkg/debugapi/chequebook_test.go
- pkg/settlement/swap/chequebook/bindings.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/chequebook_test.go
- pkg/settlement/swap/chequebook/common_test.go
- pkg/settlement/swap/chequebook/mock/chequebook.go
- pkg/settlement/swap/swap.go
- pkg/settlement/swap/swap_test.go
ensure that we are solvent when issuing a cheque.
also changes the `/chequebook/balance` endpoint to return both the total and the available balance.
closes #738
> check available balance when issuing cheques

- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/chequebook/init.go
changes goerli factory address to the correct one. the other address is a valid factory but it does not use the token we want to use. (it was the test factory used before deploying the final gbbz token)
also checks we can afford initial deposit before deploying.
> fix goerli factory address

- cmd/bee/cmd/start.go
- openapi/SwarmCommon.yaml
- pkg/crypto/crypto.go
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/p2p.go
- pkg/debugapi/p2p_test.go
- pkg/node/node.go
This PR add a log message on start with a public key and also extends debugapi addresses endpoint with the same information. Required information for encrypted PSS.
> expose swarm public key in logs and debugapi

- pkg/api/pss_test.go
- pkg/node/node.go
- pkg/pss/pss.go
- pkg/pss/pss_test.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
add length check  to `TryUnwrap` 
fixes https://github.com/ethersphere/bee/issues/753
remove error return value `TryUnwrap/deliveryCallback` to make sure no protocol  error  can result from pss dispatching
> Pss trojan  length check and no  error return in  delivery callback

- pkg/settlement/swap/chequebook/bindings.go
- pkg/settlement/swap/chequebook/chequestore.go
- pkg/settlement/swap/chequebook/chequestore_test.go
- pkg/settlement/swap/chequebook/common_test.go
instead of requiring the counterparty chequebook balance to be more than the cheque amount, just check it is more than the uncashed amount.
> account for totalPaidOut in liquidity check

- pkg/node/node.go
- pkg/settlement/swap/chequebook/common_test.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/chequebook/factory_test.go
- pkg/settlement/swap/chequebook/init.go
* Splits chequebook deployment into two parts so we can tell the user the tx hash in init.
* Some error messages changed
* insufficient token error contains info which address to fund
* more logs during init
> Swap ux improvements

- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
- pkg/debugapi/chequebook.go
- pkg/debugapi/chequebook_test.go
- pkg/debugapi/export_test.go
- pkg/debugapi/router.go
- pkg/node/node.go
- pkg/settlement/swap/chequebook/bindings.go
- pkg/settlement/swap/chequebook/cashout.go
- pkg/settlement/swap/chequebook/cashout_test.go
- pkg/settlement/swap/chequebook/common_test.go
- pkg/settlement/swap/chequebook/transaction.go
- pkg/settlement/swap/mock/swap.go
- pkg/settlement/swap/swap.go
- pkg/settlement/swap/swap_test.go
adds endpoints:
* `POST /chequebook/cashout/<peer>` to initiate a cashout for the latest cheque for this peer.
* `GET /chequebook/cashout/<peer>` to view the status or result for the latest cashout for this peer.
Info about the latest cashout per peer is stored in statestore. Builds on top of `lastcheque-endpoint` as it uses some of the interfaces / mocks from there.
This is a very minimal implementation. It does not actively monitor the transaction for success, only when queried by the user.
> cashout cheques

- go.mod
- go.sum
New version of 'ethersphere/manifest' fixes issue observed for SPA website, where `*.js.map` files were created for `*.js`, and because of the TAR is created and node trie structure of the manifest was created the `*.js` files were not marked as containing value, just as edges of the structure. Updated library fixes this issue.
Related [PR#ethersphere/manifest/11](https://github.com/ethersphere/manifest/pull/11).
> Upgrade 'ethersphere/manifest' to v0.3.1

- openapi/SwarmDebug.yaml
- pkg/debugapi/chequebook.go
- pkg/debugapi/chequebook_test.go
- pkg/debugapi/export_test.go
- pkg/debugapi/router.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/chequebook_test.go
- pkg/settlement/swap/chequebook/mock/chequebook.go
adds
* `POST /chequebook/withdraw?amount=VALUE`
* `POST /chequebook/deposit?amount=VALUE`
so users can send bzz token between chequebook and overlay.
openapi yaml use the TransactionReponse type from cashout PR which should be merged first.
> add withdraw and deposit endpoints

- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
Update the relevant schemas and openapi definitions for debugapi `/settlements/` and `/chequebook/` endpoints.
> Update openapi definitions for debugapi /settlements/ and /chequebook/ endpoints

- cmd/bee/cmd/cmd.go
Enables swap by default. To run without swap use `--swap-enable=false`, in which case it will use `pseudosettle`. This flag is necessary even in standalone mode.
> enable swap by default

- openapi/SwarmCommon.yaml
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/p2p.go
- pkg/debugapi/p2p_test.go
- pkg/node/node.go
Enables eth address to be queried by api.
Might be useful, but not strictly necessary for release.
> add ethereum address to /addresses

- pkg/retrieval/retrieval_test.go
Changes introduced in #742 are conflicting with tests that were introduced in #705. Namely the test that asserts that upstream peer should not be called.
The only way I managed to get this to fail locally is by running `go test -v -count 2 -race` in the retrieve protocol directory. using just one iteration did no manifest in a panic for some reason. But it was evident that the client handler was being called from stream recorder
fixes #764
> retrieval: remove test that forbids upstream request

- pkg/pricing/pricing.go
- pkg/settlement/swap/chequebook/init.go
log is in the wrong position. is shown even if chequebook already exists. also removes a duplicate log from payment threshold announcement.
> chequebook and payment threshold logging fixes

- go.mod
- go.sum
New version of 'ethersphere/manifest' that adds padding to internal metadata (if metadata exists).
Related [PR#ethersphere/manifest/12](https://github.com/ethersphere/manifest/pull/12).
> Upgrade 'ethersphere/manifest' to v0.3.2

- cmd/bee/cmd/cmd.go
changes the default initial deposit to the amount dispensed by the faucet. this ensure users don't end up with an unfunded chequebook unless they explicitly want to.
> default initial deposit

- pkg/hive/hive.go
This is a small change to address invalid format in log messages such as this:
```
time="2020-09-28T15:08:56Z" level=warning msg="skipping peer in response Underlay:\"\\004\\262\\375\\361\\346\\006\\033\\236\\245\\003'\\000%\\010\\002\\022!\\003N\\254\\227\\r\\302\\276\\323O\\020\\004\\216\\036\\301\\246\\301\\230\\200\\265j\\342|\\215@\\276\\212\\\"<J\\340\\037\\245|\" Signature:\" \\211\\205\\037;K\\306O\\\\\\202\\221\\231\\271\\354\\005nh\\217\\030\\2624\\313\\352\\363\\341\\311\\024$\\251\\006\\264r_$\\035\\032i\\347\\217\\325\\204\\327\\324k\\240\\nE\\024\\202\\275\\244\\332\\372\\303f~\\341\\302\\005\\267%\\345Ra\\344\" Overlay:\"\\246\\251\\373\\342\\334\\214K\\304\\013\\360b\\311\\336iQ\\013iI\\200?e\\370,\\207\\334\\022\\230\\246\\030\\006\\037\\241\" : …
```
> fix warning log message format it hive

- pkg/node/node.go
- pkg/settlement/swap/swap.go
- pkg/settlement/swap/swap_test.go
Unfortunately the last PR did not actually work the way intended. It didn't disconnect at all as the error was ignored further upstream and even if it was handled it would have disconnected the wrong peer.
This PR passes `p2p.Service` into `Swap` which can then disconnect the right peer.
> actually disconnect on no swap beneficiary

- pkg/debugapi/router.go
The pprof HTML contains relative links.
> Redirect '/debug/pprof' to endpoint with slash

- pkg/settlement/swap/metrics.go
- pkg/settlement/swap/swap.go
makes rejected cheque more easily spotted in logs
> include rejecting if cheque rejected plus metric

- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/accounting/mock/accounting.go
- pkg/pushsync/pushsync.go
- pkg/retrieval/retrieval.go
- pkg/settlement/pseudosettle/mock/pseudosettle.go
This PR changes the accounting flow so that settlement of actual debt is already triggered in the `Reserve` stage.
The new accounting flow is as follows:
* `Credit` like `Debit` now only updates balances and no longer attempts to settle.
* Settlement now uses the right context
* If in `Reserve` we detect we are close enough to payment threshold we trigger settlement right there and fail if settlement fails.
* We still block if the expected debt would exceed the threshold. this is possible even if settlement occurred (e.g. if all outstanding requests actually exceed the payment threshold and we had positive balance with the peer before).
Motivation:
* Currently it is possible to get in a state where we are above the payment threshold but we still will never attempt to settle again. The …
> accounting: settle in reserve

- pkg/node/node.go
- pkg/recovery/repair_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
This PR decouples forwardign logic from netstore into retreival, leaving retrieval not dependent on netstore behaviour.
> decouple retrieval forwarding from netstore

- go.sum
- pkg/settlement/swap/chequebook/cashout_test.go
- pkg/settlement/swap/chequebook/chequebook_test.go
- pkg/settlement/swap/chequebook/chequestore_test.go
- pkg/settlement/swap/chequebook/common_test.go
- pkg/settlement/swap/chequebook/factory_test.go
- pkg/settlement/swap/chequebook/transaction_test.go
- pkg/settlement/swap/transaction/backendmock/backend.go
Creates a proper mock for the Ethereum backend which can be used from different packages. This mock is used in all tests instead of the old ones. There are no other changes.
The mock is in the `transaction/backendmock` package because the next PR will move the transaction service to its own package.
> add proper backend mock

- pkg/localstore/metrics.go
- pkg/node/node.go
While debugging "pushsync" package, I noticed that metrics are not exported. After including those to debug API, I also noticed some other seem to be missing from there. 
This change includes those missing metrics from other packages, and fixes names of metrics from `localstore` (discovered after metrics were added).
One remaining metric group that was not included here is from `shed` package. Since that is only internally used in `localstore`, different change would be needed to include it.
Since I am not totally sure about that package anyway, I have left it out. If someone thinks that it should be added, I can update this PR.
> Export additional metrics

- pkg/api/pin.go
- pkg/localstore/pin.go
- pkg/localstore/pin_test.go
- pkg/storage/mock/storer.go
- pkg/storage/store.go
This PR adds pagination to the pin api, as well as some minor cleanups and refactorings.
A default 100 entry response is returned, and a hard limit of 1000 entries per response is enforced.
fixes #464
> localstore/pin: refactor and add paging

- Makefile
Do not rely that $GOPATH/bin is in the environment's $PATH for Makefile lint rule
fixes: #816
> use absolute path for golangci-lint in Makfile

- pkg/localstore/subscription_push.go
- pkg/localstore/subscription_push_test.go
- pkg/shed/index.go
- pkg/shed/index_test.go
This change adds support for reverse iteration over index items, and uses that for processing push index.
Since the order is reversed, last successful processed item is no longer tracked (to be used to start on next iteration). First item from iteration is saved, and each item from iteration is compared to that one, and if reached iteration stopped.
That backward processing results in FIFO processing of added chunks into push index.
relates to: #532
> Reverse the order of the queue for push sync index

- pkg/node/node.go
It is not required to wait for nat manager to be initialized if the node is started in standalone mode.
> do not wait for nat manager in standalone mode

- pkg/soc/export_test.go
- pkg/soc/soc.go
- pkg/soc/soc_test.go
- pkg/soc/validator.go
- pkg/soc/validator_test.go
This PR fixes formal documentation strings in `soc` package. Some comments copied from the swarm packages are removed, copyright statement correctly separated from the package declaration not to be rendered as the package documentation, and a small variable name correction in comment.
> fix comments in soc package

- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/static_resolver.go
Expose underlay address with NAT address parameters just as it would be communicated in the handshake in order to be discoverable in debugapi addresses response.
expected behaviour:
```
bee start \
--api-addr=:8082 \
--debug-api-enable \
--debug-api-addr=:6062 \
--data-dir=/tmp/bee2 \
--bootnode="" \
--p2p-addr=:7072 \
--swap-enable=false \
--nat-addr=83.95.91.7:7072
```
```
curl -s localhost:6062/addresses | jq
```
```json
{
"overlay": "473662ffe198262e95f74491b8cebe65c2de79b8376f2356cbf6ec7cf923eaac",
"underlay": [
"/ip4/127.0.0.1/tcp/7072/p2p/16Uiu2HAm2a5wd2Bo45haSDUKa5gYKdGJaQWrCVRcMqTSq2s9ossz",
"/ip4/192.168.0.100/tcp/7072/p2p/16Uiu2HAm2a5wd2Bo45haSDUKa5gYKdGJaQWrCVRcMqTSq2s9ossz",
"/ip6/::1/tcp/7072/p2p/16Uiu2HAm2a5wd2Bo45haSDUKa5gYKdGJaQWrCVRcMqTSq2s9ossz", …
```
> expose nat underlay address by p2p service

- pkg/hive/hive.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/p2p/libp2p/internal/handshake/handshake_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/protobuf/protobuf.go
- pkg/p2p/protobuf/protobuf_test.go
- pkg/p2p/streamtest/streamtest.go
- pkg/pingpong/pingpong.go
- pkg/pricing/pricing.go
- pkg/puller/puller.go
- pkg/pullsync/mock/pullsync.go
- pkg/pullsync/pullsync.go
- pkg/settlement/pseudosettle/pseudosettle.go
- pkg/settlement/pseudosettle/pseudosettle_test.go
- pkg/settlement/swap/swapprotocol/swapprotocol.go
This PR adjusts protobuf message read and write calls to use context for cancelation, by either adding it or replacing with timeout variant. More cancelation control is provided with context, so functions with timeout are removed. These changes may improve overall communication in not perfect network conditions and with overloaded peers.
Since pseudosettle is changed to use context in handler while reading a message, TestPayment was very flaky, as the context cancled in Pay method would cancel the context passed to the handler through streamtest Recorder. Two changes were made to fix this. First not to couple client call context with handler context in streamtest Recorder, and the second is are improvements to TestPayment to check for record error and also to synchronize observer call …
> propagate context to message read and write in p2p protocols

- pkg/pusher/pusher.go
- pkg/pusher/pusher_test.go
Change increases timeout for waiting for pending push operations to terminate. When the `Close()` function is invoked on push service, it closes the `quit` channel which triggers closing of the worker, which has logic that waits for some time to terminate all active goroutines through semaphore.
> Wait until pusher active jobs are done on Close

- .github/workflows/beekeeper.yml
- .github/workflows/slash-beekeeper.yml
To be able to differentiate **merge** and **pr** beekeeper runs
> add more info to mattermost fail notifications

- pkg/p2p/protobuf/protobuf_test.go
This PR makes minimal adjustments to fix #702 issue. A difference of 90ms may be too small for rely that goroutines will be scheduled in high load environments like github actions ci may be sometimes.
It was tested several times on ci that tests pass.
fixes: #702
> adjust tests timings in protobuf package

- pkg/settlement/swap/swapprotocol/swapprotocol.go
avoids a deadlock when two nodes send each other cheques at the same time and end up holding their accounting locks of their counterparty preventing both from processing.
> swapprotocol: don't wait for full close in emitcheque

- go.mod
- pkg/p2p/libp2p/libp2p.go
LibP2P TCP transport default behaviour is to use port reuse which allows to open multiple listeners on the same local port. This is confusing as to or more bee nodes can run on the same system with the same p2p port but makes non of them usable as packets are distributed among them.
With this change, bee node will exit with an error if another process is already listening on the same port, just as it is the case with api and debugapi listeners.
> disable port reuse in libp2p

- pkg/node/node.go
Set connection idle and read header timeouts for API and DebugAPI HTTP servers in order to cleanup connections and avoid potential large number of open files. This is something that may improve situation described in https://github.com/ethersphere/bee/issues/867.
> set http server timeouts

- .github/workflows/schedule.yaml
This action will be executed every night at 1am, check if there were any commits in the past 24h, if yes it will trigger (dispatch) `trigger-install` event to bee-argo repo and infra-tests will be executed
> add scheduled run for infra-test

- pkg/api/pss_test.go
Tests in `api/pss_test.go` are flaking. This is apparently since the read timeout for the websocket is set before mining the chunk using the real pss type. We should improve this by mocking pss in this test in a way that we don't need to mine the chunk every time and run through the actual pss code. This PR is meant to serve as a quick fix so everyone can continue working with the CI without needing the restart the builds constantly.
> api: increase pss test read timeout before mining

- pkg/localstore/gc_test.go
- pkg/localstore/index_test.go
- pkg/localstore/mode_get_test.go
- pkg/localstore/mode_set.go
- pkg/localstore/mode_set_test.go
- pkg/localstore/retrieval_index_test.go
- pkg/pullsync/pullsync.go
- pkg/pullsync/pullsync_test.go
- pkg/pusher/pusher.go
- pkg/pusher/pusher_test.go
- pkg/storage/store.go
This PR addresses the problem of data integrity with relation to setting chunk as synced by both pull and push syncing while garbage collection can remove a chunk from retrieval index (as synced by push sync) and leave its address in push index.
As discussed with @zelig and @acud, the chunk should be set as synced only by push sync.
> set chunk as synced only by push sync

- pkg/file/addresses/addresses_getter.go
- pkg/file/addresses/addresses_getter_test.go
- pkg/swarm/swarm.go
Adds new `storage.Getter` implementation that can be used to iterate through chunk addresses for the file.
> Add chunk addresses getter iterator

- pkg/file/file.go
- pkg/file/joiner/joiner.go
- pkg/file/joiner/joiner_test.go
Adds additional function to `file.Joiner` interface for iterating through chunk addresses for the file.
> Add file joiner function for iterating through chunk addresses

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bytes.go
- pkg/api/bzz_test.go
- pkg/api/dirs.go
- pkg/api/file.go
- pkg/file/file_test.go
- pkg/file/joiner/joiner_test.go
- pkg/file/pipeline/builder/builder.go
- pkg/file/pipeline/builder/builder_test.go
- pkg/manifest/manifest.go
- pkg/manifest/mantaray.go
- pkg/manifest/simple.go
Adds a postage batch ID header to the API
related to #872
> api: add postage batch id header

- pkg/postage/export_test.go
- pkg/postage/service.go
- pkg/postage/service_test.go
- pkg/postage/stamp.go
- pkg/postage/stamp_test.go
- pkg/postage/stamper.go
- pkg/postage/stamper_test.go
- pkg/postage/stampissuer.go
- pkg/postage/stampissuer_test.go
- pkg/postage/testing/stamp.go
- pkg/swarm/swarm.go
https://github.com/ethersphere/bee/issues/874
> postage: new pkg for postage stamps, uploader stamping

- go.mod
- go.sum
- pkg/collection/entry/entry.go
- pkg/file/joiner/joiner.go
- pkg/file/joiner/joiner_test.go
- pkg/manifest/manifest.go
- pkg/manifest/mantaray.go
- pkg/manifest/simple.go
- pkg/storage/mock/storer.go
- pkg/traversal/traversal.go
- pkg/traversal/traversal_test.go
Introduces package for traversing chunk addresses. It does so for bytes, files, and manifests.
It does make some (less-than-ideal) assumptions for detecting if a content is actually file or manifest.
Contains some additional optimization for checking various for types.
> Chunk traversal

- .github/workflows/beekeeper.yml
- .github/workflows/go.yml
- .github/workflows/schedule.yaml
- .github/workflows/slash-beekeeper.yml
Github action deprecated usage of command `::set-env` and `::add-path`
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
There is new way of [defining ENV variables and PATH](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable)
New version of setup-go `actions/setup-go@v2` sets all needed ENV variables
> fix all set-env and add-path

- cmd/bee/cmd/start.go
- openapi/SwarmCommon.yaml
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/p2p.go
- pkg/debugapi/p2p_test.go
- pkg/node/node.go
This PR introduces a dedicated PSS private key, log it to the user and exposes it in debug api /addresses endpoint.
This PR also makes a change to check for libp2p key if it exists when testing if keys are created for the first time. Previously, the swarm key was checked, but it may not be there if clef is used as an external signer, resulting in asking for password twice.
> add PSS dedicated private key

- cmd/bee/cmd/start.go
- pkg/node/node.go
Inform the user about her generated Ethereum address as soon as possible when calling `bee init` or `bee start`. Fixes #969
> Log ethereum address on bee init/start

- pkg/kademlia/kademlia.go
- pkg/kademlia/mock/kademlia.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
- pkg/topology/full/full.go
- pkg/topology/mock/mock.go
- pkg/topology/topology.go
Updates `pushsync.PushChunkToClosest` function with the change where it will attempt multiple peers if one fails.
Previous code only ever attempted to push to same peer (that was deemed as "closest"), even in the face of problems with that host. This change adds loop which attempts closest peer, and if there are some problems with that peer tries some other closest peer (from the available ones). Depending on the error, it may blocklist the peer for some time (one minute). It will try to maximum of `5` peers. If each of them fails it will return last error that was encountered.
Note that new code still uses original `ClosestPeer` function, in which case it will again be possible that selected peer will be "self". If we want to change this, it would be possible.
> Pushsync retry next peer after error

- openapi/Swarm.yaml
- pkg/api/export_test.go
- pkg/api/pin_chunks.go
- pkg/api/pin_chunks_test.go
- pkg/api/router.go
This change adds additional HTTP route, which allows caller to change pin counter of some chunk.
This can be done through `PUT` call on `/pin/chunks/{address}` endpoint, with the following JSON request:
```json
{
"pinCounter": 0
}
```
If the request is performed with the example request body, it should completely unpin specified chunk.
> Add API for changing pin counter

- openapi/SwarmDebug.yaml
- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/accounting/mock/accounting.go
- pkg/debugapi/balances.go
- pkg/debugapi/balances_test.go
- pkg/debugapi/router.go
This PR involves all changes from:
https://github.com/ethersphere/bee/pull/870
And...
introduces new endpoints:
/consumed
/consumed/{peer}
The /balances/{peer} and /balances endpoints now show balances deducted by surplus balances for easy comparison of balances in integration tests.
The consumed endpoint shows current balance disregarding the surplus balance, as we consider the surplus balance sort of a pre-paid service solution.
The other part of the PR concerns Reserve checking for the balance adjusted by surplus balance so that we avoid an overdraft when a situation occurs, in which our node gets an oversettlement, and keeps reserving balance while the surplus balance does not naturally drain by requests coming from the peer.
In this situation, the other side might have processed …
> Surplus balances for peers, debug API addons

- pkg/settlement/swap/chequebook/chequebook.go
currently all operations for signing and sending a cheque happen under one global lock on the chequebook. while already not ideal already, this has devastating throughput effects with clef (where signing takes longer).
this PR puts only the shared state under that lock. there is no explicit per peer lock for the other part as settlement is called under that peers accounting lock anyway.
> don't hold global chequebook lock while sending cheque

- openapi/SwarmDebug.yaml
- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/accounting/mock/accounting.go
- pkg/debugapi/balances.go
- pkg/debugapi/balances_test.go
- pkg/debugapi/router.go
The aim of this PR is to add safety for settlements that have an amount over current balance.
If a peer sends us an oversettlement, we want the extra amount to be stored as a reserve for future forwarding services towards the peer, but we do not want it to be part of regular balance, so that it can not form the base for triggering a settlement back.
> Surplus balances for peers

- pkg/accounting/accounting.go
- pkg/node/node.go
- pkg/settlement/interface.go
- pkg/settlement/pseudosettle/mock/pseudosettle.go
- pkg/settlement/pseudosettle/pseudosettle.go
- pkg/settlement/pseudosettle/pseudosettle_test.go
- pkg/settlement/swap/mock/swap.go
- pkg/settlement/swap/swap.go
- pkg/settlement/swap/swap_test.go
- pkg/settlement/swap/swapprotocol/swapprotocol.go
restores waiting for full close on sending cheques which solves problems on the real network when nodes use external blockchain nodes. to avoid reintroducing the deadlock fixed in #860, swap now calls notifypayment in a go routine. Furthermore to simplify the code this PR removes the payment observer and just passes the notify func to settlement directly.
solution 1 from #892
> call notifypayment in go routine in swap and restore full close

- pkg/accounting/accounting.go
fixes a check where the wrong payment threshold was used (ours instead of the peers). (this bug was already in the 0.3 releases but probably did not surface because everybody is using the same threshold)
> use correct payment threshold in final reserve check

- pkg/pushsync/pushsync.go
various push sync logs don't display correctly due to usage of `%w` in logging
> fix pushsync logs

- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
as payment tolerance is no longer used as a limit for incoming debt we can remove the `PaymentTolerance > PaymentThreshold/2` check.
> remove payment tolerance check

- pkg/api/gatewaymode_test.go
- pkg/api/router.go
As noticed by @acud and confirmed by @zelig https://beehive.ethswarm.org/swarm/pl/mrjeug54n7gwfcd3qmrxrtwnrw.
> forbid PSS API endpoints in the Gateway mode

- pkg/settlement/swap/chequebook/init.go
So that it's easier to copy&paste the link to the goerli faucet.
> Remove period from log output

- .github/workflows/beekeeper.yml
- .github/workflows/slash-beekeeper.yml
pullsync integration tests are not needed at this point, since we cannot ensure that a chunk has designated replicators.
> github: disable pullsync integration tests

- go.mod
- go.sum
- pkg/api/api.go
- pkg/api/bzz.go
- pkg/api/bzz_test.go
- pkg/api/dirs.go
- pkg/api/dirs_test.go
- pkg/api/file.go
- pkg/file/io.go
- pkg/file/loadsave/loadsave.go
- pkg/manifest/manifest.go
- pkg/manifest/mantaray.go
- pkg/manifest/simple.go
- pkg/traversal/traversal.go
- pkg/traversal/traversal_test.go
this is needed so we don't need to pass `crypto.Signer` and batch IDs to the manifest package as part of the storage incentives effort
needed for #873
> api, manifest: abstract saver/loader functionality

- pkg/kademlia/kademlia.go
- pkg/p2p/libp2p/libp2p.go
- pkg/pricing/pricing.go
- pkg/puller/puller.go
This PR was created based on a short discussion with @crtahlin , where he was unsure about whether the bee node ran smoothly (assumingly based on seeing the word "error" in log messages)
> Remove "error" from log messages

- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/peer.go
relates to: #1034 
Change the way how we check if some peer is connected.
In addition to checking `libp2p` peer ID, it also checks if that peer is connected through expected address (see related issue for more in-depth explanation of the problem). Only in the case when both parts are same can we say for sure that we have multiple connections to same peer.
One additional change was to one test, `TestDoubleConnectOnAllAddresses`, which was failing most of the times (few times it passed). Change involves actually changing when the other "peer" is created, and we create new peer for each address that we test for. This was done because there does not seem to be a way to make sure connection to other peer is completely terminated.
What was happening was that once a connection is created to …
> Resolve peer topology inconsistencies

- pkg/accounting/accounting.go
Right now, if the peer only has surplus balance (never had any interactions with a peer only received a settlement that went into surplus) with a peer, we would not show it's balance on the balances endpoint, because of error propagation. 
We currently don't have a scenario where this could happen.
If we used pre-settlements for any reason in the future, this change would avoid not showing peers that only pre-settled yet.
> Compensated Balances error suppression fix

- pkg/resolver/client/ens/ens.go
- pkg/resolver/client/ens/ens_integration_test.go
- pkg/resolver/client/ens/ens_test.go
- pkg/resolver/client/ens/export_test.go
- pkg/resolver/multiresolver/multiresolver.go
Pass the contract address parameter to the ENS client, allowing for an alternate address for the ENS contracts suite.
Completes #625
> Add ENS contract address parameter to config

- pkg/api/pin_bytes.go
- pkg/api/pin_bzz.go
- pkg/api/pin_chunks.go
- pkg/api/pin_files.go
- pkg/localstore/mode_put.go
- pkg/localstore/mode_put_test.go
- pkg/localstore/mode_set.go
- pkg/localstore/pin_test.go
- pkg/node/node.go
- pkg/storage/mock/storer.go
- pkg/storage/store.go
relates to: #571 
Pinning operations are changed to fetch all (locally) missing chunks.
New storage mode was added, the `storage.ModePutRequestPin`, which performs pin operation in the same time when the chunk is retrieved. This new mode might not be required, but it is safer than having fetch-pin-check operations in succession.
Modified `storage.ModeSetPin` operation, to check if the chunk exists locally before performing pin operation, under same lock (changed Mock storage also). This caused some changes on how the chunk is being pinned.
> Fetch chunks from network when pinning

- pkg/kademlia/kademlia.go
- pkg/p2p/libp2p/libp2p.go
If (for some reason) peer changes its Swarm network address (`overlay` address), and then joins again, because it will have same P2P peer ID, some peer may be marked as already connected even though it is not.
Handling of `p2p.ErrAlreadyConnected` error is changed to actually check if the already connected `overlay` address matches to the one we are trying to connect. If that is in fact the case, we correct that is the same peer, otherwise we return an error or try to connect again.
> If P2P connection exists compare overlay address

- cmd/bee/cmd/start.go
- cmd/bee/cmd/start_unix.go
- cmd/bee/cmd/start_windows.go
- go.mod
- go.sum
Adds support for running Bee as a service.
This change similar to previous one, main thing here is that we add support for writing logs to Windows Event Log, which is only enabled if we are running as Windows service. The #943 was making usage of `github.com/kardianos/service` library fully, while these changes only use it if we detect that Bee is running as Windows service.
The name for the service is `BeeSvc`. This same name must be fixed, and same one must be used when installing service on Windows machine.
To create the service on Windows run:
```
sc.exe create BeeSvc binPath="[INSTALLDIR]bee.exe start --config=[INSTALLDIR]bee.yaml" type=share start=auto displayName="Bee"
```
Note that configuration file must be properly modified, in order for Bee to be able to start properly. I …
> Windows service support

- pkg/kademlia/kademlia.go
- pkg/p2p/libp2p/internal/handshake/handshake.go
our staging cluster is constantly trying to connect to itself, and because attempt counts are not limited the kademlia iterator never returns from the `connectBootnodes` call.
we probably have other connectivity problems, but we don't have enough visibility on what's going on due to insufficient logging which is mended in this PR.
Another problem is that nodes may get their own address from the DNS discovery and try to connect to themselves. I therefore added a check to `parseCheckAck` to check that a node does not try to connect to itself. This verification is done in the Ack, when a node sends his overlay address.
> kademlia: limit bootnode connection attempts

- pkg/traversal/traversal.go
relates to: #1079 
Some trie node size from `mantaray` manifest will have size of `128` bytes, which lines up with the size of encrypted `entry.Entry` struct. In that case entry will result in two encrypted addresses (`64` bytes each), which are in itself valid. Since this case happens for trie node for non-encrypted addresses (which should have `32` byte size), we should check of unmarshaled entry address is the same size as actual reference for suspected file.
> Improve checking if file in traversal service

- go.mod
- go.sum
- pkg/api/bzz_test.go
- pkg/api/dirs.go
- pkg/api/dirs_test.go
- pkg/api/file_test.go
- pkg/api/pin_bzz_test.go
- pkg/api/tag_test.go
- pkg/manifest/manifest.go
- pkg/manifest/mantaray.go
- pkg/traversal/traversal_test.go
relates to: #1006 
Change behavior for upload to `/dirs` endpoint so that non-encrypted uploads will force `mantaray`-based manifest not to use random obfuscation key for each upload. This means that for multiple uploads of the same content to have same root hash will be generated.
> Random manifest obfuscation key only when encrypting

- openapi/SwarmCommon.yaml
When using the `/peers` `GET` endpoint I found that the documentation is with uppercase but the actual value returned is in lowercase. This PR fixes the schema definition from where the documentation is generated.
> fix address property name in openapi schema

- pkg/api/dirs_test.go
- pkg/api/file_test.go
- pkg/api/pin_bzz_test.go
Switches to using `jsonhttptest.WithUnmarshalJSONResponse` instead of `jsonhttptest.WithPutResponseBody` in tests (I was not aware of first function at the time of writing tests, although I did look for it).
> Simplify JSON response extraction in tests

- cmd/bee/cmd/start.go
I found it useful to print out the version on startup when debugging different versions of Bee. Please note that it is only printed with debug loglevel.
> print version on startup in debug mode

- pkg/crypto/signer_test.go
This PR adds a deterministically generated signature, so that other language implementations can use it as a reference for implementation.
cc @agazso
> crypto: add deterministic signer test

- pkg/postage/batch.go
- pkg/postage/batch_test.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/postage/batchstore/export_test.go
- pkg/postage/batchstore/mock/store.go
- pkg/postage/batchstore/mock/store_test.go
- pkg/postage/batchstore/store.go
- pkg/postage/batchstore/store_test.go
- pkg/postage/chainstate.go
- pkg/postage/interface.go
- pkg/postage/mock/service.go
- pkg/postage/mock/stamper.go
- pkg/postage/service.go
- pkg/postage/stamp.go
- pkg/postage/stamp_test.go
- pkg/postage/stamper.go
- pkg/postage/stamper_test.go
- pkg/postage/stampissuer.go
- pkg/postage/testing/batch.go
- pkg/postage/testing/chainstate.go
- pkg/postage/testing/stamp.go
This PR tracks the initial implementation to the postage `BatchStorer` and `EventUpdater` interfaces
- `BatchStore` handles storage of batches and `ChainState` via a storer interface
- `BatchService` implements the `postage.EventUpdater` interface and manages the business logic of postage batches
This should provide the skeleton for further features in the `postage` package.
related to #1046 #922 and parts of #934
> Postage BatchStore and BatchService

- pkg/postage/interface.go
- pkg/postage/listener/abi.go
- pkg/postage/listener/export_test.go
- pkg/postage/listener/listener.go
- pkg/postage/listener/listener_test.go
supersedes https://github.com/ethersphere/bee/pull/934 and https://github.com/ethersphere/bee/pull/921
> postage: add event listener

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- pkg/node/node.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/postage/batchstore/store.go
- pkg/postage/interface.go
- pkg/postage/listener/export_test.go
- pkg/postage/listener/listener.go
- pkg/postage/listener/listener_test.go
* add flags for contract addresses
* this reuses swap endpoint which means swap endpoint is required even if swap is off
* adds updateBlockNumber to event updater
* node.go wiring
> wire up postage stamp syncing

- pkg/api/api.go
- pkg/localstore/export.go
- pkg/localstore/export_test.go
- pkg/localstore/localstore.go
- pkg/localstore/localstore_test.go
- pkg/localstore/mode_get.go
- pkg/localstore/mode_get_multi.go
- pkg/node/node.go
- pkg/postage/service.go
- pkg/pusher/pusher_test.go
- pkg/pushsync/pushsync.go
- pkg/shed/index.go
- pkg/storage/testing/chunk.go
- pkg/swarm/swarm.go
> localstore, shed: persist stamps

- pkg/api/api.go
- pkg/api/chunk.go
- pkg/api/router.go
- pkg/api/tag.go
- pkg/api/tag_test.go
We now create a tag on each individual chunk upload.
This behavior is now changed to never create a new tag, but detect whether an existing tag uid was given in the header. In case it was provided - it will increment the appropriate fields, otherwise it will not create a new tag. Returns an error if the given tag id was not found.
related to #877
> api: dont create tag on chunk upload

- pkg/retrieval/export_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
- pkg/retrieval/skip_peers.go
relates to: #1081 
During chunk retrievals some peers may take more time to respond. Current process is to wait max possible time for client to respond with the chunk (if they manage to find it), and only when time passes (or client responds with an error) do we try to contact next peer (up to maximum number of peers configured).
This change adds additional time duration (that is less than maximum timeout for client to respond). If that duration passes, and the contacted peer has not provided response, we preemptively make another request to some other peer. This is in an attempt to mitigate problem with peers that are slow with their responses.
Current code will wait for any started retrieve request to complete, in order to credit any peer with successful delivery.
The configuration now …
> Perform preemptive retry for chunk retrieval

- cmd/bee/cmd/start.go
to discourage the usage of bee without bee-clef
> add a warning message when the user is not using clef

- pkg/node/node.go
- pkg/settlement/swap/transaction/backend.go
- pkg/settlement/swap/transaction/backend_test.go
- pkg/settlement/swap/transaction/backendmock/backend.go
waits for eth backend to be synced (latest block less than a minute in the past) on startup. this is necessary to ensure we don't reject valid chequebooks or the chequebook factory if running against an unsynced eth node (e.g. if goerli-geth was installed via dappnode at the same time as bee).
> wait for eth backend to be synced on startup

- pkg/p2p/libp2p/libp2p.go
relates to: #1074
In IPv6, the all-zeros address is represented by "`::`" (in short notation).
> IPv6 default host address be same as for IPv4

- pkg/debugapi/peer.go
- pkg/debugapi/peer_test.go
- pkg/debugapi/router.go
- pkg/p2p/libp2p/internal/blocklist/blocklist.go
- pkg/p2p/libp2p/internal/blocklist/blocklist_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
- pkg/statestore/mock/store.go
adds a debugapi to view currently blocklisted peers. if a peer is in the blocklist but the duration has already expired, it will not show up in the endpoint. however, unlike in the `blocklist.Exists` method, the entry will not get deleted while querying this endpoint, in order to reduce side-effects.
ref https://github.com/ethersphere/bee/issues/1053
> libp2p, debugapi: add API to view blocklisted peers

- pkg/api/postage.go
- pkg/api/postage_test.go
api returned base64 encoded id instead of hex.
> api: use hex encoding in postage api

- pkg/postage/listener/listener.go
increase page size to 10000. should allow syncing goerli <1min.
might be too big for real usage.
> postage: bigger page size

- pkg/localstore/subscription_push.go
Fixes a bug where outgoing chunk on pushsync did not have stamp attached to it
> localstore: attach stamp to outgoing chunk

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bytes.go
- pkg/api/chunk.go
- pkg/api/dirs.go
- pkg/api/export_test.go
- pkg/api/file.go
- pkg/api/router.go
- pkg/api/tag.go
- pkg/api/tag_test.go
- pkg/debugapi/export_test.go
- pkg/debugapi/router.go
- pkg/debugapi/tag.go
- pkg/debugapi/tag_test.go
- pkg/encryption/encryption.go
- pkg/localstore/mode_set_test.go
- pkg/manifest/manifest.go
- pkg/manifest/mantaray.go
- pkg/manifest/simple.go
- pkg/pusher/pusher_test.go
- pkg/pushsync/pushsync_test.go
- pkg/swarm/swarm.go
- pkg/tags/tag.go
- pkg/tags/tag_test.go
- pkg/tags/tags.go
- pkg/tags/tags_test.go
relates to: #1147
Changes to public `/tags/{id}` API.
The current tags API response returns following object:
```json
{
"uid": 1066766601,
"name": "unnamed_tag_1611322188",
"startedAt": "2021-01-22T14:29:48+01:00",
"address": "<hash>",
"total": 26,
"split": 26,
"seen": 4,
"stored": 26,
"sent": 33,
"synced": 22
}
```
Suggested change to this response would produce following object:
```json
{
"uid": 1066766601,
"startedAt": "2021-01-22T14:29:48+01:00",
"total": 26,    // the total number of chunks for upload(s) related with this tag (estimated until tag is done)
"processed": 26,    // the total number of chunks stored and queued for sending
"synced": 26    // the total number of chunks that are synced with the network (now of before)
}
```
Idea behind this is to have 2 names that would …
> Simplify public tags API response

- pkg/pusher/pusher.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
- pkg/topology/mock/mock.go
There's quite a bit of overlap in pushsync package logic. `handler` makes use of the same logic as `PushToClosest`. This PR changes the package to reuse that logic. It will also make use of the retry logic which is present in the `PushToClosest` method, resulting in retries when forwarding pushed chunks.
Also, some tests needed some clean up since they resulted in flow control events which are unnatural to the package in production.
> pushsync: clean up

- .github/workflows/beekeeper.yml
- .github/workflows/slash-beekeeper.yml
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/chequestore.go
there were some issues with the storage key formatting introduced in breaking pr.
the change is backwards compatible.
one ugly hack is that the key prefix for issued cheques is `swap_chequebook_last_issued_cheque_` but for received ones it is actually `swap_chequebook_last_received_cheque__`. I left it that way because there were already cheques sent on staging since the reset.
> swap: fix storage keys

- cmd/bee/cmd/cmd.go
- pkg/settlement/swap/chequebook/init.go
- pkg/settlement/swap/transaction/backend.go
- pkg/settlement/swap/transaction/backendmock/backend.go
due to obtaining gETH and gBZZ no longer being the same operation, users might run into the scenario of having BZZ on their overlay but no ETH.
This PR
* checks there is sufficient ETH available on initial startup (previously only BZZ was checked).
* shows how much BZZ is needed (this might not be obvious to the user if the deposit amount is not specified manually)
* rounds up BZZ for the bazaar link if not an exact number of BZZ
* increases default deposit to 10 BZZ
> check eth balance on initial startup and show required funds

- pkg/postage/listener/listener.go
update the goerli postage stamp defaults to contracts which use the new token. should be merged after `storage-incentives` was rebased on `master`. nodes which synced the batch store before should reset their state store.
> postage:  update contract addresses for new token

- openapi/Swarm.yaml
relates to: #1181 
Document `offset` and `limit` query parameters on endpoints where they can be used.
> Include offset and limit in API specification

- pkg/api/api.go
- pkg/api/bytes.go
- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/dirs.go
- pkg/api/feed.go
- pkg/api/file.go
- pkg/api/pin_bytes.go
- pkg/api/pin_bzz.go
- pkg/api/pin_chunks.go
- pkg/api/pin_files.go
- pkg/api/pss.go
- pkg/api/router.go
- pkg/api/soc.go
- pkg/api/tag.go
The fields on the HTTP API are exported for no particular reason, and are therefore unexported in this PR.
> api: unexport api struct fields

- .goreleaser.yml
- packaging/bee.yaml
- packaging/homebrew/bee.yaml
- packaging/rpm/post
Set `https://rpc.slock.it/goerli` as a `swap-endpoint` for deb, rpm and brew packages
@Eknir should I set that as a default for docker-compose?
> set swap-endpoint to slock.it goerli for deb, rpm and brew package

- packaging/bee-get-addr
- packaging/homebrew/bee-get-addr
Changed funding URL to bzzaar for `bee-get-addr` script
> fix funding addr for both linux and mac bee-get-addr

- pkg/api/bzz.go
Happens when the root manifest is created, but before the initial feed update has been uploaded to the network.
resolves #1241
> api: fix bzz dereference when no updates posted

- pkg/intervalstore/store_test.go
- pkg/node/node.go
- pkg/statestore/leveldb/leveldb.go
- pkg/statestore/leveldb/leveldb_test.go
It appears that the statestore might shut down in an unclean state, resulting in a corrupted db.
This PR adds an attempt to recover the statestore whenever a corrupt state is detected.
refers to a bug reported in https://github.com/ethersphere/bee/issues/1232
This is obviously controversial as it can yield some other strange states, I am open for suggestions or scratching this entirely.
> statestore: try to recover leveldb on corrupted db

- pkg/tags/tags.go
- pkg/tags/tags_test.go
Persisted tags were never removed from statestore on `Delete`, which has resulted in deleted tags to be reloaded on node restart.
addresses https://github.com/ethersphere/bee/issues/1252
> tags: delete persisted tag

- pkg/settlement/swap/chequebook/cashout.go
- pkg/settlement/swap/chequebook/cashout_test.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/chequebook_test.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/chequebook/factory_test.go
- pkg/settlement/swap/transaction/transaction.go
- pkg/settlement/swap/transaction/transaction_test.go
add support for deployment transaction in the transaction service. this is not currently used in bee itself, but is useful for some tools which are used to deploy the swap core contracts which currently have to include a slightly modified version of bees `transaction.Service`.
> transaction: add support for deployments

- packaging/docker/env
Related to https://github.com/ethersphere/docs.github.io/pull/133
The values inside the docker-compose .env file should not contain quotes. Otherwise these will be included in the values and we start seeing errors i ike :
```
Error: parse "\"https://rpc.slock.it/goerli\"": first path segment in URL cannot contain colon
```
> packaging/docker: remove quotes from compose .env file

- pkg/crypto/mock/signer.go
- pkg/node/node.go
- pkg/settlement/swap/transaction/backend.go
- pkg/settlement/swap/transaction/transaction.go
- pkg/settlement/swap/transaction/transaction_test.go
adds simple nonce tracking. this does not capture all edge cases but should work better than what we have currently when trying to send multiple transactions concurrently. further PRs will refine this mechanism later.
The logic is as follows:
* next nonce to be used is stored locally in state store
* if there is already a higher nonce response from the backend we skip forward to that (to prevent the node from getting stuck if the private key is used outside bee)
* if there is no nonce stored yet, we use the value returned from the backend
Note: this was tested with 100 concurrent deposit transactions with a local geth and goerli infura.
> transaction: add simple nonce tracking

- pkg/api/file.go
This PR adds the `Content-Disposition` header to the exposed headers for CORS request.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
Fixes https://github.com/ethersphere/bee-js/issues/86
The original problem is that filename is sent in the `Content-Disposition` header when a file is downloaded from the `/files` endpoint, but in the case of a cross-origin request by default it is not exposed (e.g. Javascript applications in the browser such as anything built with bee-js has no access to that value). This PR fixes that by exposing the `Content-Disposition` header, therefore making it available. From a security perspective we can say that it's safe to expose the filename because the requester has already access to the full file data.
> fix: expose content-disposition HTTP header for CORS requests

- pkg/p2p/libp2p/stream.go
Using our `FullClose` helper method might not always result in streams being garbage collected. This PR adds a defer call to close the stream in any case when the method returns
> libp2p: always close streams

- go.mod
- go.sum
- pkg/p2p/libp2p/static_resolver.go
- pkg/p2p/libp2p/static_resolver_test.go
when forming multiaddr there is a check if dns entry is valid so we need to check if dns entry has only one type of A record or has both A and AAAA. we set `dns4`, `dns6` or `dns` as proto for multiaddr
> enable dns entry for nat-addr

- pkg/settlement/swap/transaction/backend.go
sleep was missing for sync check. therefore we bombarded unsynced backends with maximum througput.
> add sleep for sync check

- pkg/pullsync/pullstorage/pullstorage_test.go
The `TestIntervalChunks_NoChunksLater` is flaky by design and the test case which it is testing for is implicitly covered by `TestIntervalChunks/some_in_the_middle` test case. I therefore consider this test redundant and safe to remove.
> pullstorage: remove flaky test

- pkg/api/soc.go
- pkg/api/soc_test.go
SOCs are not content addressed, therefore SOCs with different content addressed chunks in their payload can result in the same SOC address.
This PR adds a check in the API, to verify that a chunk with the same address does not exist in the localstore before inserting it.
addresses #1247
> api: dont accept two soc's with the same address

- pkg/accounting/accounting.go
the payment threshold field was set as a reference instead of a copy. therefore receiving a payment threshold update actually updated our own payment threshold as well.
I added copying to the numbers that are passed to accounting as well to avoid further unexpected surprises (e.g. many tests pass the same paymentThreshold parameter which could cause cross test effects if it were to be mutated).
> accounting: copy big numbers in various places

- packaging/docker/docker-compose.yml
new clef is released, bumping clef version inside docker-compose
> bump clef version

- pkg/shed/db.go
Users are experiencing a lot of I/O coming from bee. This PR attempts to tweak some of the leveldb parameters in order to improve the situation.
> shed: improve leveldb configuration

- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
This reverts commit 8bca1737fee541f29837880bd55b42a58d7b6b7d.
Longstanding cleanup
> Revert "kademlia: hotfix for peer list inconsistency (#1020)"

- pkg/crypto/clef/clef.go
- pkg/crypto/mock/signer.go
- pkg/crypto/signer.go
- pkg/crypto/signer_test.go
- pkg/node/node.go
- pkg/settlement/swap/transaction/transaction.go
- pkg/settlement/swap/transaction/transaction_test.go
required for compatibility with the next geth version. clef already used eip155 out of the box.
> use eip155 signing in in-memory signer

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/deploy.go
- pkg/node/chain.go
- pkg/node/node.go
- pkg/node/statestore.go
This PR adds the deploy command to bee. The `deploy` command will deploy the chequebook using the configured factory address. This is the same functionality from `start`, extracted to a separate command.
I've performed a basic test:
1. Calling deploy
2. Funding BZZ and ETH
3. Waiting for deploy to finish
4. Calling start
Expected outcome was reached: upon running `start`, bee detects and uses the same chequebook from deploy.
> Add deploy command to bee

- go.sum
- pkg/node/chain.go
format error introduced in deploy pr. also removes use of `go-log.v1 ` which was used by accident in the same pr.
> fix output of factory address

- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/p2p.go
- pkg/debugapi/router.go
- pkg/debugapi/status.go
- pkg/node/node.go
This PR introduces a two step Debug API router configuration.
Currently, debug api http listener is exposed at the end of the node starting process, when all of the services are constructed. This is a problem if there is a long running process, like localstore migration, and the /health endpoint is not exposed for a long time for kubernetes health check. This PR creates a debug api listener at the start of node initialization, exposing /health, /addresses and some other available debug endpoints, like metrics, pprof and vars. After all of the debug api dependencies are constructed, debug api service is configured with them and a full router is set.
This PR is with the minimal set of changes for this to be accomplished. A followup PR can be done to remove debugapi.Service interface and …
> debug api basic and full routing

- go.mod
this was introduced by accident in #1314, then removed in #1357, then reintroduced by accident in #1345 which changed the same file
> remove go-log.v1 yet again

- .github/workflows/beekeeper.yml
uses the new beekeeper flag to wait longer (10s instead of 5s) before checking. gc tests probably fail because gc is slower in ci.
beekeeper has been run several times on this branch. `gc-chunk-1` never failed.
> increase wait time in gc-chunk

- pkg/node/chain.go
- pkg/node/node.go
- pkg/settlement/swap/chequebook/bindings.go
- pkg/settlement/swap/chequebook/cashout.go
- pkg/settlement/swap/chequebook/cashout_test.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/common_test.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/chequebook/factory_test.go
- pkg/settlement/swap/transaction/backend.go
- pkg/settlement/swap/transaction/event.go
- pkg/settlement/swap/transaction/event_test.go
this is the first in a series of PRs which remove the use of `abigen`-generated bindings in favour of just using the few things we need directly. the reason behind this move is that generating correct abigen bindings for the correct go-ethereum version can be tricky (e.g. bindings for `>1.9.23` can only be generated with `master`, not with `1.9.23` or `1.9.25`), we can't really use them for all the things we need (we already bypass them for transaction sending and our event parsing was a bit of a hack which cannot differentiate between errors properly) and its 95% unused boilerplate code. the idea is to instead just have the abi json and the bytecode hex in our generated go library for the contracts.
This PR
* parses ABIs into package package level vars and panic if that fails (as is done …
> chequebook: better event parsing

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- pkg/crypto/clef/clef.go
- pkg/crypto/clef/clef_test.go
add a flag to enable specifying which clef account to use. It's important that if this is specified it also needs to be specified on any further run of that bee node. in a future pr the used overlay should be stored and checked.
this helps against the following problems:
* new keys are added to clef and the original is no longer at index 0
* multiple bees using the same clef
> clef: allow specifying account

- pkg/p2p/libp2p/static_resolver_test.go
CI is broken since it tries to close the broken package on the windows build, which disrupts the whole CI process.
I moved the test bootstrapping into the actual test run to avoid calling the broken package.
> libp2p: skip dns test entirely on windows

- pkg/debugapi/balances.go
- pkg/debugapi/chequebook.go
- pkg/debugapi/chunk.go
- pkg/debugapi/cors.go
- pkg/debugapi/cors_test.go
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/metrics.go
- pkg/debugapi/p2p.go
- pkg/debugapi/peer.go
- pkg/debugapi/pingpong.go
- pkg/debugapi/router.go
- pkg/debugapi/settlements.go
- pkg/debugapi/tag.go
- pkg/debugapi/topology.go
- pkg/debugapi/welcome_message.go
- pkg/node/node.go
This PR is a followup on https://github.com/ethersphere/bee/pull/1358 comments on code improvements.
- interface is removed for simplification as its purpose is not justified with the complex method that it contains
- server struct is renamed to Service and all fields are unexported
- cors headers handling is contained into one file with a dedicated handler
- basic tests for cors headers are added
> debug api as a concrete service

- cmd/bee/cmd/deploy.go
- cmd/bee/cmd/init.go
- pkg/node/node.go
- pkg/node/statestore.go
currently a bee node will happily start up with a different overlay key which breaks accounting, settlement and probably a ton of other stuff. this pr saves the expected overlay address on first boot and then checks it on every further startup. the check happens on `start`, `init` and `deploy` command.
this prevents user errors such as
* deleting swarm.key but not statestore
* changing key in clef but not deleting statestore
* adding key to clef which takes index 0 in the account list but not deleting statestore or specifying the account explicitly
* specifying another account with `clef-signer-ethereum-address` (from PR #1313) on a second run.
> prevent nodes from starting with a different overlay

- pkg/p2p/streamtest/streamtest.go
- pkg/pricing/pricing_test.go
- pkg/pushsync/pushsync_test.go
- pkg/retrieval/retrieval_test.go
- pkg/settlement/pseudosettle/pseudosettle_test.go
This rectifies the mistake we had in the recorder, where the `p2p.Peer` that we called the handler call with was the wrong address, carrying over the destination address, instead of the origin address of the message.
There is still one todo here, and that is to rewrite the preemptive retry test to use mocked server responses instead of the current behavior which is injected through a middleware if statement. Since this change is a blocker for @esadakar's PR, I'd rather have it in so he can rebase, then we can mend the skipped test.
> streamtest: add option to add a correct base address

- pkg/node/node.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/libp2p_test.go
Since the libp2p instance is created before the entire node goes online, some nodes might already be able to dial into the node, causing the handshake to pass, but to subsequent protocol bootstrapping to fail. This change adds a `Ready` call to libp2p abstraction which will be called once the node constructor finishes. It will block incoming connections before the node bootstrapping is done, preventing inconsistent state on other nodes in the meanwhile.
> libp2p: wait for readyness before accepting incoming connections

- pkg/node/chain.go
- pkg/settlement/swap/chequebook/bindings.go
- pkg/settlement/swap/chequebook/common_test.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/chequebook/factory_test.go
- pkg/settlement/swap/transaction/mock/transaction.go
- pkg/settlement/swap/transaction/transaction.go
this is the second in a series of PRs which remove the use of abigen-generated bindings in favour of just using the few things we need directly building on top of #1360.
This PR
* removes the use of bindings in `factory.go` instead doing the call via the transaction service (`Call` was copied from `storage-incentives`)
* adds abi-aware helpers to the `transaction` mock for more ergonomic checking of wether the `TxRequest`s are correct.
* adds the `transactionmock.WithABICallSequence` helper which is not used directly in this PR but in follow-ups where functions with more than one call need to be tested.
> chequebook: remove use of bindings for factory

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/node/node.go
As a result of #1352, nodes will limit the amount of incoming connections from other peers.
This is an undesirable for our bootnodes, which should be accepting more incoming connections so that new peers can get informed about the rest of the network.
In the future we should improve this by accepting new nodes in bootnode mode and either give them a list of peers to connect to, or just kick away old nodes that have been connected for a while (oldest, perhaps), so that we rotate the network that the bootnode sees, without prioritizing or preferring certain nodes over others.
> kademlia, cmd, node: add bootnode-mode flag

- go.mod
- pkg/statestore/leveldb/export_test.go
- pkg/statestore/leveldb/leveldb.go
- pkg/statestore/leveldb/leveldb_test.go
- pkg/statestore/leveldb/migration.go
- pkg/statestore/leveldb/migration_test.go
- pkg/statestore/mock/store.go
- pkg/statestore/test/store.go
This PR adds migration capabilities to our leveldb statestore implementation. Implementation was adapted from the localstore migration code
> statestore: add migration capabilities

- pkg/pullsync/pullsync.go
- pkg/pullsync/pullsync_test.go
This should also improve the CPU usage, since leveldb doesn't need to do individual writes. The downside is that because it might take longer to do the actual write, we might end up wanting the same chunk from multiple peers since this creates a possible data race (we want the chunk from one peer which is slow, and another peer which is fast, resulting in deliveries from both).
Open for discussion about this. Not entirely sure if it's needed if we get the other change which buffers the triggers to the subscriptions, which should solve the problem.
> pullsync: coalesce batch writes

- pkg/p2p/libp2p/static_resolver_test.go
this is now FUBAR. following up with the mockdns package maintainer on this
> libp2p: skip static resolver tests on windows completely

- pkg/file/pipeline/builder/builder_test.go
- pkg/file/pipeline/feeder/feeder.go
- pkg/file/pipeline/feeder/feeder_test.go
fixes a regression caused by #1267, which in turn caused #1332
> pipeline: add special case for empty file

- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/swarm/proximity.go
- pkg/swarm/swarm.go
relates to: #57 
Using base address for starting node of `00000000` rest of description is made here.
For that base address we have following (random) addresses for different proximities (first 8 here):
```
0 -> "11011011"
1 -> "01011110"
2 -> "00100010"
3 -> "00010111"
4 -> "00001000"
5 -> "00000100"
6 -> "00000010"
7 -> "00000001"
```
Bits in common are what defines bin of some other address in relation to base address.
To have some sort of balancing, we try to have some dispersion of addresses for each bin (proximity).
We define this as bit suffix for bin, and if should be number > 0. If we set it to `1` we would have 2 possibilities, with `2` we have 4, with `3` we have 8, and so on.
For 2 following suffixes are produced for address:
```
00
01
10
11
```
Using this config, for each bin …
> Balanced peers in kademlia

- pkg/localstore/mode_set.go
This fixes issue #1409 by changing the Put metric references to already defined Set metrics.
> Correct metrics to use Set instead of Put

- pkg/api/api_test.go
- pkg/api/cors_test.go
- pkg/api/router.go
- pkg/debugapi/cors.go
This PR solves a serious bug with serving CORS headers if no allowed origins are configured and an origin header is present in an HTTP request. If CORS headers are configured, the functionality is correct.
This PR adds two test cases in already existing debugapi test and adds the same test for the api package.
> fix unconfigured cors origin

- pkg/pushsync/pushsync.go
There's a lot of improper context handling on pushsync. Expiration on forwarding/reception is non existent, and on `pushToClosest` the receipt context might already be expired once it is created from the previous context, which shadows the original one. Also, defer calls are done incorrectly.
I am also raising TTL since it seems just too low value right now in the current state of the network.
> pushsync: improve context handling

- pkg/localstore/gc.go
- pkg/localstore/localstore.go
Users are reporting that we are spending a lot of time in GC, causing goroutines to pile up waiting for the lock.
> localstore: increase gc batch size

- pkg/shed/db.go
Rectifies a case where an error might be returned from leveldb but gets swallowed in the `if` statement, resulting in a `nil` `value` and eventually causing a panic in the calling context.
Should improve #1340
> shed: return swallowed error

- pkg/localstore/gc.go
- pkg/localstore/metrics.go
Adding a metric on how long it takes till we see the first item coming out of the GC iterator as well as removing unused metrics and a place where the wrong metric is incremented.
> localstore: improve metrics

- pkg/node/chain.go
- pkg/settlement/swap/chequebook/bindings.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/chequebook_test.go
- pkg/settlement/swap/chequebook/common_test.go
- pkg/settlement/swap/chequebook/init.go
- pkg/settlement/swap/erc20/erc20.go
- pkg/settlement/swap/erc20/erc20_test.go
- pkg/settlement/swap/erc20/mock/erc20.go
this is the third in a series of PRs which remove the use of abigen-generated bindings in favour of just using the few things we need directly building on top of #1361.
This PR
* removes use of bindings for erc20
* introduces an erc20 service instead which uses go-ethereum abi directly (this has been extracted as some of its functions are also needed in `storage-incentives` where some code is currently duplicated)
> chequebook: remove erc20 bindings

- pkg/pusher/pusher.go
Decrementing concurrent pusher jobs as this helps with the `context deadline exceeded problem`
> pusher: less concurrent jobs

- .github/workflows/beekeeper.yml
After beekeeper.yaml and slash-beekeeper.yaml merge we lost info is it PR or merge run in Mattermost message, this PR tries to fix that
> set ENV var with run type

- pkg/api/bzz_test.go
- pkg/api/feed.go
- pkg/api/feed_test.go
- pkg/api/soc.go
- pkg/api/soc_test.go
- pkg/feeds/feed.go
- pkg/feeds/getter.go
- pkg/feeds/putter.go
- pkg/soc/export_test.go
- pkg/soc/soc.go
- pkg/soc/soc_test.go
- pkg/soc/testing/soc.go
- pkg/soc/validator.go
- pkg/soc/validator_test.go
This PR attempt to refactor the soc API to a more idiomatic and clean API.
The new API exposes the following:
```go
func New(id ID, ch swarm.Chunk) *Soc
func NewSigned(id ID, ch swarm.Chunk, owner, sig []byte) (*Soc, error)
func (s *Soc) Sign(signer crypto.Signer) (swarm.Chunk, error)
func (s *Soc) Chunk() (swarm.Chunk, error)
func (s *Soc) WrappedChunk() swarm.Chunk
func FromChunk(sch swarm.Chunk) (*Soc, error)
func CreateAddress(id ID, owner Owner) (swarm.Address, error) 
func Valid(ch swarm.Chunk) bool
```
> Soc refactor

- pkg/localstore/gc.go
- pkg/localstore/gc_test.go
- pkg/localstore/localstore.go
- pkg/localstore/metrics.go
- pkg/localstore/mode_get.go
- pkg/localstore/mode_put.go
- pkg/localstore/mode_set.go
- pkg/swarm/swarm.go
- pkg/swarm/swarm_test.go
This PR changes the way we do the GC in localstore. Previous approach was locking the database for quite a long time, causing other protocols to slow down for a significant amount of time. This changeset introduces a flag that indicates whether gc is running, and when it does - chunk addresses that are changed in the database are logged to a slice. Once the gc collects enough candidates, it checks the slice for possible dirty candidates, leaving the dirty ones outside the GC round, then commits the result to leveldb.
Tested on our staging cluster and shows an order of magnitude improvement in the time we spend under lock while garbage collection is running.
The slice of dirty addresses can later be optimized to be a cuckoo or a bloom filter.
> localstore: reduce critical section size on gc

- pkg/settlement/swap/metrics.go
- pkg/settlement/swap/swap.go
adds more metrics so we can easily tell how much cheque traffic is actually happening. hopefully this can give some insight on why there are so many `eth_Call` operations.
> add metrics to track number of cheques

- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/metrics.go
Adds a wait to wait before retrying a peer that we failed connecting to. Observed on staging.
> kademlia: wait on peer before retrying after connect err

- pkg/localstore/gc.go
- pkg/localstore/gc_test.go
seen in a different PR:
```
=== RUN   TestGC_NoEvictDirty/get_most_recent_synced_chunk
==================
WARNING: DATA RACE
Write at 0x000005415c48 by goroutine 85:
github.com/ethersphere/bee/pkg/localstore.setTestHookCollectGarbage.func1()
/Users/runner/work/bee/bee/pkg/localstore/gc_test.go:481 +0x4d
testing.(*common).Cleanup.func1()
/Users/runner/hostedtoolcache/go/1.15.10/x64/src/testing/testing.go:880 +0x103
testing.(*common).Cleanup.func1.1()
/Users/runner/hostedtoolcache/go/1.15.10/x64/src/testing/testing.go:874 +0x91
testing.(*common).Cleanup.func1()
/Users/runner/hostedtoolcache/go/1.15.10/x64/src/testing/testing.go:881 +0x104
testing.(*common).runCleanup()
/Users/runner/hostedtoolcache/go/1.15.10/x64/src/testing/testing.go:957 +0xca
testing.tRunner.func2() …
```
> localstore: fix data race in test

- pkg/kademlia/kademlia.go
the balanced kademlia part does not check the fact that a peer might be sanctioned. i am adding a check to the `closestPeer` function, which should improve the situation. symptom is that peers just constantly try to connect to each other. this is still visible on staging
> kademlia: check peer sanctioned when connecting on balanced loop

- pkg/kademlia/kademlia.go
The balanced kademlia erroneously exits upon an error connecting to a peer. The comment maintains that we should `// continue to next` but it instead just returns, invoking the normal kademlia connection iterator below.
> kademlia: balanced iterator erroneously exits but should continue

- pkg/flipflop/falling_edge.go
Embarrassing goroutine leak spotted by @ldeffenb.
On termination of a subscribe pull subscription, the detector might have a timer that is already pending, with the select case already selecting on the timer expiration, this results in an attempt to write to an unbuffered channel that is never read from, since the listening goroutine does not try to drain the channel. Also, draining the channel would be a bit ugly, since we'd have to potentially write one value to the `in` channel then wait for the incoming message after the buffer timeout expires. So I have instead added a buffer of one and a non-blocking trigger of the output.
> flipflop: fix goroutine leak on subscription termination

- pkg/debugapi/balances.go
- pkg/debugapi/balances_test.go
- pkg/debugapi/chequebook.go
- pkg/debugapi/chequebook_test.go
- pkg/debugapi/export_test.go
- pkg/debugapi/settlements.go
- pkg/debugapi/settlements_test.go
- pkg/sctx/sctx.go
- pkg/settlement/swap/chequebook/cashout.go
Users are complaining about `out of gas` errors due to some problem in the gas estimator. This PR adds two optional headers that inject the values that users may add to the request into the context. The cashout is reading the context value, which falls back to the default values that kick in the estimator.
Should help with #1450
> swap,sctx,debugapi: add optional gas limit and gas price to cashout

- pkg/localstore/gc.go
- pkg/localstore/subscription_pull.go
- pkg/localstore/subscription_push.go
While looking at the various metrics around pull and push sync, I noticed that there was never any outstanding subscriptions.  Checking the code showed that the increment of the completion metric was occurring at the start of the goroutine instead of being deferred to the end.  This PR corrects that misteak (sic).
> Missing defers

- packaging/docker/README.md
- packaging/docker/docker-compose.yml
Not to have to update this file with every release we could go with something like this? Set image tag to `beta` every release is tagged with it and define upgrade/update as `docker-compose pull` (this will pull the latest image) `&& docker-compose up -d` (this will update running image
> set bee image to beta and adjust README

- pkg/api/pss_test.go
Potential fix for PSS API Test flakiness issue by increasing timeout of reading the message
> PSS API Test flakiness

- pkg/settlement/swap/chequebook/cashout.go
fixes the case where the cashout endpoint returns 500 if the transaction is not found on the backend.
> swap: treat not found cashout transactions as pending

- openapi/SwarmCommon.yaml
- pkg/debugapi/chequebook.go
- pkg/debugapi/chequebook_test.go
- pkg/settlement/swap/chequebook/cashout.go
- pkg/settlement/swap/chequebook/cashout_test.go
changes the GET cashout endpoint to include uncashed amount. it always returns uncashed amount even if no cashout has taken place so far (as long as we have in fact at least one cheque from the peer).
The main advantage of putting this into cashout endpoint are easier cashout scripts as we can all relevant values in one call and better handling of currently pending or cancelled transactions (in the calculation of uncashed amount).
This is an API-breaking change as in addition to the new `uncashedAmount`, several values moved into `lastCashedCheque` (which may be `null`).
> chequebook: change cashout api to include uncashed amount

- .github/workflows/release.yaml
Goreleaser now fails on shallow clones https://github.com/goreleaser/goreleaser/pull/2135
> add fetch-depth: 0 to release

- pkg/settlement/swap/transaction/transaction.go
add an extra 20% gas to all transactions if the estimator is used.
deployment transactions can also run out of gas if multiple chequebooks are deployed in the same block.
> transaction: add extra gas everywhere

- pkg/pushsync/pushsync.go
This invokes 2 lines of logging for every chunk we process and makes the console unusable. Reducing this for now
> pushsync: reduce logging

- Dockerfile
- Dockerfile.goreleaser
- pkg/node/node.go
- pkg/postage/batch.go
- pkg/postage/batch_test.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/postage/batchstore/export_test.go
- pkg/postage/batchstore/mock/store.go
- pkg/postage/batchstore/mock/store_test.go
- pkg/postage/batchstore/reserve.go
- pkg/postage/batchstore/reserve_test.go
- pkg/postage/batchstore/store.go
- pkg/postage/batchstore/store_test.go
- pkg/postage/interface.go
- pkg/postage/listener/listener.go
- pkg/postage/listener/listener_test.go
This PR implements the reserve logic for the batchstore. 
it is soon to described in AP https://hackmd.io/9ejVZEvSQg69zXG91YsFEQ
complete together with localstore reserve logic
> batchstore: reserve

- .github/workflows/beekeeper.yml
* increases the retry delays for push sync test when clef is enabled as it appears that clef is very slow within github actions.
* increases wait time for gc test a bit to decrease flakiness
Both of these tests work fine with the default parameters when running integration tests outside of github actions (even with node counts > 30), so it appears it is the extreme resource constraints in the ci which is causing all of this.
> increase delays in ci

- .goreleaser.yml
Scoop release failed because goreleaser took first file and that was binary, maybe there is some other way to fix this but this is the fastest
> switch scoop package and binary files order

- pkg/kademlia/kademlia_test.go
The `waitConn` was on the wrong line.
> fix bad connected value in kad snapshot test

- .github/workflows/beekeeper.yml
Apparently there is not enough visibility for devs when infra tests fail after they are merged into master, with this PR infra tests will be executed with every push into PR and thus merge into master will be blocked until infra tests pass.
> run beekeeper tests on every push to pr

- pkg/api/api.go
- pkg/localstore/export.go
- pkg/localstore/export_test.go
- pkg/localstore/localstore.go
- pkg/localstore/localstore_test.go
- pkg/localstore/mode_get.go
- pkg/localstore/mode_get_multi.go
- pkg/localstore/mode_put.go
- pkg/localstore/subscription_push.go
- pkg/localstore/subscription_push_test.go
- pkg/node/node.go
- pkg/postage/stamp.go
- pkg/pullsync/pullsync.go
- pkg/pullsync/pullsync_test.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
- pkg/shed/index.go
- pkg/storage/testing/chunk.go
- pkg/swarm/swarm.go
#898 
AP https://hackmd.io/2NgPR2CeQICKzWBAH7Mk0Q#
> stamp support in storage and protocols

- go.mod
- go.sum
- pkg/settlement/swap/chequebook/cashout_test.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/chequebook/factory_test.go
- pkg/settlement/swap/erc20/erc20.go
- pkg/settlement/swap/erc20/erc20_test.go
- pkg/settlement/swap/transaction/event_test.go
this is the fifth and final in a series of PRs which remove the use of abigen-generated bindings.
It removes the last traces of abigen generated code and uses the new simpler sw3 contract ABI library instead.
> replace sw3-bindings with go-sw3-abi

- .github/workflows/beekeeper.yml
adds the branch name to the message in the `github-actions` channel. should make it more visible which PRs are actually failing.
> add pr branch name to github action fail messages

- pkg/api/export_test.go
- pkg/api/postage.go
- pkg/api/postage_test.go
- pkg/api/router.go
- pkg/postage/mock/service.go
- pkg/postage/stampissuer.go
This PR adds two API endpoints as discussed with the JS team cc @agazso. These return either all available batches or the information about a specific batch and can be used to further build upon.
I did not add the OpenAPI spec and realised that it also doesn't exist for the other API endpoint (POST). And considering the amount of changes of the openapi spec on `master` I would suggest to postpone this in a few days, so that we can first rebase the storage incentives branch over `master, then deal with this, if there's no objection.
> api: endpoints for stamp issuers

- cmd/bee/cmd/deploy.go
- pkg/node/chain.go
- pkg/node/node.go
- pkg/settlement/swap/transaction/backend.go
- pkg/settlement/swap/transaction/backendmock/backend.go
- pkg/settlement/swap/transaction/backendsimulation/backend.go
- pkg/settlement/swap/transaction/export_test.go
- pkg/settlement/swap/transaction/mock/transaction.go
- pkg/settlement/swap/transaction/monitor.go
- pkg/settlement/swap/transaction/monitor_test.go
- pkg/settlement/swap/transaction/monitormock/monitor.go
- pkg/settlement/swap/transaction/transaction.go
- pkg/settlement/swap/transaction/transaction_test.go
This is a pretty radical rewrite of how transactions are monitored for confirmations.
The primary aim is to be able to:
* have a somewhat constant number of backend requests over time independent of the number of pending transactions
* give up on transactions which are provably cancelled (while avoiding giving up on transactions which might still happen, even if they take a very long time to confirm)
* provide the base for watching transactions in the background
* provide the base for advanced transaction functionality such as gas boosting, replacing or rebroadcasting transactions
The way this works is as follows:
Instead of watching transactions individually, the senders nonce is monitored and transactions are checked based on this. The idea is that if the nonce is still lower than that …
> transaction: add nonce-based monitor

- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
This PR adds unsaturated bins when calculating kademlia depth
Addresses #1418
> kademlia: add unsaturated bins to depth calculation

- pkg/pushsync/pushsync.go
use a separate context for the pushsync replication in the go routines. the context which was used before was cancelled when the handler func returned while the go routines might still be running. this leads to imbalances and sometimes canceelled settlement.
this was not an issue with 0 prices in neighbourhood where the asymmetric accounting of 0 did not matter, but now happens frequently due to the return to fixed pricing.
> separate context for pushsync replication

- .github/workflows/beekeeper.yml
- .github/workflows/release.yaml
- .goreleaser.yml
With docker introducing pull requests limits projects publish images to multiple registries just to provide users options if you hit limit on one registry, quay is one of the alternatives
> publish docker image to quay.io as well

- pkg/localstore/mode_put.go
This PR optimizes the way we acquire the `batchMu` in localstore for a single chunk.
In `pushsync`, chunks may be resent over the network. However, if a chunk already exists, the lock must not be acquired. This should improve lock contention on chunks which are retried, but as well leave the current situation in which two copies of the same chunk which are competing over the same lock will not be aware of each other. In order to solve this edge case, some sort of detection of inflight writes would be necessary, with result propagation to potentially multiple writers.
> localstore: dont acquire batchMu for a single chunk that already exists

- .github/workflows/release.yaml
- .goreleaser.yml
Releases are signed using the project GPG key with key-ID `65207E638F11F36B` and fingerprint `C07E 8D0F CC74 221F 2C24  1EEE 6520 7E63 8F11 F36B`. The key can be fetched from most keyservers.
```
gpg --recv-keys 65207E638F11F36B
```
Set trust for the key
```
$ gpg --edit-key 65207E638F11F36B
gpg> trust
pub  rsa4096/65207E638F11F36B
created: 2021-04-19  expires: 2022-04-19  usage: C
trust: ultimate      validity: ultimate
sub  rsa4096/60760BAEEDEFB3E6
created: 2021-04-19  expires: 2022-04-19  usage: S
[ultimate] (1). ethersphere-bee (github.com/ethersphere/bee project key) <security@ethswarm.org>
Please decide how far you trust this user to correctly verify other users' keys
(by looking at passports, checking fingerprints from different sources, etc.)
1 = I don't know or won't say
2 = I do …
```
> sign checksums.txt with gpg key

- pkg/kademlia/kademlia.go
- pkg/kademlia/kademlia_test.go
- pkg/node/node.go
- pkg/postage/batchstore/mock/store.go
- pkg/postage/batchstore/reserve_test.go
- pkg/postage/batchstore/store.go
- pkg/postage/batchstore/store_test.go
- pkg/postage/interface.go
This PR wires in the postage radius of responsibility into kademlia as an upper bound of the neighborhood depth, paving the way for agreement between connected neighborhoods and data persistence responsibility.
> batchstore, kademlia: add radius as depth upper bound

- pkg/node/node.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchstore/store.go
- pkg/postage/interface.go
- pkg/postage/listener/listener_test.go
fixes a panic that occurs on startup before kademlia instance is set to the batchstore. this is a bit problematic since we might miss some calls on startup. a sleep might be needed on the listener before it starts listening @ralph-pichler WDYT?
> batchstore: fix panic

- .goreleaser.yml
Per notification this two option are deprecated
https://goreleaser.com/deprecations/#nfpmsfiles
https://goreleaser.com/deprecations/#nfpmsconfig_files
> take care for option deprecation

- pkg/node/node.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/postage/interface.go
- pkg/postage/listener/listener.go
- pkg/postage/listener/listener_test.go
this adds a small improvement of waiting till the contract listener stops paging at the application startup. this might lead to a slight unnecessary delay at startup but would guarantee syncing with the contract data so that nodes dont start receiving chunks before syncing with the chain, resulting in some chunks being dropped since the batch are not yet found, since the node is not synced.
> node: wait till synced with postage contract before starting node

- pkg/api/router.go
- pkg/debugapi/cors.go
Closes #1376.
It is not a completely clean solution, as currently, it returns all Bee's custom headers across all endpoints, while a better solution would be to return only those that the endpoint indeed supports. But that would require quite a more complex support structure in the code that I was not really keen to introduce. I think this will make the work done, but it will require having it in mind when new headers are added to propagate them in here as well.
> fix cors preflight headers bug

- pkg/localstore/mode_get.go
- pkg/localstore/mode_put.go
- pkg/localstore/mode_put_test.go
- pkg/localstore/pin_test.go
This PR adds the chunk to the pullIndex when the stamp is valid and received from a retrieve request. It also simplifies the logic in the updateGC method.
> localstore: simplify updategc logic, put to pullsync index when stamp valid

- go.mod
- go.sum
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/static_resolver.go
- pkg/p2p/libp2p/static_resolver_test.go
This PR removes mockdns dependency for libp2p static address resolver by mocking the LookupIP function only.
> libp2p static address resolver test simplification

- openapi/Swarm.yaml
- openapi/SwarmDebug.yaml
- pkg/api/api_test.go
- pkg/api/bytes.go
- pkg/api/bytes_test.go
- pkg/api/bzz.go
- pkg/api/bzz_test.go
- pkg/api/chunk.go
- pkg/api/chunk_test.go
- pkg/api/dirs.go
- pkg/api/dirs_test.go
- pkg/api/gatewaymode_test.go
- pkg/api/pin.go
- pkg/api/pin_test.go
- pkg/api/postage.go
- pkg/api/postage_test.go
- pkg/api/pss.go
- pkg/api/pss_test.go
- pkg/api/tag_test.go
As per #1084 we need to return http response code 201 every time we create a new resource.
> Using the correct http response codes when creating a resource

- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/libp2p_test.go
adds nat manager cleanup to libp2p close
> libp2p: improve cleanup on shutdown

- openapi/Swarm.yaml
- pkg/api/bytes_test.go
- pkg/api/bzz_test.go
- pkg/api/chunk_test.go
- pkg/api/pin.go
- pkg/api/pin_test.go
- pkg/api/router.go
- pkg/pinning/doc.go
- pkg/pinning/mock/mock.go
- pkg/pinning/pinning.go
- pkg/pinning/pinning_test.go
This PR is a follow-up to the #1614 where the semantics of address is changed to reference for the pinning API.
> Rename address to reference in pinning related code

- pkg/p2p/libp2p/libp2p.go
as reported by user `eth1` on discord:
```
goroutine 41833 [running]:                                                                                                                           
github.com/ethersphere/bee/pkg/p2p/libp2p.(*Service).Close(0xc0003c0000, 0x0, 0x0)                                                                                                                                                                                                                        
github.com/ethersphere/bee/pkg/p2p/libp2p/libp2p.go:706 +0x54 …
```
> libp2p: fix shutdown panic

- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/pslice/pslice.go
- pkg/topology/pslice/pslice_test.go
This PR should be a good foundation for rate limiting broadcasting peers going forward. We will need to investigate if there are better strategies for the selection of peers.
> kademlia: limit broadcasting peers

- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
Let the closest peer know whether those he pushed towards in-neighborhood accepted the chunk by sending a receipt.
This circumvents accounting imbalances arised from refused out-of-neigbhborhood depth content (that might be caused by asymmetric neighborhood concepts)
> Receipts in Neighborhood sync

- cmd/bee/cmd/start_windows.go
suppress windows platform specific linter error "Error return value of `l.winlog.Error` is not checked (errcheck)" by discarding return value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1659)
> Winlog linter fix

- cmd/bee/cmd/version.go
- pkg/p2p/libp2p/connections_test.go
This PR sends the `bee version` command output to stdout. `cobra` defaults to `stderr` if output is not explicitly set.
fixes #1648
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1660)
> cmd: send version info to stdout

- pkg/localstore/migration.go
- pkg/localstore/schema.go
The DB schema changed with storage incentives. This needs to be communicated to the user which tries to update the binary unknowingly. We do this in a form of a data migration that always returns an error. Further details should be communicated in the release notes on how to migrate the nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1610)
> localstore: communicate schema incompatibility

- go.mod
- pkg/hive/export_test.go
- pkg/hive/hive.go
- pkg/hive/hive_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/pslice/pslice.go
- pkg/topology/pslice/pslice_test.go
#1645
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1654)
> kademlia, hive: rate limiting on gossiping peers (send and receive)

- pkg/api/api.go
- pkg/api/bytes.go
- pkg/api/bzz.go
- pkg/api/dirs.go
- pkg/file/file_test.go
- pkg/file/joiner/joiner_test.go
- pkg/file/loadsave/loadsave.go
- pkg/file/pipeline/builder/builder.go
- pkg/pinning/pinning_test.go
- pkg/traversal/traversal_test.go
Previously, the pipeline builder, when it reached EOF after draining the request, compared the data length argument with the amount of data read. Since EOF signal is sent when all of the data is read gracefully, the amount of data read will always be equal to the length of the request, so this check was unnecessary, and removed with this PR.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1671)
> api,file: remove data length arg from pipeline builder

- pkg/pushsync/metrics.go
- pkg/pushsync/pushsync.go
Following metrics are added:
- TotalSendAttempts
These are meant to see how many peers were considered for the push. We already track no. of successful pushes with `TotalSent`. So we should be able to infer how many failed in all with this.
- TotalFailedSendAttempts
This counter will count the no. of failed attempts. A failed attempt is when we actually made an attempt to send the data to the peer. This doesn't count the errors caused by accounting. However `TotalSendAttempts - (TotalSent + TotalFailedSendAttempts)` should tell us that.
- FailedCacheHits
This counter vector keeps track of failedRequestCache hits. It will use the `peer` and `chunk` labels to track traces for a {peer, chunk} send-request. We should ensure this no. does not rise to a high value.
---
This change is [<img …
> feat(pushsync): add metrics to push flow

- go.mod
- pkg/p2p/streamtest/streamtest.go
- pkg/p2p/streamtest/streamtest_test.go
- pkg/pushsync/export_test.go
- pkg/pushsync/metrics.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
#1638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1662)
> refactor(pushsync): Don't account for failed retries due to accounting

- .github/workflows/go.yml
- commitlint.config.js
The commit police is here :police_car: :police_car: :police_car: :ambulance: :police_car: 
Howto:
https://www.conventionalcommits.org/en/v1.0.0/#summary
https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#commit (minus `style`)
More:
https://github.com/conventional-changelog/commitlint
Future todo:
https://github.com/buchanae/github-release-notes
https://github.com/miniscruff/changie
https://github.com/googleapis/release-please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1684)
> ci: conventional commits linting in ci flow

- pkg/p2p/error.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/headers_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/protocols_test.go
- pkg/p2p/libp2p/tracing_test.go
- pkg/topology/kademlia/kademlia.go
When we connect to a peer we check if it's a light node and disconnect if true.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1689)
> fix(p2p): detect dial to light nodes and disconnect

- pkg/p2p/libp2p/libp2p.go
- pkg/topology/kademlia/kademlia.go
Added extra checks in libp2p after connect calls to kademlia. This prevents peers that disconnect in the background while the stream handle is ongoing, from remining in the kademlia list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1696)
> fix(libp2p,kademlia): fixes discrepency - kademlia and libp2p peers list

- .github/workflows/beekeeper.yml
- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/node/chain.go
- pkg/node/node.go
- pkg/settlement/interface.go
- pkg/settlement/pseudosettle/pseudosettle.go
- pkg/settlement/pseudosettle/pseudosettle_test.go
- pkg/settlement/swap/mock/swap.go
- pkg/settlement/swap/swap.go
- pkg/settlement/swap/swap_test.go
removes settlements from happening while holding the accounting lock. balance updates happens later through a call by settlements.
after triggering settlement `Reserve` will continue as if no settlement had happened. the request (and other requests during the settlement) should still work if they fit within the `payment-early` amount (e.g. if the payment threshold is `10000`, payment early `1000` and the expected debt `9000` there is still `1000` units to use while the settlement is ongoing). accounting tracks if settlement is ongoing with a peer, to avoid triggering settlement for the same debt again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1578)
> feat: async settlement

- .github/workflows/beekeeper.yml
pushsync tests are flaking since my change to introduce the block time flag. allowing more time should solve the propagation of batches across the network
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1714)
> ci: increase retry delay in pushsync check

- openapi/Swarm.yaml
- pkg/api/pin.go
The POST pinning endpoint returns now 404 on non-existing chunks
instead of 500.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1712)
> fix: http response of pinning non-existing chunks

- pkg/topology/kademlia/export_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
With this change, # of connected nodes to bootnodes will be limited. When a bin becomes oversaturated,  a random peer will be dropped.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1715)
> feat: bootnodes drop peers from oversaturated bins

- pkg/node/chain.go
wrong if broke legacy factory address auto-discovery.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1740)
> fix: check existence of legacy flag correctly

- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/peer.go
- pkg/p2p/libp2p/protocols_test.go
- pkg/p2p/p2p.go
adds needed information about whether a peer is a full node or not into the `p2p.Peer` type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1741)
> fix(libp2p): add full node info to peer

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
This PR tackles only the OpenAPI definitions with tweaks and fixes that I have discovered during working on postage stamp support in bee-js.
Also it documents returning `null` instead of empty arrays as discussed in #1663 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1738)
> docs: improving openapi docs

- pkg/settlement/pseudosettle/pseudosettle.go
decrease blocklisting time in pseudosettle, so the network is not permanently defunct if something is wrong there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1750)
> fix: blocklist for less time in pseudosettle

- cmd/bee/cmd/cmd.go
- packaging/bee.yaml
- packaging/homebrew/bee.yaml
- packaging/scoop/bee.yaml
1gBZZ is sufficient for most users for a long time. Heavy users can always add more to the initial deposit. This helps with the current shortage of gBZZ and gETH. 
Scoop package still had the old default initial deposit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1747)
> chore: change initial deposit to 10000000000000000 PLUR (1BZZ)

- pkg/pushsync/metrics.go
- pkg/pushsync/pushsync.go
During upgrade, we will see a lot of failures initially which may cause this metric to go out of hand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1748)
> refactor(pushsync): change FailedCacheHit metric from CounterVec to Counter

- pkg/node/node.go
- pkg/statestore/leveldb/migration.go
this are the log lines it produces when migrating an existent statestore:
```
...
DEBU[2021-05-18T12:50:47+03:00] deleted key fdb1d222ae51ef3d48c9ec50f7e02d73713ee049d723edc580f003ff0da17344|15 
DEBU[2021-05-18T12:50:47+03:00] deleted keys: 675                            
DEBU[2021-05-18T12:50:47+03:00] statestore: successfully ran migration: id 0 current schema: drain 
DEBU[2021-05-18T12:50:47+03:00] deleted keys: 0                              
DEBU[2021-05-18T12:50:47+03:00] statestore: successfully ran migration: id 1 current schema: clean-interval 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1734)
> feat: schema migrations to clean interval keys

- pkg/accounting/accounting.go
- pkg/settlement/pseudosettle/pseudosettle.go
* still update balance after time settle enforcement check even in case of blocklisting. this should avoid permanent imbalances arising related to enforcement issues.
* reduce the blocklisting time disconnect thresholds
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1753)
> fix: still update balance on blocklisting

- pkg/topology/kademlia/internal/metrics/metrics.go
- pkg/topology/kademlia/internal/metrics/metrics_test.go
- pkg/topology/kademlia/kademlia.go
The Finalize collector method is called after all the waits and the
timeouts for finishing the ongoing connection attempts have finished.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1765)
> fix: move metrics collector finalize at the end of the close call

- openapi/SwarmCommon.yaml
Replaces user-defined type EmptyNull with the
nullable defined by the OpenAPI specification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1752)
> refactor(openapi): swap EmptyNull with nullable

- pkg/localstore/gc.go
- pkg/localstore/gc_test.go
- pkg/localstore/localstore.go
- pkg/localstore/localstore_test.go
- pkg/localstore/reserve.go
this change enables a correct estimate:
```
time="2021-05-18T17:52:10+03:00" level=info msg="database capacity: 1000000 chunks (approximately 36.7GB)"
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1767)
> fix: include reserve capacity in estimate

- pkg/api/api.go
This makes sure that duplicate chunks don't get stamped twice. It might not be performance optimized since we're incurring more db ops per insert but at least for now it would help us maintain with relative good certainty the assumption of uniform distribution of chunks over collision buckets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1772)
> fix: dont stamp dupes

- openapi/Swarm.yaml
adds the reupload functionality to the openapi spec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1755)
> docs: document reupload

- pkg/feeds/sequence/sequence.go
This PR is a work in progress and attempt to fix this issue https://github.com/ethersphere/bee/issues/1382 related to the too-long feeds lookup time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1548)
> Feeds lookup improvements

- openapi/Swarm.yaml
Just one small inconsistency in OpenAPI related to `POST /pins` endpoint.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1788)
> docs: pin endpoint also returns 200

- pkg/localstore/reserve.go
- pkg/node/node.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/postage/batchstore/mock/store.go
- pkg/postage/batchstore/store.go
- pkg/postage/batchstore/store_test.go
- pkg/postage/interface.go
- pkg/postage/listener/listener.go
- pkg/postage/listener/listener_test.go
This PR adds a change to prevent inconsistencies when syncing the postage data from the chain.
We've found that during shutdown, the block height might be persisted before an event (or a bunch of events) are processed. This sends the node into an inconsistent state since the next time it will boot up, syncing chain data will commence from `<previous persisted block>+1`.
Due to this, we've introduced a stopgap solution that detects whether a shutdown happened while updating a batch.
Once a dirty shutdown is detected on boot up sequence, the batch store keys are swiped and the node starts to resync the chain data from the start block number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> feat: transact batchstore

- pkg/pusher/pusher_test.go
This PR addresses two related issues with TestSendChunkToPushSyncWithoutTag reported in issue https://github.com/ethersphere/bee/issues/1556.
The first one is the test failure `pusher_test.go:166: Chunk not synced` which is due to too short time waiting for chunk to be synced in the retry loop. It is addressed by raising the value to 50ms from 10ms for every retry iteration. It is possible that with race detector scheduler is not able to execute all required goroutines for test to pass even with retries. This was validate locally and validated that it does not happen with this change by running the test tens of thousand times.
The second issue is with the Closing sequence when the failure above occurs. It is incorrect to have the pusher Close only at the end of the function as it will not …
> fix(pusher): flaky test

- pkg/node/node.go
This is a fix for the following reported issue #1801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1807)
> fix(node): remove state-store close call on nil reference

- pkg/node/node.go
transaction hash parameter was checked for the wrong length and also decoded the wrong way.
additionally this PR allows tx hashes prefixed with 0x and improves logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1810)
> fix: correctly check and decode transaction hash

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/deploy.go
- cmd/bee/cmd/start.go
- openapi/SwarmDebug.yaml
- packaging/bee.yaml
- packaging/docker/env
- packaging/homebrew/bee.yaml
- packaging/scoop/bee.yaml
- pkg/debugapi/chequebook.go
- pkg/debugapi/chequebook_test.go
- pkg/node/chain.go
- pkg/node/node.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/erc20/erc20.go
add gas price setting for deployment, funding and the remaining tx triggering calls. uses the same sctx mechanism as the other gas price settings.
* `/chequebook/deposit` and `/chequebook/withdraw` use the `Gas-Price` header
* deployment gas is specified by flag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1812)
> feat: gas price for deploy, deposit and withdraw

- pkg/puller/puller.go
- pkg/puller/puller_test.go
- pkg/pullsync/pullstorage/pullstorage.go
- pkg/pullsync/pullstorage/pullstorage_test.go
- pkg/storage/mock/storer.go
We have a goroutine leak due to the iterator share change. The context propagation in this case is really not trivial to do and it appears that we have some quirks that need to be thoroughly fleshed out before this lands in `master`. Reverting for now so that release can be communicated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1832)
> revert: pullstorage iterator share

- pkg/topology/pslice/pslice.go
- pkg/topology/pslice/pslice_test.go
This PR addresses a performance problem found in profiling when adding new peer address to PSlice with a larger number of peers in it. This is manifested as a very high node start time with a large number of overlay addresses in the addressbook, directly impacting bootnode's performance.
Two improvements combined give significantly better results in newley added BenchmarkAdd test:
- optimized insertAddresses based on https://github.com/golang/go/wiki/SliceTricks#insertvector
- making the copied peers slice capacity larger by one to avoid extending the slice
The improvements are in execution time and also memory and allocations which is reducing the pressure on the gc.
The results are:
```
goos: darwin
goarch: amd64
pkg: github.com/ethersphere/bee/pkg/topology/pslice
cpu: Intel(R) Core(TM) …
```
> perf(pslice): optimize Add method

- pkg/puller/puller.go
- pkg/puller/puller_test.go
It appears that due to the airdrop process and the dirty state of the clusters some users have taken steps to update the handshake protocol version of their nodes so that they can still "participate" in the airdrop while running the old node version. This causes a panic in pull syncing due to incompatible length of cursors returned from the peer.
A more strict check is therefore added as a stopgap solution.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1851)
> fix(puller): cursors length panic

- pkg/node/node.go
as discussed on the debugging session we are temporarily disabling pull syncing on light nodes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1883)
> feat: disable lightnodes puller

- go.mod
- pkg/topology/kademlia/internal/metrics/metrics.go
- pkg/topology/kademlia/internal/metrics/metrics_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/topology.go
- all counters are stored in memory by default in order to minimize disc operations
- counters that need to be persisted are flushed periodically to the persistent store
- switch to `sync.Map` which is more suitable for the case of disjoint sets of keys
- using lock-free data structures for the critical parts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1873)
Profile snapshot taken before the changes:
Profile snapshot taken after the changes:
> refactor(kademlia,metrics): make metrics persistent writes asynchronous

- pkg/puller/puller.go
This change makes sure we send out puller `SyncInterval` requests anyway when the context expires.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1888)
> refactor: puller always send cancel ruid

- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/p2p.go
- pkg/topology/kademlia/kademlia.go
This PR rectifies a problem where information about lightnodes would be communicated to other full nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1895)
> fix: dont communicate lightnodes

- go.mod
- go.sum
- pkg/pullsync/pullstorage/pullstorage.go
- pkg/pullsync/pullstorage/pullstorage_test.go
- pkg/storage/mock/storer.go
This is an alternative approach to share pullstorage iterators by using resenje.org/singleflight which is context aware compared to the x/sync/singleflight implementation. The relevant functionality is described here https://pkg.go.dev/resenje.org/singleflight#Group.Do.
Currently, this is just a POC, unit tests should be added before merging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1891)
> feat: pullstorage iterator share

- pkg/topology/kademlia/kademlia.go
While the depth is low (early in the node uptime) connectpeers has an unintended sideeffect of connecting all low po peers treating them as neighbors before checking whether depth have changed. 
This change intends to catch depth change by checking depth before every new connection attempt, counting on that when successful connections are made the depth is recalculated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1907)
> feat: Constantly monitor depth during kademlia saturation

- pkg/pullsync/pullsync.go
After profiling existing goroutines running on a node, it is found that pullsync.Syncer.handler goroutine number is larger with the number of connected peers. One approach to optimize was to reuse the iterators but the number of handler goroutines is still high as every peer needs to have a stream opened for pull syncing, most notably live pull syncing for proximity bins.
Profiling shows that a larger meemory allocated at protobuf reader
```
(pprof) top -cum
Showing nodes accounting for 134.09MB, 23.39% of 573.29MB total
Dropped 278 nodes (cum <= 2.87MB)
Showing top 10 nodes out of 205
flat  flat%   sum%        cum   cum%
0     0%     0%   221.12MB 38.57%  github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandlerMatch.func1
0     0%     0%   205.17MB 35.79% …
```
> perf(pullsync): release reader buffer in handler

- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/libp2p_test.go
- pkg/topology/lightnode/container.go
- pkg/topology/lightnode/container_test.go
This PR limits the number of lightnodes we allow to connect inbound. This is to give some safety level to full nodes operators not to be resource overwhelmed by too many light node requests. This sets the initial limit to 100 above which the node will start kicking away other light nodes to accommodate for the new ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1898)
> feat: limit number of light nodes

- pkg/api/api.go
- pkg/node/node.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/mock/mock.go
- pkg/p2p/p2p.go
- pkg/postage/listener/listener.go
- pkg/puller/puller.go
- pkg/pullsync/pullsync.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/mock/kademlia.go
- pkg/topology/mock/mock.go
- pkg/topology/topology.go
This PR improves the shutdown sequence by introducing a few changes to the way we do shutdowns:
1. kademlia and libp2p are now `Halt`ed before anything else happens in the shutdown, this will prevent _new_ outgoing and incoming connections to be established, however existing connections will remain untouched. This will also improve exit time of kademlia when it is finally shut down since the number of ongoing goroutines dailing will be smaller, so we would need to wait less.
2. more components are shut down in parallel
3. api shutdown timeout is decreased, since shutting down with running websockets is not critical, while slowing down the rest of the process _is_
4. kademlia `Close` is bumped _before_ statestore is closed. Since metrics need to be saved before shutting down, this can …
> refactor: improve shutdown sequence

- pkg/node/node.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/metrics.go
- pkg/topology/lightnode/container.go
- pkg/topology/lightnode/metrics.go
Adds the following metrics:
- number of currently connected peers
- number of currently disconnected peers
- total number of kicked out peers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1979)
> feat(lightnode,libp2p): add prometheus metrics

- pkg/steward/steward.go
- pkg/steward/steward_test.go
Adding a regression test and explicit handling of `topology.ErrWantSelf`
addresses #1897 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1980)
> fix(steward): swallow ErrWantSelf

- pkg/node/node.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1912)
> fix: shutdown only once

- go.mod
- pkg/accounting/accounting.go
- pkg/accounting/metrics.go
- pkg/settlement/pseudosettle/metrics.go
- pkg/settlement/pseudosettle/pseudosettle.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2013)
> feat: add more metrics to accounting and settlements

- pkg/settlement/swap/chequebook/init.go
reduce required eth for initial deployment. value was still based on the pre proxy factory.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2018)
> feat: reduce required eth

- pkg/topology/kademlia/export_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
Speeds up the topology build by dividing the connect neighbor
method into two separate phases executed in sequential order.
The first phase makes a number of concurrent connections not
bigger than what is considered for the bin to be saturated. The
second phase takes care of the rest of the connection in a
regular manner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2028)
> refactor(kademlia): speeding up topology build

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- pkg/api/bytes.go
- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/dirs.go
- pkg/api/pss.go
This PR attempts to solve #2026 in part.
This particular change tries to address the postage bucket full error which is annoying as the user does not understand that he cannot use the batch anymore.
We can create a separate `errors.go` file in `pkg/api` which could house all these error case handlers. This way we can edit the same file from time to time to add special case handling.
@acud @agazso @AuHau @Eknir
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2037)
> fix: api errors related to postage stamps

- pkg/transaction/monitor.go
* don't log checking pending transactions as errors. this can happen frequently with load-balanced eth backends where later requests hit a node which has not seen the same block yet.
* don't update `lastBlock` so we retry on the next iteration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2046)
> fix: don't log checking pending transactions as errors

- .goreleaser.yml
Enable support for auto marking a release as a `pre-release` if release tag has `-rcX` suffix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2060)
> feat: enable support for releasing rc

- pkg/netstore/netstore.go
- pkg/netstore/netstore_test.go
- pkg/recovery/repair_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
- pkg/retrieval/skip_peers.go
This pr attempts to mirror some of the push sync behaviour changes introduced in #1662 and to enable retrying until a chunk is attempted to be retrieved from at least one peer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1780)
> feat: Retrial behavior in retrieval

- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/accounting/metrics.go
- pkg/accounting/mock/accounting.go
- pkg/pushsync/pushsync.go
- pkg/retrieval/retrieval.go
The aim of this change is to introduce originated balances, that keep track of credit operations done for the purpose of requests originated by the node itself, and to limit monetary payments to the debt showed by the originated balance. 
This balance changes in the following ways:
- to keep track of originated credits
+ it decreases with the value of these credit operations
- to be limited by the current outstanding debt to our peer shown by the accounting balance, 
+ when it is negative it increases to the value of the current accounting balance when the accounting balance increases to a negative value closer to or above zero, this increase can not bring the originated balance above 0
- to reflect monetary payments made with the sole purpose of compensating for the originated balance,
+ …
> feat: Maintain originated balance

- .github/patches/postageservice.patch
- .github/workflows/beekeeper.yml
- openapi/SwarmCommon.yaml
- pkg/api/api_test.go
- pkg/api/bzz.go
- pkg/api/feed.go
- pkg/api/feed_test.go
- pkg/api/postage.go
- pkg/api/postage_test.go
- pkg/api/pss.go
- pkg/api/pss_test.go
- pkg/api/soc.go
- pkg/api/soc_test.go
- pkg/node/node.go
- pkg/postage/export_test.go
- pkg/postage/mock/service.go
- pkg/postage/postagecontract/contract.go
- pkg/postage/service.go
- pkg/postage/service_test.go
- pkg/postage/stamp_test.go
- pkg/postage/stamper_test.go
- pkg/postage/stampissuer.go
- pkg/postage/stampissuer_test.go
#2038
Steps:
1. We create the StampIssuer with the blockNumber of the batch creation event on-chain.
- New `blockNumber` field added to StampIssuer
- Marshal/Unmarshal changes to store the same to statestore
2. StampIssuer uses the postage store to read the current chain state which informs us what the current block number the node is synced to.
3. When the postage service provides the StampIssuer, we will check the current block number the node is synced to is greater than the batch creation block number by a certain amount (`blockThreshold (default: 10)`). This is done to give the best chance to upstream peers to get notified of the batch and hence validate the stamps issued by this Issuer.
@agazso @AuHau 
Please note the changes in API spec. Some more errors related to postage stamps …
> feat(postage): stampissuer usability

- go.mod
- go.sum
- openapi/SwarmCommon.yaml
- pkg/api/api_test.go
- pkg/api/feed_test.go
- pkg/api/postage.go
- pkg/api/postage_test.go
- pkg/api/pss_test.go
- pkg/api/soc_test.go
- pkg/postage/batch.go
- pkg/postage/mock/service.go
- pkg/postage/postagecontract/contract.go
- pkg/postage/service.go
- pkg/postage/service_test.go
- pkg/postage/stamp_test.go
- pkg/postage/stamper.go
- pkg/postage/stamper_test.go
- pkg/postage/stampissuer.go
- pkg/postage/stampissuer_test.go
On top of the current information, the returned data are
extended by: label, depth, amount, bucketDepth,
blockNumber, and immutableFlag.
#1971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2051)
> feat: extend information returned by GET /stamps

- openapi/Swarm.yaml
- pkg/api/chunk.go
- pkg/node/node.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/postage/interface.go
- pkg/postage/mock/service.go
- pkg/postage/service.go
- pkg/postage/service_test.go
Currently, we create a new stampissuer when the user buys new stamps using the `/stamps` API.
This makes a call to the blockchain to buy a new postage batch. The operation can take some time and if for some reason the node goes down at this point, we might end up in a state where we have bought the postage batch, but a new stampissuer was not created making this batch not useful.
The change ensures that on batch creation event handled by the listener when we get the update from the blockchain, we will check if a stampissuer is present. And if it's not, we will create it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2080)
> fix: recover stampissuer on batch creation

- pkg/p2p/streamtest/streamtest.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
This PR intends to make forwarder behavior ensure that chunk is successfully written to at least one further peer before concluding attempt has been made
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2016)
> fix: delay concluding attempt in pushsync

- pkg/pushsync/pushsync_test.go
The failureThreshold of the pushSync failureCache was decreased from 3 to 2. This needs adjustments to the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2097)
> fix: pushsync test limits

- pkg/node/chain.go
- pkg/settlement/swap/swap.go
- pkg/settlement/swap/swap_test.go
don't disconnect on non-swap peers. no longer necessary as we can wait for time settlement as a fallback.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2102)
> fix: don't disconnect on non-swap peers

- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/accounting/mock/accounting.go
- pkg/node/node.go
- pkg/pushsync/pushsync.go
- pkg/retrieval/retrieval.go
- pkg/settlement/interface.go
- pkg/settlement/pseudosettle/pseudosettle.go
- pkg/settlement/pseudosettle/pseudosettle_test.go
- pkg/settlement/swap/swap_test.go
This PR introduces a failsafe mechanism for unforeseeable problems that can result in accounting discrepancies and enabling nodes to be able to recover a state of symmetric balances afterwards while inhibiting nodes of taking advantage of the failsafe mechanism.
The failsafe mechanism is that both peers start with 0 balances upon a new establishment of the connection in a peer to peer relationship.
The safety of this mechanism is guaranteed by not allowing reconnections by the same peer until the refreshement rate would remove the outstanding debt plus one times paymentthreshold worth of credit space, in case a peer disconnects from us.
This pr also introduces ghost debt, meaning we account for requests that the node attempted to serve as a forwarder - meaning it successfully requested it …
> feat: Always reset balances to zero after disconnection or blocklisting

- pkg/postage/postagecontract/contract.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/erc20/erc20.go
set explicit gas limits to work around nethermind issues.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2101)
> fix: set explicit gas limits

- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/kademlia/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2082)
> refactor(kademlia): add peers at start asynchronously

- pkg/accounting/accounting.go
- pkg/settlement/pseudosettle/pseudosettle.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2100)
> feat: disconnect from peer upon refreshment attempt being reset

- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/export_test.go
- pkg/debugapi/router.go
- pkg/debugapi/transaction.go
- pkg/debugapi/transaction_test.go
- pkg/node/node.go
- pkg/settlement/swap/chequebook/cashout.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/erc20/erc20.go
- pkg/transaction/export_test.go
- pkg/transaction/mock/transaction.go
- pkg/transaction/transaction.go
- pkg/transaction/transaction_test.go
This PR adds a few transaction related endpoints useful for debugging and fixing potential transaction-related issues.
It builds on top of the functionality introduced in #1465 and adds the following debugapi endpoints:
* `GET /transactions` to get a list of transactions sent by bee which are neither confirmed nor provably cancelled (in other words "pending")
* `GET /transactions/{hash}` to get details for a particular transaction (wether pending or not)
* `POST /transactions/{hash}` to resend a transaction to the ethereum backend. This is useful if a pending transaction disappears from the eth network for some reason.
To enable querying which transactions are actually pending, all sent transactions are monitored by default (using the machinery introduced in #1465). To make the output of …
> feat: add various transaction endpoint and track pending transactions

- pkg/postage/postagecontract/contract.go
- pkg/postage/postagecontract/contract_test.go
Fixing the precondition to be aligned with contract check:
https://github.com/ethersphere/storage-incentives/blob/master/src/PostageStamp.sol#L100
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2099)
> fix: bucket depth size expectation

- pkg/debugapi/pingpong.go
Long standing cleanup that just sends a ping and a pong in the protocol when querying through the debugapi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2107)
> debugapi: less messages on pingpong

- pkg/pusher/pusher_test.go
- pkg/pushsync/pushsync.go
well noticed by @ralph-pichler is that we are not doing NN replication as originators of requests. This causes the CI to flake (among other things...). This PR rectifies this by moving the code to the area shared by both originator and forwarder nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2115)
> fix(pushsync): originator replication

- pkg/postage/service.go
This PR fixes a condition in which two stamp issuers might be generated for the same batch. It introduces a check against duplicate stamp issuers in the `Add` call that adds the issuer to the postage service.
addresses #2121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2128)
> fix: duplicate stampissuers

- pkg/topology/kademlia/kademlia.go
This PR makes sure kademlia starts faster. This is after observing a relatively slow startup sequence on integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2130)
> fix: faster kademlia startup

- .github/patches/postagereserve_gc.patch
- .github/workflows/beekeeper.yml
- Makefile
- pkg/debugapi/postage.go
- pkg/localstore/gc.go
- pkg/localstore/gc_test.go
- pkg/localstore/localstore.go
- pkg/localstore/metrics.go
- pkg/localstore/mode_put.go
- pkg/localstore/mode_set.go
- pkg/localstore/mode_set_test.go
- pkg/localstore/reserve.go
- pkg/localstore/reserve_test.go
- pkg/node/node.go
- pkg/postage/batchstore/export_test.go
- pkg/postage/batchstore/mock/store.go
- pkg/postage/batchstore/reserve.go
- pkg/postage/batchstore/reserve_test.go
- pkg/postage/batchstore/store.go
- pkg/postage/batchstore/store_test.go
- pkg/postage/interface.go
- pkg/postage/reservestate.go
https://github.com/ethersphere/bee/issues/2040
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2071)
TODO: 
- ~~on batchstore reset we should delete all the fifo queue items~~ (already implicitly done by the `Reset` method)
- ~~retrieval protocol has to check postage stamp validity and force cache in case the stamp is invalid~~
> feat: unreserve on-demand

- pkg/transaction/transaction.go
- pkg/transaction/transaction_test.go
* a missing return led to some transactions being removed from the pending list if there was a backend error
* there was a backend error in the unit test because the mock did not have the function set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2145)
> fix(transaction): add a missing return, implement a mock function

- pkg/addressbook/addressbook.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/pslice/pslice.go
Since the process of adding peers can take a long time, I am adding an iterator that processes them in batches. It is just unclear whether this would result in increased CPU usage while this iterator is open in leveldb (@janos WDYT?).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2162)
> feat(kademlia): AddPeers batch on Start

- pkg/debugapi/peer.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/p2p.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/kademlia/mock/kademlia.go
- pkg/topology/mock/mock.go
- pkg/topology/topology.go
This PR fixes: https://github.com/ethersphere/bee/issues/1414.
Peers added by using the debug API were not being connected in the kademlia, and thus were not shown in the topology. This PR adds the `p2p.Notifier` to the topology driver to allow peers to be connected in kademlia. It also adds a flag that enables connection to over-saturated peers through the debug API.
The flag is only true if a connection request is made using the `/connect` endpoint in the debug API.
The flag does not affect bootnodes. Bootnodes always follow the saturation function.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2093)
> fix: add peer in topology through the debug api

- pkg/p2p/libp2p/internal/handshake/handshake.go
The handshake will now try to do the non-minable overlay check before it would do the network id check. If there is a network id mismatch, the blockchain verification will fail while the actual part that explicitly checks the network ID will never be reached. This PR moves this explicit check before the backend call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2170)
> fix: check network id before backend call

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bytes.go
- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/feed.go
- pkg/api/feed_test.go
- pkg/api/pss.go
- pkg/api/pss_test.go
- pkg/api/soc.go
- pkg/api/soc_test.go
- pkg/debugapi/postage.go
- pkg/debugapi/router.go
- pkg/postage/mock/service.go
- pkg/postage/service.go
Allows setting the default stamp issuer which will be used in the
case when the 'Swarm-Postage-Batch-Id' header is missing.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2175)
> feat: use default stamp issuer on missing postage batch id header

- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/router.go
- pkg/node/chain.go
- pkg/node/node.go
already enable `/transactions` endpoints on the early debug api so that it is available during chequebook deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2210)
> feat: early tx api

- pkg/crypto/clef/clef.go
Adds some verification on the data we get back from the signer and detect if it is configured for the wrong chain.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2214)
> fix: verify signer result

- pkg/traversal/traversal.go
Traversal package doesnt need access to all the functions defined in the Storer interface. Only Putter and Getter interfaces are required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2218)
> fix: remove unnecessary dependencies for traversal

- packaging/bee-get-addr
This is to prevent users from sending the wrong token on the wrong blockchain when funding their node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2203)
> Changed Ethereum address message

- pkg/node/node.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/postage/interface.go
- pkg/postage/listener/listener.go
- pkg/postage/listener/listener_test.go
This PR adds a simple, flattened merkelized hash chain checksum implementation to the batch service which processes events from the postage event listener. It is meant to provide an extra layer of debugging information to compare reserve state across nodes.
It uses a simple sha3-256 hasher and works in the following manner:
0. current checksum of state is written into the hasher (if exists on component bootstrap)
1. transaction hash bytes of event which has been read from the chain is written into the hasher after being processed
2. the sum of the hasher is produced and:
2.1. written to disk
2.2. the hasher is reset to zero, and the sum written into it again
3. repeat steps 1-2 indefinitely
The checksums will be printed alongside each event log line in the terminal.
TODO:
- ~~metric that …
> feat: batchstore checksums

- pkg/pss/mining_test.go
- pkg/pss/trojan.go
a minor improvement on pss trojan mining
- code cleanup
- using errgroup
- change to bigendian 
- fix for the parity bit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2140)
> fix(pss): make sending PSS messages more efficient

- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
- pkg/topology/mock/mock.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2237)
> fix: only in neighborhood replication

- pkg/localstore/mode_put.go
- pkg/localstore/mode_put_test.go
as reported by the Least Authority audit team, we would be doing unnecessary increments to gcSize when uploading. A subsequent migration that reindexes the gcSize index is needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2296)
> fix: least authority gcSizeChange bug

- pkg/pushsync/pushsync.go
Only using peers further away from the chunk for in-neighborhood immediate replication, as other peers could take it as a regular push attempt towards them, and cascade the immediate replication
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2293)
>  fix: replicate with peers further from the chunk

- pkg/pushsync/pushsync.go
- pkg/retrieval/retrieval.go
This PR addresses a deadlock issue discovered with @acud and @aloknerurkar on production cluster.
It handles the context cancelation in the minimal way to solve blocking on pushToClosest:
```
goroutine profile: total 31463
16690 @ 0x43a885 0x405aea 0x405895 0xe06266 0x470b81
2992 @ 0x43a885 0x44a9ef 0x11f0025 0x470b81
...
```
Additionally, the similar fix is done in the retrieval protocol preemptive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2327)
> fix(pushsync, retrieval): avoid deadlocks on context done

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
There is a need for k8s deployment to be able to define tracing-endpoint using HOST and PORT variables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2323)
> feat: allow setting tracing-endpoint using host and port

- pkg/tracing/doc.go
- pkg/tracing/tracing.go
In all grafana docs its `traceID` and not `traceid`, while field name is configurable for connecting logs to traces for grafana cloud its much easier to go with a default value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2324)
> feat: rename log field traceid to traceID

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
As part of working on documentation for `bee-js` I was investigating the exact sets of endpoints which are/are not available in Gateway mode. I have updated your docs with my findings and also included few tweaks and improvements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2325)
> docs: gateway mode forbidden and tweaks

- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
- pkg/debugapi/export_test.go
- pkg/debugapi/postage.go
- pkg/debugapi/postage_test.go
- pkg/debugapi/router.go
- pkg/postage/stampissuer.go
This PR adds a debug api endpoint to print out extended debugging information in regards to a single batch, so that we can track collisions on particular buckets (and hopefully plot them to spot anomalies)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2321)
> feat: add bucket data endpoint

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- pkg/netstore/netstore.go
- pkg/netstore/netstore_test.go
- pkg/node/node.go
- pkg/postage/stamp.go
- pkg/pullsync/pullsync.go
- pkg/pushsync/pushsync.go
- pkg/recovery/repair_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
This PR introduces a configurable behaviour to run the node caching forwarded chunks for opportunistic later reuse
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2234)
> feat: cache on forwarding in retrieval

- pkg/settlement/swap/chequebook/init.go
always run `checkBalance` so we don't send txs if we don't have any eth. not sure why this was removed in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2337)
> fix: restore initial balance check

- cmd/bee/cmd/start.go
blocktime should just be an integer. the `*time.Second` here actually converted it to nanoseconds leading to a blocktime of a million hours later.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2340)
> fix: correct blocktime for xdai

- pkg/retrieval/retrieval_test.go
Add retries to checking whether a forwarding node has the chunk or not. This is caused by a possible data race which allows for the retrieve request answer to come back to the origin, while the forwarder does the caching after answering the request. This is in order not to burden the request propagation time with latencies caused by local storage on the forwarder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2345)
> fix(retrieval): flaky retrieval test

- go.mod
- pkg/hive/hive.go
- pkg/p2p/libp2p/export_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/libp2p/protocols_test.go
- Adding a new HostFactory option to libp2p to enable test host creation for unit tests.
- Ping test now works
-  Correcting log msg #2343
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2349)
> fix: flaky ping test and log correction

- pkg/localstore/localstore.go
This adjusts the worst case timing for the flipflop subscription debouncer, as it helps with the performance of our integration tests (chunks get pushed faster).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2352)
> chore: adjust flipflop worst case time

- pkg/api/bzz.go
adjusts API logging so that we have better context where it is coming from.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2353)
> chore(api): improve logging

- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/p2p.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/kademlia/mock/kademlia.go
- pkg/topology/lightnode/container.go
- pkg/topology/lightnode/container_test.go
- pkg/topology/mock/mock.go
Right now we announce nodes to light nodes only when they connect. This does not allow them to know about new nodes as they join the network. This also causes the integration tests to fail, as light nodes may connect early to the bootnode, never knowing anything about any other node in the network, leaving them only with a connection to the bootnode, which results in the tests to flake much more, since they overdraft with the bootnode very quickly, which then eventually results in errors in retrieval.
This PR rectifies this by notifying light nodes about new full nodes as they join the network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2351)
> feat: announce to lightnodes
