ethersphere/bee

pkg/p2p/libp2p/libp2p.go

Just an idea, for the future protocols as well. It might be a good idea to wait for the last side that is processing response to close the stream.
If it makes sense we might need to refactor a bit to make it happen cleanly by either expanding `p2p.Stream` or encapsulating req/resp sending and stream creation.

Wait for remote stream to close in handshake

---

pkg/p2p/libp2p/internal/handshake/mock/stream.go

Typo fix when I was renaming + merging.

handshake mock rename bug fix

---

pkg/debugapi/export_test.go
pkg/debugapi/peer.go
pkg/debugapi/peer_test.go
pkg/debugapi/router.go

This PR exposes p2p Peers method on debugapi endpoint.

add debugapi p2p peers endpoint

---

go.sum
pkg/hive/hive_test.go

Fixes flacky tests for `BroadcastPeers` call in discovery.
caused by https://github.com/ethersphere/bee/pull/46

Hive tests fix - expect values eventually

---

go.mod
go.sum
pkg/statestore/store.go
pkg/statestore/test/store_test.go
pkg/storage/store.go

uses leveldb for now. will be converted later to badger
dependency of https://github.com/ethersphere/bee/issues/59

statestore: add initial implementation

---

CODING.md
README.md

This PR adds a new file CODING.md with guidelines on writing code for this project.
I invite everyone in the team to review it, without creating a list of individual members which could end up incomplete.

add CODING.md

---

pkg/shed/db.go
pkg/shed/field_uint64.go
pkg/shed/index.go
pkg/shed/index_test.go
pkg/shed/vector_uint64.go
pkg/storage/localstore/export.go
pkg/storage/localstore/gc.go
pkg/storage/localstore/gc_test.go
pkg/storage/localstore/localstore.go
pkg/storage/localstore/localstore_test.go
pkg/storage/localstore/migration.go
pkg/storage/localstore/migration_test.go
pkg/storage/localstore/mode_get.go
pkg/storage/localstore/mode_put.go
pkg/storage/localstore/mode_set.go
pkg/storage/localstore/schema.go
pkg/storage/localstore/subscription_pull.go
pkg/storage/localstore/subscription_push.go

This PR  replaces localstore log library with bee logging library, to remove a dependency on swarm codebase.
Refer P8 in #66

P8 - Add Bee's logging to localstore

---

Makefile
go.mod
pkg/sctx/sctx.go
pkg/storage/localstore/localstore.go
pkg/tags/tag.go
pkg/tags/tag_test.go
pkg/tags/tags.go

10/12 part 2: remove spancontext dependency, remove mockstore, migrate sctx

---

.github/workflows/coverage.yml

add coverage.yaml to github actions

---

cmd/bee/cmd/cmd_test.go
pkg/hive/hive.go
pkg/localstore/localstore.go
pkg/shed/example_store_test.go
pkg/statestore/test/store.go
pkg/storage/testing/chunk.go

This PR contains fixes that are related to errors reported by deepsource service https://deepsource.io/gh/ethersphere/bee/issues/?category=all.

fix errors reported by deepsource

---

pkg/storage/mock/validator/validator.go
pkg/storage/mock/validator/validator_test.go

The validator PR previously merged omitted a test for the mock validator. It's submitted here separately for sake of completeness and closure.

Add omitted test for mock validator

---

pkg/file/error.go
pkg/file/file.go
pkg/file/joiner/internal/job.go
pkg/file/joiner/internal/job_test.go
pkg/file/joiner/joiner.go
pkg/file/joiner/joiner_test.go
pkg/file/testing/chunk.go
pkg/storage/testing/chunk.go
pkg/swarm/swarm.go

This PR introduces the interfaces for split and join. The interfaces are intended to be appropriate for public API level.
Closes https://github.com/ethersphere/bee/issues/108

Introduce interface for file join and simple implementation

---

pkg/api/bzz.go
pkg/api/bzz_test.go
pkg/api/bzzchunk_test.go
pkg/api/export_test.go
pkg/api/router.go

add an api endpoint to upload raw data and get back a content address hash.

add raw data upload api

---

.github/workflows/coverage.yml
.github/workflows/go.yml

This way we will be sure that tests are being executed after the code is merged to master but those tests will not slow down the development

run go and coverage tests after code is merged to master for sanity check

---

.githooks/pre-push.bash
Makefile

Add git pre-push hook so that before pushing all tests are passed on local dev machine
Install it with `make hooks`, it will create symlink `.githooks/pre-push.bash -> .git/hooks/pre-push`

Git pre push hook

---

.github/workflows/beekeper.yaml

Adding new beekeeper tests to github actions pipeline

add pingpong and fullconnectivity e2e tests to github actions

---

.githooks/pre-push.bash

fixing githook for case when there is no upstream branch

check if its only local branch

---

cmd/bee-join/main.go
cmd/bee-split/main.go

Adds a CLI command that retrieves a file from a Swarm Hash through Bee HTTP API.

Add join cli

---

.gitignore
pkg/api/bzzchunk.go
pkg/api/bzzchunk_test.go
pkg/debugapi/debugapi_test.go
pkg/debugapi/pin.go
pkg/debugapi/pin_test.go
pkg/debugapi/router.go
pkg/jsonhttp/jsonhttptest/jsonhttptest.go
pkg/localstore/pin.go
pkg/localstore/pin_test.go
pkg/storage/mock/storer.go
pkg/storage/mock/validator/validator.go
pkg/storage/store.go

Refer https://github.com/ethersphere/bee/issues/182 for task details

Local pinning of chunk

---

pkg/localstore/export.go
pkg/localstore/gc.go
pkg/localstore/migration.go
pkg/localstore/mode_get.go
pkg/localstore/mode_set.go
pkg/localstore/subscription_pull.go
pkg/localstore/subscription_push.go

This PR fixes improperly formatted log messages in localstore package.

fix localstore log messages

---

.github/workflows/beekeeper.yaml

github actions runners changed how they resolve `.localhost` domain, before it was 127.0.0.1, now its unresolvable, fix is simple, add entries to `/etc/hosts`

fix dns resolution adding entries to hosts

---

.github/workflows/beekeeper.yaml

Fix copy/paste typo from previous merge

fix copy/paste mistake

---

pkg/node/node.go

This PR adds retrieval protocol to p2p service. This PR is somehow late, I thought that I created it when I pushed the branch. Sorry for that.
fixes https://github.com/ethersphere/bee/issues/230

add retrieval protocol to p2p service in node package

---

cmd/bee/cmd/start.go
pkg/localstore/localstore.go
pkg/localstore/localstore_test.go
pkg/node/node.go

add a dbCapacity flag so that we can test local pinning

Add db capacity flag

---

pkg/bzz/address.go
pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/internal/handshake/handshake.go
pkg/p2p/libp2p/internal/handshake/handshake_test.go
pkg/p2p/libp2p/internal/handshake/pb/handshake.pb.go
pkg/p2p/libp2p/internal/handshake/pb/handshake.proto
pkg/p2p/libp2p/libp2p.go

Address https://github.com/ethersphere/bee/issues/249 by exchanging observable underlay in  handshake.

Handshake with observable underlay

---

pkg/node/node.go

The purpose of this PR is to allow all close functions to be called in node Shutdown function so that they can give their best to cleanup. Multiple errors are returned as the consequence.

return multiple errors from node Shutdown to call all close functions

---

pkg/pusher/pusher.go

While running a node that has no connected pusher very frequently tries to push chunks with errors that no peers could be found for every chunk. This raises significantly as number of chunks gets larger. A proper way to handle this case would be to have a backoff mechanism or some event notifications, but for now, I think that we should address the log messages. I know that @acud was not for doing this, but I think that this will be needed for alpha.

reduce some of very frequent pusher log messages

---

pkg/localstore/localstore.go
pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go

reverts the abomination of a fix we introduced here: https://github.com/ethersphere/swarm/pull/1940
we need to find a way to test of this properly with integration testing

localstore: remove gc check hack

---

pkg/api/file.go

This PR fixes the problem of wrongly reported content-length on file download.
The problem is that the size that was got is on the address of the entry.Entry which is always 64 as its content is always two addresses. This is change to get the size of the reference from the entry that is the root hash of the content served.
Also, error reporting on io.Copy is added as the error was not visible in logs while we experienced the problems related to the incorrect content length on the public testnet.

get the correct data size for file download

---

pkg/bzz/address.go
pkg/kademlia/kademlia.go
pkg/p2p/libp2p/libp2p.go

Print bzz addresses when the node is connected a bit nicer + plus improve bzzAddr debug logs a bit.

Printing bzzaddress

---

pkg/retrieval/retrieval.go

This PR is adding a a singleflight on RetrieveChunk to avoid multiple parallel chunk requests.

use singleflight in retrieval

---

pkg/puller/puller.go
pkg/pullsync/pullsync.go

reduce pull sync logging

---

pkg/bzz/address.go
pkg/bzz/address_test.go
pkg/crypto/crypto.go
pkg/crypto/crypto_test.go
pkg/debugapi/peer_test.go
pkg/hive/hive_test.go
pkg/keystore/file/key.go
pkg/node/node.go
pkg/p2p/libp2p/internal/handshake/handshake_test.go
pkg/p2p/libp2p/libp2p_test.go

Hashing of ethereum address by public key was not called correctly.
See https://github.com/ethersphere/bee/pull/345/files#diff-aa4c96b4d3b1b4d4fcd8f914144cd943L59

Ethereum address creation faulty

---

pkg/kademlia/pslice/pslice.go

This PR implements COW in PSlice.

kademlia pslice copy on write

---

cmd/bee/cmd/start.go
pkg/api/api.go
pkg/api/router.go
pkg/node/node.go

This PR adds CORS headers option to the main API.

implement CORS headers in API

---

pkg/p2p/libp2p/headers.go

send headers method has a ten seconds timeout using context, but header handler method had only 1 second timeout for each operation to succeed. this more or less gives them the same timing, although receive headers method should have shorter timeout to respond theoretically

libp2p: increase receiveHeaders timeout

---

pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pullsync/pullsync.go

puller, pull sync: clean shutdown

---

pkg/pullsync/pullsync.go

pullsync: fix shutdown

---

README.md

The docs are now in a good shape and contain all information (and more) which was provided here.
I added the links to the documentation in the readme and removed the content
@crtahlin

removed content from readme and added link to docs

---

pkg/kademlia/kademlia_test.go
pkg/puller/puller_test.go

tried to reproduce #344 locally as part of this PR but couldn't. some cleanups were necessary to add to kademlia anyway and so they are now there.
fixes #382

fix puller test, add cleanups to kademlia

---

pkg/api/bytes.go

Addresses cleanup request in https://github.com/ethersphere/bee/pull/327#issuecomment-646057120

Use files join code in bytes

---

cmd/bee/cmd/start.go

This PR changes CLI boolean flags as per suggestions in documentation channel from @crtahlin and @Eknir.
Heads up for the bee helm chart @svetomir.

consistency in cli boolean flags

---

pkg/puller/puller_test.go

fixes https://github.com/ethersphere/bee/issues/400

puller: fix live sync test flake

---

pkg/puller/puller.go

puller: exit on nextInterval error

---

go.sum
pkg/pushsync/pushsync.go

https://github.com/ethersphere/bee/issues/403

Pushsync - stream reset

---

go.sum
pkg/retrieval/retrieval.go

https://github.com/ethersphere/bee/issues/403

Retreival - stream reset

---

go.sum
pkg/hive/hive.go

https://github.com/ethersphere/bee/issues/403

Stream reset - hive

---

go.sum
pkg/node/node.go
pkg/p2p/libp2p/libp2p.go

Connection reset on header exchange error

---

pkg/hive/hive.go
pkg/pullsync/pullsync.go

https://github.com/ethersphere/bee/pull/403

Pullsync - reset stream on errors

---

pkg/content/validator.go
pkg/content/validator_test.go
pkg/node/node.go
pkg/soc/validator.go
pkg/soc/validator_test.go

Add the soc validator to array of netstore validators.

Add soc validator to node

---

install.sh

before merging needs to be tested on macos and windows (cygwin and git-bash)
`wget -q -O - https://raw.githubusercontent.com/ethersphere/bee/install-script/install.sh | bash`

add install.sh

---

pkg/api/bzz_test.go
pkg/api/router.go

This PR makes a very small change from issue https://github.com/ethersphere/bee/issues/459.
fixes: https://github.com/ethersphere/bee/issues/459

api: rename bzz: path segment to bzz

---

pkg/p2p/streamtest/streamtest.go
pkg/p2p/streamtest/streamtest_test.go
pkg/pushsync/pushsync.go

Update the `streamtest` to support reset functionality as well.
https://github.com/ethersphere/bee/issues/403

Reset in streamtest

---

pkg/retrieval/retrieval.go

This PR addresses the comment that was missed in the previous PR https://github.com/ethersphere/bee/pull/524#pullrequestreview-461755846.

set retrieve chunk max peers log message level to trace

---

pkg/p2p/libp2p/peer.go

While investigating this https://github.com/ethersphere/bee/issues/515, I noticed that ordering of peer addIfExists is not perfect. I don't think this is the cause of the bug, because it is still somewhat guarded by the ordering of actions, but I think this is much more clear.

Peer added fix

---

pkg/file/buffer.go
pkg/file/buffer_test.go

In some case it might happen that byte array sent to write be bigger from `swarm.ChunkSize`, in which case `ChunkPipe.Write` function must read all data from byte array.
Previous code only could read up to `maxBufferSize` (which is `swarm.ChunkSize * 2`), after which it responds that it read all bytes (`len(b)`), which is not correct.
These changes actually make sure to read all bytes from input.
NOTE: Check linked issue for more explanation.
Fixes #526

Respect 'Writer' interface contract in 'ChunkPipe'

---

pkg/file/buffer.go

I missed this one. No real reason not to check actual result of operation. Should protect against any other destinations that make similar issue that was present here.

Validate write operation expected result

---

pkg/debugapi/debugapi.go
pkg/debugapi/debugapi_test.go
pkg/hive/hive.go
pkg/hive/hive_test.go
pkg/kademlia/kademlia.go
pkg/kademlia/kademlia_test.go
pkg/node/node.go
pkg/pingpong/pingpong.go
pkg/pingpong/pingpong_test.go
pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pullsync/pullsync.go
pkg/pullsync/pullsync_test.go
pkg/pusher/pusher.go
pkg/pusher/pusher_test.go
pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go
pkg/recovery/repair_test.go
pkg/retrieval/retrieval.go
pkg/retrieval/retrieval_test.go

https://github.com/ethersphere/bee/issues/538
Removed usage of Options struct or fields in all cases I saw that are part of critical part and don't have sensible defaults handled.

Options structs cleanup - part2

---

.github/workflows/beekeeper.yaml
.github/workflows/go.yml

Trigger beekeeper workflow only once and remove bee pods directly using helm

Fix workflow trigger

---

.github/beekeeper/bee.yaml
.github/workflows/beekeeper.yaml

add chunkrepair (global-pinning) test to beekeeper workflow

add chunkrepair test

---

cmd/bee/cmd/cmd.go

add the global pinning flag to the command line so that it is exposed.

aded global pinning flag

---

pkg/api/api.go
pkg/api/bytes.go
pkg/api/bzz_test.go
pkg/api/dirs.go
pkg/api/file.go
pkg/api/file_test.go
pkg/file/joiner/joiner_test.go
pkg/file/pipeline/pipeline.go
pkg/file/pipeline/pipeline_test.go
pkg/manifest/simple.go

integrates the new encryption pipeline into the api and other dependencies

api: integrate encryption pipeline

---

pkg/api/api.go
pkg/api/tag.go
pkg/localstore/mode_put.go
pkg/localstore/mode_set.go
pkg/localstore/mode_set_test.go
pkg/pusher/pusher_test.go
pkg/pushsync/pushsync_test.go
pkg/resolver/multi_test.go
pkg/tags/tag.go
pkg/tags/tag_test.go
pkg/tags/tags.go
pkg/tags/tags_test.go

removes the unused anonymous field from tag struct

tags: remove anonymous field

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

This PR updates specifications for both main and debug APIs. It also groups related endpoints in tags for easier browsing in the menu on the left.

update openapi specifications

---

pkg/file/file_test.go

fixes https://github.com/ethersphere/bee/issues/630

SplitThenJoinTest: switch to pipeline

---

openapi/SwarmCommon.yaml

Related to the new Releaser feature. Should be merged after https://github.com/ethersphere/bee/pull/634.

add DomainName openapi component

---

pkg/kademlia/kademlia.go
pkg/kademlia/kademlia_test.go
pkg/p2p/discover.go

1. Change kademlia code to connect to bootnodes without notification 
2. Fix loop bug in `Discover`

Fix loop break bug in discover

---

README.md

Remove link on swarm-gateways as now documentation was not updated there, and update the quick start documentation link.

update documentation links in readme file

---

go.sum

Remove old version of go-ethereum.

Tidy dependencies

---

pkg/api/api.go
pkg/api/bytes.go
pkg/api/bzz.go
pkg/api/dirs.go
pkg/api/file.go
pkg/api/router.go

Adds OpenTracing instrumentation to the http package.

add opentracing instrumentation to http package

---

pkg/accounting/accounting.go
pkg/accounting/metrics.go
pkg/accounting/pricer.go

Added missing comments, fixed existing documentation comments, format fixes

Fix comments, formatting, exports in Accounting

---

cmd/internal/file/io_test.go
go.mod
pkg/api/api.go
pkg/api/api_test.go
pkg/api/bytes_test.go
pkg/api/bzz_test.go
pkg/api/chunk_test.go
pkg/api/dirs_test.go
pkg/api/file_test.go
pkg/api/gatewaymode_test.go
pkg/api/pin_test.go
pkg/api/pss.go
pkg/api/pss_test.go
pkg/api/router.go
pkg/api/tag_test.go
pkg/logging/http_access.go
pkg/node/node.go
pkg/pss/pss.go
pkg/pss/pss_test.go
pkg/pushsync/mock/mock.go
pkg/pushsync/pushsync.go
pkg/recovery/export_test.go
pkg/recovery/repair.go
pkg/recovery/repair_test.go

Test code in https://github.com/acud/bee-pss-websockets
fixes #650
manual testing:

api: add pss websockets api

---

pkg/accounting/accounting.go
pkg/accounting/accounting_test.go
pkg/accounting/metrics.go
pkg/accounting/pricer.go

The aim of this PR is to avoid overflows coming from extreme values and arithmetics

Safety checks in accounting

---

.github/workflows/beekeeper.yaml

It comes up that keys are generated per session

fix debug runtime

---

.github/workflows/beekeeper.yaml

fix command order

---

pkg/accounting/pricer.go

This PR only increases the prices in pricer by 1* poPrice so that maxPO chunks are not unaccounted for

Charge for MaxPO chunks

---

pkg/debugapi/chequebook.go
pkg/debugapi/chequebook_test.go
pkg/debugapi/debugapi.go
pkg/debugapi/debugapi_test.go
pkg/debugapi/export_test.go
pkg/debugapi/router.go
pkg/node/node.go
pkg/settlement/swap/chequebook/chequebook_test.go
pkg/settlement/swap/chequebook/mock/chequebook.go

The aim of this PR is to add /chequebook/balance & /chequebook/addess to the list of endpoints in the bee debug api

Chequebook endpoint

---

pkg/node/node.go
pkg/settlement/swap/chequebook/factory.go

add factory address for chain id 5 (`goerli`)
https://goerli.etherscan.io/address/0x334394e8c891e77b1449084aadd659920bb25247#code

add configuration for goerli

---

pkg/pusher/pusher.go

some housekeeping and increase of concurrent chunk jobs in pusher.

pusher: increase concurrent chunk jobs

---

cmd/bee/cmd/start.go

actually pass the early flag value to the node

add early payment to NewBee

---

.github/workflows/beekeeper.yaml

manifest test is failing because of low payment threshold that is configured for settlements test

fix test order and payment threshold

---

.github/workflows/beekeeper.yaml

Enable geth-swap on infra tests

Enable geth infra tests

---

pkg/debugapi/chequebook.go
pkg/debugapi/chequebook_test.go
pkg/debugapi/debugapi.go
pkg/debugapi/debugapi_test.go
pkg/debugapi/export_test.go
pkg/debugapi/router.go
pkg/node/node.go
pkg/settlement/swap/mock/swap.go
pkg/settlement/swap/swap.go

The aim of this pr is to add the 
/chequebook/lastcheque/{peer}
&
/chequebook/lastcheque
endpoints on the debug api.

Lastcheque endpoints

---

pkg/node/node.go

make it a bit clearer what this error is about

better error if no backend

---

pkg/puller/puller_test.go

puller: fix test flake

---

pkg/api/tag_test.go

these tests are still fragile and some of them overlap in functionality. further cleanup can be done but i think for now this is ok.
fixes #576

api/tag: cleanup tests

---

pkg/api/bytes.go
pkg/api/bzz.go
pkg/api/chunk.go
pkg/api/file.go

api: standardize error codes

---

pkg/settlement/swap/swap.go

fix disconnect non-swap node log

---

version.go

bump version to 0.3.2

---

pkg/pushsync/pushsync.go

This PR fixes a problem with context not being propagated on receipt message exchange and also without timeout.
fixes: #807

propagate context in pushsync receipt message exchange

---

pkg/crypto/mock/signer.go
pkg/node/node.go
pkg/settlement/swap/chequebook/cashout.go
pkg/settlement/swap/chequebook/cashout_test.go
pkg/settlement/swap/chequebook/cheque_test.go
pkg/settlement/swap/chequebook/chequebook.go
pkg/settlement/swap/chequebook/chequebook_test.go
pkg/settlement/swap/chequebook/chequestore.go
pkg/settlement/swap/chequebook/common_test.go
pkg/settlement/swap/chequebook/factory.go
pkg/settlement/swap/chequebook/factory_test.go
pkg/settlement/swap/chequebook/init.go
pkg/settlement/swap/transaction/backend.go
pkg/settlement/swap/transaction/backendmock/backend.go
pkg/settlement/swap/transaction/mock/transaction.go
pkg/settlement/swap/transaction/transaction.go
pkg/settlement/swap/transaction/transaction_test.go

* transaction service to its own package
* proper mock for `crypto.Signer` and `transaction.Service`

move transaction service to its own package

---

pkg/puller/puller.go
pkg/pullsync/mock/pullsync.go

This PR fixes some of the issues in #329, namely:
- removal of the `top==0` in puller implementation. this was necessary due to incorrect behavior of the mock, which should have returned a context cancelled error, but instead just returned.
- moving some of the functionality related to sync context to the `syncPeer` object. it is a question whether this type needs to be exposed in a different package.
- some small cleanups and DRYing of the existing logic
closes #329 as rest of tasks have discrete issues now

puller, pullsync: fix outstanding tasks

---

.github/workflows/slash-beekeeper.yml

fix GitHub actions Beekeeper Get PR Branch step

---

pkg/node/node.go

try to use content addressed validator before soc validator.
should improve #829 but it is uncertain

node: change chunk validator order

---

pkg/file/pipeline/builder/builder_test.go
pkg/file/splitter/splitter_test.go

fixes https://github.com/ethersphere/bee/issues/709

add basic pipeline benchmarks

---

go.mod
go.sum
pkg/bmtpool/bmtpool.go
pkg/content/content.go
pkg/file/pipeline/bmt/bmt.go
pkg/file/pipeline/bmt/bmt_test.go
pkg/file/pipeline/builder/builder.go
pkg/file/splitter/internal/job.go
pkg/node/node.go
pkg/pss/trojan.go
pkg/swarm/swarm.go

The PR integrates the new bmt hasher pool from the bmt package in order to reduce allocations.

all: use bmt hasher pool

---

pkg/api/chunk.go
pkg/api/tag.go
pkg/debugapi/balances.go
pkg/p2p/libp2p/libp2p.go

as I kept finding incorrect logging in various places I grepped through the codebase and fixed all of them at once.

fix remaining logging formatting issues

---

pkg/addressbook/addressbook.go
pkg/addressbook/doc.go
pkg/jsonhttp/doc.go
pkg/jsonhttp/jsonhttptest/doc.go
pkg/jsonhttp/jsonhttptest/jsonhttptest.go
pkg/keystore/file/service.go
pkg/keystore/keystore.go
pkg/keystore/mem/service.go
pkg/keystore/test/test.go
pkg/tracing/doc.go

This change adds some additional documentation on several packages.

Update package documentation

---

pkg/localstore/subscription_push.go
pkg/localstore/subscription_push_test.go

* Revert "Reverse the order of the queue for push sync index (#827)"
relates to #843

Revert reversing the iteration order from pushsync

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/init.go
cmd/bee/cmd/start.go
pkg/node/node.go

add a `bee init` command which only does key generation.

add init command

---

.goreleaser.yml
packaging/bee.service
packaging/bee.yaml
packaging/deb/postinst
packaging/deb/postrm
packaging/deb/preinst
packaging/deb/prerm
packaging/deb/templates
packaging/default
packaging/rpm/post
packaging/rpm/postun
packaging/rpm/pre
packaging/rpm/preun

Packages will be created when we release new version, until then it is possible to test build locally.
Install latest `goreleaser` (submitted couple of PRs to support our build) and run `goreleaser release --skip-publish --rm-dist`

deb and rpm support

---

pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go

This is a quick solution to https://github.com/ethersphere/bee/issues/949, as discussed earlier.

add to localstore gc index on ModePutSync

---

pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go

https://github.com/ethersphere/bee/issues/951

localstore: dont store chunk when it already exists

---

cmd/bee/cmd/start.go
pkg/node/node.go

As per comment https://github.com/ethersphere/bee/pull/980#issuecomment-730351322.

remove unused arguments and options from node.NewBee

---

cmd/bee/cmd/start.go
packaging/bee.yaml
packaging/deb/postinst
packaging/deb/preinst
packaging/deb/templates
packaging/rpm/post
packaging/rpm/pre

Create (hopefully) better support for enabling clef during bee install.

Packaging clef option

---

packaging/rpm/post

One typo and chmod in wrong place

fix post script for rpm

---

pkg/api/api.go
pkg/api/pss.go
pkg/api/router.go

supersedes https://github.com/ethersphere/bee/pull/963

api: add pss CORS check

---

pkg/settlement/swap/chequebook/init.go

should further improve the initial startup experience

adjust link to faucet to autofill address

---

.goreleaser.yml
packaging/homebrew/bee-get-addr
packaging/homebrew/bee.yaml

There is other service  in brew called bee and there is a possibility that user has both. Renaming folders to `swarm-bee`

rename folders for brew to swarm-bee

---

pkg/pushsync/pushsync.go

We should not blocklist peers pushsync.
depends on: #1009

Pushsync should not blocklist peer

---

.goreleaser.yml
packaging/bee-get-addr
packaging/deb/postinst
packaging/homebrew/bee-get-addr
packaging/rpm/post

Added links for more info on SWAP (ethereum) endpoint and external signer (clef)
Added auto URL for faucet thanks @ralph-pichler

nicer package post install output

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

Fixes and pre-release updates to the API descriptions
- Fix tags POST endpoint description
- Version numbers increased to 0.4.0's
- Miscellanous fixes

Openapi update

---

.github/workflows/beekeeper.yml
.github/workflows/slash-beekeeper.yml

beekeeper needs path to kubeconfig inside its config

add beekeeper.yaml to workflows

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml

Minor fixes
* newtagresponse to show example address instead of "string"
* bee api description mentions messaging capabilities

Openapi description fixes

---

pkg/api/dirs.go
pkg/api/dirs_test.go

Clean file path from tar archive

---

pkg/accounting/accounting.go
pkg/resolver/multiresolver/multiresolver.go
pkg/settlement/swap/chequebook/cashout.go
pkg/settlement/swap/swap_test.go
pkg/tracing/tracing_test.go

due to deepsource complaints on a different pr

minor code hygiene fixes

---

packaging/docker/docker-compose.yml

With new release fix for Dockerfile will be applied in released container, hardcoding version in docker-compose.yaml

Fix version docker compose

---

packaging/docker/README.md
packaging/docker/docker-compose.yml
packaging/docker/env

fixing multiple typos inside docker-compose related files

fix multiple typos in docker-compose

---

.github/workflows/beekeeper.yml
.github/workflows/slash-beekeeper.yml

Enable beekeeper test that check pin remote chunks

---

pkg/api/api.go
pkg/api/router.go
pkg/debugapi/router.go
pkg/logging/http_access.go
pkg/logging/httpaccess/http_access.go
pkg/tracing/tracing.go

Support tracing in HTTP headers

---

pkg/api/pin_bytes_test.go
pkg/api/pin_chunks.go
pkg/file/addresses/addresses_getter.go
pkg/file/addresses/addresses_getter_test.go
pkg/file/joiner/joiner.go
pkg/file/joiner/joiner_test.go
pkg/manifest/manifest.go
pkg/manifest/mantaray.go
pkg/manifest/simple.go
pkg/swarm/swarm.go
pkg/traversal/traversal.go
pkg/traversal/traversal_test.go

related to: #945 
Tackle some technical depth (details in the issue).

Return error from address iteration function

---

pkg/postage/listener/listener.go

naive implementation to keep on syncing forever

event listener: sync forever

---

cmd/bee/cmd/start.go
packaging/bee.service
packaging/deb/postinst

only the EnvironmentFile part is important (for the nixos packages).
i can drop the other commits from the PR if asked.

bee.service: make EnvironmentFile optional

---

pkg/node/node.go
pkg/retrieval/metrics.go
pkg/retrieval/retrieval.go

relates to: #1102
Introduces additional metrics in the `retrieval` package, and exposes them.

Instrument retrieval package

---

pkg/p2p/libp2p/libp2p.go
pkg/p2p/libp2p/metrics.go

this pr adds more metrics to our libp2p abstraction

libp2p: improve metrics

---

pkg/settlement/swap/chequebook/chequebook.go
pkg/settlement/swap/chequebook/chequebook_test.go
pkg/settlement/swap/chequebook/mock/chequebook.go
pkg/settlement/swap/metrics.go
pkg/settlement/swap/swap.go
pkg/settlement/swap/swap_test.go

adds a metric to show available balance. it is updated only when we pay, but I think it might be necessary in other places too. @ralph-pichler @metacertain can you please advise?
#1168

settlement: add available balance metric

---

pkg/debugapi/router.go

fix: conditionally enable chequebook endpoints

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

POST @ /soc
POST @ /chunk
debugapi / blocklist

OAS description updates

---

openapi/SwarmCommon.yaml

See https://github.com/ethersphere/bee/blob/42c12ede8c0b73aa6da097feb78a779535990be9/pkg/debugapi/chequebook.go#L40

docs: fix chequebookaddress response property name

---

pkg/settlement/swap/chequebook/init.go

app requires receiver to be prefixed with 0x

fix receiver encoding in bzzaar url

---

packaging/docker/README.md
packaging/docker/docker-compose.yml

Added instructions on how to run multiple bee nodes

---

pkg/debugapi/settlements.go
pkg/debugapi/settlements_test.go

debugapi: set received / sent to 0 if no settlements

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

used `prettier` to make nice again

openapi: lint yamls

---

pkg/pricing/pricing.go

a log line was not properly updated for the big int change

fix payment threshold log message

---

packaging/deb/postinst

In previous PR I missed deb postinst file and printed line

change print line for deb postinst, missed in previous pr

---

pkg/feeds/epochs/lookup_test.go

epoch feeds flake quite often. disabled for now

feeds: disable epochs tests

---

pkg/p2p/libp2p/libp2p.go

This PR adds more stream cleanups in some places where a dangling stream may still be left half-open.

libp2p: add more stream cleanups

---

pkg/api/chunk.go
pkg/api/soc.go
pkg/cac/cac.go
pkg/cac/cac_test.go
pkg/cac/export_test.go
pkg/feeds/putter.go
pkg/file/splitter/internal/job.go
pkg/soc/export_test.go
pkg/soc/soc.go
pkg/soc/soc_test.go
pkg/storage/testing/chunk.go

This PR refactor the chunk construction methods and remove some duplicated code.

Cac refactor

---

.goreleaser.yml

upgrades using brew overwrites existing password, with this PR installation will generate password only if password doesnt exist

check if password file already exists

---

pkg/settlement/swap/chequebook/init.go

wait for previous deployment attempt to succeed if bee is stopped while waiting for deploy tx

chequebook: continue waiting for previous deploy transaction

---

.github/workflows/release.yaml
.goreleaser.yml

Before this is released build and docker release on docker hub side is going to be disabled

Docker arm image support

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

Top up descriptions of request and response headers in bee API

Openapi headers revised

---

.goreleaser.yml

There is an issue when you brew upgrade the package.
Clef is already released with same fix and it works

fix brew post_install

---

.github/workflows/beekeeper.yml

Now its fixed for good, renamed `.event_type` to `.action`

fix repo dispatch for good

---

CODING.md

Update coding guidelines

---

pkg/kademlia/export_test.go
pkg/kademlia/kademlia.go
pkg/kademlia/kademlia_test.go
pkg/node/node.go
pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/mock/mock.go
pkg/p2p/p2p.go
pkg/topology/topology.go

Introducing the oversaturation limit and disconnections based on

Limit incoming connections

---

cmd/bee/cmd/start.go
packaging/bee-get-addr

mostly just rewordings, but
- fixes the Bzzaar URL's status=%d
- turns an error log into a warning

some housekeeping

---

pkg/kademlia/kademlia.go

kademlia: add bootnode connection timeout

---

pkg/localstore/gc.go

I thought the other PR (#1412 ) would automatically pick up my new commit, but I guess I messed up between the branch and master.  But THIS one passes the gofmt test, so hopefully it can go forward.

Gc metric fix

---

README.md

update the godoc badge to point to `pkg.go.dev`

readme: update godoc link

---

Dockerfile
Dockerfile.goreleaser

add --no-install-recommends to apt-get install

---

packaging/homebrew/bee-get-addr

fix amount

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

Add cashout endpoint parameters

---

pkg/settlement/swap/transaction/transaction.go

add a simple log line so we see what nonce bee is actually using

add nonce log line

---

pkg/bmt/bmt.go
pkg/bmt/cmd/generate-hashes/generate-hashes.go
pkg/bmt/cmd/main_legacy.go
pkg/bmt/doc.go
pkg/bmt/errors.go
pkg/bmt/legacy/bmt.go
pkg/bmt/legacy/bmt_test.go
pkg/bmt/legacy/doc.go
pkg/bmt/pool/pool.go
pkg/bmt/pool/pool_test.go
pkg/bmt/reference/doc.go
pkg/bmt/reference/reference.go
pkg/bmt/reference/reference_test.go
pkg/bmtpool/bmtpool.go

This PR imports the BMT repo content into the bee repo as is, so that we can maintain the part of the codebase more closely.

bmt: import bmt repo

---

.github/workflows/beekeeper.yml

pss: beekeeper tests

---

pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pullsync/mock/pullsync.go

pullsync: sync only in nn

---

Dockerfile
Dockerfile.goreleaser

Bump base image for docker image

bump debian base to 10.9-slim

---

.github/workflows/beekeeper.yml
pkg/pushsync/pushsync.go

restore CI parameters for thresholds

Restore CI parameters for thresholds

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/bzz.go
pkg/api/chunk.go
pkg/api/dirs.go
pkg/api/export_test.go
pkg/api/feed.go
pkg/api/feed_test.go
pkg/api/pss.go
pkg/api/pss_test.go
pkg/api/soc.go
pkg/api/soc_test.go
pkg/pss/pss.go
pkg/pss/pss_test.go
pkg/recovery/repair.go
pkg/recovery/repair_test.go

This PR wires in the stamper interface to stamp incoming chunks in places they were missing before.

api: stamper propagation

---

Makefile

Add to Makefile ability to spin up local bee cluster with single command

Make localcluster

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/db.go
cmd/bee/cmd/deploy.go
cmd/bee/cmd/init.go
cmd/bee/cmd/start.go
pkg/localstore/export.go
pkg/localstore/export_test.go

Adding Import/Export functionality to `bee`

cmd: add db import export

---

pkg/api/api.go
pkg/api/bzz.go
pkg/api/dirs.go
pkg/api/export_test.go
pkg/feeds/feed.go
pkg/feeds/testing/lookup.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/batchstore/reserve_test.go
pkg/postage/listener/listener.go
pkg/postage/postagecontract/contract.go
pkg/postage/testing/batch.go
pkg/postage/testing/chainstate.go
pkg/pss/trojan.go
pkg/resolver/client/ens/ens.go
pkg/settlement/swap/transaction/event_test.go
pkg/swarm/test/helper.go
pkg/tracing/tracing.go

Fixing some ongoing nuisances from deepsource.

storage incentives: reduce deepsource complaints

---

pkg/p2p/libp2p/internal/handshake/handshake.go

On outgoing connections logging of welcome messages has already been happening, this PR adds logging of incoming connections welcome message in handler of handshake

Add logging welcome message on incoming connections

---

pkg/node/node.go

Fixes some changes introduced with storage incentives branch which messed up the standalone mode. This is now rectified but uploads are not possible if no stampissuers are found. This is OK for now, but we'd need to think about some workaround to test the API locally somehow.
Also, a panic on shutdown is now fixed.

node: fix standalone mode, fix panic

---

cmd/bee/cmd/cmd.go
pkg/p2p/libp2p/internal/handshake/handshake.go

Fixed handshake string representation.

Light nodes: flipped default value

---

.github/workflows/beekeeper.yml
openapi/Swarm.yaml
openapi/SwarmCommon.yaml

Several inconsistencies declared in the pins and stamps endpoints
of the OpenAPI specification and the bee API server implementation
are removed. On top of that also fixes several declaration errors.

Fix OpenAPI specification inconsistencies

---

pkg/node/node.go
pkg/postage/mock/service.go
pkg/postage/service.go
pkg/postage/service_test.go

Wires in the functionality of persisting and loading batches on node shutdown and startup.

node, postage: persist and load batches

---

pkg/manifest/mantaray.go

This quick-fix prevents the mantaray manifest IterateAddresses method
walker to fail when it encounters an empty address, otherwise, the unpin
traversal operation for the manifest fails.

Quick-fix unpinning error caused by a manifest serialization bug

---

pkg/node/node.go
pkg/pricer/pricer.go
pkg/pricing/pricing.go
pkg/pricing/pricing_test.go

Right now it will disconnect if the condition is not met
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1635)

Add payment threshold validation

---

pkg/manifest/mantaray/marshal_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1666)

manifest: TestMarshal fix

---

go.mod
pkg/p2p/streamtest/streamtest.go
pkg/p2p/streamtest/streamtest_test.go
pkg/pushsync/export_test.go
pkg/pushsync/metrics.go
pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1680)

feat(pushsync): Add LRU cache to remember failed requests and select better peers

---

.github/workflows/beekeeper.yml
cmd/bee/cmd/cmd.go
cmd/bee/cmd/deploy.go
cmd/bee/cmd/start.go
pkg/node/chain.go
pkg/node/node.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go

Improve how many calls to the ethereum backend we're doing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1697)

feat: add block-time cli flag

---

pkg/api/router.go

This is follow up PR after #1597 that adds the new Postage stamp batch id header for CORS Preflight
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1706)

fix: postage header for cors preflight

---

pkg/node/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1713)

fix: unable to boot in standalone

---

cmd/bee/cmd/cmd.go
packaging/bee.yaml
packaging/docker/env
packaging/homebrew/bee.yaml
packaging/scoop/bee.yaml
pkg/localstore/localstore.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1709)

chore: decrease db capacity to 1M

---

pkg/p2p/streamtest/streamtest.go
pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1739)

fix: light node check in pushsync replication

---

pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/internal/metrics/metrics_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1730)

feat: quick prune of new peers with failed initial connection  

---

.github/workflows/go.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1751)

ci: commit lint only in PR

---

pkg/pushsync/pushsync.go

With forwarding replication in pushsync protocol, storer nodes ended up storing the chunk twice. With this fix, chunks will be stored only once. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1749)

fix: storer nodes to store the chunk only once

---

pkg/node/node.go
pkg/postage/batchservice/batchservice.go
pkg/postage/interface.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go
pkg/settlement/swap/transaction/transaction.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1745)

fix: start syncing at a later block

---

pkg/postage/batchstore/store.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1760)

fix: log missing batch id on err

---

pkg/pusher/pusher.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1758)

fix: pusher log on error

---

pkg/postage/batchstore/reserve_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1764)

fix: batchstore error assertion order

---

Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1763)

ci: failfast on makefile

---

pkg/postage/batchstore/reserve_test.go
pkg/postage/stamp.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1762)

fix(postage): dont swallow error

---

openapi/Swarm.yaml
pkg/api/postage.go
pkg/api/postage_test.go
pkg/api/router.go
pkg/postage/postagecontract/contract.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1769)

feat: allow specifying gasprice for postage stamp creation

---

openapi/SwarmDebug.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1771)

feat: Add /timesettlements endpoint

---

pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1754)

Fix: do not confirm replication happened unless chunk is stored

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

bee version update in openapi specification
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1776)

chore: version number in openapi

---

openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml
pkg/debugapi/postage.go
pkg/debugapi/postage_test.go
pkg/debugapi/router.go
pkg/postage/batchservice/batchservice.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/batchstore/mock/store.go
pkg/postage/batchstore/reserve.go
pkg/postage/batchstore/reserve_test.go
pkg/postage/batchstore/store.go
pkg/postage/chainstate.go
pkg/postage/interface.go
pkg/postage/reservestate.go
pkg/postage/testing/chainstate.go
pkg/tags/tags.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1756)

feat: expose chain state through the debug API endpoint

---

pkg/postage/batchservice/batchservice.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1778)

fix: postage sync update events

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
go.mod
go.sum
pkg/node/node.go
pkg/postage/listener/export_test.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go

* new postage contracts
* remove price oracle
* update blocknumber in listener even if there are no events
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1781)

feat: new postage contracts

---

pkg/node/node.go
pkg/postage/listener/listener.go
pkg/postage/listener/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1786)

feat: add listener metrics

---

.github/patches/postagereserve_gc.patch
pkg/postage/batchstore/reserve.go

Update reserve capacity to conform with storage requirements from users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1775)

feat: lower reserve capacity

---

pkg/localstore/migration.go
pkg/node/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1716)

chore: swipe migrate v0.5.3 to v0.6.0

---

packaging/bee.yaml
packaging/docker/env
packaging/homebrew/bee.yaml
packaging/scoop/bee.yaml

Added all new config options into packages config files with default values and descriptions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1794)

chore: add new config options into packages config with default values

---

pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1796)

refactor(kademlia): add manage loop notification as a separate method

---

pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

Change default bin size / balanced connection number to 8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1729)

param: change binsize

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1795)

chore: increment version to v0.6.1

---

pkg/node/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1808)

refactor(node): simplify bee shutdown repetitive io.Closer procedure

---

go.mod
go.sum
pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/internal/metrics/metrics_test.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1804)

fix(kademlia): inspect peer metrics snapshot in a safe manner

---

packaging/docker/docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1813)

chore: bump clef version in docker-compose.yaml

---

pkg/topology/kademlia/kademlia.go

This PR is trying to improve the situation (in one aspect) when a lot of peers are being added to the Kademlia. The keys in waitNext map are always encoded in hex format and that is not necessary. It is replaces with swarr.Address.ByteAddress which exists for this type of optimizations.
This is just a suggestion and I am attaching a part of cpu profile showing the path that is optimized here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1817)

perf(kademlia): optimize wait next map keys

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1835)

chore: bump version to 0.6.2

---

.github/workflows/go.yml
.github/workflows/release.yaml
Dockerfile
go.mod

This reverts commit 17f7837b9eb1e535739958f9534614e17e275039.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1855)

Revert "go: update to 1.16 (#1657)"

---

pkg/topology/kademlia/kademlia.go

@ldeffenb Sorry for hijacking your PR but I had not way to push to your branch :)
This PR is the same as ldeffenb's https://github.com/ethersphere/bee/pull/1826/files with the requested changes.
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1857)

fix: carry over existing failedAttempts after disconnect

---

pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1859)

fix: missing knownPeers remove

---

pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1861)

Kamdelia and metrics mutex optimizations 

---

pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1862)

fix: reduce bootnodes peers count

---

pkg/topology/kademlia/internal/waitnext/waitnext.go
pkg/topology/kademlia/internal/waitnext/waitnext_test.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1863)

refactor: waitNext map as a type

---

pkg/puller/puller.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1869)

refactor: puller mutex optimzations

---

pkg/node/node.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1868)

fix: shutdown node on errors from blockchain endpoint

---

pkg/topology/kademlia/export_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1878)

refactor: kademlia quicker bin saturation

---

pkg/topology/pslice/pslice.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1899)

fix: pslice variadic index panic

---

pkg/puller/puller.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1890)

refactor: improve puller cancellations

---

pkg/bmt/pool.go
pkg/node/chain.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1880)

chore: fix comment typo

---

pkg/node/node.go
pkg/pullsync/pullstorage/metrics.go
pkg/pullsync/pullstorage/pullstorage.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1913)

feat: add pullstorage metrics

---

openapi/Swarm.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1797)

fix: openapi remove linebreaker

---

.github/patches/listener.patch
.github/workflows/beekeeper.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1925)

ci: faster chain polling on ci

---

pkg/sctx/sctx.go
pkg/settlement/swap/chequebook/chequestore.go
pkg/statestore/leveldb/leveldb.go
pkg/statestore/leveldb/leveldb_test.go
pkg/statestore/mock/store.go
pkg/statestore/mock/store_test.go
pkg/statestore/test/store.go
pkg/steward/steward.go
pkg/steward/steward_test.go
pkg/storage/store.go

just fix several typo
solved: https://github.com/ethersphere/bee/issues/1896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1901)

fix: typo in comments

---

pkg/accounting/accounting.go
pkg/accounting/accounting_test.go
pkg/settlement/pseudosettle/doc.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1928)

chore: fix some comment typo

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1932)

chore: increment v0.6.3

---

pkg/api/pss.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1952)

fix: granular pss errors

---

.github/workflows/go.yml
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1956)

ci: add coveralls

---

openapi/SwarmCommon.yaml

Fixes #1920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1953)

fix: #/components/schemas/ProblemDetails definition was incorrect

---

.github/workflows/beekeeper.yml

fix version of contract deployment to use. this will enable us to increase the version in postage indexing PR.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1957)

feat: fix contract versions

---

pkg/api/postage_test.go
pkg/localstore/export.go
pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1961)

chore: same stamp unit test

---

pkg/localstore/localstore.go
pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go
pkg/localstore/mode_set_test.go
pkg/localstore/reserve_test.go
pkg/postage/batchstore/mock/store.go
pkg/postage/batchstore/mock/store_test.go
pkg/postage/stamp.go
pkg/postage/stamp_test.go
pkg/postage/stamper_test.go
pkg/storage/store.go
pkg/swarm/swarm.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1975)

chore: add batch params to chunk and add immutable stamp tests

---

pkg/node/node.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1960)

feat(kademlia): add prometheus metrics

---

pkg/pusher/metrics.go
pkg/pusher/pusher.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1977)

feat(pusher): receipt depth metric

---

pkg/topology/kademlia/kademlia_test.go

fixes the flaky address book prune test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1989)

fix(kademlia): flaky prune test

---

pkg/p2p/libp2p/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1990)

fix(libp2p): rename kickedout peers counter

---

.github/workflows/beekeeper.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1992)

ci: apply patches earlier

---

pkg/postage/listener/listener.go
pkg/settlement/swap/chequebook/factory.go
pkg/settlement/swap/priceoracle/priceoracle.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2065)

feat: add xdai addresses

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2067)

chore: bump v1.0.0

---

.goreleaser.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2073)

feat: add support for tagging docker image with prerelease version

---

pkg/topology/kademlia/kademlia.go

fix #2002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2003)

chore: error log info

---

pkg/pusher/pusher.go

This fixes a spurious error that is incorrectly logged when pushing chunks that were uploaded through the chunks api without a tag. This is visible in the integration tests since some of the tests use the chunks api directly, and therefore the pusher incorrectly logs that an error has occurred, since no tag is associated with the chunk.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2081)

fix(pusher): dont increment missing tags

---

go.mod
go.sum
pkg/debugapi/chequebook.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2030)

Fix cashout debug log format

---

pkg/postage/service.go

`master` does not compile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2095)

fix: new stamp issuer call

---

CODING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2104)

docs: add commit message convention to the CODING.md

---

pkg/p2p/libp2p/internal/handshake/handshake.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2110)

chore: increment handshake protocol

---

pkg/accounting/accounting.go
pkg/accounting/accounting_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2116)

fix: recompute expected debt after time settlement

---

pkg/accounting/accounting.go
pkg/accounting/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2120)

feat: Detailed accounting disconnect metrics

---

pkg/accounting/accounting.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2124)

fix: move a misplaced unlock

---

cmd/bee/cmd/db.go
pkg/localstore/gc_test.go
pkg/localstore/localstore.go
pkg/localstore/localstore_test.go
pkg/localstore/migration.go
pkg/localstore/migration_batch_index.go
pkg/localstore/migration_test.go
pkg/localstore/migration_yuj.go
pkg/localstore/schema.go
pkg/node/node.go
pkg/pullsync/pullstorage/pullstorage_test.go
pkg/pusher/pusher_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2112)

feat(localstore): add migration for batch-index

---

pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2127)

fix: origin credit in replication

---

pkg/bzz/address.go
pkg/debugapi/peer.go
pkg/debugapi/peer_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/p2p.go
pkg/settlement/swap/addressbook.go
pkg/settlement/swap/swap.go
pkg/settlement/swap/swap_test.go
pkg/settlement/swap/swapprotocol/swapprotocol.go
pkg/settlement/swap/swapprotocol/swapprotocol_test.go

Add a new `migratePeer` method to update addressbook.
Add new field `ethereum address`
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2126)

 fix: add Ethereum address field

---

pkg/node/statestore.go

Old overlay key is migrated to a new one for old nodes (mainly test-net) to operate properly. This will be be removed in the future, and we can may also migrate it back to the old key.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2133)

fix: old node overlay migration

---

pkg/statestore/leveldb/migration.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2136)

fix: flush stamps

---

pkg/accounting/accounting.go
pkg/accounting/accounting_test.go
pkg/settlement/pseudosettle/pseudosettle.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2135)

fix: non-blocking calls in pseudosettle

---

cmd/bee/cmd/cmd.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2139)

fix: update network id value

---

pkg/node/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2142)

feat: change global bandwidth refreshment rate

---

pkg/localstore/gc.go
pkg/localstore/reserve.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2144)

chore: remove logging from localstore

---

pkg/statestore/leveldb/migration.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2146)

fix: address delete

---

packaging/bee.yaml
packaging/docker/env
packaging/homebrew/bee.yaml
packaging/scoop/bee.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2155)

fix: update thresholds in packaging

---

pkg/accounting/accounting.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2152)

fix: seconds in overdraft blocklist

---

pkg/statestore/leveldb/migration.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2156)

fix: delete blocklist entries

---

pkg/node/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2154)

fix: introduce max threshold

---

README.md
cmd/bee/cmd/start.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2147)

add disclaimer

---

README.md
cmd/bee/cmd/start.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2157)

fix: remove whatsoever

---

pkg/node/node.go
pkg/transaction/sender_matcher.go
pkg/transaction/sender_matcher_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2160)

fix: cache verifications

---

Makefile
cmd/bee/cmd/start.go
cmd/bee/cmd/timebomb.go
version.go

This will print warnings about outdated version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2158)

feat: time based warning

---

pkg/transaction/export_test.go
pkg/transaction/sender_matcher.go
pkg/transaction/sender_matcher_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2161)

feat: add greylist to sender matcher

---

pkg/localstore/gc_test.go

fix localstore flaky test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2164)
fixes https://github.com/ethersphere/bee/issues/2153

fix: flaky test

---

pkg/postage/batchstore/metrics.go
pkg/postage/batchstore/reserve.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2163)

feat(batchstore): add storage radius metric

---

pkg/transaction/sender_matcher.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2166)

perf: tiny peer string optimization

---

pkg/transaction/sender_matcher.go

Only add to the greylist after actual errors. This is necessary because the handshake can and does frequently run mutiple times concurrently for the same peer.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2168)

fix: only greylist after error

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
packaging/bee.yaml
packaging/docker/docker-compose.yml
packaging/docker/env
packaging/homebrew/bee.yaml
packaging/scoop/bee.yaml

Allows for providing network alias instead of IDs.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2159)

feat: main net flag

---

cmd/bee/cmd/cmd.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2172)

chore: warmup time increase

---

.goreleaser.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2173)

chore: remove Prerelease docker tag

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2070)

bump to 1.0.1

---

.goreleaser.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2174)

chore: change beta tag to stable

---

pkg/debugapi/router.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2179)

fix: always enable tx api

---

.goreleaser.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2196)

fix: add commit time in releaser

---

packaging/bee.yaml
packaging/homebrew/bee.yaml
packaging/scoop/bee.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2186)

fix: change bee-mainnet to mainnet in yaml config file

---

cmd/bee/cmd/start.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2193)

fix: override block time for mainnet

---

openapi/SwarmDebug.yaml
pkg/debugapi/router.go
pkg/debugapi/transaction.go
pkg/debugapi/transaction_test.go
pkg/transaction/mock/transaction.go
pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2212)

feat: add tx cancel

---

pkg/node/chain.go
pkg/transaction/backend.go
pkg/transaction/backend_test.go

* show users how far behind the backend is
* show for which chain id factory was not found (so we can rule out a wrong backend connection)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2211)

feat: more blockchain related logging

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/bytes.go
pkg/api/bzz.go
pkg/api/chunk.go
pkg/api/feed.go
pkg/api/feed_test.go
pkg/api/pss.go
pkg/api/pss_test.go
pkg/api/soc.go
pkg/api/soc_test.go
pkg/debugapi/postage.go
pkg/debugapi/router.go
pkg/postage/mock/service.go
pkg/postage/service.go

This reverts commit 11fd56886cb0739aa3d510bcb7bb579632858fb2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2219)

revert: default stamp issuer

---

pkg/pullsync/pullsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2228)

fix: continue processing pullsync batch on unverifiable stamp

---

openapi/SwarmDebug.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2231)

revert: default stamp issuer OpenAPI debug endpoint

---

pkg/hive/hive.go
pkg/hive/hive_test.go
pkg/ratelimit/ratelimit.go
pkg/ratelimit/ratelimit_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2235)

feat: rate limit hive broadcast calls

---

pkg/pricing/pricing.go
pkg/pushsync/pushsync.go
pkg/settlement/pseudosettle/pseudosettle.go
pkg/settlement/pseudosettle/pseudosettle_test.go
pkg/settlement/swap/chequebook/chequestore.go
pkg/settlement/swap/chequebook/factory.go
pkg/settlement/swap/chequestore/mock/chequestore.go
pkg/settlement/swap/headers/utilities.go
pkg/settlement/swap/mock/swap.go
pkg/settlement/swap/priceoracle/mock/priceoracle.go
pkg/settlement/swap/priceoracle/priceoracle.go
pkg/settlement/swap/swap.go
pkg/settlement/swap/swapprotocol/swapprotocol.go

Fixing some deepsource complaints seen in other PRs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2281)

fix: deep source

---

cmd/bee/cmd/start.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2225)

fix: typo in URL

---

pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2233)

fix: disable forwarding node stamp verification

---

.goreleaser.yml
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2285)

fix: commit hash for bee version

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
pkg/config/chain.go
pkg/node/chain.go
pkg/node/node.go
pkg/postage/listener/listener.go
pkg/settlement/swap/chequebook/factory.go
pkg/settlement/swap/priceoracle/priceoracle.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2232)

fix: default network config

---

.github/workflows/beekeeper.yml
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/1978)

fix: enable light node test

---

pkg/localstore/mode_set.go

This PR adds a comment that is meant to resolve issue D from the least authority audit report
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2313)

chore: document implementation detail

---

openapi/Swarm.yaml
pkg/api/export_test.go
pkg/api/postage.go
pkg/api/postage_test.go
pkg/api/router.go

Reinstating the stamps to the api and marking them as deprecated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2279)

chore: reinstate stamps on the api

---

Dockerfile
Dockerfile.goreleaser
Dockerfile.scratch

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2315)

chore: bump base docker image

---

pkg/debugapi/peer_test.go
pkg/p2p/libp2p/internal/handshake/handshake.go
pkg/p2p/libp2p/internal/handshake/handshake_test.go
pkg/resolver/client/ens/ens_integration_test.go
pkg/resolver/client/ens/export_test.go
pkg/settlement/swap/mock/swap.go
pkg/tags/tag.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2320)

chore: fix typo

---

openapi/SwarmCommon.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2322)

fix: OpenAPI transaction info response fields type

---

openapi/SwarmCommon.yaml
pkg/debugapi/postage.go
pkg/debugapi/postage_test.go
pkg/postage/batchstore/mock/store.go
pkg/postage/batchstore/store.go
pkg/postage/interface.go
pkg/postage/mock/service.go
pkg/postage/service.go

Adds information to the endpoint to determine
whether a batch has already expired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2328)

feat: add expired field to the postage stamp response

---

pkg/p2p/libp2p/protocols_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2341)

ci: disable flaky test

---

pkg/localstore/mode_get.go
pkg/localstore/mode_get_multi.go
pkg/localstore/mode_get_multi_test.go
pkg/storage/store.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2338)

chore: remove dead code

---

pkg/debugapi/debugapi.go
pkg/debugapi/debugapi_test.go
pkg/debugapi/postage.go
pkg/debugapi/postage_test.go
pkg/node/node.go
pkg/postage/mock/service.go
pkg/postage/service.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2336)

feat: estimate expected lifetime of batches

---

openapi/SwarmCommon.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2350)

chore: add OpenAPI postage batch missing field

---

.github/patches/postagecontract.patch
.github/patches/postagereserve.patch
.github/patches/postagereserve_gc.patch
.github/workflows/beekeeper.yml
Makefile
pkg/debugapi/postage.go
pkg/postage/batchstore/reserve.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2318)

fix: reinstate gc test

---

openapi/Swarm.yaml
pkg/api/bzz.go
pkg/api/bzz_test.go
pkg/api/router.go
pkg/api/stewardship.go
pkg/api/stewardship_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2356)

refactor(api): move bzz patch under the stewardship endpoint

---

openapi/Swarm.yaml
openapi/SwarmDebug.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2364)
fixes https://github.com/ethersphere/bee/issues/2222

chore: bump openapi version

---

packaging/docker/docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2366)

bump clef in dockercompose

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2365)

chore: bump bee version

---

pkg/pullsync/pullsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2370)

fix: bad err formatting

---

pkg/transaction/backend.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2372)

fix: query header instead of block

---

pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2374)

fix: closest peer skip list

---

pkg/debugapi/postage.go

Fixes #2373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2375)

fix: postage stamp usable flag

---

pkg/debugapi/postage.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2376)

fix: postage stamp estimate batch not found result

---

pkg/hive/hive.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2377)

chore(hive): reduce log verbosity

---

pkg/pushsync/pushsync.go

Increasing the timeouts we have per chunk and less granular error handling as it has proved not to make a big difference and that out of NN blocking per chunk actually improves the experienced network behavior
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2378)

refactor: simplify error handling

---

pkg/debugapi/chequebook.go
pkg/debugapi/debugapi.go
pkg/debugapi/postage.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2379)

feat: limit concurrent access to some parts of the api resources

---

openapi/SwarmDebug.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2383)

fix: OpenAPI typos

---

openapi/Swarm.yaml
openapi/SwarmDebug.yaml
version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2386)

chore: bump to 1.1.0

---

openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2389)

docs: debug batch api

---

pkg/transaction/monitor.go
pkg/transaction/monitor_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2395)

fix: correct cancel nonce check

---

pkg/pusher/pusher.go

fixes https://github.com/ethersphere/bee/issues/1701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2402)

fix(pusher): err want self logging

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
pkg/node/node.go
pkg/postage/batchservice/batchservice.go
pkg/postage/batchservice/batchservice_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2405)

feat: add resync and more pprof profiles

---

.github/workflows/beekeeper.yml
Makefile
openapi/Swarm.yaml
openapi/SwarmCommon.yaml
pkg/api/api.go
pkg/api/api_test.go
pkg/api/export_test.go
pkg/api/router.go
pkg/api/stewardship.go
pkg/api/stewardship_test.go
pkg/debugapi/debugapi.go
pkg/debugapi/debugapi_test.go
pkg/node/devnode.go
pkg/node/node.go
pkg/steward/steward.go
pkg/steward/steward_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2357)

feat: add an API endpoint that checks if content is available

---

pkg/api/pss.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2406)

chore: increase targetMaxLength

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2414)

chore: add new badges to README

---

pkg/tags/tag.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2433)

fix: add missing ticker stop

---

pkg/api/pin_test.go

PR enhances the api/pin_tests to add pinning and encrypting to /bzz uploads
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2411)

chore: added encrypt and pin headers for /bzz requests in api/pin test 

---

packaging/bee.yaml
packaging/docker/env
packaging/homebrew/bee.yaml
packaging/scoop/bee.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2437)

fix: change default bootnode inside config to testnet

---

pkg/crypto/signer_test.go
pkg/transaction/sender_matcher_test.go
pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2421)

chore: remove use of some deprecated go-ethereum apis

---

pkg/node/chain.go
pkg/transaction/backend.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2416)

feat: wait for confirmations in WaitBlock

---

pkg/hive/hive.go

fixes a goroutine pileup on hive when validating large amounts of peers. this was only visible on the bootnodes on mainnet and this fix apparently solves the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2444)

fix(hive): prevent goroutine pileup on hive validation

---

pkg/node/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2438)

fix: chain ID error message

---

.goreleaser.yml
packaging/deb/postinst
packaging/rpm/post

printe text looks bad with it because it fails to properly parse it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2447)

fix: remove ` from print text

---

go.mod
go.sum

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2461)

chore: update libp2p version

---

pkg/retrieval/retrieval_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2469)

fix: retrieval flaky test

---

pkg/resolver/client/ens/ens.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2458)

fix: use correct prefix for ens entries

---

pkg/topology/kademlia/binprefix.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2468)

refactor: move bin prefix logic to new file

---

pkg/tags/tags.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2476)

chore: remove tag logline

---

pkg/p2p/mock/mock.go
pkg/topology/kademlia/binprefix.go
pkg/topology/kademlia/export_test.go
pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/internal/metrics/metrics_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2412)

feat: prune oversaturated bins when depth increases

---

pkg/topology/kademlia/internal/metrics/metrics_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2483)

fix: unit test

---

pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2484)

fix: added missing metric

---

.github/workflows/go.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2486)

chore: remove deepsource for good

---

pkg/localstore/metrics.go
pkg/localstore/mode_get_multi.go
pkg/pushsync/metrics.go
pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2487)

chore: improve metrics

---

.github/stale.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2488)

chore: add stale bot config

---

pkg/tags/tags.go
pkg/tags/tags_test.go

This PR attempts to solve a problem with fixed seed generation of new tags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2425)

fix: random generation of tag uids

---

.github/workflows/beekeeper.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2500)

fix: updated go version in beelocal tests

---

cmd/bee/cmd/bee-welcome-message.txt
cmd/bee/cmd/start.go

Separating makes future alternation to the welcome
message and its ASCII art much easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2333)

refactor: move welcome message into separate file

---

pkg/hive/hive.go
pkg/hive/metrics.go

Few more metrics to improve visibility around connectivity.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2497)

feat: extra metrics for connectivity

---

pkg/hive/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2504)

chore: lint

---

.github/workflows/go.yml
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2510)

ci: test once

---

pkg/hive/hive.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2511)

fix: add peer to cache if found in addressbook

---

pkg/p2p/libp2p/libp2p.go
pkg/p2p/libp2p/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2513)

refactor: add p2p headers exchange duration metrics

---

pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2514)

fix(kademlia): change metric histogram resolution to seconds

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2519)

chore: bump 1.2.0

---

.github/workflows/go.yml

Disabling coveralls till they sort stuff out
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2525)

ci: disable coveralls

---

pkg/pushsync/metrics.go
pkg/pushsync/pushsync.go

Metrics to show how many times replication request came from any other node than the closest connected peer to chunk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2509)

feat: metrics for non closest storer

---

pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2528)

chore: added more logs to pushsync

---

pkg/pushsync/pushsync.go
pkg/retrieval/retrieval.go
pkg/swarm/swarm.go
pkg/swarm/swarm_test.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2527)

refactor: closer func

---

pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2529)

fix: switched to each peer iterator for pushsync replication

---

pkg/discovery/mock/mock.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2539)

fix: handle background broadcasts using separate context

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
pkg/hive/hive.go
pkg/hive/hive_test.go
pkg/node/node.go

related to #1439 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2538)

fix: avoid advertising private IP addresses to the public network

---

pkg/topology/kademlia/export_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2547)

chore: increase ping interval

---

pkg/blocker/blocker.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2548)

refactor: kademlia close err group

---

pkg/node/devnode.go
pkg/postage/batchservice/batchservice.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/interface.go
pkg/postage/mock/service.go
pkg/postage/postagecontract/contract.go
pkg/postage/service.go
pkg/postage/service_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2546)

fix: persist postage stamps on add

---

.github/workflows/go.yml

Reverts ethersphere/bee#2525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2558)

revert: disable coveralls

---

pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2557)

fix(kademlia): bootnode metrics

---

.github/workflows/go.yml
README.md
openapi/SwarmCommon.yaml
pkg/node/node.go
pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/export_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/p2p.go
pkg/p2p/p2p_test.go
pkg/puller/metrics.go
pkg/puller/puller.go
pkg/recovery/repair_test.go
pkg/retrieval/retrieval_test.go
pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/internal/metrics/metrics_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go
pkg/topology/kademlia/mock/kademlia.go
pkg/topology/mock/mock.go
pkg/topology/topology.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2564)

feat: update reachability state of node

---

pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2570)

fix: bootnode connection direction

---

pkg/p2p/discover.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2571)

fix: include all dns protocol prefixes in discovery

---

pkg/puller/puller.go
pkg/pullsync/pullsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2572)

chore: disable logging again

---

pkg/topology/kademlia/kademlia.go

Fixes #2634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2636)

fix: panic in kademlia metrics

---

Makefile
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml
pkg/api/version.go
pkg/debugapi/debugapi_test.go
pkg/debugapi/status.go
pkg/debugapi/status_test.go
pkg/debugapi/version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2638)

feat: add bee open API versions info to the health endpoint

---

pkg/api/bzz_test.go
pkg/api/stewardship_test.go
pkg/node/devnode.go
pkg/steward/mock/steward.go

Closes #2441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2640)

fix: panic on stewardship endpoints in dev mode

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2647)

chore(ver): bump v1.4.0

---

pkg/auth/auth.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2652)

fix: add accounting endpoint role

---

.github/workflows/beekeeper.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2657)

ci: add postage intergration test to git workflow

---

.github/workflows/beekeeper.yml
pkg/api/api.go
pkg/pusher/pusher.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2658)

fix: retry push on err, drain semaphore

---

pkg/auth/auth.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2660)

fix: topup role

---

pkg/auth/auth.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2659)

fix(auth): missing roles

---

pkg/api/api.go
pkg/pusher/pusher.go
pkg/pusher/pusher_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2662)

fix: direct op

---

pkg/api/api.go
pkg/api/export_test.go
pkg/api/metrics.go
pkg/api/metrics_test.go
pkg/api/router.go

related to https://github.com/ethersphere/grafana-dashboards/issues/54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2655)

chore: upload and download api metrics middleware

---

.github/workflows/beekeeper.yml
pkg/node/devnode.go
pkg/node/node.go
pkg/settlement/pseudosettle/pseudosettle.go
pkg/settlement/pseudosettle/pseudosettle_test.go

This PR attempts to differentiate a refresh rates given to / enforced by light nodes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2621)

feat: differentiate refresh rate

---

pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2664)

feat: make forwarder storing non-blocking

---

.github/workflows/beekeeper.yml

restore beekeeper branch used to master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2675)

fix: beekeeper branch

---

pkg/p2p/libp2p/internal/handshake/handshake.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2676)

chore(handshake)!: bump protocol version

---

pkg/api/bytes.go

Do not create tags before validating stamp during bytes upload
#2141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2673)

fix: check stamp before creating tag in /bytes upload

---

README.md

Note about Bee's versioning strategy. Feel free to comment if you want different wording or something is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2678)

docs: versioning strategy note

---

pkg/api/router.go
pkg/debugapi/cors.go

Closes #2683 
Co-authored-by: Cafe137 <77121044+Cafe137@users.noreply.github.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2684)

fix: cors passing user-agent

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2695)

chore(version): bump to 1.4.1

---

pkg/pusher/pusher.go

fixes #2702 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2703)

fix(pusher): feed channel respects warmup

---

CODINGSTYLE.md
README.md
style.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2666)

doc: style guide

---

Makefile

Run `make format` to sort imports deterministically and apply an enhanced `gofmt` code simplifier (throughout the project).
To format a location run `make format FOLDER=pkg/mypackage`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2691)

feat: code formatter command

---

.golangci.style.yml
CODINGSTYLE.md

Run `lint-style` to run the linter with this profile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2690)

feat: lint style command

---

pkg/p2p/streamtest/streamtest.go
pkg/retrieval/metrics.go
pkg/retrieval/retrieval.go
pkg/retrieval/retrieval_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2706)

feat: preemptive retrieval based on mainnet p90

---

pkg/p2p/streamtest/streamtest.go
pkg/retrieval/metrics.go
pkg/retrieval/retrieval.go
pkg/retrieval/retrieval_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2718)

revert: preemptive retrieval based on mainnet p90

---

pkg/retrieval/retrieval.go
pkg/retrieval/retrieval_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2719)

perf(retrieval): faster preemptive retry

---

CODINGSTYLE.md

Add missing chapter on naked returns
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2716)

docs: naked returns chapter

---

version.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2730)

chore: bump v1.4.2

---

.goreleaser.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2726)
Closes #2725

fix: add missing goreleaser ldflags

---

pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2731)

feat: nonconditional expiring skip of peers pushed

---

pkg/topology/kademlia/kademlia.go

Closes #2693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2728)

fix: changing node reachability status

---

pkg/node/node.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2733)

fix: no pulling on bootnodes

---

pkg/topology/kademlia/kademlia.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2734)

fix: ignore reachability status updates to unknown

---

openapi/SwarmCommon.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2738)

fix: whitespace

---

pkg/debugapi/node_test.go

https://github.com/ethersphere/bee/pull/2649#discussion_r763010896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2720)

test: add missing unit test for BeeNodeMode enum

---

.github/workflows/release.yaml
.goreleaser.yml

set missing env variables inside .goreleaser.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2739)

fix: set missing env variables inside .goreleaser.yaml

---

pkg/node/devnode.go

Closes #2440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2743)

fix: inaccurate database capacity in dev mode

---

cmd/bee/cmd/db.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2746)

fix: remove subdirectories, not root path for migration command

---

codecov.yml

Due to popular demand
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2748)

ci: disable codecov comments

---

pkg/localstore/mode_put_test.go

Adds the missing unit test for this edge case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2753)

test(localstore): add write-in-place test

---

pkg/localstore/disaster_recovery.go
pkg/localstore/disaster_recovery_test.go
pkg/localstore/localstore.go
pkg/localstore/migration.go
pkg/localstore/migration_sharky.go
pkg/localstore/schema.go
pkg/shed/db.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2752)

feat: sharky DRP

---

pkg/localstore/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2763)

feat: enable sharky metrics

---

CODINGSTYLE.md
pkg/accounting/accounting_test.go
pkg/postage/batchservice/batchservice_test.go
pkg/pushsync/pushsync_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2769)

docs(styleguide): don't use fail as test keyword

---

openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml
pkg/debugapi/export_test.go
pkg/debugapi/postage.go
pkg/debugapi/postage_test.go
pkg/debugapi/router.go
pkg/postage/batchstore/mock/store.go
pkg/postage/batchstore/store.go
pkg/postage/batchstore/store_test.go
pkg/postage/interface.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2767)

feat(postage): network commitment

---

pkg/sharky/store.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2770)

fix: read error metrics counter

---

pkg/sharky/metrics.go
pkg/sharky/store.go

Add release counters and current shard size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2771)

Improve sharky metrics

---

pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2774)

fix(kademlia): no once on reachability

---

pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

Increase redundancy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2772)

feat: increase minimum neighborhood size

---

pkg/localstore/localstore.go
pkg/localstore/migration_sharky.go
pkg/sharky/recovery.go
pkg/sharky/recovery_test.go
pkg/sharky/shard_only_test.go
pkg/sharky/shard_slots_test.go
pkg/sharky/sharky_test.go
pkg/sharky/slots.go
pkg/sharky/store.go

This change removes the check for the upper size limit of sharky.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2764)

fix: remove sharky size limit

---

pkg/node/devnode.go
pkg/postage/batchservice/batchservice.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/batchstore/export_test.go
pkg/postage/batchstore/mock/store.go
pkg/postage/batchstore/mock/store_test.go
pkg/postage/batchstore/reserve.go
pkg/postage/batchstore/reserve_test.go
pkg/postage/batchstore/store.go
pkg/postage/batchstore/store_test.go
pkg/postage/interface.go
pkg/postage/testing/batch.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2782)

refactor: split batchstore Put method to Create and Update

---

version.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2801)

chore: bump v1.4.3

---

pkg/chainsync/chainsync.go

Fixes a stream leak in chainsync
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2802)

fix(chainsync): stream leak

---

pkg/p2p/libp2p/connections_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2804)

chore: disable flaky test

---

version.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2803)

chore: bump 1.4.4

---

pkg/p2p/libp2p/connections_test.go

New test is added to ensure that all new libp2p streams after the number of concurrent max input streams limit is reached result with the stream reset error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2809)

test(libp2p): validate max input stream behaviour

---

openapi/SwarmDebug.yaml

Closes #2813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2817)

fix: OpenAPI stamps EP amount value

---

pkg/intervalstore/store_test.go
pkg/keystore/file/service_test.go
pkg/localstore/gc_test.go
pkg/localstore/localstore.go
pkg/localstore/migration_test.go
pkg/postage/batchstore/reserve_test.go
pkg/shed/db_test.go
pkg/statestore/leveldb/leveldb_test.go

We can write less code by using the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2790)

test: use T.TempDir to create temporary test directory

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml
pkg/api/pin.go
pkg/debugapi/peer.go
pkg/debugapi/postage.go
pkg/debugapi/postage_test.go
pkg/pinning/pinning.go

our collection responses are not aligned when it comes to empty arrays - we get mixed `[]` and `null`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2821)

fix: return empty array instead of null

---

pkg/postage/batchstore/export_test.go
pkg/postage/batchstore/reserve.go
pkg/postage/batchstore/store.go
pkg/postage/batchstore/store_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2825)

refactor: batchstore migration

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2831)

chore: bump 1.5.0

---

pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go
pkg/sharky/store.go

Fixes #2845
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2848)

fix: incorrect release of sharky locations

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2852)

chore: bump v1.5.1

---

go.mod
go.sum
pkg/crypto/eip712/typeddata.go

Updating the `karalabe/usb` dependency to fix m1 build warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2835)

chore(deps): update go-ethereum

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
pkg/node/bootstrap.go
pkg/node/node.go
pkg/node/statestore.go
pkg/postage/batchservice/batchservice.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/interface.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go
pkg/retrieval/retrieval.go
pkg/storage/inmemstore/store.go
pkg/storage/inmemstore/store_test.go

[Issue](https://github.com/ethersphere/bee-backlog/issues/17)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2814)

feat: bootstrap node from postage snapshot

---

go.mod
go.sum
pkg/blocker/blocker.go
pkg/blocker/blocker_test.go
pkg/blocker/export_test.go
pkg/chainsyncer/chainsyncer_test.go

Stops the internal clock of the blocker instance during hibernation so that the peer list is not blocked upon wakeup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2857)

fix: blocklisting peers after waking up from hibernation

---

pkg/file/joiner/joiner.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2863)

fix: an attempt to validate data mutation

---

pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/export_test.go
pkg/sharky/sharky_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2867)

fix: increase timeout for flaky test

---

pkg/blocker/blocker.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2871)

feat: suspend kademlia blocklisting on network outage

---

pkg/localstore/localstore_test.go
pkg/netstore/netstore.go
pkg/netstore/netstore_test.go
pkg/sharky/shard.go
pkg/sharky/store.go
version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2870)

fix: hotfix for v1.5.0 download race

---

.github/workflows/beekeeper.yml
.github/workflows/go.yml
.github/workflows/release.yaml
.github/workflows/release_triggers.yaml
.github/workflows/schedule.yaml

This PR consolidates all secrets variables, we defined some org wide variables and bee will use them, we will rotate and manage those variables more easily
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2874)

chore: consolidate all secrets variables

---

version.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2877)

chore: bump to v1.5.2

---

openapi/SwarmCommon.yaml
pkg/blocker/blocker.go
pkg/blocker/blocker_test.go
pkg/chainsyncer/chainsyncer.go
pkg/chainsyncer/chainsyncer_test.go
pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/libp2p/unreachable_errors_unix.go
pkg/p2p/libp2p/unreachable_errors_windows.go
pkg/p2p/mock/mock.go
pkg/p2p/p2p.go
pkg/p2p/streamtest/streamtest.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/metrics.go
pkg/topology/topology.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2880)

refactor: move the network availability functionality to the libp2p

---

pkg/blocker/blocker.go
pkg/blocker/blocker_test.go
pkg/chainsyncer/chainsyncer_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/mock/mock.go
pkg/p2p/p2p.go
pkg/p2p/streamtest/streamtest.go
pkg/topology/kademlia/kademlia.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2886)

refactor: simplification and cleanup

---

pkg/settlement/swap/chequebook/init.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2861)

feat: print required funds for gas and respect deployment gas price

---

pkg/p2p/libp2p/libp2p.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2885)

fix: reset stream on addcontextheader fail

---

pkg/netstore/metrics.go
pkg/netstore/netstore.go
pkg/node/node.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2882)

feat: add netstore metrics

---

pkg/node/devnode.go
pkg/steward/mock/steward.go

Fixes #2888
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2889)

fix: panic for the stewardship endpoint in dev mode

---

pkg/file/joiner/joiner.go
pkg/file/joiner/joiner_test.go
pkg/localstore/mode_set.go
pkg/pinning/pinning.go

Fixes a bug where unpinning of encrypted content resulted in an error, this is due to the traversal service reporting long references that include the decryption key, which in turn resulted in the localstore trying to unpin an address that doesn't exist. This is due to the fact that localstore does not perform a bounds check on the input of `swarm.Address` and the fact that `swarm.Address` is an unbounded type that does not enforce input validation on the size of the address/reference. Therefore, the localstore was looking for a chunk with 64 byte long address which never existed in the pin index. 
I conducted some tests to verify that no chunks are stored with 64 byte long addresses on `Put` but it seems that this doesn't happen. Plus, the `cac` and `soc` validators make sure that the …

fix: unpinning of encrypted references

---

pkg/api/api.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2901)

chore(api): improve logging on middleware error

---

.github/workflows/release_triggers.yaml
.goreleaser.yml
packaging/bee.yaml
packaging/homebrew-amd64/bee.yaml
packaging/homebrew-arm64/bee.yaml

Consolidate linux package names and set trigger to publish newly created packages in orgs deb and rpm [repo](https://github.com/ethersphere/repos) (`bee-clef` is already included)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2892)

Package repos

---

pkg/blocker/blocker_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2903)

chore: fix flaky test

---

pkg/statestore/leveldb/migration.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2908)

chore: remove delete log from statestore migration

---

packaging/bee.yaml
packaging/docker/docker-compose.yml
packaging/docker/env
packaging/homebrew-amd64/bee.yaml
packaging/homebrew-arm64/bee.yaml
packaging/scoop/bee.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2906)

chore: remove global pinning config from packaging
