pkg/settlement/pseudosettle/pseudosettle.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2358)

fix: use our own timestamp in too soon check

---

pkg/topology/kademlia/kademlia.go

This PR disabled active dialing for bootnodes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2169)

feat: bootnodes dont dial

---

packaging/docker/env

updates the comment to set the correct chain ID when running in docker compose
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2367)

chore(packaging): update comment

---

.goreleaser.yml

When tagging RC push only `rc` and `latest` tag to the dockerhub
@acud I think this makes sense, only when releasing stable version set all other tags (`major`, `major.minor`, `major.minor.patch` and `stable`) for RC only `major.minor.patch-rc` and `latest` (rc tag will not be set for stable build)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2369)

feat: dont push all docker image tags to the dockerhub for rc

---

openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

Adds missing HTTP responses to the POST `/stamps/{amount}/{depth}`
and POST `/chequebook/cashout/{peer}` endpoints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2387)

chore(openapi): add missing HTTP responses

---

pkg/manifest/mantaray/export_test.go
pkg/manifest/mantaray/marshal.go
pkg/manifest/mantaray/marshal_test.go
pkg/manifest/mantaray/node.go
pkg/manifest/mantaray/node_test.go
pkg/manifest/mantaray/walker_test.go

The fix added earlier to fix the nodeType information on root nodes actually overrides the values in the case of other nodes, resulting in incorrect nodeType information on Lookup. Due to this, we will not process the node returned as a valid path and hence return `404` although we have the reference.
The correct fix for the above issue was actually sitting in the original manifest repository as an open PR. This PR was approved but never merged. Pulling in the changes here.
https://github.com/ethersphere/manifest/pull/20/files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2380)

fix(mantaray): mantaray lookup issue

---

pkg/debugapi/postage.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2390)

fix: turn on postage usable flag only when postage stamp exists

---

openapi/Swarm.yaml
pkg/api/api_test.go
pkg/api/chunk.go
pkg/api/chunk_stream.go
pkg/api/chunk_stream_test.go
pkg/api/export_test.go
pkg/api/pss.go
pkg/api/router.go
pkg/api/tag_test.go

Currently in the `/chunks` API we only support single chunk upload
Applications using the `/chunks` endpoint need to loop while sending multiple chunks. This can cause server to hit issues due to too many connections (or on client-side while re-using connections we might see an EOF).
As we already use the `gorilla/websocket` library, I think it would be better to have a client-side streaming endpoint to upload multiple chunks. This will be easier on the server side as well as would re-use all the resources initialised for the first chunk upload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2230)

feat: chunk stream upload endpoint

---

.github/ISSUE_TEMPLATE/bug-report.md

Changing the default label from `bug` to `needs-triaging` since not every new issue is a bug and issue reports that lack proper description should be closed and not accounted for. This will hopefully lower the psychological barrier of closing sloppily described issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2404)

chore: improve issue template

---

Makefile

Updated to the earliest version that supports M1 chip. This should not change any linter rules. See the corresponding issue https://github.com/golangci/golangci-lint/issues/1725
Feel free to reject this if you have different workflow to update dependencies.
NOTE: tests still don't work as these would require beekeeper to be compiled to M1 chip
before:
`make lint`
```sh
test -f $(go env GOPATH)/bin/golangci-lint || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
golangci/golangci-lint info checking GitHub for tag 'v1.30.0'
golangci/golangci-lint info found version: 1.30.0 for v1.30.0/darwin/arm64
make: *** [linter] Error 1
```
after:
`make lint`
```sh
test -f $(go env GOPATH)/bin/golangci-lint || curl -sSfL …
```

chore(deps): update linter version to make linting work on macs with M1

---

pkg/topology/kademlia/internal/metrics/metrics.go

Fixes #2417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2418)

fix: only flush dirty metrics

---

pkg/topology/kademlia/kademlia.go

Fixes #2423 
This PR moves the kademlia metrics flushing out of the main ManageC loop and into a dedicated goroutine.  This solves the issue of the 15 second timer never (or rarely) actually firing and the metrics never actually flushing until the node is terminated.  The new goroutine is added to the wait group and marks itself done when it exits so that the kademlia shutdown logic remains consistent.
I also changed the timer to 5 minutes since the metrics do actually get flushed now without competing with the connector.  The shutdown logic in Close still Finalizes the metrics collector which will ensure that the most recent updates are still persisted.
You will also notice a new Tracef log showing that the flush happened and how long it took to execute. This is similar to the existing …

feat: flush metrics in separate goroutine

---

pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/internal/metrics/metrics_test.go
pkg/topology/kademlia/kademlia.go

this PR introduces an expiring context to the metrics finalizer in kademlia. as noted by @ldeffenb the shutdown takes too long and we should not wait indefinitely there. this is a stopgap solution until we come up with a better persistence solution that doesn't burden the shed abstraction with too much IO with regards to these metrics. We also need metrics pruning, since this can just burden other components with statestore size at some point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2428)

fix: allow dirty metrics shutdown

---

pkg/transaction/sender_matcher.go
pkg/transaction/sender_matcher_test.go

allow transactions whose transaction data matches the overlay eth address exactly (a 32-byte data), regardless of sender. the first 4 bytes are required to be 0 to distinguish it from a 32-byte data transaction from the overlay. That way every tx can only be valid for one overlay.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2409)

feat: allow transaction from another sender for identity tx

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/bzz.go
pkg/api/bzz_test.go
pkg/api/dirs.go
pkg/api/dirs_test.go
pkg/api/feed.go
pkg/api/feed_test.go
pkg/file/loadsave/export_test.go
pkg/file/loadsave/loadsave.go
pkg/file/loadsave/loadsave_test.go
pkg/traversal/traversal.go
pkg/traversal/traversal_test.go

this PR simplifies the `loadsave` abstraction to remove state like encryption and mode. those are now injected through a pipeline factory. It also handles more explicitly the cases where a readonly loadsaver is needed, so that readonly operations on manifest can happen. this is now possible by requesting explicitly a read-only loadsaver.
also adds missing unit test coverage and documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2443)

refactor(loadsave): simplify interface

---

openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml

This PR fixes few things in the OpenAPI regarding the pending transactions API:
- TransactionHash is to my knowledge prefixed with `0x` as all the Ethereum hashes should be...
- The `/transactions` endpoint actually provides all the `TransactionInfo` and not only `TransactionHashes`
- Fixing some typos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2439)

docs: correct types for transaction listing and tweaks

---

pkg/topology/kademlia/kademlia.go
pkg/topology/pslice/pslice.go
pkg/topology/pslice/pslice_test.go

PR intends to limit the balanced connector's domain of work to bins that could be balanced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2430)

feat: balancer connector skips unpopulated, out of depth bins

---

pkg/api/chunk_stream.go

Don't log an error message on `ReadMessage` if the client closed the connection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2445)

fix: unnecessary error message on close

---

pkg/topology/kademlia/kademlia.go
pkg/topology/pslice/pslice.go
pkg/topology/pslice/pslice_test.go

PR removes the `overSaturationPeers` check in `connectNeighbours`, and the second iterator neighborhood connector. We have more PRs up now that prunes oversaturated bins (which this PR causes to happen) and more optimizations to increase build up time. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2427)

feat: simplify kademlia topology build up

---

pkg/api/bzz_test.go
pkg/api/dirs.go
pkg/api/tag_test.go

I was tracking down why in browser I would not get created `Swarm-Tag` header for uploaded collection, but I would get it for uploaded file. 
I added some checks for tests for this which did not catch the problem as it was CORS related, but I think I can leave the tests checks for completnes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2450)

fix: cors expose swarm-tag header for bzz dir upload

---

pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/metrics.go

After running a bee node in main-net for two days with the discrepancy metric, it was discovered that the issue has been fixed and the kludge can be removed.
PR includes deepsource fixes:
`kad.connected` renamed to `kad.onConnected`
`pslice.exists` renamed to `pslice.index`
`Announce`, `Connected`, `AnnounceTo` split into two new functions to avoid control coupling or simplified
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2429)

fix: removed kademlia and libp2p discrepancy kludge

---

pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/export_test.go
pkg/p2p/libp2p/libp2p.go

This PR add a custom User Agent string to libp2p host which is communicated between peers over the internal libp2p Identify protocol. On every connection, the user agent is logged if it exists.
The current proposal for the user agent is in this form: `bee/<version> <goversion> <GOOS>/<GOARCH>`. For example `bee/1.1.1-dev go1.15.14 darwin/amd64`. It is debatable if all of these information should be included. It is encouraged to give your opinions on this subject.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2462)

feat(libp2p): add custom user agent and log it on connection

---

.github/workflows/beekeeper.yml
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2456)
To build, install and use custom beekeeper branch you can set env variable globally or set it in make command
```
jobs:
beekeeper:
name: Infra tests
env:
REPLICA: 3
RUN_TYPE: "PR RUN"
SETUP_CONTRACT_IMAGE_TAG: "0.2.0"
BEEKEEPER_BRANCH: "CUSTOM-BRANCH"
```
`Line 51` of `beekeeper.yaml`
```
make beekeeper BEEKEEPER_INSTALL_DIR=/usr/local/bin BEEKEEPER_USE_SUDO=true BEEKEEPER_BRANCH=CUSTOM-BRANCH
```

fix: build custom beekeeper

---

pkg/node/node.go

verify our own identity transaction on startup. primarily useful to prevent user mistakes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2422)

feat: verify own transaction

---

openapi/SwarmCommon.yaml
pkg/api/pss.go
pkg/api/pss_test.go

This PR improves the API responses for not valid PSS targets and improves documentation of the PSS targets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2463)

feat: pss target input validation

---

pkg/statestore/leveldb/migration.go

- enable the migration
- fix unmarshal hex string without 0x prefix
into Go value of type common.Address
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2480)

fix: ethereum address migration

---

pkg/accounting/accounting.go
pkg/accounting/accounting_test.go
pkg/debugapi/peer.go
pkg/debugapi/peer_test.go
pkg/node/devnode.go
pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/libp2p/protocols_test.go
pkg/p2p/mock/mock.go
pkg/p2p/p2p.go
pkg/p2p/streamtest/streamtest.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2471)

feat: p2p disconnect with reason

---

pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/libp2p.go

This pr fixes the flaky test that checks for libp2p user agent in logs in high load environments like CI. It also ensures higher probability that the user agent is logged in high load environments.
The core problem is that the peerstore may not contain all keys and values right after the connections is created.
This retry mechanism ensures more reliable user agent propagation.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2482)

fix: retry user agent get from libp2p peerstore

---

pkg/file/joiner/joiner.go
pkg/file/joiner/joiner_test.go

**SWA-01-010 WP2: Unbounded recursion in file joiner** _(Medium)_
While reviewing the file joiner implementation, it was found that the code allows for an
unbounded recursive call.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2481)

fix: recursive file joiner read

---

pkg/api/bzz.go
pkg/api/bzz_test.go

**SWA-01-012 WP2: Potential directory traversal in download API** _(Medium)_
While reviewing the API implementation, it was found that the file download API possibly a directory traversal issue
It can be observed that the filename provided in the file’s metadata is directly returned in filename part of the Content-Disposition header. An attacker might, however, provide names   such   as  `../../../../etc/passwd`  or   similar,   which   could   subsequently   be accidentally used by client-code. In order to address this issue, it is recommended to already filter file names in the API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2489)

fix: filter out filename path

---

.github/workflows/go.yml
.github/workflows/release.yaml
Dockerfile
go.mod
go.sum

leveldb has updated the snappy compression that caused a segfault on arm64 cpus. as of such we can update to go 1.16 (although 1.17 is already out)
related to #1876 #1806 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2495)

chore: update golang and ldb

---

pkg/p2p/libp2p/internal/handshake/handshake.go
pkg/p2p/libp2p/internal/handshake/metrics.go
pkg/p2p/libp2p/metrics.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2490)

feat: add handshake protocol messages metrics

---

pkg/hive/hive.go
pkg/hive/metrics.go

This should make network latency observable.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2498)

feat: ping time metric

---

pkg/pushsync/metrics.go
pkg/pushsync/pushsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2502)

feat: invalid stamp metric

---

pkg/hive/hive.go
pkg/hive/hive_test.go
pkg/node/node.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2491)

feat: skip validation if peer is known

---

.github/workflows/go.yml

moving the coverage step so that tests are cached (now they aren't)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2506)

ci: move coverage step

---

pkg/pushsync/pushsync.go

this PR adds traces for replication (on the origin and target nodes) and moves the handler span creation to the right place
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2520)

refactor(pushsync): better tracing

---

pkg/pushsync/pushsync.go

Forwarding nodes that replicate should be warmed up and, in the case of a replication error, should continue forwarding it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2524)

fix: continue forwarding if replication fails

---

pkg/pushsync/metrics.go
pkg/pushsync/pushsync.go

PR includes timer metrics, we time the entire handler method and also individual push calls to peers.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2508)

feat: more pushsync metrics

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
pkg/node/node.go
pkg/topology/kademlia/export_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go
pkg/topology/topology.go

Add configuration for adding protected nodes on the bootnodes. This change will prevent kicking out of the protected nodes to ensure better connectivity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2512)

 feat(kademlia): static nodes

---

pkg/statestore/leveldb/migration.go

prevents the corruption of the swarm peer address and already migrated keys during the migration. Note that this does not help nodes which already ran the migration.
* both `swarm.Address` and `common.Address` are treated as string in their state store representation, so just loading and storing preserves the correct value.
* addresses which are not length 20 strings are assumed to be already migrated
* in case of a conflict, the newer value takes precedence
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2537)

fix: fix swap migraton state store corruption

---

pkg/localstore/gc.go
pkg/localstore/migration.go
pkg/localstore/migration_dead_push.go
pkg/localstore/mode_set.go
pkg/localstore/schema.go

gc not removing the pushindex items, resulting in a corrupt index when subscribe push cannot find the chunks that pop out of the index. a migration is added to remove the stale entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2534)

fix(localstore): stale push index items

---

pkg/p2p/libp2p/internal/handshake/handshake.go
pkg/p2p/libp2p/internal/handshake/handshake_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/p2p.go

Oversaturated bins reject new incoming peers, so in the life time of a node, after the warmup period, almost all of connection attempts are rejected. 
The PR moves the Pick check before the overlay verification step. As a result, the number of eth backend calls are drastically reduced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2541)

opt: handshake handle checks with kademlia pick before overlay verification

---

openapi/SwarmCommon.yaml

adding missing connectedPeers and disconnectedPeers definitions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2523)

docs(openapi): add array of swarm addresses to topology bins

---

pkg/node/node.go

service variable was shadowed, causing it not to register in the prometheus metrics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2561)

fix: puller metrics registration

---

.github/workflows/go.yml
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2559)

ci: use codecov

---

pkg/puller/metrics.go
pkg/puller/puller.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2566)

fix: never store max uint topmost

---

pkg/pusher/pusher.go

fixes #2568 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2569)

fix(pusher): non-fatal tag error

---

pkg/puller/puller.go
pkg/pullsync/metrics.go
pkg/pullsync/pullsync.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2562)

fix: pullsync context cancellation

---

packaging/bee-get-addr

At some moment `bee init` started creating files inside `statestore` folder, this fix makes sure that those files have correct ownership
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2573)

fix: chown all bee files to bee user

---

pkg/pusher/pusher.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2637)

fix: continue on invalid stamp

---

pkg/node/chain.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2618)

feat: show eth backend client on startup

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/bytes.go
pkg/api/bytes_test.go
pkg/api/bzz.go
pkg/api/bzz_test.go
pkg/api/chunk.go
pkg/api/chunk_stream.go
pkg/api/chunk_stream_test.go
pkg/api/chunk_test.go
pkg/api/cors_test.go
pkg/api/dirs.go
pkg/api/dirs_test.go
pkg/api/feed.go
pkg/api/feed_test.go
pkg/api/gatewaymode_test.go
pkg/api/pin_test.go
pkg/api/postage_test.go
pkg/api/pss_test.go
pkg/api/soc_test.go
pkg/api/stewardship_test.go
pkg/api/tag_test.go
pkg/pusher/pusher.go

integrating the pushing stamper putter into the api
todo:
- how to deal with soc already exists error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2633)

feat: api push

---

pkg/puller/puller.go

Removes outdated cursors on peer disconnect.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2630)

fix(puller): delete cursors on disconnect

---

.github/workflows/release.yaml
.github/workflows/release_triggers.yaml

This PR is part of an automatization initiative to stream-line updating Bee versions across our JS land. This action triggers automatically build of Bee Factory images that will be then propagated to our JS repos with PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2654)

ci: trigger bee-factory builds on release

---

pkg/pushsync/pushsync.go

Increase number of peers tried for a chunk in push sync from 3 to 8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2629)

Feat: Increase number of originator retries for chunk

---

pkg/accounting/accounting.go
pkg/accounting/metrics.go
pkg/settlement/pseudosettle/pseudosettle.go

The aim of this PR is to make time based settlements more safe, by verifying timestamps from both sides to conclude whether 1 second passed since the last refreshment happened.
As an implication of this, the refreshments can be deintensified to once every two seconds in case there is an NTP difference observed on the two sides.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2651)

fix: checks at time based refreshment

---

pkg/retrieval/retrieval.go
pkg/retrieval/skip_peers.go

The aim of this PR is to make originated retrieval attempts more persistent in trying to find a peer with free accounting balance by increasing the number of times reserving (PrepareCredit) is attempted. 
This change does not effect the maximum number of actual requests made to retrieve a chunk. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2650)

feat: retrieval attempt persistently tried on originator

---

pkg/pushsync/metrics.go
pkg/pushsync/pushsync.go

removes attempted and bin labels from the pushsync metric as we haven't gotten value from it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2674)

fix: remove unnecessary labels from pushsync metric

---

openapi/Swarm.yaml

Major bump for the OpenAPI Bee API thanks to Stamps API removal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2679)

docs(openapi): major bump for bee api

---

pkg/transaction/backend.go

It was observed that in case of an error the retry loop is very tight. This adds a polling delay to every iteration.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2667)

fix: retry transaction receipt with delay

---

pkg/netstore/netstore.go
pkg/netstore/netstore_test.go
pkg/node/node.go

This PR aims to optimize the `netstore` Get operation by doing the store Put operation in the background. This allows the chunk to be returned early for processing and unblock the client to request more chunks.
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2665)

feat: async writes to store for netstore retrieval

---

.github/patches/listener.patch
.github/workflows/beekeeper.yml
pkg/node/node.go
pkg/postage/listener/export_test.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go

always process at least 5 blocks at once to drastically reduce our number of backend requests. (note this means it might take up to 4.5 block times longer until a postage batch is accepted). this change is necessary as otherwise the listener of one node alone already exhausts the free budget from some api providers.
Syning before:
```
200 201 202 203 204 205 206 207 208 209 210 (block height)
196 197 198 199 200 201 202 203 204 205 206 (last synced block)
```
Syning after:
```
200 201 202 203 204 205 206 207 208 209 210 (block height)
195 195 195 195 200 200 200 200 200 205 205 (last synced block)
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2641)

feat: sync postage stamps in batches

---

pkg/node/node.go
pkg/p2p/libp2p/internal/handshake/handshake.go
pkg/p2p/libp2p/internal/handshake/handshake_test.go
pkg/p2p/libp2p/libp2p_test.go
pkg/transaction/sender_matcher.go
pkg/transaction/sender_matcher_test.go

Currently we greylist our own address if the node is started before the transaction has been included and one block on top (which can happen if you use a transaction from outside bee). Which means we cannot attempt to start the node for another 5 minutes. This adds an exception for this check.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2688)

fix: ignore greylist for self verification

---

pkg/pushsync/pushsync.go

Current implementation allows forwarding replication logic to run when the storer node fails to validate or store the chunk. PR fixes that.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2694)

fix: storer node forwarder replication edge case

---

pkg/retrieval/metrics.go
pkg/retrieval/retrieval.go

Improves the metrics we have in the retrieval protocol (removes existing unused metrics and introduces a new histogram for all retrieve request timings).
The following measurements have been observed on production (local node setup):
```
bee_retrieval_retrieve_chunk_time_bucket{le="0.01"} 0
bee_retrieval_retrieve_chunk_time_bucket{le="0.1"} 215
bee_retrieval_retrieve_chunk_time_bucket{le="0.25"} 3538
bee_retrieval_retrieve_chunk_time_bucket{le="0.5"} 4309
bee_retrieval_retrieve_chunk_time_bucket{le="1"} 6053
bee_retrieval_retrieve_chunk_time_bucket{le="2.5"} 6594
bee_retrieval_retrieve_chunk_time_bucket{le="5"} 6634
bee_retrieval_retrieve_chunk_time_bucket{le="10"} 6662
bee_retrieval_retrieve_chunk_time_bucket{le="+Inf"} 6662
bee_retrieval_retrieve_chunk_time_sum 3114.7905996460104 …
```

chore(retrieval): improve metrics

---

pkg/keystore/file/key.go

turns out the reason we cannot load ethereum key files is because we compute the mac differently. with this change bee can load its own key format as well as the one from geth and clef.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2710)

feat: support loading ethereum key files

---

pkg/keystore/file/key.go

this makes our key format compatible so swarm keys can be loaded into geth or clef (the base PR enables the other direction). this only affects newly created keys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2711)

feat: create eth V3 compatible keys

---

pkg/topology/kademlia/kademlia.go

This PR intends to change the selection of balanced connections by relaxing the criteria from selecting a closest peer to selecting a close-enough peer for a pseudo-address
https://github.com/ethersphere/bee/issues/2521
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2677)

feat: relax balancing

---

.github/patches/postageservice.patch

block threshold in ci is too too low leading to unnecessary push sync fails due to unsynced batch stores. it might take up to 5 blocks for a batch to become valid (4 tail size, 2 batch factor), so I used 6 as threshold here. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2714)

chore(ci): adjust block threshold for ci

---

openapi/Swarm.yaml

The promise was that `tag` is created and returned for every uploading action, which is not true for `/chunks` upload as it only returns it if the user himself put tag already into the request. This documents this behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2717)

docs: update chunk endpoint info

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
openapi/SwarmCommon.yaml
pkg/debugapi/chequebook.go
pkg/debugapi/debugapi.go
pkg/debugapi/debugapi_test.go
pkg/debugapi/node.go
pkg/debugapi/router.go
pkg/node/devnode.go
pkg/node/node.go
pkg/settlement/swap/swap.go

* add a now flag `chequebook-enable` which is true by default.
* if `chequebook-enable` is false but `swap-enable` is true the node will still be able to receive and cash cheques but does not deploy a (or use a preexisting) chequebook and therefore does not send cheques. only time-based settlement will be used.
* transaction hash needs to be supplied manually if started with this and there has been no deployment in the past. as sending a tx manually from the overlay key can be tricky this is best done using the new alternative tx data type (#2409).
* several api endpoints are disabled in this mode.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2236)

feat: allow swap without chequebook

---

pkg/retrieval/retrieval.go

This change improves a rare edge case where the channel for results would be filled by asynchronous retrieves, also removing the buffer for the channel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2729)

fix: unblocking write to channel in retrieval

---

pkg/node/chain.go
pkg/settlement/swap/swap.go
pkg/settlement/swap/swap_test.go

the last PR did not handle cashouts correctly if running without a chequebook. this prevents a go panic and uses the nodes overlay eth address as a destination instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2732)

fix: cashout to overlay address if no chequebook

---

openapi/SwarmCommon.yaml

This change intends to fix an error thrown by openapi generator, e.g. run in /openapi:
npx @openapitools/openapi-generator-cli generate -i SwarmDebug.yaml -g python-flask -o ./debugAPI
It also intends to simplify / correct the description for /stamps and /stamps/id GET endpoints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2736)

fix: fix openapi generator for debug api

---

.goreleaser.yml

For now only enabling darwin arm64 build, later homebrew support will be enabled as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2740)

feat: enable darwin arm64 binary build

---

pkg/statestore/leveldb/leveldb.go

Fixes an abysmal bug where the underlying unsafe leveldb iterator slice address was leaked to callers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2747)

fix(statestore): dont share iterator slice

---

pkg/localstore/localstore.go

adds the missing scalar field to the debug indices method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2750)

chore(localstore): add reserve size to debug

---

pkg/node/statestore.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2751)
Now that all nodes in the network are using > 1.0.0, we can remove this bit of old code.

fix: remove old overlay delete

---

pkg/localstore/localstore.go
pkg/localstore/migration.go
pkg/localstore/migration_sharky.go
pkg/localstore/schema.go
pkg/shed/db.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2704)

Sharky db migration

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml

The OpenAPI spec for the authentication modes was split between Swarm and SwarmCommon which did not work. Not sure if it is possible to have these split between two files or not, but it works in this way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2755)

docs: functional auth openapi spec

---

pkg/localstore/subscription_pull.go

Decreases the amount of logging we do on pull subs in localstore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2756)

chore(localstore): decrease debug logging for pull subs

---

pkg/node/node.go
pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/libp2p/libp2p_test.go

Starting the reacher worker in the `Ready` function to avoid a race condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2757)

fix: notifier setter race condition

---

pkg/sharky/metrics.go
pkg/sharky/store.go

Introduces basic metrics for sharky as read, write counters and their error counters, shard size counter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2759)

feat: add basic metrics for sharky

---

pkg/localstore/gc.go
pkg/localstore/gc_test.go

Increase the limit of the number of chunks in a single transaction on garbage collection from 2k to 10k.
Changes the approach in regards to chunk collection - previously the strategy was to start with a minimal amount of chunks and work our way up, in the new approach we try to collect as many as possible, only stopping when the target is achieved.
Currently garbage collection tends to lag behind the influx of chunks, leading to poor eviction performance.
This change takes a different approach - specifically - trying to over-collect chunks pending for eviction, minimizing the lag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2779)

fix: gc over collecting

---

pkg/api/router.go

It was reported by a user (https://github.com/ethersphere/bee-js/issues/525) that getting the expected download file size for tracking downloading progress is not possible. I have noticed that you use `Decompressed-Content-Length` to communicate this size, but (again 😅  as so many times) this is not exposed with CORS settings. This fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2786)

fix(cors): expose Decompressed-Content-Length header

---

install.sh

Noticed you are missing `darwin-arm64` from supported list.
Btw. a funny thing is if you run an M1 non-native terminal application then the `uname -m` incorrectly reports `x86_64` as it runs in the emulation software (Rossetta). I am using [Hyper](https://hyper.is/) which for example is not yet compatible (I am running old version).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2789)

build: support m1 macs install

---

pkg/p2p/libp2p/libp2p.go

This PR adds explicit handling to a stream reset on the header exchange with the peer. We've found that this is caused by an inconsistent state of the peerstore, in which apparently disconnections do no propagate correctly to our abstraction, so we seem to be connected to a peer, while the other peer does not seem to accept the same assumption. This results in an immediate stream reset from the other side, resolving the long mystery under which we were operating.
Note that this is a stopgap solution and creates an unnecessary dependency in the headers exchange in order to determine connectivity status. Not exactly textbook solution, but allows for a clear disambiguation of the case since this error should definitely _never ever_ happen in this code block, and will give us a bit of leeway …

fix(p2p): handle header stream reset explicitly

---

pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/internal/handshake/handshake.go
pkg/p2p/libp2p/internal/handshake/handshake_test.go
pkg/p2p/libp2p/libp2p.go

As discussed while looking into various errors we've been running into on the libp2p abstraction level, it has been concluded that removing the duplicate handshake constraint is not beneficial and should be removed. It does not guard against anything, and duplicate handshakes are allowed even _with_ this code section (since we can dial to a node and a node can dial back and there's no keeping track of the bidirectional connections). Furthermore, libp2p allows for multiple underlying connections and will use the best one when sending a message according to its internal heuristics of connection selection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2794)

refactor: allow duplicate handshakes

---

pkg/sharky/shard.go
pkg/sharky/shard_slots_test.go
pkg/sharky/slots.go
pkg/sharky/store.go

This PR is an attempt to use wait group in more predictable way in order to fix the issue with closing the sharky.
Testing these changes on integration would be needed as unit tests are injecting wait group which removes a bit of reliability from them.  
Make shutdown process reliable.
https://github.com/ethersphere/bee/issues/2840
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2841)

fix: sharky waitgroup handling

---

pkg/transaction/backend.go

we get inconsistent behavior when checking for synced status, this change will discriminate ethereum errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2844)

fix: catch eth error

---

pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/metrics.go
pkg/topology/kademlia/unreachable_unix.go
pkg/topology/kademlia/unreachable_windows.go

Allows keeping the number of known peers in the kademlia topology unchanged during the network outage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2853)

feat: keep known peers list on network outage

---

pkg/topology/kademlia/kademlia.go

I see a lot of log records looking like this:
```sh
could not connect to peer \"036cbb366d8fd4d3a8fdc6fb81855e94e1aacdcdec9340c5716715c91a4c0fb2\":
```
this PR removes the quotes as I don't think they improve readability in any way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2878)

fix: remove quotes in kademlia logs

---

pkg/node/bootstrap.go
pkg/node/node.go

Currently, the overlay check to see if the statestore exists for bootstrapping the node does not cover the case where only the batchstore is missing after a migration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2895)

feat: bootstraping node after batchstore migration

---

pkg/postage/batchstore/reserve.go
pkg/postage/batchstore/store.go

recent changes to the batchstore have increased the amount of logging we do on every batch insertion. this PR reduces the number of loglines we do per operation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2897)

chore: reduce batchstore logging

---

pkg/api/api.go

If `decompressed-content-length` fails try the normal one before stopping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2907)

fix: add fallback content length check in middleware

---

pkg/node/node.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2910)

fix: node start up to continue on bootstrapper error

---

pkg/sharky/shard.go
pkg/sharky/shard_slots_test.go
pkg/sharky/store.go

Fixes a bug where a cancelled context would result in a deadlock on the sharky read which tries to write the error back to the `sh.errc` channel
Caught in a goroutine dump from @tmm360 on #2909.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2932)

fix: sharky read deadlock on context cancelled

---

pkg/sharky/slots.go

Sharky leaks data because of the next slot allocation optimization.
Since grabbing the next slot from 0 is cheap to make, I am temporarily disabling this till we have time to optimize this again.
Addresses the most recent problems raised in #1258, at least for now (since this problem haunts us every now and then, I will refrain from closing the issue).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2953)

fix(sharky): remove next slot allocation optimization

---

cmd/bee/cmd/start_dev.go

To improve the developer's experience the `dev` mode has a default admin password when ran in `restricted` mode.
To be used like so:
```http
POST localhost:1633/auth
Content-Type: application/json
Authorization: Basic OmhlbGxv
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2947)

feat: set default admin password in restricted dev

---

pkg/api/dirs.go
pkg/api/dirs_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2951)

fix: allow nested paths for multipart upload

---

pkg/bmt/proof.go
pkg/bmt/proof_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2952)

feat(bmt): segment inclusion Merkle proofs

---

pkg/node/node.go

Interrupting boot during postage sync causes an NPE
Closes #2962 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2968)

fix: NPE on shutdown

---

pkg/puller/puller.go

Since the context governs the syncing process lifecycle, it can result in the `CancelRuid` process being called with an already-expired context. This PR changes it to create a new context object so that the process can continue uninterrupted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2979)

fix(pullsync): create a new context on cancel ruid

---

pkg/p2p/libp2p/libp2p.go
pkg/p2p/mock/mock.go
pkg/p2p/p2p.go
pkg/topology/kademlia/kademlia.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2976)

fix(kademlia): check if peer is blocklisted before connection

---

pkg/logging/logging.go
pkg/node/node.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2981)

fix: reduce logging during bootstrapping

---

.github/workflows/beekeeper.yml

It's no longer needed to use PAT (personal access token) to push to github's container registry. Using GITHUB_TOKEN it's much more secure because it allows access only for current pipeline run.
GIthub has changed the way how to authenticate to their container registry that we use as image cache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2987)

fix: replace PAT with GITHUB_TOKEN for ghcr.io login

---

openapi/Swarm.yaml

This PR is follow-up to #3003. After a bit more digging around the merged APIs I have discovered that some of the merged endpoints are not actually protected by authentication (so-called "technical debug") so this PR reflects that. Moreover `/health` endpoint documentation is missing so I have added that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3008)

docs: some endpoints are without authentication

---

pkg/traversal/traversal.go
pkg/traversal/traversal_test.go

Fixes #2999 
Ideally, joiner and other file-related operations don't need to know about SOC. But the problem is we might call Traversal from the API layer with all kinds of chunks. We expect traversal to traverse any and all kinds. I feel this safeguard in Joiner would be the easiest way to understand and also prevent this type of use of Joiner in future.
The problem is when the problem occurs, we will see `storage: not found` errors which are false positives and we might end up wasting effort looking at all sorts of things, like I did here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3006)

fix: check for SOC while doing traversal operations

---

pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

Use legacy tx instead of access control tx which does not work with the configured signer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3018)

fix(transaction): use legacy tx for cancel operations

---

pkg/accounting/accounting.go
pkg/accounting/accounting_test.go
pkg/accounting/mock/accounting.go
pkg/pushsync/pushsync.go
pkg/retrieval/retrieval.go

In order to minimize lock contention for the accounting peer we will reject the goroutines that have an expired context as well as the goroutines that do not receive the lock within the context deadline.
This PR introduces a context aware mutex for that purpose.
Closes #2959
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2961)

fix: prepare credit context argument

---

pkg/api/chunk_stream.go
pkg/api/pss.go

Currently, the `/chunks/stream` endpoint uses the HTTP request context which expires once the API returns. However, the websocket connection is expected to be alive for a longer time. This change allows clients to maintain long-running connections to upload a stream of chunks. The websocket connection is tracked using the `wsWg` in the api handler, so by passing a background context we allow the server read loop to be alive till the client closes the connection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3047)

fix(api): streaming chunk upload for long running connections

---

cmd/bee/cmd/cmd.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3059)

chore: reduce warmup time

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
packaging/bee.yaml
packaging/homebrew-amd64/bee.yaml
packaging/homebrew-arm64/bee.yaml
packaging/scoop/bee.yaml
pkg/node/chain.go
pkg/node/node.go

Decommissions the `chain-enable` flag in favor of checking if `swap-endpoint` is provided.
Closes: #3062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3066)

fix: use swap endpoint as chainless mode flag

---

pkg/api/api.go
pkg/api/router.go
pkg/node/node.go

After merging the APIs we open the listener before the postage syncing begins, this PR makes the listener to start only once the syncing is done.
Closes: #3060 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3065)

fix: open listener after syncing is done

---

pkg/pushsync/pushsync.go
pkg/retrieval/retrieval.go
pkg/skippeers/skip_peers.go
pkg/skippeers/skip_peers_test.go

[Push Sync closestPeer overdraft case](https://hackmd.io/oZTAHIZjRdm6PUcimWY20Q)
Closes: #3048 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3052)

fix: retry when overdraft peer might be closest

---

cmd/bee/cmd/start_dev.go

The default admin password for `dev` mode was base64 encoded, which is unnecessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3076)

fix: no encoding for default dev admin password

---

pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

#3023; Closes #3020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3077)

fix: add sanity checks to ethereum gas prices

---

pkg/node/chain.go
pkg/postage/noop.go

There's a case when a `noOp` method is being called and that crashes the process.
Closes: #3082
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3093)

fix: error instead of panic

---

pkg/sharky/slots.go

This reverts commit 6ceadd35db7f6128c50cec454d3e8fa9c8afb4d9 from PR #2953
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3105)

perf(sharky): reinstate naive next slot allocation (#2953)

---

cmd/bee/cmd/start.go
cmd/bee/cmd/start_windows.go
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml
pkg/api/bytes.go
pkg/api/export_test.go
pkg/api/logger.go
pkg/api/logger_test.go
pkg/api/router.go
pkg/log/example_test.go
pkg/log/formatter.go
pkg/log/formatter_test.go
pkg/log/log.go
pkg/log/logger.go
pkg/log/logger_test.go
pkg/log/noop_logger.go
pkg/log/registry.go
pkg/log/registry_test.go
pkg/logging/httpaccess/http_access.go
pkg/logging/logging.go
pkg/logging/metrics.go
pkg/node/bootstrap.go
pkg/node/devnode.go
pkg/node/node.go
pkg/pusher/pusher.go
pkg/settlement/swap/swapprotocol/swapprotocol_test.go
pkg/tracing/tracing.go
pkg/tracing/tracing_test.go
pkg/util/ioutil/ioutil.go

This new logger borrows some of the ideas described here: https://github.com/go-logr/logr#background
with the exception of excluding warning and debug log levels, for compatibility reasons. In addition, it adds V levels to the debug log level, so that messages with larger V levels can be logged if needed. The status of loggers can be queried via the HTTP endpoint, and verbosity can also be set for single or multiple loggers (based on regex matching) via the HTTP endpoint at runtime.
During debugging sessions, it is often necessary to reduce or increase/decrease the range of log messages for individual packages (or groups) in order to efficiently focus on the relevant log messages. It is also very important to have this ability to turn on/off/change the verbosity of the logs at runtime …

refactor: introduce structural logging

---

.github/pull_request_template.md

As per the discussion of today's backlog refinement meeting I add a checklist item to make sure that the description is filled out in the template and issues are linked.
It is possible to reference issues just by using a hash and the issue number. Github also recognises certain keywords and can automate the workflow if you use them. Here is the documentation about it:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3137)

chore: add description checklist item to PR template

---

cmd/bee/cmd/start.go
pkg/api/api.go
pkg/api/api_test.go
pkg/api/postage.go
pkg/api/postage_test.go
pkg/api/router.go
pkg/node/node.go
pkg/postage/batchservice/batchservice.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/batchstore/mock/store.go
pkg/postage/interface.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go
pkg/util/signaler.go

Foreground postage batch syncing results in a bad user experience because of the time it takes to complete.
This PR moves it to a background process - and while it's ongoing - the relevant endpoints will return `503`
Closes: #3094
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3127)

feat(postage): background postage sync for light node

---

cmd/bee/cmd/start.go

if the user has set `mainnet` to false and not provided a network ID we should default to ID `10`
this is a regression introduced after the default network ID was set to `1` in order to remediate an inconsistency in `printconfig` command: #3141 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3154)

fix: programmatically set test network ID

---

pkg/api/bzz_test.go
pkg/api/dirs.go

fix for POST /bzz - Very long directory name yields store dir err: read tar stream: archive/tar: invalid tar header
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3133)

fix: long directory name error

---

pkg/node/chain.go

Removes forgotten fmt string part in the log message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3169)

fix: remove forgotten fmt string in log message

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
pkg/api/api.go
pkg/api/api_test.go
pkg/api/bzz.go
pkg/api/bzz_test.go
pkg/api/cors_test.go
pkg/api/router.go
pkg/api/stewardship.go
pkg/api/stewardship_test.go
pkg/resolver/cidv1/cidv1.go
pkg/resolver/cidv1/cidv1_test.go
pkg/resolver/client/ens/ens.go
pkg/resolver/client/ens/ens_test.go
pkg/resolver/resolver.go

if the reference is incorrect (not 64 or 128 hex characters), return 400
if the reference is correct but not found, then return 404
Remove bzz patch endpoint as it is deprecated.
Closes #1803 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3170)

chore: validation checks bzz and stewardship

---

pkg/localstore/localstore.go
pkg/node/node.go
pkg/postage/batchstore/export_test.go
pkg/postage/batchstore/mock/store.go
pkg/postage/batchstore/reserve.go
pkg/postage/batchstore/reserve_test.go
pkg/postage/batchstore/store.go
pkg/postage/batchstore/store_test.go
pkg/postage/interface.go
pkg/postage/noop.go
pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pullsync/pullsync.go
pkg/rate/export_test.go
pkg/rate/rate.go
pkg/rate/rate_test.go
pkg/storage/mock/storer.go
pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go
pkg/topology/depthmonitor/export_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go
pkg/topology/kademlia/metrics.go
pkg/topology/kademlia/mock/kademlia.go
pkg/topology/mock/mock.go
pkg/topology/topology.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3061)

feat(depthmonitor): depthmonitor service

---

pkg/node/node.go

Fixes formatting of the nonce in the log messages:
before: `..."msg"="finding new overlay corresponding to previous overlay with nonce" "nonce"=[0,9,61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]`
after: `..."msg"="finding new overlay corresponding to previous overlay with nonce" "nonce"="0052bc0f00000000000000000000000000000000000000000000000000000000"`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3235)

fix(node): nonce log formatting

---

pkg/p2p/libp2p/internal/blocklist/blocklist.go
pkg/p2p/libp2p/internal/blocklist/blocklist_test.go
pkg/p2p/libp2p/internal/blocklist/export_test.go
pkg/p2p/libp2p/internal/breaker/breaker.go
pkg/p2p/libp2p/internal/breaker/breaker_test.go
pkg/p2p/libp2p/internal/breaker/export_test.go

`blocklist` and `breaker` packages had a hacky way for mocking current time in tests using global variable. 
This PR provides cleaner solution for mocking current time in tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3125)

chore: remove global var from blocklist,breaker packages

---

pkg/api/api.go
pkg/api/bytes.go
pkg/api/bzz.go
pkg/api/metrics.go
pkg/feeds/sequence/sequence.go
pkg/file/buffer_test.go
pkg/tags/tags.go

Occurrences of `fmt.Sprintf("%d",...)` were replaced with `strconv.FormatInt(..)`; later approach is already suggested in [go style guide](https://github.com/ethersphere/bee/blob/master/CODINGSTYLE.md#prefer-strconv-over-fmt).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3226)

chore: format int numbers using strconv

---

pkg/api/api.go
pkg/api/api_test.go
pkg/node/devnode.go
pkg/node/node.go

Makes chain-backend available before the technical debug mount is called.
Fixes #3256
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3261)

fix: make chain-backend available before technical debug is mounted

---

cmd/bee/cmd/start.go
pkg/node/node.go

At the moment the process of finding the new overlay is not interruptible, the user can only stop it by killing the process.
This PR makes the mining loop to be `os.Signal` aware and cleanly exit when the signal is received.
Closes #3251
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3253)

fix: interrupt mining

---

pkg/api/router.go

Fixes the case when the `swap-enable` flag/configuration value is set to false, then the `/wallet` endpoint should not be available because it uses the swap-backend.
Fixes #3268
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3271)

fix: make wallet endpoint avaiable only when swap-enabled is set to true

---

pkg/node/node.go
pkg/postage/interface.go
pkg/postage/mock/service.go
pkg/postage/service.go

set stamps expiration field after batch sync completes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3269)

fix: set stamps expiration field after batch sync completes

---

.github/pull_request_template.md

Adds a checkbox to the PR template to remind of the necessary changes to the Open API specification, if applicable.
PR authors often forget to update (or change the version number of) the Open API specification when changes are made to the endpoints, adding a checkbox should remind them to make those changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3244)

docs: add Open API spec question checkbox to the PR template

---

pkg/postage/mock/service.go
pkg/postage/service.go
pkg/postage/stampissuer.go

If the batchstore is unstable due to whatever reason, on reboot, if a batch exists, then the stamp should have field false regardless of previous value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3289)

fix: set stamp expiration to false if batch exists

---

.golangci.yml
cmd/bee/cmd/deploy.go
pkg/file/pipeline/feeder/feeder.go
pkg/localstore/mode_set.go
pkg/log/formatter.go
pkg/log/formatter_test.go

- enable `wastedassign` lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3305)

feat(lint): enable wastedassign

---

.golangci.yml
pkg/pricer/headerutils/utilities_test.go

- enable `dogsled` lint rule
- ignored all issues in api test files; because there are a lot of occurrences with construct `testServer, _, _, _ := newTestServer(..)`, which can be addressed later
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3308)

feat(lint): enable dogsled

---

pkg/localstore/reserve.go
pkg/localstore/reserve_test.go
pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go

When the depthmonitor changes the storage radius, this does not automatically alter the radius that the localstore keeps in it's reserve, so the `ReserveSize` does not return an accurate number. With this PR, we iterate on the pull index to manually count all chunks whose PO is greater than or equal to the storage radius.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3322)

fix: reserve size to return chunks with po greater than and equal to storage radius

---

pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/export_test.go
pkg/p2p/libp2p/headers.go
pkg/p2p/libp2p/libp2p.go

Make the headers read/write timeout an option that can be passed to prevent data races in tests.
Fixes the `TestWithDisconnectStreams` test flakiness.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3327)

refactor(libp2p): make the headers read/write timeout an option

---

pkg/node/node.go
pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go
pkg/topology/depthmonitor/export_test.go

Passes the wakeup interval of the manage method as a service parameter to prevent data races in tests.
Fixes #3286
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3328)

refactor(depthmonitor): pass the wakeup interval for manage method

---

pkg/api/bzz.go
pkg/api/bzz_test.go

Please refer to tagged issue for details. This pr sends correct response if there is a slash in website index document
This pr fixes #2661 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3229)

fix: response for slash in website index document

---

pkg/topology/depthmonitor/depthmonitor.go

Fixes the depth monitor default wakeup interval changed in #3328
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3348)

fix: depth monitor default wakeup interval

---

pkg/api/pss_test.go

Disabling parallel tests in `TestPssSend` due to [data race issue](https://github.com/ethersphere/bee/actions/runs/3133612924/jobs/5087178378).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3349)

fix: disabled parallel tests in TestPssSend

---

.github/pull_request_template.md

Removes the checkbox from the PR template which reminds of the necessary changes to the Open API specification, if applicable.
#3354
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3353)

docs: remove Open API spec question checkbox from the PR template

---

pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go
pkg/topology/depthmonitor/export_test.go

Refactored `depthmonitor` so that custom `minimumRadius` is set using setter, instead of hacky approach using global vars.

refactor(depthmonitor): avoid configuration using global vars

---

pkg/api/api.go
pkg/api/api_test.go
pkg/auth/auth.go
pkg/auth/auth_test.go
pkg/auth/mock/auth.go
pkg/node/devnode.go
pkg/node/node.go

Updated `auth.Authenticator` type use time.Duration instead of int in `GenerateKey` and `RefreshKey` methods. This enabled tests to specify much shorter `expiryDuration` thus reducing total execution time for tests.
Additionally, added `Authenticator` interface in order to be reused on other places.

refactor(auth): interface with duration

---

pkg/topology/depthmonitor/depthmonitor.go

Removing minimum storage radius 4 for depthmonitor
The aim of this PR is to retire an artificial safeguard that kept the storage radius from descending below 4 to avoid a fully connected topology in case of the storage radius decrease erronously never stopped. With the given period of testing this doesn't seem necessary anymore, as well as inhibiting the full scalability of the network

feat: decrease lower bound

---

pkg/statestore/leveldb/migration.go

- [N/A] My change requires a documentation update, and I have done it.
- [N/A] I have added tests to cover my changes.
#3331 fixed by preserving an additional prefix on db nuke
N/A
db nuking an already migrated and nonce-mined node will no longer re-mine the nonce.
#3331

fix: preserve new overlay on db nuke

---

.golangci.yml
pkg/manifest/mantaray/marshal_test.go
pkg/manifest/mantaray/node_test.go
pkg/manifest/mantaray/persist_test.go
pkg/manifest/mantaray/walker_test.go
pkg/manifest/simple/manifest_test.go
pkg/pullsync/pullstorage/pullstorage_test.go
pkg/pullsync/pullsync_test.go
pkg/resolver/cidv1/cidv1_test.go
pkg/resolver/client/ens/ens_test.go
pkg/resolver/multiresolver/config_test.go
pkg/resolver/multiresolver/multiresolver_test.go

This PR is the first part of effort to improve static code analysis (issue https://github.com/ethersphere/bee/issues/3255)
- fixed paralleltest lint errors in `manifest`, `resolver` and `pullsync` packages and enabled checks for it

chore(lint): make test execute in parallel (part 8)

---

.golangci.yml
pkg/node/node.go
pkg/pusher/export_test.go
pkg/pusher/inflight.go
pkg/pusher/pusher.go
pkg/pusher/pusher_test.go

This PR is the first part of effort to improve static code analysis (issue https://github.com/ethersphere/bee/issues/3255)
- fixed `paralleltest` lint errors in `pusher` package and enabled check for it

chore(lint): make test execute in parallel (part 7) 

---

pkg/accounting/accounting.go

Fix for a malformed log line: 
```
"error"="send headers: read message: stream reset" "<non-string-key: \"117000000\">"="to peer" "<non-string-key: \"f365667f28ea14a>"="<no-value>"
```

fix: missing key in log line

---

pkg/file/buffer_test.go

Test `TestCopyBuffer` and `TestChunkPipe` had timer with 1s timeouts which were making it flaky in some runs. 
This PR removes these timers since there is no real need for them.
Closes #3409

fix: flaky tests TestCopyBuffer and TestChunkPipe

---

pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

Kademlia randomly picks 4 peers from each bin to broadcast when a new connection is made. If the connected peer is a neighbor, however, the broadcast peer size should not be capped.

feat: broadcast size should not be capped for newly connected neighbors

---

.github/workflows/release.yaml
Dockerfile
Dockerfile.goreleaser
Dockerfile.scratch

Latest RC release failed in the end because of default timeout that goreleaser uses (30min). Good is that artifacts were uploaded but workflow was cut by the timeout and release is marked as failed.
Base docker images are upgraded as a part of a regular update of all infra components.

fix: increase timeout for release action and bump base docker images

---

.github/workflows/beekeeper.yml

Trigger bee-factory build only in the [events](https://github.com/ethersphere/bee/blob/master/.github/workflows/beekeeper.yml#L357) when latest bee image is being pushed to the registry

ci: trigger bee-factory only in the event latest image is being pushed

---

pkg/storageincentives/agent.go
pkg/storageincentives/metrics.go

Adds metrics for errors for Grafana dashboard
An extension of Agent feature in storage incentives. 
NA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3449)

feat(agent):metrics for errors in agent

---

pkg/localstore/gc_test.go
pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go
pkg/localstore/mode_set.go
pkg/localstore/pin_test.go
pkg/localstore/reserve_test.go

Currently, the localstore indexes are not reliable to be used for logical components like the reserve, cache etc. This is a known issue and there is a storage rewrite in progress to handle that.
For the current release, in order to test storage incentives, we will change the behaviour to delete the pullIndex when a chunk is put into the gcIndex. This is because, the pullIndex is now used to create the reserve sample. The cache chunks should not be present here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3447)

fix(localstore): remove pullIndex on caching

---

pkg/puller/puller.go
pkg/pullsync/mock/pullsync.go
pkg/pullsync/pb/pullsync.pb.go
pkg/pullsync/pb/pullsync.proto
pkg/pullsync/pullsync.go
pkg/pullsync/pullsync_test.go

PR removes the cancellation ruid and all related code after the latest changes to the puller and pullsync protocols.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3456)

chore(pullsync): cancel ruid cleanup

---

pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/export_test.go
pkg/p2p/libp2p/libp2p.go
pkg/p2p/libp2p/metrics.go
pkg/p2p/libp2p/stream.go
pkg/postage/batchservice/batchservice.go

We need metrics to see how many streams we are closing/resetting and how many closed streams libp2p library reports.
It's likely the libp2p library does not releases the resources after a stream is closed.
Closes #3439
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3474)

fix: stream related metrics

---

pkg/puller/puller.go
pkg/puller/puller_test.go

Because of the missing PO assignment, disconnected peers were not getting cleaned up in puller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3501)

fix(puller): missing po assignment in new sync peer

---

pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

As part of EIP 1559, cancel and resend trx should use new suggested price.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3506)

fix: cancel and resend to use new gas price

---

pkg/node/node.go
pkg/puller/puller.go
pkg/pullsync/pullsync.go

Puller only sleeps when there is a connection related error from sync interval.
Sync from field is only incremented when previous sync attempt and received top value are good (nonzero)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3515)

fix(puller): increment from value on successful sync only and sleep only on connection error

---

openapi/Swarm.yaml
openapi/SwarmDebug.yaml

Staking endpoints are documented under the main API, while it is being mounted on the `mountBusinessDebug()` function, so this PR reflects this placement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3517)

docs: move staking endpoint to debug api

---

pkg/api/staking.go
pkg/api/staking_test.go

Fixes serialization of staked amount into a string instead of a number that loses precision.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3521)

fix: serialise amount into string

---

pkg/puller/puller.go
pkg/pullsync/pullsync.go
pkg/pullsync/pullsync_test.go

Pullsync will only return an error if the interval needs to be retried, (eg: connection or localstore related errors), for other errors, we simply log and continue the operation.
This way the puller can easily determine when to retry the same interval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3555)

fix: pullsync will only return an error if the interval needs to be retried

---

pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

Adding one for the gas tip is not enough to prioritize the transaction for cancellation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3559)

fix: larger tip on cancellation

---

pkg/storageincentives/redistribution/redistribution.go
pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3562)

fix: boost gas fee cap as well

---

pkg/postage/batchstore/reserve.go
pkg/postage/batchstore/reserve_test.go

Currently, when an eviction is necessary, localstore will evict batches one by one until the reserve size falls below a certain threshold.
The radius of the evicted batch is increased by one so that when another eviction process runs in the future, chunks of lower radius batches will be evicted first.
The problem with this is that pull syncing continues to sync at storage radius so the node may receive chunks belonging to bins lower than the radius of the batch.
This change will not skip evictions on any batch and will call eviction of the batch not with the radius of the batch but the storage radius. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3565)

fix: do not skip eviction of batches with higher radius

---

pkg/localstore/gc.go
pkg/localstore/gc_test.go
pkg/localstore/localstore.go
pkg/node/node.go

The localstore reserve size calculation is not correct and for storage incentives, we manually calculate the syncing index to calculate the reserve size.
In the private testnet we observed that the reserve eviction was causing some inconsistencies in the samples generated. During GC, we evict chunks from the reserve till we reach 90% capacity and move them to the cache. As we no longer consider cache chunks in the sample calculation, we have decided to relax the eviction till we are at 100% capacity. So, only evict if we have more chunks.
Also, as the storage radius is now dynamic, we will need to calculate the reserve size using the current radius during eviction. This might lead to node having to store some more data, but eventually, all the expiring batches should be cleaned up.
- - - …

fix: relax reserve eviction during GC

---

openapi/SwarmDebug.yaml
pkg/api/postage.go
pkg/api/staking.go
pkg/api/staking_test.go
pkg/node/devnode.go
pkg/postage/postagecontract/contract.go
pkg/storageincentives/staking/contract.go
pkg/storageincentives/staking/contract_test.go
pkg/storageincentives/staking/mock/contract.go

The PR adds transaction hash to the staking API.
#3359
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3573)

feat(staking): add tx hash

---

pkg/api/api.go
pkg/api/postage.go
pkg/api/pss.go
pkg/api/soc.go
pkg/postage/mock/service.go
pkg/postage/postagecontract/contract_test.go
pkg/postage/service.go
pkg/postage/service_test.go

We have seen MANY chunks whose stamp indexes are colliding with others chunks belonging to the same batch.
This is possible if stamp issuer data is not stored to disk properly on `Close()` such that on the next restart of the node, the same bucket and indexes are assigned to a different uploaded chunk. 
This change makes sure that after a stamp is used, the bucket data is stored immediately with a callback.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3577)

fix: save stamp issuer data after usage not service close

---

pkg/localstore/gc.go
pkg/localstore/gc_test.go
pkg/localstore/index_test.go
pkg/localstore/localstore.go
pkg/localstore/localstore_test.go
pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go
pkg/localstore/mode_set.go
pkg/localstore/pin_test.go
pkg/localstore/reserve.go
pkg/localstore/reserve_test.go
pkg/localstore/sampler_test.go
pkg/localstore/subscription_pull_test.go
pkg/node/node.go
pkg/pullsync/pullstorage/pullstorage_test.go
pkg/pullsync/pullsync.go

During the recent storage incentives changes, we found that the reserve size calculation in the localstore was off. A bunch of efforts has already been made to understand and fix this, but due to the dynamic nature of storage depth, it seems like it is not possible to have a static count of reserve size stored in the localstore, which can represent the current reserve size.
The reserve size is now synonymous with the pullIndex as this is the index we use to generate the sample. This index will now be used to represent the reserve chunks in the localstore. So if chunks are put into GC index, which represents the cache, we should remove them from pullIndex as they are no longer part of the reserve. This change will make the addition of pullIndex more strict and only allow syncing related …

fix(localstore): remove reserve calculation from localstore

---

pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go

Ignore Batch overwrite error for syncing context. This was changed as old behaviour was to silently return without returning error. However we should only allow this for syncing. If for upload user tries this, we should still catch this error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3589)

fix: ignore overwrite errors for syncing

---

pkg/localstore/gc.go
pkg/localstore/metrics.go
pkg/localstore/reserve.go

This is a minor change to use the gcSizeChange as the number for eviction count and not use the separate reserveSize calculation which was recently removed.
Also, added a new metric to show the eviction count.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3591)

fix: simplify gc size calculation

---

pkg/puller/puller.go
pkg/statestore/leveldb/migration.go

At the moment testnet is "broken", storage radiuses and reserve content are not consistent.
As a result, the nodes need to resync chunks, which is possible by resetting all sync intervals.
This is a good exercise, because we will need to reset the sync intervals on the mainnet as well .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3590)

fix: nuke statestore to remove sync intervals

---

pkg/localstore/migration.go
pkg/localstore/migration_gc_reset.go
pkg/localstore/schema.go

Reset the gcSize to gcIndex. Currently, we have chunks lying in the localstore gcIndex that may not be accounted for in the gcSize calculation as these were fixed recently.
This migration resets the gcSize to force a gc eviction in the node and clean up the stale entries. This along with the new reserveSize calculation should cleanup the data from localstore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3595)

fix: new localstore migration to reset gcSize

---

pkg/puller/puller.go
pkg/puller/puller_test.go

When the storage radius decreases, to completely resync the bin, the bin sync interval must be reset.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3600)

fix: reset sync interval for the new lower bin

---

pkg/localstorev2/internal/cache/cache.go
pkg/localstorev2/internal/cache/cache_test.go
pkg/localstorev2/internal/cache/export_test.go
pkg/storagev2/chunkstore.go
pkg/swarm/swarm.go

This PR adds the Cache component of the new localstore. The Cache is modeled as a queue that keeps the old content at the start and the recently accessed/stored content at the end. The capacity can be specified by the user and if we go above capacity, we will start evicting chunks from the cache.
The main goal of the current design is to not have any background processes to do GC. The GC brings indeterministic behavior and hence a self-cleaning cache is considered better in the long term. The additional indexes to be updated are hence considered okay.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3469)

feat(localstorev2): add cache store

---

pkg/api/dbindices.go
pkg/api/dbindices_test.go
pkg/api/router.go

This change adds a new API endpoint to print out the DebugIndices output of localstore. This gives us the count of items in the different indexes. This API should be used with care as it takes sometime and will count all the items in the localstore. Should be strictly used for debugging.
As such, I am not sure if we should add openapi spec for this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3612)

feat: dbIndices on debug API

---

pkg/localstore/migration.go
pkg/localstore/migration_postage_index.go
pkg/localstore/schema.go

The bug found in gc recently left these stale postageIndexIndex entries in the localstore. It will be better to remove all these stale entries before we go to mainnet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3609)

fix: migration to remove stale postageIndexIndex entries

---

pkg/storageincentives/redistribution/redistribution.go
pkg/transaction/transaction.go

Introduces the possibility to specify a minimum gas limit for a transaction in case the gas limit is estimated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3617)

feat: introduce min estimated gas limit

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/dbindices.go
pkg/api/dbindices_test.go
pkg/node/node.go

The DB Indices API is not working on the node as the API uses a wrapped netstore as Storer.
We will need to explicitly provide the interface from localstore. This time it is tested on a running node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3622)

fix: dbindices API

---

pkg/localstore/mode_put.go

In ModePutSync, if we get a chunk with radius lesser than the last known eviction radius of the batch, we force it to cache and not add it to reserve.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3627)

fix: prevent reserve put for out of depth chunks

---

pkg/pullsync/metrics.go

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3628)

fix: pullsync metric pointer

---

pkg/localstore/mode_put.go
pkg/localstore/mode_put_test.go
pkg/localstore/mode_set.go
pkg/localstore/pin_test.go
pkg/localstore/sampler_test.go

This test failure was seen on master as two changes were merged together and unit tests were not run after rebasing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3629)

fix: use withinRadiusFn for the tests

---

pkg/localstore/gc_test.go
pkg/localstore/localstore.go
pkg/localstore/localstore_test.go
pkg/localstore/sampler.go
pkg/localstore/sampler_test.go

In the sampler test we use the valid chunk checks, so we created a new testing function which mines the chunks to generate valid chunks. This however leads to timeouts in the race tests.
Instead, we will configure a testing validChunk function to skip this for the tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3642)

fix: flaky sampler test

---

pkg/localstore/gc.go
pkg/localstore/localstore.go
pkg/localstore/reserve.go
pkg/localstore/reserve_test.go

The current implementation of localstore and batchstore is a little problematic. We assign the localstore.EvictBatch function to batchstore to perform evictions due to batch expirations and batchstore.Unreserve to localstore to free reserve when we go over capacity.
This causes a deadlock situation as reserveEvictionWorker could acquire the GC lock and then wait for batchstore lock which is held by the cleanup function of batchstore which calls evictFn (localstore.EvictBatch), which waits on the GC lock. Solution is to allow only 1 reserve eviction process to start at a time. This is done by adding a new lock.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3641)

fix: deadlock in localstore batchstore interaction

---

pkg/localstore/gc.go
pkg/localstore/localstore.go
pkg/localstore/reserve.go
pkg/localstore/reserve_test.go

The previous fix for synchronizing the eviction processes was not the right fix for the goroutine pileup seen on the testnet. The problem happens because of the batchstore.Mutex contention as PutChainState in batchstore can call EvictBatch under the batchstore.Lock which will be waiting for GC lock held by reserveEvictionWorker that could be running simultaneously waiting for the batchstore.Mutex through Unreserve.
Solution is to not have any locking when we call evictFn from batchstore. So now we will register the expiredBatches in localstore when called from the batchstore and trigger the reserveEviction worker. This will enable only 1 flow of eviction and hence prevent any locking problems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

fix: batchstore localstore deadlock

---

pkg/puller/puller.go

It was observed on the private testnet that no pullsyncing was occurring because the topology change subscription never fired as there were no changes in the topology after the warm up period.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3643)

fix: recalc puller peers more periodically

---

pkg/postage/batchstore/reserve.go
pkg/postage/batchstore/store.go
pkg/pullsync/pullsync.go

It could happen that we pushsync chunks of newer batches that are outside our radius of responsibility as we have not seen the batch before. So we consider the current radius of this batch is 0 in localstore and might end up storing chunks for it.
With this fix, we use the initial value of current storage radius for a batch while adding it to batchstore. This would disallow any chunks from lower bins to be replicated by pushsync in the reserve.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3651)

fix: set batch storage radius on global storage radius change

---

go.mod
go.sum

Update storage-incentives to version v0.4.0-rc5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3657)

chore: update storage-incentives to rc5

---

.github/workflows/beekeeper.yml

Staging is no more, thus we should disable deployment as well
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3661)

ci: disable deploy to staging

---

openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml
pkg/api/export_test.go
pkg/api/router.go
pkg/api/staking.go
pkg/api/staking_test.go
pkg/storageincentives/staking/contract.go
pkg/storageincentives/staking/contract_test.go
pkg/storageincentives/staking/mock/contract.go

Adds an endpoint to delete all existing stake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3662)

refactor: enable withdraw all stake endpoint

---

.github/workflows/beekeeper.yml

Update the docker-setup-contracts version to latest (rc-5)
Move stake test next to stamp test, for relevance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3663)

fix: stake test order

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
cmd/bee/cmd/start_dev.go
pkg/node/bootstrap.go
pkg/node/node.go
pkg/postage/batchservice/batchservice.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/interface.go
pkg/postage/listener/listener.go
pkg/postage/listener/listener_test.go

Closes: #3660
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3671)

fix: gracefully suspend bee node on interrupt signal

---

pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3682)

fix: reduce depthmonitor target size to 40 percent

---

pkg/node/node.go
pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pullsync/pullsync.go
pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go

In some cases where the node is using high CPU or disk IO, or pulling intervals with invalid chunks for some, it may appear that the pullsync rate is zero, although there are active historical sync jobs running in the background.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3680)

fix: depthmonitor to track active syncing counter instead of rate

---

pkg/localstorev2/internal/cache/cache_test.go
pkg/localstorev2/internal/internal.go
pkg/localstorev2/internal/pinning/export_test.go
pkg/localstorev2/internal/pinning/pinning.go
pkg/localstorev2/internal/pinning/pinning_test.go
pkg/localstorev2/internal/upload/uploadstore_test.go

Minor changes in the pin store putter implementation. The problem was that the Putter creation initially required a root reference. However, this is available at the end in some cases where we haven't finished splitting the file yet. So now the upload putter will be closed with the reference and the root collection item will only be created at the end.
Also, created a function in the internal package for tests to reduce common code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3693)

refactor: pin store changes

---

pkg/localstorev2/internal/cache/cache.go
pkg/localstorev2/internal/cache/cache_test.go
pkg/localstorev2/internal/internal.go
pkg/localstorev2/internal/pinning/export_test.go
pkg/localstorev2/internal/pinning/pinning.go
pkg/localstorev2/internal/pinning/pinning_test.go
pkg/localstorev2/internal/upload/export_test.go
pkg/localstorev2/internal/upload/uploadstore.go
pkg/localstorev2/internal/upload/uploadstore_test.go
pkg/storagev2/chunkstore.go

After discussions within the team, it was agreed that the current tags-related functionality is not ideal. We need to pass the tag around on the chunk and across components using context key-value pairs. This has become pretty ugly. With the new localstore, we have a separate component called upload store which is used to consume uploads. It is possible to clean up all the ugly tag handling now by moving the tag-related logic into the upload store.
This PR refactors the originally envisioned upload store by also adding the tag functionality. Each putter can be assigned a new tag ID and hence serves as a session to upload data and keep track of the information related to this particular session. The Tag IDs can be thought of as file descriptors. They can be monotonically increasing …

refactor: upload store with tags

---

pkg/localstore/migration_residue.go

Ideally, we should not see this error. But if we do, we should ignore it and continue as a best-effort cleanup.
A proper fix would be to identify why we dont have retrievalDataIndex. But this would be a much bigger investigation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3715)

fix: continue migration on error

---

pkg/node/devnode.go
pkg/node/node.go
pkg/postage/batchstore/mock/store.go
pkg/postage/batchstore/reserve_test.go
pkg/postage/batchstore/store.go
pkg/postage/batchstore/store_test.go
pkg/postage/interface.go
pkg/postage/noop.go
pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pusher/pusher.go
pkg/pusher/pusher_test.go
pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go
pkg/storageincentives/agent.go
pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go
pkg/topology/kademlia/export_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/mock/kademlia.go
pkg/topology/mock/mock.go
pkg/topology/topology.go

Closes #3700 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3703)

fix: puller and pushync should use storage radius only for syncing

---

pkg/localstorev2/internal/chunkstore/chunkstore.go
pkg/localstorev2/internal/chunkstore/export_test.go
pkg/localstorev2/internal/chunkstore/txchunkstore.go
pkg/localstorev2/internal/chunkstore/txchunkstore_test.go
pkg/localstorev2/localstore.go
pkg/storagev2/inmemstore/transaction.go
pkg/storagev2/storagetest/chunkstore.go
pkg/storagev2/storagetest/transaction.go
pkg/storagev2/transaction.go

This PR adds the TxChunkStore implementation for the localstorev2.ChunkStore. The chunkstore uses the storage.Store as well as Sharky. So implementing a transaction functionality is a little tricky.
The way it is done here is to have a simple transaction functionality over sharky, where released locations are only released on commit, so that they can be rolled back and committed locations are released on rollback to give back the slots to sharky.
Along with this, we use the TxStore internally in the transactions to revert the state of the Store items to their original state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3702)

feat: tx chunkstore and multiple stamp support

---

pkg/retrieval/retrieval.go
pkg/retrieval/retrieval_test.go

The PR simplifies the retrieval logic while maintaining preventive and on error retries.
Tests passed without any edits.
https://github.com/ethersphere/bee-backlog/issues/36
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3428)

fix: retrieval rewrite

---

openapi/SwarmCommon.yaml
pkg/api/redistribution.go
pkg/storageincentives/agent.go
pkg/storageincentives/redistributionstate.go
pkg/storageincentives/redistributionstate_test.go

add isFullySynced field, which indicates that the node is ready to participate in the game
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3751)

feat: add isFullySynced field

---

pkg/pullsync/pullsync.go

PR increases the max page of a pullsync pull request from 
50 chunks (~200kb) to 250 chunks (~1MB)
this will reduce the number of opened and closed streams, and makes skipping unwanted bin intervals quicker.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3754)

feat: increase max page of pullsync requests

---

pkg/puller/puller.go

reset all intervals below the new radius to resync:
1. previously evicted chunks
2. previously ignored chunks due to a higher radius
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3753)

fix(puller): reset all lower bins on storage radius decrease

---

pkg/storageincentives/agent.go

IsFullySynced property should be set frequently instead of only when the neighbourhood is selected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3758)

fix: isFullySynced needs to be check frequently

---

pkg/pusher/pusher.go
pkg/pusher/pusher_test.go

Because pusher does stamp validation before the semaphore acquire, under extreme heavy loads (as seen in the testnet), the pusher could be overwhelmed and batches that originally passed the validation may become expired while waiting in the queue to be pushed.
The fix is to move the validation to just before pushing the chunk.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3760)

fix(pusher): move stamp validation just before pushing

---

pkg/localstorev2/export_test.go
pkg/localstorev2/localstore.go
pkg/localstorev2/localstore_test.go
pkg/localstorev2/netstore.go
pkg/localstorev2/netstore_test.go

This PR adds the netstore interfaces as specified in the new localstore design. The Netstore is a special storage.Getter and storage.Putter which deals with the network. It will be used for direct upload and download. On direct upload, it will straight away push the chunks to the pusher. On download, it will retrieve the chunk from the network if not found locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3766)

feat(localstorev2): netstore interfaces

---

.github/workflows/release.yaml
.goreleaser.yml

Updated goreleaser version and fixed deprecated option
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3770)

ci: bump goreleaser and fix deprecated option

---

pkg/p2p/libp2p/main_test.go
pkg/pss/main_test.go

- Ignoring one more libp2p goroutine
- Removed unnecessary goleak ignore from pss package
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3807)

fix(goleak): ignore libp2p goroutine

---

pkg/p2p/libp2p/internal/reacher/reacher_test.go

Fore some reason this was not detected by linter in previous CI runs.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3812)

fix(lint): lint issue fixed

---

.github/workflows/go.yml
Makefile
pkg/api/api_test.go
pkg/feeds/epochs/lookup_test.go
pkg/hive/hive_test.go
pkg/localstore/sampler_test.go
pkg/p2p/libp2p/connections_test.go
pkg/puller/puller_test.go
pkg/topology/depthmonitor/depthmonitor_test.go
pkg/topology/kademlia/kademlia_test.go

This PR makes changes to CI jobs per proposal #3427.
Changes:
- `Lint` job will now execute `Whitespace check` as additional step. Previously this step was executed as par of `Coverage Report` job.
- `Coverage Report` is now only executed for master branch (there is no need to send coverage reports for commits to PRs)
- `Test (flaky)` job was added which executes unit tests ending with `FLAKY` string. This job will 'continue on error' on master branch (thus not affecting green check marks), but on other branches this job will fail (making red cross mark) giving developers the same level of insight as before this PR. 
- `Test` step of `Test` job was changed so that it runs all unit tests that are not marked as flaky (unit tests which do not end `FLAKY` string)
- Added FLAKY annotation
- on …

feat(ci): run flaky test separately

---

pkg/swarm/distance.go
pkg/swarm/distance_test.go
pkg/swarm/swarm.go

In this PR `swarm.Distance` arguments are changed to `swarm.Address` to enforce better type safety.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3830)

chore(swarm): distance args to use Address type

---

pkg/topology/kademlia/kademlia_test.go

marking `TestSnapshot` and `TestAnnounceBgBroadcast` as flaky, issue #3834 #3836
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3835)

chore: set TestSnapshot and TestAnnounceBgBroadcast as flaky

---

pkg/api/api_test.go

Method `ResolveNameOrAddress` returns zero address for empty string but the test case was expecting an error.
The test wasn't failing simply because it itself was broken.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3815)

fix(api): bad test case

---

pkg/log/log.go

It seems a change in the library led to level hooks not being plugged in properly into the log options and.
As a result the grafana dashboards stopped reporting log counts. This PR should fix that. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3848)

fix: log level hooks

---

.goreleaser.yml

By default goreleaser sorts tag version in reverse using, sort `-version:refname`
```
❯ git tag --points-at HEAD --sort=-version:refname --format='%(creatordate)%09%(refname)'
Thu Mar 2 21:38:51 2023 +0300   refs/tags/v1.13.0-rc3
Thu Mar 2 21:38:51 2023 +0300   refs/tags/v1.13.0
```
With this fix it will produce outcome that we expect `version:refname`
```
❯ git tag --points-at HEAD --sort=version:refname --format='%(creatordate)%09%(refname)'
Thu Mar 2 21:38:51 2023 +0300   refs/tags/v1.13.0
Thu Mar 2 21:38:51 2023 +0300   refs/tags/v1.13.0-rc3
```

ci: fix release tag version sort

---

pkg/util/ioutil/ioutil.go
pkg/util/ioutil/ioutil_test.go

Fixes the case where the timeout reader `cancel` function is called after the normal completion of a read.

fix: timeout reader cancel func call on normal read

---

pkg/util/ioutil/ioutil.go
pkg/util/ioutil/ioutil_test.go

Improve timeout reader:
- don't terminate the underlying goroutine when zero bytes are read
- terminate underlying goroutine on any error encounter

refactor: improve underlying goroutine termination of timeout reader

---

openapi/SwarmCommon.yaml

Added missing fields for debug api "phase" and "hasSufficientFunds" to openapi SwarmCommon.yaml file.

docs: added missing fields to openapi definition

---

pkg/api/bzz.go

Fixes
```
"msg"="bzz download: invalid path" "traceID"="c58e21a191226be" "traceID"="c58e21a191226be"
```

fix: duplicate trace id in logs

---

pkg/retrieval/retrieval.go

The main loop on rare edge cases would freeze as the default case for the retry was missing.

fix(retrieval): added missing select default case for retry func

---

pkg/node/node.go
pkg/puller/puller.go
pkg/pullsync/pullsync.go

There are two groups of pullsyncing: neighbors and non-neighbors. For fresh nodes especially, each time we lower the storage radius, all previous intervals below the radius are reset, meaning syncing starts from scratch for those bins. For peers that is within the radius, no resyncing occurs because the reset radiuses are below the storage radius, but for the out of depth peers, syncing has to be done from scratch. 
To prevent too much resyscing, we delay the the start of the out of depth syncing until after 24 hours of running, which should be enough time for the storage radius to stabilize.

perf: delay out of depth syncing for some time

---

pkg/storageincentives/agent.go
pkg/storageincentives/events.go
pkg/storageincentives/events_test.go
pkg/storageincentives/redistributionstate.go

Removing sample end phase/event because it appears to be unnecessary and introduces confusion because it is not valid phase.
Logic of old sample end event was added to sample handler where it suits more. 
Additional, minor change, was cleaning up commit handler. It now follows same handler convention of previous PR. Also previous phase type event check was removed because handler will be able to know if phase could be played or not based on stored information.

chore(storageincentives): removed sample end phase/event

---

pkg/pullsync/pullsync.go

fix(pullsync): null chunk adress when stamp is invalid

---

pkg/pushsync/pushsync.go
pkg/retrieval/retrieval.go
pkg/skippeers/skippeers.go
pkg/skippeers/skippeers_test.go

fix(retrieve, pushsync): wait for overdraft peers to refresh

---

pkg/api/bytes.go
pkg/api/bytes_test.go
pkg/api/bzz_test.go
pkg/api/chunk.go
pkg/api/chunk_test.go
pkg/api/router.go

- disabled compression handler in API for download endpoints; because this handler is always removing `Content-Length` header
- improved API test when asserting response 
- added assertion of Content-Length header 
- utilized WithExpectedResponseHeader for other headers

fix(api): set Content-Length header on download endpoints

---

pkg/node/node.go
pkg/pusher/pusher.go
pkg/pusher/pusher_test.go

Full node must use storage radius, not neighborhood depth, to confirm receipt depth.

fix(pusher): full nodes use the storage radius for receipt check

---

go.mod
go.sum

Bump storage-incentives abi to `v0.5.0`.

chore: bump storage-incentives abi to v0.5.0

---

pkg/postage/batchstore/reserve.go
pkg/postage/batchstore/reserve_test.go
pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go

It was discovered on the dev-bee-gateway cluster that the storage radius may drop to zero if the the rpc endpoint is faulty.
This removes the logic from batchstore that lowers the storage radius, since we already have a mechanism (depthmonitor) that takes care of this anyways.

fix(batchstore): allow depthmonitor only to reduce the storage radius

---

go.mod
pkg/node/bootstrap.go
pkg/node/node.go
pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go
pkg/retrieval/retrieval.go
pkg/retrieval/retrieval_test.go
pkg/skippeers/main_test.go
pkg/skippeers/skippeers.go
pkg/skippeers/skippeers_test.go

It was identified in a testing session that during uploads, most CPU cycles are wasted on pruning the skiplist.
With this change, the prune call is no longer needed before every push/retrieval.
The clean up call of items is done once at the time of expiration.
Internally, the skiplist now uses a minimum heap to wake up at the time of the closest expiration.

perf(pushsync, retrieval): skiplist prunes items internally on expiration 

---

pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pullsync/pullsync.go
pkg/topology/depthmonitor/depthmonitor.go

When the neighborhood size is large, node have to sync with many peers that ultimately respond with the same chunks because reserves are identical across neighborhoods. It is wasteful to have to sync with ALL of the neighbors at the SAME time. 
So, we can limit the amount of parallel hist sync jobs and that should reduce the intensity of the initial syncing.
Since reserves are identical across neighborhoods (we get the same chunk from different peers), the time to find a stable storage radius does not get affected. 
This change also propagates through the network because peers now have to respond to fewer sync requests. 
At the end, we still complete historical syncing with every neighbor. 
The depthmonitor wake up interval is also increased.

perf(puller): reduce historical sync workload

---

pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go

as the reserve size gets near the tipping point of over filling and causing the radius to increase, it was discovered that the threshold of 40% is too low that fresh nodes may linger at a storage radius one higher than the rest of network.

fix(depthmonitor): change threshold back to 50 percent

---

pkg/node/node.go

Fixes panic on negative WaitGroup counter:
```
panic: sync: negative WaitGroup counter
goroutine 87 [running]:
sync.(*WaitGroup).Add(0x9f2c7a099b40bc0f?, 0x26d354ac58e15864?)
sync/waitgroup.go:62 +0xe5
sync.(*WaitGroup).Done(0x2d66c9c4fd2b7fa1?)
sync/waitgroup.go:87 +0x25
github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown.func11()
github.com/ethersphere/bee/pkg/node/node.go:1283 +0x8d
created by github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown
github.com/ethersphere/bee/pkg/node/node.go:1280 +0x714
panic: sync: negative WaitGroup counter
goroutine 90 [running]:
sync.(*WaitGroup).Add(0xf08b306d2c0b7911?, 0x4280c26bdb144bc1?)
sync/waitgroup.go:62 +0xe5
sync.(*WaitGroup).Done(0xd44234d4b5331c0f?)
sync/waitgroup.go:87 +0x25
github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown.func14() …
```

fix: negative work group counter on shutdown

---

pkg/topology/kademlia/kademlia.go

In some cases, the balanced connector is not sufficient, causing the depth to fluctuate when a shallow bin count goes below 8 peers:
ex: 
````
"bins": {
"bin_0": {
"population": 2103,
"connected": 9
},
"bin_1": {
"population": 970,
"connected": 7
},
"bin_2": {
"population": 483,
"connected": 19
},
"bin_3": {
"population": 227,
"connected": 40
},
"bin_4": {
"population": 118,
"connected": 41
},
```
after change
```
{
"depth": 8,
"reachability": "Private",
"networkAvailability": "Available",
"bins": {
"bin_0": {
"population": 1996,
"connected": 17
},
"bin_1": {
"population": 822,
"connected": 14
},
"bin_2": {
"population": 455,
"connected": 16
},
"bin_3": {
"population": 234,
"connected": 16
},
"bin_4": {
"population": 110,
"connected": 18
},
```

fix(kademlia): new prune log, oversaturation check fix, and more aggressive balance connector

---

pkg/postage/stamp.go
pkg/postage/stamper.go
pkg/postage/testing/stamp.go
pkg/storage/testing/chunk.go

Changes: 
- add `RecoverBatchOwner` + usage refactor
- add `MustNewValidStamp` + usage refactor
These changes are needed by PR #4040. They are made in individual PR in order to prevent future merge conflicts on #4040.

chore(postage): add RecoverBatchOwner and MustNewValidStamp

---

pkg/node/node.go
pkg/postage/service.go
pkg/pusher/pusher.go
pkg/storer/internal/reserve/reserve.go
pkg/topology/kademlia/kademlia.go

Latest round of testing after rebase
Issues:
1. Initialize inmem store for stampissuer on restart. Required till peter's changes are in.
2. Direct upload gets stuck if we see lot of failures. This is because we dont give up the sem till we are able to repeat.
3. Reserve.Put lock. The Put method needs lock as simultaneous puller routines might try to add the same chunks which causes new binIDs to be assigned to same chunk as we dont have sync.
4. In the private testnet we dont have any outside connections, which leads to all nodes having reachability unknown. So this is a temporary fix for the private testnet.
Results:
1. Uploads, direct uploads, pinning all working well
2. Syncing also working well
3. Retrieval also works well

fix(storer): misc fixes from testing

---

pkg/pushsync/pushsync.go

In the case that no neighbor peer can be found for a chunk, the closest peer should store the chunk.
1. Origin peers should not store the chunk initially so that the chunks is always forwarded into the network, 
2. If no peer can be found from an origin peer, the origin peer may store the chunk.
3. Non-origin peers store the chunk if the chunk is within depth.
4. For non-origin peers, if the chunk is not within depth, they may store the chunk if they are the closest peer to the chunk.
Puller continues to pull chunks from out of depth bins, so that these out of depth chunks eventually find their way into a proper neighborhood.
Pusher continues to check the depth of the receipt so for shallow receipts, the chunk is retried up to 5-6 times.

fix(pushsync): include self in the case no neighbor can be found

---

openapi/SwarmCommon.yaml
pkg/api/api_test.go
pkg/node/node.go
pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go
pkg/salud/metrics.go
pkg/salud/salud.go
pkg/salud/salud_test.go
pkg/storageincentives/agent.go
pkg/storageincentives/agent_test.go
pkg/topology/kademlia/export_test.go
pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/internal/metrics/metrics_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go
pkg/topology/kademlia/mock/kademlia.go
pkg/topology/mock/mock.go
pkg/topology/topology.go

The salud service utilizes the status protocol and marks a peer as unhealthy if it does not pass certain checks.
The checks are:
1. Calculate 80th percentile of response durations from each peer and marks peers above the percentile as unhealthy
2. Calculate the most common storage radius and marks peers that have a different radius.
3. Calculate the most common batch commitment and marks peers that have a different commitment. 
4. Calculate 80th percentile of connected peers count and marks peers lower than the percentile. 
5. The agent stops the node from playing a round if the peer's radius is different from it's peers. 
some logs 
```
"msg"="radius check failure" "radius"=0 "peer_address"="***"
"msg"="dur check failure" "dur"=4.9897606 "peer_address"="***"
"msg"="dur check failure" …
```

feat(salud): new health service

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/main_test.go
pkg/api/pss.go
pkg/node/devnode.go
pkg/node/node.go
pkg/node/statestore.go
pkg/postage/service.go
pkg/postage/stamp_test.go
pkg/postage/stamper.go
pkg/postage/stamper_test.go
pkg/postage/stampissuer.go

Use leveldb instead of in-memory db in the stamper.

refactor: use leveldb in stamper

---

pkg/node/node.go
pkg/puller/metrics.go
pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pullsync/metrics.go
pkg/pullsync/pullsync.go
pkg/pullsync/pullsync_test.go

Added some new metrics.
Removed the 24h wait period for out of depth syncing now that hist syncing is rate limited.

chore(puller, pullsync): remove 24 wait period for puller, new metrics, cleanup

---

Makefile
pkg/api/health.go
pkg/api/version.go

```
λ curl localhost:1635/health
{"status":"ok","version":"1.16.0-af961dc1","apiVersion":"4.1.0","debugApiVersion":"3.1.0"}
```

fix: debug api version in health endpoint

---

pkg/node/chain.go
pkg/node/node.go
pkg/puller/mock/puller.go
pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pusher/pusher.go
pkg/pusher/pusher_test.go
pkg/salud/salud.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/mock/mockreserve.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go

Instead of getting the initial radius from the batchstore for the storer reserve, utilize salud's network radius.
this causes the node to quickly start syncing from the correct radius.
With this, light nodes will use the network storage radius for receipt checks, instead of neighborhood depth. 
To be released with #3936

feat(reserve, salud): utilize network radius from salud for inital storage radius and pusher receipt checks

---

pkg/puller/puller.go

There is a potential for a data race in the way the synced intervals are stored between historical and live syncing so we added a mtx lock.

fix(puller): added new mtx locking to interval state storing

---

pkg/node/node.go
pkg/salud/main_test.go
pkg/salud/metrics.go
pkg/salud/salud.go
pkg/salud/salud_test.go

Stops the node from playing the game when the reserve is off by some percentage err.
the reserve size avg is computed by first trimming the lower and top 10% of the responses, this actually ends up creating a rather accurate number.

feat(salud): self health check based on reserve size

---

pkg/api/status.go
pkg/api/status_test.go
pkg/chainsyncer/chainsyncer.go
pkg/node/bootstrap.go
pkg/puller/puller.go
pkg/pushsync/pushsync.go
pkg/retrieval/retrieval.go
pkg/salud/salud.go
pkg/status/status.go
pkg/status/status_test.go
pkg/topology/depthmonitor/depthmonitor.go
pkg/topology/depthmonitor/depthmonitor_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go
pkg/topology/kademlia/mock/kademlia.go
pkg/topology/mock/mock.go
pkg/topology/topology.go

pruning out of depth and oversaturated bins is for unhealthy or reachable peers.
renamed topology.Filter -> topology.Select

feat(kademlia): prune out of depth oversaturated bins based on peer health

---

pkg/puller/puller.go

```
"time"="2023-06-01 10:45:28.299523" "level"="info" "logger"="node/puller" "msg"="puller shutting down"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x118e613]
goroutine 2131 [running]:
github.com/ethersphere/bee/pkg/puller.(*Puller).Close(0xc0002b9080)
github.com/ethersphere/bee/pkg/puller/puller.go:408 +0x53
github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown.func1({0x1ad73e0?, 0xc0002b9080?}, {0x157a01f, 0x6})
github.com/ethersphere/bee/pkg/node/node.go:1287 +0x5b
github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown.func7()
github.com/ethersphere/bee/pkg/node/node.go:1335 +0x7e
created by github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown
github.com/ethersphere/bee/pkg/node/node.go:1333 +0x56e …
```

fix(puller): nil pointer on Close

---

cmd/bee/cmd/db.go
cmd/bee/cmd/db_test.go
pkg/pullsync/pullsync.go
pkg/pusher/pusher.go
pkg/pusher/pusher_test.go
pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go
pkg/storer/debug_test.go
pkg/storer/internal/cache/cache.go
pkg/storer/internal/cache/cache_test.go
pkg/storer/internal/cache/export_test.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/mock/mockreserve.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go

The current Reserve and Cache synchronization is a little problematic. The mutexes in the internal packages dont protect against Txn rollbacks that can occur due to failures. As a result it is better to have the locking in the storer package.
Also, the cache optimization for saving state in memory could also be problematic. Right now it seems like an unnecessary optimization. So instead it will read the state for every op.
The mem profiles after the changes show significant improvements all round.

fix(storer): cleanup reserve and cache synchronization

---

pkg/storage/inmemchunkstore/transaction.go
pkg/storage/inmemstore/transaction.go
pkg/storage/leveldbstore/transaction.go
pkg/storage/storagetest/transaction.go
pkg/storage/transaction.go
pkg/storer/internal/chunkstore/transaction.go

The `Rollback` transaction function returns a value of `nil` on its first call after the parent context has been canceled.

fix: transaction rollback logic

---

pkg/api/status_test.go
pkg/node/node.go
pkg/status/status.go
pkg/status/status_test.go
pkg/storer/reserve.go
pkg/storer/storer.go

status api returns that all connected peers are neighbors because of a bug in the status pkg.

fix(status): get radius before calculations

---

pkg/node/bootstrap.go
pkg/node/node.go
pkg/salud/salud.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go
pkg/topology/kademlia/metrics.go
pkg/topology/kademlia/mock/kademlia.go
pkg/topology/mock/mock.go
pkg/topology/topology.go

Since salud acquires the status msg from every peer (reachable or not), we can use this mechanism to record peer latency instead of kademlia's ping.

feat: salud to record peer latency

---

pkg/api/tag.go
pkg/sharky/recovery.go
pkg/storage/storageutil/storageutil.go
pkg/storer/epoch_migration.go
pkg/storer/epoch_migration_test.go
pkg/storer/export_test.go
pkg/storer/internal/internal.go
pkg/storer/internal/pinning/export_test.go
pkg/storer/internal/pinning/pinning.go
pkg/storer/internal/pinning/pinning_test.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/internal/upload/export_test.go
pkg/storer/internal/upload/uploadstore.go
pkg/storer/internal/upload/uploadstore_test.go
pkg/storer/mock/mockstorer.go
pkg/storer/mock/mockstorer_test.go
pkg/storer/netstore.go
pkg/storer/pinstore.go
pkg/storer/reserve.go
pkg/storer/storer.go
pkg/storer/subscribe_push.go
pkg/storer/uploadstore.go
pkg/storer/uploadstore_test.go

- During manual testing we observed that there is high memory usage during upload of large (1.5G+) files. One reason for this is currently 1 upload only does 1 txn. This will be a problem for large uploads as the txn state grows in-mem. Also, if the node blows up during this upload, we cannot uncommit the changes. So this change makes upload and pinning stores use 1 txn per Put op. This is similar to how we do for Cache and Reserve. Also, Cleanup mechanism is now added which can recover from restarts as well. So the file will not be pushed till it is successfully uploaded and incomplete pinning collections will also be removed.
- We also saw that the test coverage of the master branch went down. This was contrary to what we had tested before and seems like there is some drop in coverage …

fix(storer): refactor upload and pinning putters

---

openapi/SwarmCommon.yaml
pkg/api/redistribution.go

Change: `minimumFunds` -> `minimumGasFunds`, reflected in `redistributionStatusResponse` object and the OpenApi specification.
See #4003

refactor(api): improve vagueness of 'minimumFunds' label

---

pkg/node/devnode.go
pkg/node/node.go
pkg/postage/batchstore/store.go
pkg/postage/batchstore/store_test.go
pkg/storer/internal/reserve/reserve.go

The mutex locks were originally placed to protect internal variables like radius. The PR cleans up these mutexes.

fix(batchstore,reserve): cleanup mtx locks

---

pkg/pusher/pusher.go
pkg/storer/export_test.go
pkg/storer/netstore.go
pkg/storer/storer.go

PR makes direct upload concurrency level the same as differed uploads.
multiple parallel uploads are limited by the same worker so the node remains protected against goroutine pileup.

fix(direct-upload): use same concurrency as deferred upload

---

pkg/storer/epoch_migration.go

Read chunk data in order to populate the chunk type information during migration. If for some reason we get error while reading from sharky there is no recovery path. So ignore the error and continue. The location will be freed and chunk will be gone in this case. This should never happen though.

fix: read chunk data during migration

---

packaging/bee.service

Just in case restart service always, even if it exits with a clean code

fix: restart always systemd service

---

pkg/pusher/pusher.go
pkg/storer/netstore.go
pkg/storer/netstore_test.go

In the pusher we return shallow receipt error on pushing if we receive a receipt with invalid depth. This is to allow the pusher to retry again to get a better receipt. This was missing in the direct upload. In the old version, direct upload keeps retrying on error, so this change will revert to old behavior. After the allowed retry limit, this error will be swallowed by the pusher and the operation will be termed success.

fix: retry on shallow receipt for direct upload

---

pkg/storage/transaction.go

Allow transaction rollback on `context.DeadlineExceeded` error.

fix: allow tx rollback on context deadline exceeded error

---

pkg/postage/export_test.go
pkg/postage/stampissuer.go
pkg/postage/stampissuer_test.go
pkg/storer/internal/upload/uploadstore.go

fix: mutable batches resets index buckets

---

pkg/postage/export_test.go
pkg/postage/stamper.go
pkg/postage/stamper_test.go
pkg/postage/stampissuer.go
pkg/storer/internal/upload/uploadstore.go

If we assign a stamp index to a chunk but the upload fails, we should not assign the same index to the chunk again untill the stampissuer has reached that index. If we dont handle this, we could assign an index to a chunk which will be overwritten in future.

fix: check stampissuer saved index

---

pkg/postage/batchstore/store.go

We should delete the batchstore contents before doing the eviction on localstore. This is to ensure the validStamp function will return error for this batch while eviction can happen at its pace.

fix: move eviction to the end of batch expiration handling

---

pkg/postage/stampissuer.go
pkg/pushsync/pushsync.go
pkg/storer/internal/reserve/reserve.go

It was observed during testing that a dirty shutdown during a running eviction can cause unwanted entries to be left behind and cause future evictions to fail. 
so we change the `removeChunk` to do a best attempt to remove all items and not return an error early.

fix(reserve): best attempt to remove all related items

---

pkg/pusher/pusher.go
pkg/salud/salud.go

Pusher starts sending chunks even though health service has no run yet. Checking the radius at this point causes pusher to wait for a radius to arrive.

fix: wait for network radius

---

pkg/pullsync/pullsync.go
pkg/pullsync/pullsync_test.go

Fixes panic on reading zero value from closed channel:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x118f6c1]
bee
goroutine 136436466 [running]:
github.com/ethersphere/bee/pkg/pullsync.(*Syncer).collectAddrs.func1({0x1afb098, 0xc0690ee460})
github.com/ethersphere/bee/pkg/pullsync/pullsync.go:414 +0x2a1
resenje.org/singleflight.(*Group).Do.func1()
resenje.org/singleflight@v0.2.0/singleflight.go:59 +0x35
created by resenje.org/singleflight.(*Group).Do
resenje.org/singleflight@v0.2.0/singleflight.go:58 +0x2d5
```

fix(pullsync): panic on reading from closed channel

---

pkg/storer/reserve.go

Because SetRadius is not called in the initialization of the reserve worker, kademlia never picks up the storage radius from the reserve initially.
The side effect is metrics can show the wrong radius.

fix(reserve): must call set radius to notify kademlia

---

Makefile
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/reserve.go

Currently, the eviction function holds the lock for the entire duration of the call. This includes holding the lock during iteration of the bin items and also Put to cache. These are not required. We only need the lock while we remove the chunk related indexes.

perf: reduce locking context during evictions

---

pkg/storer/metrics.go

Ignore `storage.ErrNotFound` error in getterWithMetrics `Get` calls.

refactor: ignore error not found in getter metrics

---

pkg/postage/batchstore/store.go
pkg/postage/listener/listener.go

Replace chain state guarding mutex for atomic pointer and add extra logging to see if the listener was silently shutdown.

refactor(listener): use atomic pointer for chain state and add extra log line

---

pkg/node/node.go
pkg/puller/mock/puller.go
pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go

During shutdown the pullsync protocol is stuck with:
```
"time"="2023-06-27 11:35:15.950681" "level"="debug" "logger"="node/libp2p" "msg"="handle protocol: handle headers failed" "protocol"="pullsync" "version"="1.3.0" "stream"="pullsync" "peer"="e1dc994c4a8ba82c183cd9b773210d7c88061c507fb9a9dfcbccea04b8380134" "error"="read message: context canceled"
"time"="2023-06-27 11:35:15.950759" "level"="debug" "logger"="node/libp2p" "msg"="handle protocol: handle headers failed" "protocol"="pullsync" "version"="1.3.0" "stream"="pullsync" "peer"="e1dc994c4a8ba82c183cd9b773210d7c88061c507fb9a9dfcbccea04b8380134" "error"="read message: context canceled"
"time"="2023-06-27 11:35:15.950764" "level"="debug" "logger"="node/libp2p" "msg"="handle protocol: handle headers failed" "protocol"="pullsync" …
```

fix: pass ctx to stop puller

---

pkg/node/node.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/reserve.go
pkg/storer/storer.go

fix: clean up runs when reserve is constructed and reserve size recount is removed

---

pkg/storer/subscribe_push.go

Just in case we dont get a trigger from anywhere else, we should trigger again.

fix: trigger subscribe push to ensure new iteration

---

pkg/node/node.go
pkg/puller/metrics.go
pkg/puller/puller.go
pkg/puller/puller_test.go
pkg/pullsync/mock/pullsync.go

Removes the need to maintain rate limiting for syncing.
Halves the number of workers, goroutines, open streams, etc.
Much cleaner code...

feat(puller): remove historical syncing and run a single syncer

---

pkg/storage/leveldbstore/store.go

Closes iterator if prefix is not found.

fix: close iterator on empty iteration

---

pkg/node/statestore.go
pkg/storage/cache/cache.go
pkg/storage/cache/cache_test.go

Includes a namespace in the cache key, which addresses the case where two entries from different namespaces may have the same ID.

fix(cache): include namespace in the cache key

---

pkg/storage/storagetest/batch.go
pkg/storage/storagetest/storage.go

Remove duplicate batched store interface in the `storagetest` package.

refactor(storagetest): remove duplicate batched store interface

---

pkg/storer/internal/reserve/items.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/metrics.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go

Single worker is not fast enough to handle unreserve as well as postage expirations. So we will handle them in separate goroutines so the eviction worker is unblocked to listen to signals.

perf: parallelize eviction and expiration

---

pkg/storer/internal/reserve/items.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/reserve.go
pkg/storer/storer.go

Caused us to release all sharky slots on restart. Was discovered with the help of @ldeffenb. For more details please go to discord.

fix: do epoch migration only once

---

pkg/storer/internal/cache/cache.go
pkg/storer/internal/reserve/items.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go

Debugging on resource-constrained machines, we found some unnecessary goroutine creations and also excessive expiry checks. Thanks to @ldeffenb for helping out with this! These changes should improve the CPU consumption of the nodes.
Also, a bug was found with the move to cache where the reserve size was not being changed correctly. This is fixed by moving the cache op into the same transaction, so it can be reverted together.

perf: improve eviction worker cpu use

---

pkg/storer/internal/cache/cache.go
pkg/storer/internal/cache/cache_test.go
pkg/storer/internal/reserve/items.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go

Optimize moving chunks from reserve to cache. Avoid the extra reads by not deleting chunks when removing from reserve.

perf: optimize reserve eviction

---

pkg/storer/internal/cache/cache.go
pkg/storer/internal/cache/cache_test.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go

Missed expiry triggers. If expiry triggers are swallowed after we already selected batches to expire and no new signals for expiry are received, we will keep a hold of the expired chunks till cleanup comes and helps us. This change ensures we trigger a run if we have selected entries to ensure we havent swallowed any triggers. If there are no more batches, then it wont re-trigger it.

fix: swallowed batchExpiry trigger

---

pkg/storer/epoch_migration_test.go
pkg/storer/export_test.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/reserve.go
pkg/storer/storer.go

Issues found in upgrage testing. While upgrading light nodes, the way the reserve was passed in to the function resulted in panic. This is because the interface was pointing to a valid type and hence the `!= nil` check failed. As a result the node was trying to migrate reserve for light nodes which caused the panic.

fix: lightnode migration

---

pkg/storer/cachestore_test.go
pkg/storer/internal/cache/cache.go
pkg/storer/internal/cache/cache_test.go
pkg/storer/internal/cache/export_test.go
pkg/storer/migration/all_steps.go
pkg/storer/migration/export_test.go
pkg/storer/migration/step_02.go
pkg/storer/migration/step_02_test.go
pkg/storer/storer_test.go

Simplifying cache component. Having a simpler timestamp index to iterate makes things much simpler and less error prone. The linked list is very error prone and leaves the cache useless if we hit any issues.
Verified on mainnet dev cluster:

fix: simplify cache handling

---

pkg/storer/reserve.go
pkg/storer/reserve_test.go

Batch expiration and unreserve worker has been greatly simplified.
1. Batch expiration still has higher priority over unreserve. The unreserve now listens on batch expiration events and stops early if the expiration event is fired.
2. Expiration and unreserve still do not overlap (same as before).
3. Cleanup worker is removed (mainly for simplification, can be readded if it's discovered it would add value, has not so far)

fix(reserve): simplify batch expiration and unreserve interaction

---

openapi/SwarmCommon.yaml
pkg/api/redistribution.go
pkg/storageincentives/agent.go
pkg/storageincentives/redistributionstate.go

Adds `isHealthy` to `redistributionstate` response.
Fixes #4212

feat: add isHealthy to redistributionstate

---

pkg/p2p/libp2p/libp2p.go

fixes the unnecessary quotes in logs like these
```
"err"="new stream: new stream for peerid: create stream \"/swarm/pullsync/1.3.0/pullsync\" to \"Qmbioqnig2LCEUZasLEkt5noahWcST4Ur9zSKWwHDCYiSY\": context canceled"
```

fix: err format

---

pkg/storer/cachestore_test.go
pkg/storer/debug.go
pkg/storer/debug_test.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/reserve_test.go

Puller sync intervals start from binID 1, as such the first binID in localstore should also start from 1, not 0!
ex log: `"msg"="syncWorker interval failed" "peer_address"="a71da0378051958fab7a299f7036cc1cb1dd9fc4e47135c51bf6e27c2169e43b" "bin"=18 "cursor"=0 "start"=1 "topmost"=0 "err"="read offer: stream reset"`

fix: first binID to start from 1 and print the last bin ids in /debugstore

---

pkg/salud/salud.go
pkg/salud/salud_test.go

After v1.17.0, the reserve size is no longer a count of chunks of PO >= storage radius.
It includes chunks of all POs, as such, reserve sizes between [0, storage radius) can be under constant fluctuation, mainly due to unpredictable batch evictions.
So we remove the self reserve size check.

fix(salud): remove reserve size self health check

---

pkg/api/api.go
pkg/api/postage.go
pkg/api/postage_test.go
pkg/api/pss.go
pkg/api/stewardship.go
pkg/node/node.go
pkg/postage/batchservice/batchservice.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/batchstore/store.go
pkg/postage/interface.go
pkg/postage/mock/service.go
pkg/postage/postagecontract/contract_test.go
pkg/postage/service.go
pkg/postage/service_test.go

Revert stamp issuer to its previous implementation that allowed concurrent use of the same issuer.

feat: allow concurrent use of the same issuer

---

pkg/storer/reserve.go

- [N/A] My change requires a documentation update, and I have done it.
- [N/A] I have added tests to cover my changes.
Avoid panic if querying ReserveLastBinIDs on ultra-light node with no reserve.
Closes #4270
N/A
Issue #4270 
#4270

fix: don't panic if no reserve in ReserveLastBinIDs

---

pkg/storer/epoch_migration.go

The migratePinning routine uses a single putOpStorage structure to specify the chunk location through pinningPutter.Put and back to putOpStorage's Write in order to properly invoke p.recovery.Add for that location.  Unfortunately, the mutex wasn't actually protecting the single structure, but allowed each of the 4 goroutines to clobber the location before it could get to sharky.
N/A
Migrating a node with pins from 1.16 to 1.17 ends up with incorrect chunk reference counts in Sharky resulting in invalid chunk content being read at some point in the future.
Note that this only fixes future pinning nodes that migrate.   Something else needs to be done to correct the sharky refCnt for nodes that have already migrated with active pins.

fix: protect pStorage.location in migratePinning

---

openapi/Swarm.yaml
pkg/api/feed.go
pkg/api/feed_test.go
pkg/feeds/epochs/epoch.go
pkg/feeds/epochs/finder.go
pkg/feeds/epochs/lookup_benchmark_test.go
pkg/feeds/getter.go
pkg/feeds/sequence/sequence.go
pkg/feeds/testing/lookup.go

Adds an `after` query param for `GET feed` that helps speed up the lookup.
Closes #4173

feat: add feed after index

---

cmd/bee/cmd/start.go

- [ x] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
Removed warning message which says to run Bee Clef so there are no longer logs like this suggesting to run Clef (which has been deprecated):
```
"time"="2023-08-17 07:48:53.313506" "level"="warning" "logger"="node" "msg"="clef is not enabled; portability and security of your keys is sub optimal"
```

fix: remove warning to run clef on startup

---

pkg/storer/internal/chunkstore/recovery_test.go
pkg/storer/internal/chunkstore/transaction.go
pkg/storer/migration/all_steps.go
pkg/storer/migration/all_steps_test.go
pkg/storer/migration/export_test.go
pkg/storer/migration/step_04.go
pkg/storer/migration/step_04_test.go
pkg/storer/storer.go
pkg/storer/storer_test.go

In the latest version we actually dont release the sharky locations properly. This was introduced with the txn recovery mechanism. In order to ensure the correct locations are referenced we will have to perform a new migration.

fix: sharky release in txn

---

cmd/bee/cmd/cmd.go
pkg/bzz/address.go
pkg/node/chain.go
pkg/node/devnode.go
pkg/node/node.go

Ranames "ethereum"/"eth" log and error strings to blockchain on order to minimize confusion reported here #3980 
Closes #3980

fix: raname ethereum and eth log and error strings to blockchain

---

pkg/postage/postagecontract/contract.go

…tract
Indicate the reason for the unsuccessful call of the postage contract.
Closes #3320

fix: include the reason when the postage contract call fails

---

pkg/api/rchash.go

Fixes the case where the rchash API is called with depth equal to `0`.
Closes  #4249

fix(api): allow 0 value for rchash depth

---

cmd/bee/cmd/cmd.go
pkg/node/node.go

This changes the `bee start` cmd default behavior to start the node in the ultra-light mode.
Closes 
#4114
#3756

feat: bee start cmd starts the node in the ultra-light mode

---

pkg/api/api.go
pkg/api/postage.go
pkg/api/pss.go
pkg/api/stewardship.go
pkg/postage/mock/service.go
pkg/postage/service.go
pkg/postage/service_test.go
pkg/postage/stamper.go
pkg/postage/stamper_test.go
pkg/postage/stampissuer_test.go

The stamp indexes are saved to disk after every upload session regardless of upload result.

fix: save stamps for all upload types regardless of any errors 

---

.github/patches/postage_api.patch
.github/workflows/beekeeper.yml
pkg/api/postage.go
pkg/api/postage_test.go

In order to improve batch utilization, the node now has a minimum depth requirement.
Closes ethersphere/bee-backlog#58

feat: introduce min bucket depth

---

cmd/bee/cmd/db.go
pkg/sharky/recovery.go
pkg/storer/compact.go
pkg/storer/compact_test.go
pkg/storer/internal/cache/cache.go
pkg/storer/internal/chunkstore/helpers.go
pkg/storer/migration/step_04.go
pkg/storer/reserve_test.go

Adds a compaction cmd to resize sharky to smallest size possible.
Also includes a before and after chunk validation step to verify chunks are moved around properly.
closes #3844

feat: db compaction cmd

---

pkg/storageincentives/soc_mine_test.go

TestSocMine dumps a sample made out SOCs to upload for storage incestives
dump chunks
```
go test -v ./pkg/storageincentives/ -run TestSocMine -count 1 > socs.txt
```
to generate uploads using the input
```
cat socs.txt | tail 19 | head 16 | perl -pne 's/([a-f0-9]+)\t([a-f0-9]+)\t([a-f0-9]+)\t([a-f0-9]+)/echo -n $4 | xxd -r -p | curl -X POST \"http:\/\/localhost:1633\/soc\/$1\/$2?sig=$3\" -H \"accept: application\/json, text\/plain, \/\" -H \"content-type: application\/octet-stream\" -H \"swarm-postage-batch-id: 14b26beca257e763609143c6b04c2c487f01a051798c535c2f542ce75a97c05f\" --data-binary \@-/'
```
it also serves as a sanity check showing the number of chunks it needed to find. 16 below the max value
```
soc_mine_test.go:133: LOG quit worker: 4, rounds: 355870, found: 3 …
```

 feat(storageincentives): test and utility to generate SOCs by mining ids for storage incentives phase 4 testing

---

pkg/pullsync/metrics.go
pkg/pullsync/pullsync.go
pkg/pullsync/pullsync_test.go
pkg/storer/mock/mockreserve.go

swallow errors produced by this bug #4337

fix(pullsync): swallow and log process want reserve get errs

---

pkg/postage/postagecontract/contract.go
pkg/storageincentives/agent.go
pkg/storageincentives/redistribution/redistribution.go
pkg/transaction/mock/transaction.go
pkg/transaction/transaction.go

Indicate the reason for the unsuccessful call of the redistribution contract.

fix: include the reason when the redistribution contract call fails

---

cmd/bee/cmd/db.go
pkg/cac/cac.go
pkg/sharky/recovery.go
pkg/sharky/shard.go
pkg/storer/compact.go

Log timestamp of invalid chunks.
It was discovered that multiple chunks were sharing the same sharky slot.
To log the chunk that took over the slot, we compute the chunk address using `cac.DoHash` and log relevant info of the chunk if the retrieval index item can be retrieved.

feat(compact): log retrieval item data of invalid chunks

---

CODING.md

Introduction of updated logging guidelines.
Closes #4122

docs: introduce updated logging guidelines

---

go.mod
go.sum
pkg/pullsync/pullsync.go
pkg/retrieval/retrieval.go

This PR removes the need for topCtx variable that needs to creep into the goroutine that is created in the retrieval singleflight to preserve the tracing span. This is possible by upgrading the singleflight to the latest v0.4.0 release which preserves values between function calls, while keeping the same cancelation behaviour.
It is optional to wait for bee to support building with bee 1.21 and use context.WithoutCancel in the retrieval goroutine.
The side effect of the singleflight upgrade is the usage of type parameters to avoid runtime type casts.
General code improvement.

chore: remove retrieval ctx scope leak

---

pkg/postage/stamp.go
pkg/postage/stamp_test.go
pkg/storer/sample.go

```
"time"="2023-09-29 17:19:18.849686" "level"="error" "logger"="node" "msg"="failed to build bee node" "error"="storage incentives agent: failed decoding value json: cannot unmarshal object into Go struct field SampleItem.RoundData.Sa
mpleData.ReserveSampleItems.Stamp of type swarm.Stamp"
```

fix(postage): added postage stamps json marshaling

---

go.mod
go.sum

Update storage-incentives abi to `v0.6.0-rc8`.

chore: bump storage-incentives abi to v0.6.0-rc8

---

pkg/storer/internal/reserve/reserve.go
pkg/storer/metrics.go
pkg/storer/reserve.go

chore: added extra logging in reserve worker for invalid batches

---

pkg/node/node.go
pkg/postage/service.go
pkg/postage/service_test.go

Moves the postage logger under the node logger tree.

fix: move the postage logger under the node logger tree

---

pkg/node/chain.go
pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

Enriches transaction service logs to always have the sender address included.
Closes #4357

refactor: enrich transaction service logs with sender address

---

pkg/postage/stampissuer_test.go

feat: stamp issuer utilization rate test

---

.github/workflows/go.yml
.golangci.yml
Dockerfile
go.mod
go.sum
pkg/encryption/encryption.go
pkg/skippeers/skippeers.go
pkg/storage/leveldbstore/recovery_test.go
pkg/storer/internal/chunkstore/recovery.go
pkg/storer/internal/chunkstore/recovery_test.go
pkg/storer/reserve.go
pkg/storer/uploadstore.go
pkg/topology/mock/mock.go

Go 1.21.0 is out so starting a PR to keep bee up to date.
Linked to #3927

chore: bump go version to 1.21.0

---

pkg/node/bootstrap.go
pkg/node/node.go
pkg/pushsync/pushsync.go
pkg/retrieval/retrieval.go
pkg/retrieval/retrieval_test.go

introduces a similar multiplexing mechanism as the pushsync one.
Peers that are one hop away from the neighborhood (and the neighbor peers) have extra retries to find the chunk.
closes https://github.com/ethersphere/bee-backlog/issues/67

feat(retrieval): multiplex into the neighborhood

---

go.mod
go.sum
pkg/hive/hive.go
pkg/hive/hive_test.go
pkg/node/bootstrap.go
pkg/node/node.go
pkg/p2p/libp2p/internal/reacher/reacher.go
pkg/p2p/libp2p/internal/reacher/reacher_test.go
pkg/spinlock/wait.go
pkg/topology/kademlia/export_test.go
pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go
pkg/topology/topology.go

* Reacher now periodically tests a peer's reachability, instead of doing it only once after the initial connection
* All of the neighbor peers are broadcasted to the neighbor after a connection
* Kademlia will prediocally (hive) broadcast to each neighbor about other neighbors
* Neighbor max connect attempt increased. 
* Hive will re-add a peer if the underlay has changed.

fix(kademlia, reacher): various connection fixes

---

pkg/node/node.go
pkg/postage/listener/listener.go
pkg/retrieval/retrieval.go
pkg/salud/salud.go
pkg/salud/salud_test.go

chore: extra batch listener log and salud tweaks

---

pkg/api/pin.go
pkg/api/pin_test.go

perf(pin_api): fetch chunks in parallel

---

pkg/api/bytes_test.go
pkg/api/bzz.go

The node should return 404 when no peers are found during retrieval
Closes #4374, closes #4340

fix: return 404 when no peers found during retrieval

---

cmd/bee/cmd/db.go
pkg/storer/compact.go
pkg/storer/validate.go

Support `db validate` as separate from the `--validate` option on `db compact`.  Moves the actual validation logic out of compact.go and into validate.go.
N/A
There are sharky stores in the wild that have corrupted hash chunks.  This makes it possible to do an in-place `validate` without the risks of the `compact`.
N/A
Sample output from this features on a database that has a bad chunk hash.
`./bee-amd64-v1.17.5-rc5-f5acd99c-dirty db validate --data-dir xdai5`
```
"time"="2023-10-28 18:53:01.285201" "level"="warning" "logger"="node" "msg"="Validation ensures that sharky returns a chunk that hashes to the expected reference."
"time"="2023-10-28 18:53:01.285249" "level"="warning" "logger"="node" "msg"="    Invalid chunks logged at Warning level."
"time"="2023-10-28 18:53:01.285252" …
```

feat: support db validate command

---

pkg/node/node.go
pkg/postage/batchstore/store.go
pkg/postage/interface.go
pkg/postage/mock/service.go
pkg/postage/service.go
pkg/postage/service_test.go
pkg/storer/cachestore.go
pkg/storer/cachestore_test.go
pkg/storer/internal/cache/cache.go
pkg/storer/internal/cache/cache_test.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/reserve.go
pkg/storer/storer.go
pkg/storer/storer_test.go

Includes various improvements to how the cache works.
The storer now has a cache worker that keeps track of the cache size and evicts as necessary.
This means that other cache ops do not need to remove any items before inserting entries.
In the postage service, the set expire func now removes all expired stamp issuers and stamp data.
Added new metrics to cachestore.

fix: cache and stamper store

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml
pkg/api/postage.go
pkg/api/postage_test.go
pkg/node/node.go
pkg/postage/batchstore/store.go
pkg/postage/batchstore/store_test.go
pkg/postage/interface.go
pkg/postage/mock/service.go
pkg/postage/service.go
pkg/postage/service_test.go
pkg/postage/stampissuer.go

closes #4438
When a batch is expired, the stamp issuer and stamp data are removed immediately.

fix: remove stamp data on expiration, not on node start up and API changes

---

pkg/api/postage.go
pkg/api/postage_test.go
pkg/api/router.go
pkg/postage/mock/service.go

For older stamps that have not been removed because postage resyncing has not taken place, the API must check the existence of the issuer as well as the batch.

fix(postage_api): check if batch exists for stamp issuer

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
pkg/api/bzz.go

Adds `Swarm-Cache` header (default = `true`) to cache/not-cache downloaded data.

feat: added swarm-cache header for download

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/peer.go
pkg/node/node.go
pkg/p2p/libp2p/peer.go
pkg/p2p/p2p.go

This PR is adding the underlay address from the addressbook and and sets connections field as it is useful to get the information about the established connections.
TODO
More precise debugging information.

feat(api): serve underlay and connections in /peers response

---

pkg/storer/internal/upload/uploadstore.go

Return `errOverwriteOfNewerBatch` only when the timestamp of the existing stamp index is actually newer (strictly greater) than that of the chunk to store 
Closes #4460

fix: overwrite existing stampindex if they have the same timestamp

---

go.mod
go.sum

Bumps storage-incentives abi to v0.6.0-rc16 which introduces phase 4.

chore: bump storage-incentives abi to v0.6.0-rc16

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/split.go
cmd/bee/cmd/split_test.go
pkg/api/api.go
pkg/api/export_test.go

A command that outputs a list of all chunk hashes for an input file
`bee split --input-file x --output-file y`
#4475

feat: split cmd

---

openapi/Swarm.yaml
pkg/api/chunk.go

Adds an optional `Swarm-Cache` header to `GET /chunks/{address}` endpoint that enables/disables local caching of downloaded chunks.
#4475

feat: added swarm-cache header to chunks get handler

---

pkg/statestore/storeadapter/migration.go
pkg/storer/internal/reserve/reserve.go

1. Properly resets the batchstore.
2. Sets a new minimum storage radius threshold.

fix: patch fix for batchstore reset and storage radius

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
pkg/config/chain.go

Replaces fixed network IDs (for mainnet and testnet) with IDs imported from the ABI as the single source of truth.

fix: replace fixed network IDs with those imported from ABI

---

pkg/storer/compact.go

Changes:
- check for DB items before compacting
Steps:
1. `mv ~/.bee ~/.bee.bak`
2. `bee start`
3. `CTRL+C`
4.  `bee db compact --data-dir=~/.bee/`
Result:
```
"time"="2023-12-01 13:04:56.120772" "level"="info" "logger"="node" "msg"="starting compaction"
panic: runtime error: index out of range [-1]
goroutine 1 [running]:
github.com/ethersphere/bee/pkg/storer.Compact({0x1abfa40?, 0x2777be0}, {0xc0004e8588, 0x11}, 0x4?, 0x0)
github.com/ethersphere/bee/pkg/storer/compact.go:77 +0x107a
github.com/ethersphere/bee/cmd/bee/cmd.dbCompactCmd.func1(0xc0001b3d00?, {0x1500ebe?, 0x4?, 0x1500dc2?})
github.com/ethersphere/bee/cmd/bee/cmd/db.go:149 +0x5d8
github.com/spf13/cobra.(*Command).execute(0xc00016a280, {0xc0004f9b40, 0x1, 0x1})
github.com/spf13/cobra@v1.5.0/command.go:872 +0x6aa …
```

fix: prevent a panic on an empty db compact

---

packaging/bee.yaml
packaging/docker/env
packaging/homebrew-amd64/bee.yaml
packaging/homebrew-arm64/bee.yaml
packaging/scoop/bee.yaml

Changes:
- align config templates with defaults for `swap-enable`
Regression from:
- https://github.com/ethersphere/bee/commit/ca786462d244ff2fa4f22bf17c1642344a197082
- https://github.com/ethersphere/bee/pull/4326

docs: align config templates with defaults for swap-enable

---

openapi/Swarm.yaml

The "/soc/{owner}/{id}" endpoint requires a request body. It's not indicated in the Swagger doc.
https://github.com/ethersphere/bee/issues/3761

fix: add missing request body to /soc endpoint openapi spec [3761]

---

cmd/bee/cmd/start.go

Fixes https://github.com/ethersphere/bee/issues/4262.
Currently, when starting a node with a default config, it asks for a new lib2p2 password each time, even when theres already one set.
Changes:
- take the libp2p PK filename from 1 source for both writes and reads
- `make format`

fix: ask for a new libp2p password only once

---

pkg/puller/puller.go

Adds a token bucket limiter to make sure the puller is rate limited to some degree.

feat(puller): limiter

---

pkg/node/node.go
pkg/storer/compact_test.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go

fix: lower radius with respect to reserve size within radius

---

go.mod
go.sum
pkg/api/pss_test.go
pkg/crypto/crypto.go
pkg/crypto/dh_test.go
pkg/crypto/signer.go
pkg/keystore/file/key.go
pkg/pss/trojan.go

This PR bumps the btcd version that fixes the "btcd mishandles witness size checking" vulnerability: https://github.com/ethersphere/bee/security/dependabot/21

chore: bump btcd to version v2

---

pkg/file/redundancy/getter/getter_test.go
pkg/replicas/replicas.go
pkg/soc/validator.go
pkg/soc/validator_test.go
pkg/swarm/swarm.go

Dispersed Replica SOC validation in order to prevent attack.

feat: dispersed replica validation

---

pkg/crypto/crypto_test.go

added 4 test cases under `TestNewOverlayFromEthereumAddress`  to test `NewOverlayFromEthereumAddress` of crypto library

chore: add tests for NewOverlayFromEthereumAddress method

---

pkg/api/bytes.go
pkg/api/bzz.go
pkg/api/dirs.go
pkg/api/router.go
pkg/node/node.go
pkg/pusher/pusher.go
pkg/pushsync/pushsync.go
pkg/retrieval/retrieval.go
pkg/storer/netstore.go
pkg/storer/storer.go
pkg/tracing/tracing.go

fix: tracing for pushsync and retrieval

---

pkg/replicas/getter.go
pkg/replicas/getter_test.go

We seem to be doing error unwrapping by hand when there is a convenient method provided.

fix: redundant error unwrap method

---

pkg/api/bzz_test.go
pkg/file/joiner/joiner_test.go
pkg/replicas/getter.go
pkg/replicas/getter_test.go

Running sub-tests in parallel to not hit the timeout: https://github.com/ethersphere/bee/actions/runs/7471805050/job/20377396685?pr=4529.

fix: slow redundancy test

---

pkg/storer/compact_test.go
pkg/storer/epoch_migration.go
pkg/storer/epoch_migration_test.go
pkg/storer/internal/chunkstamp/chunkstamp.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go

fix(reserve): evict just enough chunks to reach the capacity

---

pkg/api/api.go
pkg/api/stewardship.go
pkg/statestore/storeadapter/migration.go
pkg/storageincentives/proof_test.go
pkg/storer/internal/reserve/reserve.go

The reserve will now overwrite the index in the case of a collision regardless of the batch is immutable or not.
Because collision overwrite is permitted for all batch types, saving the incremented stamp indexes should be delayed until after a successful upload.

fix(reserve): force overwrite index on collion

---

pkg/storer/internal/pinning/export_test.go
pkg/storer/internal/pinning/pinning.go
pkg/storer/internal/pinning/pinning_test.go
pkg/storer/pinstore_test.go
pkg/storer/storer_test.go

fix(pinning): check before writing root address

---

pkg/postage/stamper.go
pkg/postage/stamper_test.go
pkg/postage/stampissuer.go

feat: stamper fixes

---

pkg/storer/debug.go
pkg/storer/internal/upload/uploadstore.go
pkg/storer/internal/upload/uploadstore_test.go
pkg/storer/migration/all_steps.go
pkg/storer/migration/export_test.go
pkg/storer/migration/step_05.go
pkg/storer/migration/step_05_test.go

1. Remove stamp index check from `uploadPutter.Put`
2. Delete all associated uploadItems after close
Closes #4541

fix: upload store fixes

---

pkg/storage/inmemchunkstore/inmemchunkstore.go
pkg/storage/storagetest/chunkstore.go
pkg/storageincentives/proof_test.go
pkg/storer/internal/cache/cache.go
pkg/storer/internal/cache/cache_test.go

fix(cache): deference already cached chunk during shallow copy

---

pkg/storer/internal/cache/cache.go

Add a mutex lock after the iterator in the RemoveOldest func.

fix(cache): missing chunk

---

pkg/postage/service.go
pkg/postage/stamper.go
pkg/postage/stampissuer.go

Previous lock would only protect against data races within the same upload session, not against parallel upload sessions, using the same batch.

fix(stamper): global lock stamper across multiple upload sessions

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
pkg/node/node.go
pkg/util/nbhdutil/neighborhoodsuggestion.go
pkg/util/nbhdutil/neighborhoodsuggestion_test.go

Adds a neighborhood suggester config option
closes #4577

feat: neighborhood suggester config

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/integritycheck.go
pkg/api/integritycheck_test.go
pkg/api/router.go
pkg/node/node.go
pkg/storer/storer.go
pkg/storer/validate.go

This is a new debug API endpoint that performs the same validation as the pin integrity check command line tool: https://hackmd.io/@F-mGf2lBSoGylLGQE6rRkA/ByVp6Ac9p
To trigger chunk validation for all pins: send an http get request to `/check/pin`, if you want to limit to a specific reference add a query parameter:
```sh
curl -v -XGET "localhost:1635/check/pin?ref=0874f94e9009628a70247c7b77f9034c8729c38d153a9fa42058bf5c7b341495"
```
The data will be flushed periodically and is `.jq` friendly: `jq 'select(.invalid>0) | .ref' out.json`
The background job is responsive to interruptions if you want to stop the pin validation process.
Because the validation process is disk bound it's not desirable to trigger it on a busy instance (while downloading/uploading).
Closes: #4566

feat: pinned reference integrity check API

---

pkg/file/joiner/joiner.go
pkg/file/redundancy/getter/getter.go
pkg/file/redundancy/getter/strategies.go

fix(redundancy): on by default when downloading

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml

fix: add missing openapi spec

---

openapi/Swarm.yaml
pkg/api/bytes.go
pkg/api/bzz.go
pkg/api/bzz_test.go
pkg/api/cors_test.go
pkg/api/router.go
pkg/api/subdomain.go
pkg/auth/auth.go

feat: bzz resource info API

---

.github/workflows/beekeeper.yml
pkg/api/chunk.go
pkg/api/router.go
pkg/soc/soc_test.go

feat: redundancy ci

---

cmd/bee/cmd/split.go
cmd/bee/cmd/split_test.go

Split input file to chunks. Refactored the cmd to 2 subcommands
- `refs`: outputs only list of refs to file: 
```
bee split refs --input-file random.txt --output-file output.txt
```
- `chunks` ouptuts chunks to directory:  
```
bee split chunks --input-file random.txt --output-dir ./chunks --r-level 4
```
`--r-level` specifies the redundancy level. It's optional. Default is 0.
closes #4599

feat: split input file to chunks with specified redundancy

---

pkg/api/bzz.go
pkg/api/bzz_test.go
pkg/file/joiner/joiner.go
pkg/file/joiner/joiner_test.go
pkg/file/redundancy/getter/getter.go
pkg/file/redundancy/getter/getter_test.go
pkg/file/redundancy/getter/strategies.go

1. When enough chunks are fetched for the recovery to run, inflight fetches are canceled.
2. strategy-timeout config option is removed
3. if recovery fails, the getter is removed completely from the cached getters so that a new attempt to fetch at the same position may retry the recovery with a new getter.

perf(getter): cancel inflight requests if enough chunks are fetched for recovery

---

pkg/api/dirs.go
pkg/api/dirs_test.go

We are doing checks on `Content-Type` or `Content-Length` when iterating folders, checks that are not aligned with http RFCs.
As a result bee returns status code `500` although it should accept the payload.
Closes: #4464

fix: store dir error info

---

pkg/api/bzz_test.go
pkg/api/metrics.go
pkg/file/joiner/joiner.go
pkg/file/redundancy/getter/getter.go
pkg/file/redundancy/getter/getter_test.go

1. removed close call
2. remove ctx in the struct antipattern
3. inflight requests are canceled when recovery is initialized.
4. the joiner does not construct a redundancy getter when fallback mode is false and the strategy is none.

fix(getter): redundancy getter cleanup

---

pkg/storer/internal/pinning/export_test.go
pkg/storer/internal/pinning/pinning.go
pkg/storer/uploadstore.go
pkg/storer/uploadstore_test.go

Fix error when uploading the same file with pinning multiple times.
fixes #4630

fix: duplicate pin

---

cmd/bee/cmd/configurateoptions.go

Return error when an invalid config is encountered instead of panicking 
e.g 
```
> bee printconfig 
...
...
full-node: true
help: false
Error: invalid-config is not a valid flag
``` 
closes #4646

fix: panic on printconfig

---

pkg/bmt/proof.go
pkg/storageincentives/proof_test.go
pkg/storageincentives/testdata/inclusion-proofs.json
pkg/storer/sample.go

Data race appeared by referencing some elements of the buffer of the bmt pool in the `bmt.Prover.Proof` method.
it may resolve inclusion proof related errors as well in the redistribution game.
Other corrections have been made in  `TestMakeInclusionProofsRegression` which is not flaky anymore.
fixes: #4531

fix: proof data race

---

CODINGSTYLE.md

Small change to the look and feel in the coding style document.

fix: proper display of go code in codingstyle doc

---

pkg/pullsync/pullsync.go
pkg/storer/migration/reserveRepair.go

For error checking before/after running the reserve repair, we should be checking batchRadiusItem instead of chunkBinItem .

fix: check chunkBinItem during reserve repair

---

pkg/node/node.go

Fix panic when `/redistributionstate` was called on the main API because the redistribution agent was not set.
```
"time"="2024-05-15 13:38:01.362418" "level"="error" "logger"="node" "msg"="http: panic serving 10.3.3.68:33706: runtime error: invalid memory address or nil pointer dereference
goroutine 949893580 [running]:
net/http.(*conn).serve.func1()
net/http/server.go:1868 +0xb9
panic({0x13b40c0?, 0x246ef20?})
runtime/panic.go:920 +0x270
github.com/ethersphere/bee/v2/pkg/storageincentives.(*Agent).Status(...)
github.com/ethersphere/bee/v2/pkg/storageincentives/agent.go:554
github.com/ethersphere/bee/v2/pkg/api.(*Service).redistributionStatusHandler(0xc000202a80, {0x1a36bc0, 0xc007e82320}, 0xc007d03100)
github.com/ethersphere/bee/v2/pkg/api/redistribution.go:42 +0xda …
```

fix: apiservice

---

go.mod
go.sum

Bumps google.golang.org/protobuf from 1.30.0 to 1.33.0.

chore: bump protobuf version to 1.33.0 (#4613)

---

pkg/api/api.go

We were not saving the stamp issuer batch indexes after a failed upload.

fix: save stamp issuer after failed uploads

---

go.mod
go.sum
openapi/SwarmCommon.yaml
openapi/SwarmDebug.yaml
pkg/api/router.go
pkg/retrieval/retrieval.go

Updates OpenAPI version and improves logging.
Updated mainnet contract address.

chore: pre-release updates

---

pkg/pushsync/pushsync.go

If `maxMultipleForwards` is set to zero, pushsync is completely disabled.   This is not good.
Ensure that future coders don't run into this unintended issue if they set this to zero.
#4681

fix: allow maxMultiplexForwards to be set to zero

---

openapi/SwarmCommon.yaml
pkg/api/redistribution.go
pkg/api/status.go
pkg/api/status_test.go
pkg/status/status.go
pkg/status/status_test.go

fix: several api fixes

---

pkg/puller/puller.go
pkg/storer/migration/reserveRepair.go

chore: more repair cmd logs

---

pkg/api/bytes.go
pkg/api/bzz.go
pkg/file/pipeline/hashtrie/hashtrie_test.go
pkg/replicas/putter.go
pkg/replicas/putter_test.go

fix: redundancy root push

---

cmd/bee/cmd/db.go
pkg/node/devnode.go
pkg/node/node.go
pkg/node/statestore.go
pkg/statestore/storeadapter/storeadapter.go
pkg/storage/statestore.go
pkg/topology/kademlia/kademlia.go
pkg/util/ioutil/ioutil.go

Allowing the overlay address mining even when nonce exists. That case, `localstore` and `kademlia-metrics` folders will be removed and `statestore` will be cleared to start a clean state in the new neighborhood. Before the wipe, 10 seconds wait time allows the user to change their mind.

feat: mine new overlay

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
pkg/api/api.go
pkg/api/chunk.go
pkg/api/chunk_test.go
pkg/api/soc.go
pkg/api/soc_test.go
pkg/postage/stamper.go
pkg/postage/testing/stamp.go

Introducing `Swarm-Postage-Stamp` header on `/chunk` and `/soc` POST endpoints.
It allows to push chunk to the Swarm network with pre-signed postage stamp on the attached chunk by the Bee client.
The header value must be a valid Postage Stamp otherwise error 400 has been thrown.
It means that the stamp is signed against the attached chunk and the signature is created by its on-chain owner.
A correct Postage Stamp value is 113 bytes encoded as hex string and consists of:
- :32 - ID of the batch
- 32:40 - index
- 40:48 - timestamp
- 48: - signature
Closes #2905

feat: pre-signed chunks

---

pkg/node/node.go
pkg/storageincentives/staking/contract.go
pkg/storageincentives/staking/contract_test.go
pkg/storageincentives/staking/mock/contract.go

Change overlay address in staking contract if new overlay address has been mined. 
Continuation of #4685

feat: change staking overlay

---

pkg/salud/salud.go

Issue is described in [salud IsHealthy using wrong radius](https://github.com/ethersphere/bee/issues/4697)
Node radius has to be compared only with network radius because this is the only way of certainty, the only source of truth. Comparing node radius to neighbourhood radius could lead to issues and also to attacks from bad intended actors  in that neighbourhood. 
Hopefully the change is a solution to the particular case from the above issue.

fix: improve the way a node is healthy based on network radius

---

cmd/bee/cmd/cmd.go
cmd/bee/cmd/start.go
pkg/node/node.go
pkg/postage/postagecontract/contract.go
pkg/postage/postagecontract/contract_test.go
pkg/storageincentives/redistribution/redistribution.go
pkg/storageincentives/redistribution/redistribution_test.go
pkg/storageincentives/staking/contract.go
pkg/storageincentives/staking/contract_test.go
pkg/transaction/transaction.go

Introduces a new flag that overrides the `EstimateGas` step for contract transactions.

feat: transaction debug mode

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
pkg/api/envelope.go
pkg/api/envelope_test.go
pkg/api/router.go

Introducing `/envelope` POST endpoint for issuing postage stamp signature on an arbitrary chunk address.
Closes #4713

feat: envelope

---

pkg/file/joiner/joiner_test.go
pkg/storer/mock/forgetting.go

Fail 1: 
```
--- FAIL: TestJoinerRedundancy (0.00s)
--- FAIL: TestJoinerRedundancy/redundancy=2_encryption=false (0.19s)
--- FAIL: TestJoinerRedundancy/redundancy=2_encryption=false/recover_from_replica_if_root_deleted (0.01s)
joiner_test.go:1147: unexpected error reading chunkdata at chunk position 107: expected <nil>. got storage: not found
```
Fail 2:
```
--- FAIL: TestJoinerRedundancyMultilevel (0.00s)
--- FAIL: TestJoinerRedundancyMultilevel/rLevel=1 (8.60s)
--- FAIL: TestJoinerRedundancyMultilevel/rLevel=1/encrypt=true_levels=2_chunks=3481_full (2.54s)
--- FAIL: TestJoinerRedundancyMultilevel/rLevel=1/encrypt=true_levels=2_chunks=3481_full/DATA_w_fallback_CAN_retrieve (0.00s)
joiner_test.go:1280: storage: not found
--- FAIL: …
```

fix: TestJoinerRedundancy failing flaky test 

---

pkg/storer/internal/reserve/olditems.go
pkg/storer/internal/stampindex/export_test.go
pkg/storer/internal/stampindex/oldstampindex.go
pkg/storer/internal/stampindex/stampindex.go
pkg/storer/internal/stampindex/stampindex_test.go
pkg/storer/migration/reserveRepair.go
pkg/storer/migration/reserveRepair_test.go
pkg/storer/migration/step_06.go
pkg/storer/migration/step_06_test.go

Previous stamp hash migration took ~30 mins to migrate a reserve size of 3.5m chunks.
This iteration takes ~7mins
```
"time"="2024-07-24 22:38:55.579963" "level"="info" "logger"="migration-step-06" "msg"="start adding stampHash to BatchRadiusItems, ChunkBinItems and StampIndexItems"
"time"="2024-07-24 22:39:55.580311" "level"="info" "logger"="migration-step-06" "msg"="still migrating items..."
...
"time"="2024-07-24 22:45:16.067493" "level"="info" "logger"="migration-step-06" "msg"="finished migrating items" "seen"=3426797 "migrated"=3426797
```

feat: stamp hash migration perf

---

pkg/steward/steward.go

[Issue](https://github.com/ethersphere/bee/issues/4696)

fix: stewardship api doesn't check final leaves

---

pkg/topology/kademlia/export_test.go
pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

Terminology and wording around the peer filtering is confusing. This PR aims to clear it up a bit more.
Adds a new regression test that checks that the pruning process counts peers correctly.

fix(kademlia): confusing filters operations renamed and extra regression test

---

pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

opt(kademlia): prune periodically

---

pkg/node/node.go
pkg/pusher/metrics.go
pkg/pusher/pusher.go
pkg/pusher/pusher_test.go
pkg/pushsync/metrics.go
pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go
pkg/retrieval/retrieval.go
pkg/skippeers/skippeers.go
pkg/storer/netstore.go
pkg/storer/netstore_test.go

closes #4683
closes #4680 
Read the above issues for more details.
Before this change, the pushsync would add every attempted peer to global skiplist because in the event that the pusher deems a receipt as shallow, in the next attempt to pushsync again, the same peer won't be tried.
Now, pushsync only adds peers to the global skiplist on error. Since a shallow receipt is an error, pushsync will check the receipt for shallowness, and will add the peer to the skiplist and return the error back to the pusher. The pusher then retries again. What this resolves is that if the same chunk arrives from a different upload request, since the skiplist wont now contain successful paths, the same path to the storer node will be tried again for chunks with good receipts.
Another change is that the …

fix: shallow receipt check moved to pushsync

---

pkg/file/joiner/joiner_test.go
pkg/soc/testing/soc.go
pkg/storage/chunkstore.go
pkg/storage/inmemchunkstore/inmemchunkstore.go
pkg/storer/internal/chunkstamp/chunkstamp.go
pkg/storer/internal/chunkstore/chunkstore.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/internal/stampindex/stampindex.go
pkg/storer/internal/transaction/transaction.go

Override chunk with the same address.
When we attempt to delete the chunk, the delete operation is appended to the current batch. However, since this [Get](https://github.com/ethersphere/bee/blob/master/pkg/storer/internal/chunkstore/chunkstore.go#L77) reads from disk, it returns the old `refCnt`. So it ignores the new chunk.
To fix this, we introduce a new `replace` method that does not relly on `refCnt`.
#4739

fix: override same chunk

---

pkg/api/staking.go

Update `txHash` json field in `stakeTransactionReponse` to be consistent with other tx hashes in the openAPI docs.

fix: json field in stakeTransactionReponse

---

pkg/pullsync/metrics.go
pkg/pullsync/pullsync.go

Adding Offer and Want metrics on the handler side of pullsync to match the ones already available on the client side of the protocol.
N/A
With only "Sent" metrics on the handler side, you cannot see the peer-generated load of offering chunks via pullsync.
N/A

feat: additional pullsync handler metrics

---

pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/migration/step_06.go
pkg/storer/migration/step_06_test.go

chore(reserve): comments and rewording and final migration check

---

.github/workflows/beekeeper.yml
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go

Reduce the reserve count when putting the same address chunk that has an index collision with a different chunk

fix: reduce reserve cnt on same chunk and index collision

---

.github/workflows/beekeeper.yml
openapi/Swarm.yaml
openapi/SwarmCommon.yaml
pkg/api/export_test.go
pkg/api/staking.go
pkg/api/staking_test.go
pkg/node/devnode.go
pkg/storageincentives/staking/contract.go
pkg/storageincentives/staking/contract_test.go
pkg/storageincentives/staking/mock/contract.go

Rename only the response for 'withdrawablestake' api

fix: rename only withdrawable stake response

---

pkg/hive/hive.go
pkg/puller/puller.go
pkg/pullsync/pullsync.go
pkg/ratelimit/ratelimit.go
pkg/ratelimit/ratelimit_test.go
pkg/storer/reserve.go

Added a basic rate limiter to pullsync handler.

feat(pullsync): rate limit handler

---

pkg/pullsync/pullsync.go
pkg/storer/migration/step_06.go
pkg/storer/migration/step_06_test.go

fix: move pullsync rate limiter and remove reserve epoch in migration

---

pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go

fix: reset epoch timestamp when the reserve is reset

---

pkg/pullsync/pullsync.go

Fixes [4823](https://github.com/ethersphere/bee/issues/4823)

fix: adapt comment to corresponding used value

---

pkg/api/transaction.go
pkg/postage/listener/listener.go
pkg/topology/kademlia/kademlia.go

note that i did not compile the code, because i don't have a go devenv set up.
the log is very noisy at the default (info) level, and arguably with useless information unless someone wants to debug bee's behavior. but the vast majority of the users are node operators, not developers.
more some `info` log entries to the `debug` level.
smaller disk usage, and more readable log on `info` level.
https://github.com/ethersphere/bee/issues/4824

chore: reduce log noise at default level (#4824)

---

pkg/transaction/transaction.go
pkg/transaction/transaction_test.go

**WARNING:** i'm not experienced in golang, and i don't know the bee internals either. this commit requires review by someone who understands the codebase.
Stop keeping the next nonce in our local state. Instead we always calculate it from the blockchain nonce and the local list of pending transactions.
Fixes issue [#4826](https://github.com/ethersphere/bee/issues/4826) where the local nonce cache was out of sync with the blockchain for an unknown reason. Because of that no transactions got incorporated into the blockchain. This made it impossible to unstake or to participation in the reserve incentives, probably forever (until fixed).
It only became apparent when i tried to unstake my nodes at the v2.2.0 upgrade, and some of them got stuck. It also explains why i stopped seeing rewards …

fix: Eliminate local transaction nonce cache.

---

openapi/SwarmCommon.yaml
pkg/api/api.go
pkg/api/status.go
pkg/status/status.go
pkg/status/status_test.go
pkg/storer/migration/all_steps.go
pkg/storer/migration/all_steps_test.go
pkg/storer/migration/refCntSize.go
pkg/storer/migration/refCntSize_test.go
pkg/storer/migration/step_04.go
pkg/storer/migration/step_04_test.go
pkg/storer/migration/step_05.go
pkg/storer/migration/step_05_test.go
pkg/storer/migration/step_06.go
pkg/storer/migration/step_06_test.go
pkg/storer/mock/mockstorer.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go
pkg/storer/storer_test.go
pkg/swarm/swarm.go
pkg/swarm/swarm_test.go

fix: new neighborhood type and cleanup

---

openapi/Swarm.yaml
openapi/SwarmCommon.yaml
pkg/api/api.go
pkg/api/router.go
pkg/api/status.go
pkg/api/status_test.go
pkg/status/status.go
pkg/status/status_test.go
pkg/storer/migration/all_steps.go
pkg/storer/migration/all_steps_test.go
pkg/storer/migration/refCntSize.go
pkg/storer/migration/refCntSize_test.go
pkg/storer/migration/step_04.go
pkg/storer/migration/step_04_test.go
pkg/storer/migration/step_05.go
pkg/storer/migration/step_05_test.go
pkg/storer/migration/step_06.go
pkg/storer/migration/step_06_test.go
pkg/storer/mock/mockstorer.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go
pkg/storer/storer.go
pkg/storer/storer_test.go
pkg/swarm/swarm.go
pkg/swarm/swarm_test.go

Part 7 of [#4842](https://github.com/ethersphere/bee/issues/4842)

feat: add status neighborhoods endpoint

---

pkg/node/node.go
pkg/storageincentives/staking/contract.go
pkg/storageincentives/staking/contract_test.go
pkg/storageincentives/staking/mock/contract.go

feat(staking): change height on restart

---

pkg/transaction/monitor.go

Fixes [#4826](https://github.com/ethersphere/bee/issues/4826).
This is part two of the solution, provided by @janos . The issue investigation and solution are described in the above issue https://github.com/ethersphere/bee/issues/4826#issuecomment-2391045378.

fix: check all transactions in monitor check pending with timeout

---

pkg/node/node.go
pkg/storageincentives/staking/contract.go
pkg/storageincentives/staking/contract_test.go

Updates height in the staking contract if the height is changed (increase AND decrease).
Deposit stake returns with an error if the staked amount is not enough with respect to the height.

fix: update height if staked when height decreases

---

pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/libp2p.go

A peer did not update its `network availability` on an inbound connection. Hence, it was unable to perform a `blocklist` operation.
closes #4833

fix: blocklist

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/router.go
pkg/api/router_test.go
pkg/jsonhttp/handlers.go
pkg/node/devnode.go
pkg/node/node.go

This PR addresses issue #4734 by improving the behavior of the Bee API during the node initialization process. Previously, when the node was syncing batch data, the API appeared to be inaccessible, providing no indication of the ongoing sync process. Now, all routes are mounted immediately, but some may be temporarily disabled during initialization, returning appropriate status codes.
- **503 Service Unavailable**: Routes that are disabled during the syncing phase now return a `503 Service Unavailable` status with the message:  
*"Node is syncing. This endpoint is unavailable. Try again later."*  
Once the syncing is complete, the routes will be enabled and respond normally.
- **501 Not Implemented**: If the `swapEnabled` or `chequebookEnabled` flags are set to `false`, routes that depend …

fix(api): add api initialization notice

---

pkg/storer/internal/reserve/reserve_test.go

Add case where a chunk c1, with same address as an existing one c2, is trying to replace another chunk c3 on the same batch index but c3 has a higher timestamp than c1.

test: add reserve case

---

pkg/api/status.go
pkg/postage/postagecontract/contract.go
pkg/storageincentives/staking/contract.go
pkg/storer/reserve.go
pkg/storer/reserve_test.go

approve transactions also rely on the estimator

fix: reserve returns proximity for neightborhood stats

---

pkg/soc/soc.go
pkg/soc/soc_test.go
pkg/storer/sample.go

Cpu profiling revealed that the unnecessary crypto recovery inside soc.FromChunk was the bottleneck.

perf: sampler optimization

---

go.mod
go.sum

security scans show:
OWASP Top Ten 2017 Category A9 - Using Components with Known Vulnerabilities
CVE-2022-29583	service	1.2.0

chore: update service package to mitigate CVE-2022-29583

---

pkg/file/joiner/joiner_test.go
pkg/storage/chunkstore.go
pkg/storage/inmemchunkstore/inmemchunkstore.go
pkg/storer/internal/chunkstamp/chunkstamp.go
pkg/storer/internal/chunkstamp/chunkstamp_test.go
pkg/storer/internal/chunkstore/chunkstore.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go
pkg/storer/internal/transaction/transaction.go

wrote a new reserve eviction test for SOCs.
fixed:
chunkstamp expects that the chunk address and batch id are unique entries
anywhere we use chunkstamp.LoadWithBatchID, we can't reliably tell it's the correct stamp
i wrote a unit test that uploads 10 gsoc chunks and the chunkstamp.LoadWithBatchID was an issue
the chunkstore.Replace is also supposed to increment the refCnt as each SOC creates a new reserve entry.
fixed index collision checks

fix: chunkstamp load with hash, replace to increase refCnt, new soc eviction unit test, index collision check changes

---

openapi/Swarm.yaml
pkg/api/accesscontrol_test.go
pkg/api/api_test.go
pkg/api/soc.go
pkg/api/soc_test.go
pkg/storer/internal/chunkstore/chunkstore_test.go
pkg/storer/mock/mockstorer.go

1. Disabling pinning in soc upload
2. Chunkstore replace unit tests
#4901

feat: chunkstore replace unit test & soc pinning

---

pkg/storer/internal/reserve/reserve_test.go
pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/internal/metrics/metrics_test.go
pkg/topology/kademlia/kademlia.go
pkg/topology/kademlia/kademlia_test.go

fix: exclude bootnode from protocol requests

---

pkg/topology/kademlia/internal/metrics/metrics.go
pkg/topology/kademlia/internal/metrics/metrics_test.go
pkg/topology/kademlia/kademlia.go

For fresh nodes, bootnodes are discovered and are excluded from any protocol requests. For older nodes, however, because there are other peers in the addressbook, it may not have to call `connectBootNodes` to discover peers from the network. The older node may also connect to the bootnode at some point because there will an entry for it in the addressbook without realizing that the peer is in fact a bootnode.  As a result, the node may accidently send protocol requests to the bootnode.
As such, it's important that on every start up, the node discovers the bootnodes to exclude the bootnodes from the protocol requests peer list.
We are also persisting which peers are bootnodes so that "always discover" part can be removed in the future.

fix(kademlia): always connect to bootnodes on startup to identify them

---

.golangci.yml
pkg/postage/batch_test.go
pkg/postage/batchservice/batchservice_test.go
pkg/postage/batchstore/mock/store_test.go
pkg/postage/batchstore/store_test.go
pkg/postage/listener/listener_test.go
pkg/postage/postagecontract/contract_test.go
pkg/postage/service_test.go
pkg/postage/stamp_test.go
pkg/postage/stamper_test.go
pkg/postage/stampissuer_test.go

Fixes [3831](https://github.com/ethersphere/bee/issues/3831)

fix: enable paralleltest lint check in package postage

---

pkg/p2p/libp2p/connections_test.go

unskip TestWithBlocklistStreams test which was alwats faukubg before.
- TestWithBlocklistStreams failure [#2787](https://github.com/ethersphere/bee/issues/2787)

test: unskip TestWithBlocklistStreams test

---

pkg/api/soc.go
pkg/settlement/swap/addressbook.go
pkg/storer/sample_test.go

fix some comments and method name

chore: fix some comments and method name

---

packaging/bee.yaml
packaging/docker/env
packaging/homebrew-amd64/bee.yaml
packaging/homebrew-arm64/bee.yaml
packaging/scoop/bee.yaml
pkg/api/bytes.go

docs: update bee configs

---

pkg/api/bzz.go
pkg/api/feed.go
pkg/feeds/getter.go

fix: feed wrap should download the wrapped chunk from the network

---

pkg/bmt/bmt.go
pkg/bmt/pool.go

Contains minor editorial fixes removing dead code within the `bmt` package.
N/A
Early spring cleaning of code :broom: 
#4942 
N/A

chore(bmt): remove dead code

---

pkg/api/pin_test.go
pkg/storer/internal/pinning/pinning.go
pkg/storer/internal/pinning/pinning_test.go

Ensures that `GET /pins` endpoint will now return empty array (`{"references":[]}`) instead of null (`{"references":null}`).
This change is important for consistency in API responses across different endpoints, ensuring that all endpoints return empty arrays instead of null when there are no items.
[GET /pins should return empty array instead of null when there are no items #4964](https://github.com/ethersphere/bee/issues/4964)

fix(api): return empty array for pins instead of null

---

cmd/bee/cmd/start.go

The block time for the testnet (Sepolia) has been updated to 12 seconds.
Sepolia's block time was previously 15 seconds but has since been changed to 12 seconds. The current implementation still reflects the outdated 15-second value. This update ensures that the correct 12-second block time is used going forward.
[Update Sepolia Testnet Block Time to 12 Seconds #4968
](https://github.com/ethersphere/bee/issues/4968)

fix(cmd): set sepolia block-time to 12s

---

pkg/api/api.go
pkg/api/api_test.go
pkg/api/bytes.go
pkg/api/bytes_test.go
pkg/api/bzz.go
pkg/api/bzz_test.go
pkg/api/chunk.go
pkg/api/dirs.go
pkg/api/feed.go
pkg/api/feed_test.go
pkg/api/soc.go
pkg/api/soc_test.go
pkg/api/util.go

…response header
- Replaced w.Header().Set with w.Header().Add to append headers rather than overwrite them.
- Corrected delimiter for Access-Control-Expose-Headers from `;` to `,` as per MDN documentation.
- Browser behavior: The semicolon delimiter (;) was causing issues, particularly in Chromium-based browsers. This was corrected by switching to a comma (,) delimiter for separating multiple header values.
- Header overwriting: The use of w.Header().Set was causing overwriting of Access-Control-Expose-Headers. Replacing it with w.Header().Add ensures headers are appended, resolving inconsistencies in the response headers.
[[2.4.0] Access-Control-Expose-Headers is overridden, breaking browser Swarm apps #4959](https://github.com/ethersphere/bee/issues/4959)

fix(api): resolve header overwriting and delimiter issue in Access-Control-Expose-Headers

---

pkg/api/chunk_stream.go

Do not use HTTP request context so that tags will be saved when `putter.Done` is called after the HTTP connection is upgraded to websocket.
closes #4858

fix: save tags when using chunk/stream

---

cmd/bee/cmd/split.go
cmd/bee/cmd/split_test.go

Sets the right redundancy level in context so the redundancy getter can use the correct r-level instead of defaulting to PARANDOID.

fix:  set level in ctx

---

openapi/SwarmCommon.yaml
pkg/api/p2p.go
pkg/api/p2p_test.go

This PR will add `chain_address` to `/addresses` response. The idea is to deprecate `ethereum` field in response of that endpoint.

fix(api): replace ethereum with chain_address in /addresses response

---

pkg/api/stewardship_test.go
pkg/file/joiner/joiner.go

When iterating over chunks, parity chunks were incorrectly attempted to be fetched from the redundancy getter, which only supports shards.
closes #4948

fix: stewardship with erasure encoding

---

openapi/Swarm.yaml

Update OpenAPI to use the correct response for `PATCH /tags/{uid}`
[OpenAPI PATCH /tags/{uid} wrong response type #4976](https://github.com/ethersphere/bee/issues/4976)

fix(openapi): correct response type for PATCH /tags/{uid}

---

openapi/Swarm.yaml

This PR will remove 2 tags from OpenAPI `/gsoc/subscribe/{address}` endpoint, and use only one. 
This will enable to show this endpoint only once.
[GSOC is triplicated in Bee API sidebar #4967](https://github.com/ethersphere/bee/issues/4967)

fix(openapi): leave only one tag for /gsoc/subscribe/{address}

---

packaging/docker/env

This environment variable is incorrect, as they must use underscores.
According to the [documentation](https://docs.ethswarm.org/docs/bee/working-with-bee/configuration/#environment-variables):
> All available configuration options are available as BEE prefixed, capitalised, and underscored environment variables, e.g. --api-addr becomes BEE_API_ADDR.

fix: rename BEE_RESERVE_CAPACITY_DOUBLING variable using underscores

---

pkg/pushsync/pushsync.go
pkg/retrieval/retrieval.go
pkg/skippeers/skippeers.go
pkg/skippeers/skippeers_test.go

Before, for each pushsync and retrieval, a separate skippeers list was created, along side it a worker that would prune entries based on a timer. Now, the worker is created once only for the errSkip peers list, and not for each request.

perf: remove unncessary goroutine pileup of skippeer workers

---

pkg/storer/cachestore.go
pkg/storer/internal/cache/cache.go
pkg/storer/internal/cache/export_test.go

Prevent cache size from underflowing
#4982

fix: prevent cache size underflow

---

pkg/traversal/traversal.go

Stewardship of `/byte` uploads was repeatedly retrieving the root chunk because it first attempts to load a manifest, which the upload is not.
To address this, we now iterate over manifest addresses only if the input reference is "likely" a manifest reference i.e The root chunk span is  small (less than swarm.ChunkSize)
#4977

fix: stewardship retrieving the same chunk multiple times

---

pkg/api/accesscontrol.go
pkg/api/bzz.go
pkg/api/dirs_test.go
pkg/api/feed_test.go
pkg/file/loadsave/loadsave.go
pkg/file/loadsave/loadsave_test.go
pkg/node/bootstrap.go
pkg/traversal/traversal.go

Since the read-only `loadsaver` didn't have a putter, the redundancy getter could not save recovered chunks.
This fixes that issue by providing a putter to the load saver. 
fixes #5001

fix: provide putter to loadsave

---

pkg/accounting/accounting.go
pkg/accounting/accounting_test.go

fix some function names in comment

chore: fix some function names in comment

---

pkg/storer/internal/upload/uploadstore.go

Some refactoring of the uploadstore and tag deletion.

refactor(uploadstore): cleanup of code around tag deletion

---

pkg/pullsync/pullsync.go
pkg/pushsync/pushsync.go

Log the source of gsoc handler (push or pull sync)

chore: log gsoc source

---

Dockerfile.dev
Makefile

Add support for build arguments (REACHABILITY_OVERRIDE_PUBLIC, BATCHFACTOR_OVERRIDE_PUBLIC) in Dockerfile and PLATFORM in Makefile.
`make docker-build` cmd when needed to build docker image with  REACHABILITY_OVERRIDE_PUBLIC and  BATCHFACTOR_OVERRIDE_PUBLIC flags, and in case when we are deploying cluster using `beelocal`

chore: add docker build arguments to Dockerfile.dev

---

pkg/api/accesscontrol.go
pkg/api/bytes.go
pkg/api/bzz.go
pkg/api/chunk.go
pkg/api/dirs.go
pkg/api/feed.go
pkg/api/soc.go

When uploading to any of the api endpoints the ACT relevant headers, i.e.: history address, are not added to the expose headers.
Adds the **SwarmActHistoryAddressHeader** to the **AccessControlExposeHeaders**, only if the **Swarm-Act** is set.
-
-
fixes #5023

fix: act expose headers

---

pkg/manifest/mantaray/marshal.go
pkg/manifest/mantaray/node.go
pkg/manifest/mantaray/persist.go
pkg/manifest/mantaray/persist_test.go

This PR fixes https://github.com/ethersphere/bee/issues/4808. Where loading a manifest then removing forks from it would not persist in the next load.

fix(manifest): resolve node persistence after removal

---

pkg/api/bzz.go
pkg/postage/interface.go
pkg/storer/metrics.go

chore: fix some struct field names

---

openapi/Swarm.yaml
pkg/settlement/swap/chequebook/init.go

This PR will change error msg for intial deposit to `insufficient xDAI for deploying chequebook`.
Also, it will fix openapi spec for `/stake` endpoint.
version: 7.4.0
[POST stake/:amount response type #5004](https://github.com/ethersphere/bee/issues/5004)
[Misleading chequebook init: insufficient xDAI for initial deposit error message #4924](https://github.com/ethersphere/bee/issues/4924)

fix: chequebook error msg and `/stake` openapi

---

go.mod
pkg/storer/internal/chunkstore/chunkstore.go

Since Go 1.21, the functions in x/exp used here can already be replaced by functions from the standard library.

refactor: replace golang.org/x/exp with stdlib

---

.github/workflows/release_triggers.yaml

remove deprecated bee-factory
replace deprecated set-output

chore: update release triggers

---

pkg/pushsync/pushsync.go
pkg/pushsync/pushsync_test.go

Forward a chunk to the closest peer after storing it

feat(pushsync): forward chunk after storing

---

pkg/api/metrics.go
pkg/p2p/libp2p/internal/reacher/metrics.go
pkg/postage/batchstore/metrics.go
pkg/puller/metrics.go
pkg/pushsync/metrics.go
pkg/storer/metrics.go
pkg/storer/storer.go

This PR fixes the issue where prometheus vector variables are concrete values that results in their own lock being copied making them unreliable.

fix: prometeus vector variables as pointers

---

pkg/storer/storer.go

Bump in background cache worker count caused memory spike

revert: defaultBgCacheWorkers from 128 to 32

---

cmd/bee/cmd/cmd.go
packaging/bee.yaml
packaging/homebrew-amd64/bee.yaml
packaging/homebrew-arm64/bee.yaml
packaging/scoop/bee.yaml

This is a small but important change for the P2P layer functionality. WebSockets P2P transport is enabled by default allowing the in-browser implementation to connect to peers in the network.
Before the release, the performance of the network should be measured in the testnet to ensure that no performance degradation is observed.

feat(libp2p): enable websockets transport by default

---

pkg/api/router_test.go
pkg/storer/netstore_test.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use slices.Contains to simplify code

---

cmd/bee/cmd/cmd.go
packaging/bee.yaml
packaging/homebrew-amd64/bee.yaml
packaging/homebrew-arm64/bee.yaml
packaging/scoop/bee.yaml

This reverts commit 9c0554636f315a071ce8fd17053053f936771d2c.
https://github.com/ethersphere/bee/pull/5101#issuecomment-2901490207

revert: "feat(libp2p): enable websockets transport by default (#5095)"

---

go.mod
pkg/pingpong/pingpong.go
pkg/salud/salud.go
pkg/storer/internal/stampindex/stampindex.go

Idea is to reduce the time that salud spends to update the peer status. This will help the light node spin time and readiness.

fix(salud): use exponential backoff for wake up of salud check

---

pkg/config/chain.go
pkg/node/chain.go
pkg/sctx/sctx.go
pkg/storageincentives/redistribution/redistribution.go
pkg/storageincentives/staking/contract.go
pkg/transaction/backend.go
pkg/transaction/backendmock/backend.go
pkg/transaction/transaction.go
pkg/transaction/transaction_test.go
pkg/transaction/wrapped/metrics.go
pkg/transaction/wrapped/wrapped.go

This PR refactors the gas cost estimation to be fully EIP-1559 compliant. The previous implementation relied on the outdated legacy SuggestGasPrice method, which provided inaccurate estimates for the required gas funds.
- `suggestedFeeAndTip` is modified
- This function calculates an estimated transaction cost by using the latest block's baseFee and a suggested tip (`SuggestGasTipCap`).
- the estimation uses a buffered baseFee plus the tip (`gasFeeCap = (2 * baseFee) + gasTipCap`)
- `SuggestGasPrice` is removed from `suggestedFeeAndTip`

fix(transaction): implement EIP-1559 compliant fee calculation

---

pkg/bigint/bigint.go
pkg/crypto/eip712/typeddata.go
pkg/crypto/signer.go
pkg/log/formatter_test.go
pkg/storageincentives/proof_test.go

Optimize code using a more modern writing style. Official support by Go Team. https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor: replace []byte(fmt.Sprintf) with fmt.Appendf

---

openapi/SwarmCommon.yaml
pkg/api/postage.go
pkg/api/postage_test.go
pkg/storer/mock/mockreserve.go
pkg/storer/mock/mockstorer.go
pkg/storer/reserve.go
pkg/storer/storer.go

Adds `reserveCapacityDoubling` to `/reservestate` response
closes #5126

feat: add reserveCapacityDoubling to /reservestate

---

pkg/file/pipeline/encryption/encryption_test.go
pkg/file/pipeline/feeder/feeder.go
pkg/pusher/pusher_test.go
pkg/pushsync/pushsync_test.go

make function comments match function names

chore: make function comments match function names

---

pkg/file/joiner/joiner_test.go
pkg/file/splitter/internal/job_test.go
pkg/p2p/libp2p/connections_test.go
pkg/p2p/libp2p/headers_test.go
pkg/p2p/libp2p/protocols_test.go
pkg/p2p/libp2p/tracing_test.go

Optimize code using a more modern writing style. Official support from Go Team. https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor: replace context.WithCancel with t.Context

---

pkg/node/metrics.go
pkg/node/node.go

default proposed buckets do not fit with current measurements.
Times measurements are collected from the new logs (0.5-7 mins warmup, ~2-3 hours pull sync) by which the buckets could be adjusted.

refactor: init metrics

---

pkg/bmt/benchmark_test.go
pkg/feeds/epochs/lookup_benchmark_test.go
pkg/feeds/sequence/lookup_benchmark_test.go
pkg/file/pipeline/builder/builder_test.go
pkg/file/splitter/splitter_test.go
pkg/pss/mining_test.go
pkg/storage/storagetest/benchmark.go
pkg/storage/storagetest/storage.go
pkg/topology/pslice/pslice_test.go

replace `for i := range b.N` or `for range b.N` in a benchmark with `for b.Loop()`, and remove any preceding calls to `b.StopTimer`,` b.StartTimer`, and `b.ResetTimer`.
Supported by Go Team, more info: https://go.dev/blog/testing-b-loop

refactor: use b.Loop() to simplify the code

---

pkg/storer/cachestore.go
pkg/storer/migration/refCntSize.go
pkg/storer/migration/reserveRepair.go
pkg/storer/reserve.go

use the built-in max/min to simplify the code
Inspired by https://github.com/ethersphere/bee/pull/5103

refactor: use the built-in max/min to simplify the code

---

pkg/storer/internal/pinning/pinning.go
pkg/storer/internal/reserve/reserve.go
pkg/storer/internal/reserve/reserve_test.go

The changes implemented comprehensive pin protection for chunk eviction by addressing a critical bug in the `EvictBatchBin` method.
The fix modified the `EvictBatchBin` method to properly check each chunk against all pin collections using the newly created `pinstore.IsChunkPinnedInCollection` function. When a pinned chunk is found, the eviction only removes reserve related records of that chunk. This ensures that non-pinned chunks can still be evicted while maintaining the integrity of pinned content.
Reserve capacity eviction is directly protected through the `EvictBatchBin` method. 
Batch expiry eviction is automatically protected because the entire flow from `EvictBatch` ultimately calls `EvictBatchBin`. 
Cache eviction was determined to not require pin protection because pinned chunks …

fix: pin eviction guard
