ethersphere/bee

- version.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2912)
> chore: bump version to v1.6.0

- pkg/chainsyncer/chainsyncer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2922)
> chore(chainsyncer): reinstate 24h blocking

- .github/workflows/stale.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2923)
> chore: update stale bot configuration

- cmd/bee/cmd/db.go
- pkg/localstore/localstore.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2924)
> feat(cmd): add db indices command

- pkg/accounting/accounting.go
- pkg/api/chunk_stream.go
- pkg/api/dirs.go
- pkg/api/pss_test.go
- pkg/api/tag.go
- pkg/bigint/bigint_test.go
- pkg/bitvector/bitvector_test.go
- pkg/debugapi/chequebook.go
- pkg/debugapi/transaction.go
- pkg/debugapi/welcome_message.go
- pkg/feeds/getter.go
- pkg/flipflop/falling_edge_test.go
- pkg/localstore/localstore.go
- pkg/localstore/migration_test.go
- pkg/netstore/netstore_test.go
- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/pullsync/pullsync.go
- pkg/settlement/swap/chequebook/init.go
- pkg/statestore/leveldb/migration_test.go
- pkg/topology/pslice/pslice_test.go
In some places we improperly format errors (by using `Errorf` without arguments).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2921)
> fix: improper error formatting

- pkg/postage/service.go
- pkg/postage/service_test.go
- pkg/statestore/leveldb/migration.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2914)
> fix: postage service initialization bug

- pkg/pushsync/pushsync.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2928)
> fix(pushsync): replace standard logger with trace logger

- pkg/node/node.go
- pkg/topology/kademlia/kademlia.go
In chain-less mode the topology depth is not updated, staying at 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2929)
> fix: add ignore radius flag

- pkg/node/devnode.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2945)
> fix: devmode postage amount bug

- pkg/sharky/shard.go
- pkg/sharky/store.go
I missed the fact that the context error must be emitted to the reader of the channel with the last fix around the context cancellation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2948)
fixed #2943
> fix(sharky): emit error on context cancelation

- pkg/debugapi/postage.go
- pkg/node/devnode.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2949)
> fix: devmode batch ttl wrong response

- version.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2954)
> chore: bump v1.6.1

- .goreleaser.yml
- packaging/bee-get-addr
- packaging/deb/postinst
- packaging/homebrew-amd64/bee-get-addr
- packaging/homebrew-arm64/bee-get-addr
- packaging/rpm/post
https://github.com/ethersphere/bee/issues/2935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2967)
> chore: update package post install messages

- pkg/accounting/accounting.go
- pkg/accounting/metrics.go
- pkg/settlement/pseudosettle/pseudosettle.go
Extra metrics for accounting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2966)
> feat: accounting metrics

- pkg/postage/batchstore/metrics.go
- pkg/postage/batchstore/reserve.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2984)
> chore(batchstore): commitment metric

- go.mod
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bzz.go
- pkg/api/router.go
- pkg/api/subdomain.go
- pkg/api/subdomain_test.go
- pkg/logging/httpaccess/http_access.go
- pkg/node/node.go
- pkg/resolver/cidv1/cidv1.go
- pkg/resolver/cidv1/cidv1_test.go
- pkg/resolver/multiresolver/multiresolver.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2970)
> feat(api): subdomain support

- pkg/topology/kademlia/export_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2971)
> fix(kademlia): increase bit suffix length to improve bin population

- pkg/feeds/sequence/sequence.go
- [] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md)
- [] My change requires a documentation update and I have done it
- [] I have added tests to cover my changes.
I fix it the comment.
Comment was not accurate.
No dependencies were harmed in the creation of this commit.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2915)
> fix:sequence comment

- pkg/node/bootstrap.go
- pkg/postage/batchstore/reserve.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2997)
> feat: bootstrapper more resilient with retries

- .github/workflows/beekeeper.yml
This PR adds trigger for Bee Factory to create `latest` images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3002)
> ci: bee factory latest builds

- openapi/Swarm.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3003)
> docs: note about presence of debug endpoints in normal api

- pkg/api/router.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3007)
> fix: move readiness endpoint to technical debug

- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/p2p/libp2p/libp2p.go
- pkg/topology/kademlia/kademlia.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3010)
Closes https://github.com/ethersphere/bee/issues/2982
> refactor: reduce info logs

- pkg/topology/kademlia/export_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/2996)
> fix(kademlia): saturation peers count cleanup

- pkg/api/router.go
Fixes missing `/tags/{id}` debug endpoint.
Closes #3029
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3030)
> fix: add back tags endpoint

- pkg/api/api.go
- pkg/api/bytes.go
- pkg/api/bytes_test.go
- pkg/api/router.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3027)
> feat(api): allow HEAD requests on the bytes endpoint

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/router.go
- pkg/node/devnode.go
- pkg/node/node.go
Addresses the regression of missing `cors` handler on the debug endpoints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3040)
> fix: missing debug cors regression

- pkg/api/export_test.go
- pkg/api/router.go
- pkg/api/tag_debug.go
- pkg/api/tag_debug_test.go
The `/tags` endpoint has different shapes on api from debug api.
Closes #3043
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3045)
> fix: debug tags endpoint

- pkg/api/bytes.go
- pkg/util/ioutil/ioutil.go
- pkg/util/ioutil/ioutil_test.go
Closes #2946
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3041)
> fix: timeout stuck upload on bytes endpoint

- pkg/depthmonitor/depthmonitor.go
- pkg/node/node.go
- pkg/postage/batchstore/mock/store.go
- pkg/postage/batchstore/reserve_test.go
- pkg/postage/batchstore/store.go
- pkg/postage/batchstore/store_test.go
- pkg/postage/interface.go
- pkg/postage/noop.go
- pkg/puller/puller.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/kademlia/mock/kademlia.go
- pkg/topology/mock/mock.go
- pkg/topology/topology.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3055)
> feat: depth reporting

- pkg/node/node.go
- pkg/pullsync/pullsync.go
- pkg/rate/rate.go
- pkg/rate/rate_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3056)
> feat: pullsync rate

- cmd/bee/cmd/cmd.go
- pkg/depthmonitor/depthmonitor.go
- pkg/localstore/localstore.go
- pkg/node/node.go
- pkg/pullsync/pullsync.go
- pkg/topology/kademlia/kademlia.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3058)
> feat: reserve size

- pkg/node/devnode.go
Closes: #3057 
Dev mode is missing a valid batch store for the chain state handler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3063)
> fix: chainstate dev mode panic

- pkg/localstore/localstore.go
- pkg/node/node.go
- pkg/rate/export_test.go
- pkg/rate/rate.go
- pkg/rate/rate_test.go
- pkg/topology/depthmonitor/depthmonitor.go
- pkg/topology/depthmonitor/depthmonitor_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/metrics.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3080)
> fix: use time pkg

- .github/workflows/go.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3088)
> ci: remove mingw and disable race detector on windows

- .github/bin/beekeeper_artifacts.sh
- .github/workflows/beekeeper.yml
Related to https://github.com/ethersphere/bee/issues/3050
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3085)
> chore: add new debug endpoint and support for dynamic cluster

- .github/workflows/beekeeper.yml
- .github/workflows/release.yaml
- Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3102)
> chore: update docker to use go1.18

- version.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3110)
> chore(version): bump to v1.7.0

- pkg/netstore/netstore.go
- pkg/netstore/netstore_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
- pkg/steward/steward.go
- pkg/steward/steward_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3106)
> fix(retrieval): determine request origin correctly on forward

- pkg/node/bootstrap.go
- pkg/node/node.go
We increase the timeout of the context for fetching the snapshot to 2min because the previous 30s is too aggressive. PR also includes some simple restructuring of the retry mechanism.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3081)
> fix: improve bootstrapper reliability

- pkg/retrieval/export_test.go
- pkg/retrieval/retrieval.go
- pkg/retrieval/retrieval_test.go
- pkg/topology/mock/mock.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3108)
> fix: retrieval closestpeer bug and unit tests

- version.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3115)
> chore: bump version to 1.7.1

- pkg/accounting/accounting.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3116)
> chore: reduce accounting logging on error

- .github/workflows/go.yml
This upgrade helps with the readability of the error messages.
Old:
```sh
Error: error running commitlint
ensure-case: Unknown target case "sentence-case,start-case,pascal-case,upper-case"
TypeError: ensure-case: Unknown target case "sentence-case,start-case,pascal-case,upper-case"
at toCase (/node_modules/@commitlint/rules/node_modules/@commitlint/ensure/lib/case.js:47:19)
at Object.ensureCase [as case] (/node_modules/@commitlint/rules/node_modules/@commitlint/ensure/lib/case.js:18:25)
at exports.bodyCase (/node_modules/@commitlint/rules/lib/body-case.js:14:33)
at /node_modules/@commitlint/lint/lib/lint.js:98:40
at Array.map (<anonymous>)
at lint (/node_modules/@commitlint/lint/lib/lint.js:90:10)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async …
```
> chore: upgrade commitlint to version 5

- .github/workflows/beekeeper.yml
- .github/workflows/docs.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3118)
> chore: migrate digital ocean buckets

- cmd/bee/cmd/start_windows.go
- pkg/api/bytes.go
- pkg/logging/httpaccess/http_access.go
- pkg/logging/logging.go
- pkg/logging/metrics.go
- pkg/node/bootstrap.go
- pkg/node/devnode.go
- pkg/node/node.go
- pkg/pusher/pusher.go
- pkg/settlement/swap/swapprotocol/swapprotocol_test.go
- pkg/tracing/tracing.go
- pkg/tracing/tracing_test.go
- pkg/util/ioutil/ioutil.go
This change replaces the old logger with the new log package. This change is necessary so that the `logger` package can be gradually replaced by the new `log` package, both of which can exist at the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3079)
> refactor: replace logrus with new logger

- pkg/api/router.go
Closes: #3028
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3121)
> feat(api): restrict transaction endpoint

- pkg/node/node.go
- pkg/postage/batchstore/export_test.go
- pkg/postage/batchstore/mock/store.go
- pkg/postage/batchstore/reserve.go
- pkg/postage/batchstore/reserve_test.go
- pkg/postage/batchstore/store.go
- pkg/postage/batchstore/store_test.go
- pkg/postage/interface.go
- pkg/postage/noop.go
- pkg/storage/mock/storer.go
- pkg/topology/depthmonitor/depthmonitor.go
- pkg/topology/depthmonitor/depthmonitor_test.go
- pkg/topology/depthmonitor/export_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/topology.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3132)
> feat: remove storage depth

- pkg/puller/puller.go
- pkg/pullsync/pullsync.go
- pkg/topology/depthmonitor/depthmonitor.go
- pkg/topology/depthmonitor/depthmonitor_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/topology.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3138)
> historical syncing to dictate storage radius decrease

- cmd/bee/cmd/cmd.go
Closes #3141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3142)
> fix: default network id

- pkg/api/bytes.go
- pkg/api/bytes_test.go
- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/dirs.go
- pkg/api/feed.go
- pkg/api/peer.go
- pkg/api/peer_test.go
- pkg/api/pin.go
- pkg/api/pingpong.go
- pkg/api/pingpong_test.go
- pkg/api/postage.go
- pkg/api/pss.go
- pkg/api/soc.go
- pkg/api/stewardship.go
- pkg/api/tag.go
Closes: #2026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3148)
> fix: add error body to 500 responses

- .github/bin/beekeeper_artifacts.sh
There was a change in beekeeper flag to suppress log output, this PR fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3191)
> fix: fix beekeeper_artifacts.sh script

- pkg/node/chain.go
- pkg/puller/puller.go
removed some leftover formatting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3196)
> fix: leftover formatting

- go.mod
- go.sum
- pkg/storagev2/chunkstorer.go
- pkg/storagev2/inmemstore/inmemstore.go
- pkg/storagev2/inmemstore/inmemstore_test.go
- pkg/storagev2/storage.go
- pkg/storagev2/testsuite/testsuite.go
This PR implements the in-mem Store. This is part of the localstore rewrite epic.
The PR closes #3172 #3173 #3174 #3180 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3190)
> feat: in-mem implementation and testsuite

- pkg/topology/depthmonitor/depthmonitor.go
- pkg/topology/depthmonitor/depthmonitor_test.go
- pkg/topology/depthmonitor/export_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3197)
> feat: depthmonitor minimum storage radius decrease

- pkg/node/devnode.go
Minor fix in dev node, this fix sorts out the nullPtr err in api.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3201)
> fix: minor null ptr error in dev mode

- pkg/postage/batchservice/batchservice.go
fixes
```
"time"="2022-08-18 12:01:28.666395" "level"="debug" "logger"="node/batchservice" "msg"="batch created" "batch_id"="..." "tx"=[69,73,110,192,7,108,144,235,1,86,148,95,175,181,146,9,163,189,106,108,134,194,120,81,128,30,254,82,222,17,125,130] 
```
to look like
```
"time"="2022-08-18 12:01:28.667012" "level"="debug" "logger"="node/batchservice" "msg"="batch created" "batch_id"="..." "tx"="67c7be46792f5d7afba223f57ba3aa6ccbcca195a1e038d6bdec13744f244f50"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3206)
> fix: hash as byte array

- pkg/storagev2/chunkstorer.go
- pkg/storagev2/inmemchunkstore/inmemchunkstore.go
- pkg/storagev2/inmemchunkstore/inmemchunkstore_test.go
- pkg/storagev2/testsuite/chunkstoretests.go
Add simple in-mem chunk store implementation and testsuite.
Closes #3208
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3210)
> feat: inmem chunkstorer and testsuite

- CODINGSTYLE.md
This PR adds a naming recommendation to the CODINGSTYLE.md guide.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3223)
> chore: add a naming recommendation to the coding style guide

- openapi/SwarmCommon.yaml
Please refer to the related issue for description
This pr fixes #3112 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3228)
> fix: correct OpenApi definition for ChainState object

- pkg/ratelimit/ratelimit.go
This PR fixes overlocking in `Allow` method which can arise when `Allow` is concurrently being called with two or more different keys. 
Instead of locking  whole functionality of `Allow` method we are now locking only part that changes state of limiters map, leaving individual limiter to handle synchronization individually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3152)
> chore: reduce locking extent in ratelimit package

- packaging/bee.yaml
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
Closes:  #3083
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3225)
> chore: packaging documentation link update

- pkg/storagev2/chunkstore.go
- pkg/storagev2/inmemchunkstore/inmemchunkstore.go
- pkg/storagev2/inmemchunkstore/inmemchunkstore_test.go
- pkg/storagev2/inmemstore/inmemstore.go
- pkg/storagev2/inmemstore/inmemstore_test.go
- pkg/storagev2/leveldbstore/store.go
- pkg/storagev2/leveldbstore/store_test.go
- pkg/storagev2/storage.go
- pkg/storagev2/storagetest/chunkstore.go
- pkg/storagev2/storagetest/storage.go
Cleanups
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3239)
> refactor: cleanups

- pkg/localstore/reserve.go
- pkg/localstore/reserve_test.go
- pkg/postage/testing/stamp.go
Fixes #3123
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3247)
> fix(localstore): out of memory issue during unreserve

- pkg/statestore/leveldb/migration.go
- version.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3257)
> fix: statestore migration schema update 

- openapi/Swarm.yaml
added documentation for required header param in bytes and soc
Api refactoring
fixes #3100 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3259)
> fix: documentation for required header param in bytes and soc

- pkg/topology/depthmonitor/depthmonitor.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3264)
> chore: add depthmonitor guard rail post release testing

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/health.go
- pkg/api/health_test.go
- pkg/api/probe.go
- pkg/api/readiness.go
- pkg/api/readiness_test.go
- pkg/api/router.go
- pkg/node/devnode.go
- pkg/node/node.go
Closes: #2956,  #2793
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3248)
> feat(api): expose readiness and health endpoints

- pkg/localstore/mode_put.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3274)
> fix: sharky release leak when context is canceled

- .github/workflows/go.yml
- .golangci.yml
- Makefile
- add all rules that are currently compliant with the code
- remove `make vet` since same check is done using `govet` lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3281)
> feat(lint): add all rules that are currently compliant with the code

- pkg/config/chain.go
- pkg/statestore/leveldb/migration.go
- version.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3288)
> feat: new contract addresses

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3295)
> chore: bump api version

- pkg/cac/cac.go
- pkg/cac/cac_test.go
- pkg/storage/mock/storer_test.go
- pkg/transaction/backend_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3294)
> chore: add missing file header

- pkg/p2p/libp2p/libp2p.go
- pkg/settlement/swap/swapprotocol/swapprotocol.go
Fixes log messages with a missing or extra key.
Closes #3291
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3292)
> fix: log messages with a missing or extra key

- .golangci.yml
- pkg/api/api.go
- pkg/api/bytes.go
- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/chunk_stream.go
- pkg/api/dirs.go
- pkg/api/feed.go
- pkg/api/router.go
- pkg/api/soc.go
- pkg/storage/store.go
- enable `goconst` lint rule
- temporally disabled rule in test files, in order to reduce merge conflicts until `paralleltest` lint issues get fixed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3304)
> feat(lint): enable goconst

- .golangci.yml
- pkg/api/api.go
- pkg/api/transaction.go
- pkg/hive/hive_test.go
- pkg/node/node.go
- pkg/p2p/protobuf/protobuf_test.go
- pkg/pingpong/pingpong_test.go
- pkg/resolver/multiresolver/config.go
- pkg/retrieval/retrieval_test.go
- enable `prealloc` lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3298)
> feat(lint): enable prealloc

- .golangci.yml
- pkg/pullsync/pullstorage/pullstorage_test.go
- enable `exportloopref` lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3297)
> feat(lint): enable exportloopref

- .golangci.yml
- pkg/api/api_test.go
- pkg/api/cors_test.go
- enable `noctx` lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3299)
> feat(lint): enable noctx

- .golangci.yml
- pkg/file/loadsave/export_test.go
- pkg/file/loadsave/loadsave.go
- pkg/file/loadsave/loadsave_test.go
- pkg/log/formatter_test.go
- enable `errname` lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3296)
> feat(lint): enable errname

- .golangci.yml
- enable `forbidigo` lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3301)
> feat(lint): enable forbidigo

- pkg/storagev2/batch.go
- pkg/storagev2/inmemstore/inmembatch.go
- pkg/storagev2/inmemstore/inmemstore.go
- pkg/storagev2/inmemstore/inmemstore_test.go
- pkg/storagev2/leveldbstore/batch.go
- pkg/storagev2/leveldbstore/store.go
- pkg/storagev2/leveldbstore/store_test.go
- pkg/storagev2/storage.go
- pkg/storagev2/storagetest/batch.go
- pkg/storagev2/storagetest/benchmark.go
- pkg/storagev2/storagetest/storage.go
Closes #3278
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3279)
> feat: localstore batching

- .golangci.yml
-    enable durationcheck lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3318)
> feat(lint): enable durationcheck

- .golangci.yml
- pkg/postage/batchstore/store.go
- pkg/resolver/cidv1/cidv1.go
- enabled  most `govet` linter rules; some rules were temporally disabled until future efforts
- fixed errors reported by rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3317)
> feat(lint): enable govet linters

- pkg/settlement/swap/chequebook/init.go
Closes: #2991
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3230)
> fix: appreciate gas price set by user

- version.go
Version bump after release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3336)
> chore: bump version to 1.8.3

- .golangci.yml
Enabling `tparallel` which was unintentionally removed in (https://github.com/ethersphere/bee/pull/3265)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3334)
> feat(lint): enable tparallel

- .golangci.yml
- pkg/log/logger.go
- pkg/log/registry.go
- pkg/topology/kademlia/internal/metrics/metrics.go
- enable `predeclared` lint rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3306)
> feat(lint): enable predeclared

- pkg/storagev2/batch.go
- pkg/storagev2/inmemstore/inmemstore_test.go
- pkg/storagev2/leveldbstore/store_test.go
- pkg/storagev2/storage.go
- pkg/storagev2/storagetest/batch.go
- pkg/storagev2/storagetest/benchmark.go
- pkg/storagev2/storagetest/benchmark_test.go
- pkg/storagev2/storagetest/storage.go
Clarifies `Batch` interface and cleanups tests and benchmarks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3330)
> refactor: batchedstore tests and bench cleanup

- pkg/topology/kademlia/internal/metrics/metrics.go
Fixes copied comment on `IsUnreachable` method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3329)
> style(kademlia/metrics): fix copied method comment

- .golangci.yml
- cmd/bee/cmd/cmd.go
- pkg/api/api_test.go
- pkg/bmtpool/bmtpool.go
- pkg/encryption/encryption_test.go
- pkg/file/pipeline/encryption/encryption_test.go
- pkg/file/pipeline/hashtrie/hashtrie_test.go
- pkg/file/span.go
- pkg/localstore/localstore.go
- pkg/localstore/localstore_test.go
- pkg/manifest/mantaray/marshal.go
- pkg/manifest/mantaray/marshal_test.go
- pkg/manifest/mantaray/node.go
- pkg/p2p/libp2p/libp2p.go
- pkg/pullsync/pullsync_test.go
- pkg/storage/testing/chunk.go
- pkg/topology/kademlia/kademlia_test.go
- enable `gochecknoinits` lint rule
- ignored all current issues; some of these issues will be fixed together with `paralleltest` rule, some should stay ignored.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3307)
> feat(lint): enable gochecknoinits

- .github/pull_request_template.md
Adds a new section to the PR template that collects the necessary changes to the Open API specification, if applicable.
#3353
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3354)
> docs: add Open API spec section to the PR template

- pkg/api/pss_test.go
`TestPss*` were taking to much time to execute ~20sec (~50sec before parallel tests). The reason for such long execution was high `mTimeout` value which set to `10sec`. 
This PR optimizes execution of same test by:
- reducing this timeout value (set to 2sec; which still has a lot of extra time because messages are sent in 1/100 of second)
- utilized channels for message passing (in order to efficiently parallelize reading messages and asserting message contents)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3351)
> refactor: improve api pss test execution time

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- pkg/node/node.go
Feature flag to enable the storage incentives agent during testing.
> chore: incentives feature flag

- pkg/soc/validator_test.go
- pkg/swarm/swarm.go
- pkg/swarm/swarm_test.go
There was race condition is `soc/TestInvalid` which is fixed with this PR.
> fix: race condition in soc/TestInvalid

- pkg/storageincentives/agent_test.go
> chore: tweak agent test

- pkg/api/postage.go
> fix: cannot get batch after purchase

- pkg/storageincentives/agent.go
- pkg/storageincentives/agent_test.go
> fix: reveal phases 39 blocks long

- .github/workflows/go.yml
Temporarily disabled commit linting due to errors in executing this github action
> chore: temporarily disabled commitlint

- pkg/storageincentives/agent.go
- version.go
> chore: bump version

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
> chore: rename option

- .github/workflows/go.yml
- commitlint.config.js
Enables previously disabled commitlint.
Closes #3403
> chore(lint): enable disabled commitlint

- pkg/pusher/pusher_test.go
`pusher_tests` had different and not obvious timeouts in unit tests, which were based on retry count and goroutine delays. Increasing retry count would increase timeout for all tests, but some which required lower timeout would then fail. 
This PR uses same spin lock like logic to wait for condition with configurable timeout. 
This PR doesn't fully addresses fix for flaky tests. They could still appear but with increased timeout this is going to happen less often. Issue #3032 should still be open to track effort for providing full solution for this issue.
> fix: flaky test TestSendChunkAndTimeoutinReceivingReceipt

- pkg/api/router.go
- pkg/localstore/sampler.go
- pkg/localstore/sampler_test.go
- pkg/storage/store.go
- pkg/storageincentives/agent.go
Adding a consensus of deterministic time-delimiter for reserve sample inclusion of chunks based on timestamp of postage stamp
> feat: add consensus time for sampler

- pkg/pushsync/pushsync.go
- pkg/retrieval/retrieval.go
UX increasing feature
While trying to download quake through http://localhost:1633/bzz/429564bc77733dfc76b3de9ed282b1177f245ff6bf5598f0bd79a8fbdcfd5796/
light node without chequebook was not able to fully download content before something timed out and operation failed
With the change included, downloading the file succeeded
https://github.com/ethersphere/bee/issues/3075
> feat: increase attempt count in retrieval and pushsync

- pkg/blocker/blocker_test.go
> fix(blocker): fix flaky tests

- pkg/feeds/sequence/lookup_test.go
- pkg/feeds/testing/lookup.go
Adding more parallel tests in `feeds` package to improve test execution time.
> chore(feeds): better parallel tests

- pkg/localstore/sampler.go
> fix: sampler duration tracks seconds

- .golangci.yml
> chore(lint): simplified govet rules

- openapi/Swarm.yaml
- pkg/api/api.go
- pkg/api/bytes.go
- pkg/api/bytes_test.go
- pkg/api/bzz.go
- pkg/api/bzz_test.go
- pkg/api/chunk.go
- pkg/api/chunk_test.go
- pkg/api/export_test.go
- pkg/api/feed_test.go
- pkg/api/logger.go
- pkg/api/postage_test.go
- pkg/api/pss_test.go
- pkg/api/router.go
- pkg/api/soc.go
- pkg/api/soc_test.go
- pkg/api/stewardship.go
- pkg/api/stewardship_test.go
- pkg/api/tag_test.go
- pkg/api/util.go
- pkg/api/util_test.go
- pkg/sctx/sctx.go
parsing and validation of headers and changes in tests 
w thanks to Vlado
extension of #3344 
related #3163 #3165 #3166 
blocking #3249 #3344 
closes #3371
> refactor: parsing and validation

- .golangci.yml
- pkg/bmt/bmt_test.go
- pkg/bmt/proof_test.go
- pkg/bmt/reference/reference_test.go
This PR is part of https://github.com/ethersphere/bee/issues/3255 effort.
Enabled parallel tests lint in `bmt` package.
> chore(bmt): enable parallel tests

- .golangci.yml
- pkg/puller/metrics.go
- pkg/puller/puller.go
- pkg/pullsync/pullsync.go
if SyncInterval has a chunk with an invalid/expired batch, or a write to storage fails, both historical and live syncs terminate on error. these should be "soft" errors, and not terminate syncing. With this change, the error is logged, the node sleeps for some time, then continues to sync with the peer.
> fix: pullsync and puller sync process to continue

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/deploy.go
- cmd/bee/cmd/start.go
- packaging/bee.yaml
- packaging/docker/env
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
- pkg/node/node.go
Rename swap-endpoint to blockchain-rpc-endpoint.Closes  #3263
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3345)
> fix: rename swap

- pkg/storagev2/migration/export_test.go
- pkg/storagev2/migration/migration.go
- pkg/storagev2/migration/migration_test.go
Closes #3401 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3424)
> feat: migration initiation

- pkg/puller/puller_test.go
- pkg/topology/kademlia/kademlia_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3458)
> fix: flaky unit tests

- pkg/storagev2/migration/export_test.go
- pkg/storagev2/migration/index.go
- pkg/storagev2/migration/index_test.go
- pkg/storagev2/migration/migration.go
- pkg/storagev2/migration/migration_test.go
- pkg/storagev2/migration/steps_chain.go
- pkg/storagev2/migration/steps_chain_test.go
Closes:  #3402
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3421)
> feat(migration): store migration helpers

- pkg/api/bzz.go
- pkg/api/bzz_test.go
added a not found error if there was no path
finally closes the major issues in refactoring epic for atleast some time
w thanks to @vladopajic & @AuHau 
fixes #3199 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3457)
> fix: redirect loop

- pkg/localstore/reserve.go
- pkg/localstore/sampler.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3459)
> chore: cleanup of unnecessary address at bin function

- pkg/topology/depthmonitor/depthmonitor_test.go
Increasing timeout for `waitForDepth` function to `3sec` (fix for #3395).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3461)
> fix(depthmonitor): increased depth wait timeout

- pkg/storageincentives/redistribution/redistribution.go
- pkg/storageincentives/redistribution/redistribution_test.go
- pkg/transaction/mock/transaction.go
- pkg/transaction/transaction.go
- pkg/transaction/transaction_test.go
To make sure reveal transactions are processed in time with higher reliability, increase suggested gasprice by 50%
Gas limits are also lowered for commit and reveal to help the transactions being processed more easily
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3452)
> feat: increase reveal price

- pkg/config/chain.go
- pkg/storageincentives/agent.go
Price adjustment aware redistribution contract update address
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3460)
> feat: new redistribution address

- pkg/storageincentives/redistribution/redistribution_test.go
- pkg/transaction/mock/transaction.go
Unit test broken on master
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3470)
> fix: redistribution tests

- pkg/topology/depthmonitor/depthmonitor_test.go
- pkg/topology/depthmonitor/export_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3473)
> fix(depthmonitor): unit tests

- pkg/localstore/sampler.go
- pkg/storageincentives/agent.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3471)
> chore: sampler logs fix and agent timer limit helper func

- pkg/pushsync/pushsync_test.go
Temporal fix for #3478
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3480)
> fix: TestReplicateBeforeReceipt flaky test

- .golangci.yml
- pkg/pushsync/pushsync_test.go
- [] I have filled out the description and linked the related issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3481)
> chore(lint): pushsync parallel tests

- pkg/p2p/libp2p/libp2p.go
- pkg/postage/batchservice/batchservice.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3482)
> fix: log fixes

- cmd/bee/cmd/cmd.go
- packaging/bee.yaml
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
Closes #3243
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3489)
> feat: initial deposit zero

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bytes.go
- pkg/api/bytes_test.go
- pkg/api/bzz.go
- pkg/api/bzz_test.go
- pkg/api/chunk.go
- pkg/api/chunk_test.go
- pkg/api/export_test.go
- pkg/api/feed.go
- pkg/api/feed_test.go
- pkg/node/devnode.go
Closes #3227
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3466)
> fix(api): direct upload

- pkg/localstore/localstore.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3487)
> chore: log sharky recovery

- pkg/localstore/sampler.go
So seems like we need to pass the pointer to the stat item. This is because of how the logger internally handles printing the string.
Fixes #3490 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3491)
> fix: sampler log regression

- pkg/postage/postagecontract/contract.go
- pkg/postage/postagecontract/contract_test.go
- pkg/settlement/swap/chequebook/cashout.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/chequebook/factory.go
- pkg/settlement/swap/erc20/erc20.go
- pkg/storageincentives/redistribution/redistribution.go
- pkg/storageincentives/redistribution/redistribution_test.go
- pkg/storageincentives/staking/contract.go
- pkg/storageincentives/staking/contract_test.go
- pkg/transaction/mock/transaction.go
- pkg/transaction/transaction.go
- pkg/transaction/transaction_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3497)
> chore: boost all agent calls

- pkg/hive/hive.go
- pkg/p2p/libp2p/libp2p.go
- pkg/postage/listener/listener_test.go
- pkg/pricing/pricing.go
- pkg/retrieval/retrieval.go
- pkg/settlement/pseudosettle/pseudosettle.go
Removed unnecessary sleep and goroutines likely to be added to avoid potential race conditions which have been fixed in #3475
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3495)
> chore: remove unnesesery sleep

- pkg/postage/postagecontract/contract.go
- pkg/settlement/swap/chequebook/cashout.go
- pkg/storageincentives/redistribution/redistribution.go
Now that batches are cleaned up before the main transaction is sent, the gas limit can be reduced everywhere. 
Ex claim trx: https://goerli.etherscan.io/tx/0xe9693efb0cceca14564a04d5bfcaa27b664e4d4c08b20c8ff3cb5067f4ec49f6
ex create batch trx https://goerli.etherscan.io/tx/0x511f44e9a1bcf152db91d5bc235c9c07a75c6cc3b157203582eedac75c883900
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3496)
> chore: adjust gas limits

- pkg/puller/puller_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3508)
> fix(puller): flaky tests

- pkg/storageincentives/agent_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3507)
> chore(agent): renable test

- pkg/config/chain.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3510)
> chore: compact chain config

- pkg/storageincentives/agent_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3512)
> fix: agent unit test

- pkg/accounting/accounting.go
improved logging
closes #3448 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3467)
> refactor: keyval pairs for logger in accounting

- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3513)
> chore: account disconnect reason for blocklistig

- pkg/config/chain.go
- pkg/storageincentives/agent.go
- pkg/storageincentives/agent_test.go
- pkg/storageincentives/redistribution/redistribution.go
- pkg/storageincentives/redistribution/redistributionABI.go
- pkg/storageincentives/redistribution/redistribution_test.go
In order to avoid a high traffic blockchain environment with delayed transaction processing to register our commit to a later round than intended, add explicit round argument to the commit function in the redistribution contract
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3477)
> feat: add commit round argument

- pkg/node/node.go
- pkg/pullsync/pullstorage/pullstorage.go
- pkg/pullsync/pullstorage/pullstorage_test.go
- pkg/pullsync/pullsync.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3518)
> chore: more logs to pullsync and pullstorage

- .github/workflows/beekeeper.yml
Update CI workflow to disable the beekeeper gc test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3525)
> fix: disable beekeeper gc test

- pkg/config/chain.go
- pkg/node/chain.go
- pkg/node/node.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3537)
> chore: rename swap oracle to avoid confusion

- pkg/config/chain.go
Closes #3543
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3544)
> fix: goerli postage stamp start block number

- pkg/api/transaction.go
In case of error we are logging an incorrect value for the tx: `0x00000000...`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3554)
> fix: use the correct hash

- pkg/storageincentives/redistribution/redistribution.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3558)
> fix: increase reveal gas limit

- pkg/puller/puller.go
- pkg/pullsync/pullstorage/pullstorage.go
- pkg/pullsync/pullsync.go
- pkg/storageincentives/redistribution/redistribution.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3561)
> chore: disable puller logs

- pkg/localstore/sampler.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3567)
> chore: more logs for the sampler

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- pkg/api/postage.go
- pkg/api/postage_test.go
- pkg/node/devnode.go
- pkg/postage/postagecontract/contract.go
- pkg/postage/postagecontract/contract_test.go
- pkg/postage/postagecontract/mock/contract.go
Closes #3359 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3535)
> fix: add transaction hash

- pkg/localstore/mode_put.go
- pkg/localstore/mode_set.go
- pkg/pullsync/pullsync.go
- pkg/topology/depthmonitor/depthmonitor.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3572)
> chore: explicit error messages from put sync

- openapi/SwarmCommon.yaml
- pkg/api/wallet.go
- pkg/api/wallet_test.go
Closes #3569 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3571)
> feat: add wallet address

- pkg/puller/puller_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3564)
> chore: enable puller test

- pkg/chainsyncer/chainsyncer.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3578)
> chore: reduce verbosity of chainsync

- pkg/postage/postagecontract/contract.go
- pkg/storageincentives/redistribution/redistribution.go
- pkg/storageincentives/staking/contract.go
- pkg/transaction/transaction.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3582)
> fix: use gas estimate

- pkg/localstore/reserve.go
- pkg/sharky/metrics.go
- pkg/sharky/store.go
Add missing metric for reserve size. Also some new ones for sharky.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3587)
> fix: add missing and some new metrics

- go.sum
- pkg/intervalstore/main_test.go
- pkg/pullsync/pullstorage/main_test.go
As part of https://github.com/ethersphere/bee/issues/3522, this PR addresses goroutine leaks in intervalstore package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3548)
> fix(intervalstore): go leak enabled

- go.mod
- pkg/postage/batchstore/main_test.go
As part of https://github.com/ethersphere/bee/issues/3522, this PR addresses goroutine leaks in postage/batchstore package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3547)
> fix(batchstore): go leak check enabled

- pkg/node/main_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3594)
> chore(node): ignore leaky goroutine

- pkg/localstore/gc_test.go
- pkg/localstore/localstore_test.go
- pkg/localstore/reserve.go
- pkg/localstore/reserve_test.go
- pkg/localstore/sampler_test.go
- pkg/topology/depthmonitor/depthmonitor.go
- pkg/topology/depthmonitor/depthmonitor_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3599)
> revert: compute reserve to start from po 0 (#3596)

- pkg/statestore/leveldb/migration.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3605)
> revert: nuke statestore to remove sync intervals (#3590)

- pkg/localstore/mode_put.go
- pkg/puller/puller.go
- pkg/puller/puller_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3603)
> fix: padded bin str to avoid unintentionally deleting different bins

- pkg/localstore/mode_has.go
- pkg/localstore/sampler.go
- pkg/pullsync/pullstorage/pullstorage.go
- pkg/storage/store.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3607)
> fix: pullsync 'has' checks the pull index 

- pkg/storageincentives/agent_test.go
Closes: #3613
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3615)
> fix(storageincentives): data race in `mockchainBackend`

- pkg/statestore/leveldb/migration.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3621)
> fix: no op migration after reverting previous migration

- pkg/storageincentives/agent_test.go
Fixes storageincentives package chain backend mock datarace: https://github.com/ethersphere/bee/actions/runs/3603052071/jobs/6070762703
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3619)
> fix: storageincentives chain backend mock data race

- pkg/api/api_test.go
Fixes flaky `TestPostageDirectAndDeferred/bzz:_deferred` test: https://github.com/ethersphere/bee/actions/runs/3603341092/jobs/6071418497
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3620)
> fix: flaky postage direct upload test

- pkg/storageincentives/agent_test.go
Reverts #3615 in favor of #3619
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3623)
> Revert "fix(storageincentives): data race in `mockchainBackend` (#3615)"

- pkg/storageincentives/agent_test.go
Fixes whole `BlockNumber` mock method to avoid data-race.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3624)
> fix: lock whole `BlockNumber` mock method to avoid data-race

- Makefile
CI build fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3633)
> ci: fix CGO_ENABLED=0

- pkg/postage/batchstore/metrics.go
- pkg/postage/batchstore/reserve.go
- pkg/postage/batchstore/store.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3640)
> fix: read write mutex in batchstore

- pkg/transaction/transaction.go
Closes: #3498
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3647)
> fix: filtering non pending transactions before waiting on them

- pkg/auth/auth.go
Staking endpoints were missing from the auth config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3646)
> fix: add staking auth rule

- pkg/config/chain.go
- pkg/settlement/swap/chequebook/init.go
Closes: #2754
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3648)
> chore: read token symbol name based on configuration

- go.mod
- go.sum
Fixes #3649
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3653)
> chore: update storage-incentives to rc4

- pkg/p2p/libp2p/internal/handshake/handshake.go
Bump handshake version because of new contracts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3659)
> feat: bump handshake version for release

- .github/workflows/beekeeper.yml
Removed duplicate stake test from beekeeper.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3668)
> ci: remove duplicate stake test

- pkg/api/api.go
`swarm-deferred-upload` is missing from allowed CORS headers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3669)
> fix: add deferred header to allowed cors headers

- pkg/auth/auth.go
Testing extra checks in the stake test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3667)
> feat: stake withdraw role

- pkg/node/node.go
- pkg/node/statestore.go
Closes: #3254
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3684)
> chore: remove overlay mining

- pkg/api/api.go
cleanups
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3678)
> chore(api): stamper putter cleanups

- pkg/localstore/migration.go
- pkg/localstore/migration_residue.go
- pkg/localstore/schema.go
This is sort of leftover from the previous version. The initial state of localstore is not correct on some of the mainnet nodes. There were some inconsistencies from the previous version that might have tripped over. If the nodes were nuked/new then they will not be affected by this.
This migration will sanitize the pullIndex if required. This is important as these entries could potentially end up in the sample causing the node to be frozen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3686)
> feat: residual migration

- pkg/node/node.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3688)
> fix: cancel bee node construction while waiting on nat manager

- pkg/postage/export_test.go
- pkg/postage/stampissuer.go
- pkg/postage/stampissuer_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3685)
> fix: mutable batches do not stop uploads that reach max utilization

- cmd/bee/cmd/start.go
- pkg/api/pss_test.go
- pkg/hive/hive_test.go
- pkg/netstore/netstore_test.go
- pkg/node/bootstrap.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/libp2p_test.go
- pkg/p2p/libp2p/protocols_test.go
- pkg/p2p/streamtest/streamtest.go
- pkg/puller/puller_test.go
- pkg/pullsync/pullstorage/pullstorage_test.go
- pkg/pusher/pusher_test.go
- pkg/retrieval/retrieval_test.go
- pkg/spinlock/wait.go
- pkg/spinlock/wait_test.go
- pkg/topology/depthmonitor/depthmonitor_test.go
- pkg/topology/kademlia/kademlia_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3493)
> chore(spinlock):  utilize spinlock

- pkg/node/node.go
Bootnodes should have depthmonitor disabled. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3691)
> fix: disable depthmonitor for bootnodes

- pkg/log/formatter_test.go
- pkg/manifest/mantaray/marshal_test.go
- pkg/statestore/leveldb/leveldb.go
A few linter fixes that have been moved out of the libp2p upgrade PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3697)
> fix: linter

- pkg/postage/listener/listener.go
- pkg/postage/listener/listener_test.go
- pkg/postage/listener/main_test.go
As part of https://github.com/ethersphere/bee/issues/3522, this PR addresses goroutine leaks in postage/listener package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3533)
> fix(postage/listener): goroutine leak

- pkg/file/buffer_test.go
- pkg/file/main_test.go
As part of https://github.com/ethersphere/bee/issues/3522, this PR addresses goroutine leaks in file package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3530)
> fix(file): goroutine leak

- pkg/hive/hive.go
- pkg/hive/hive_test.go
- pkg/hive/main_test.go
As part of https://github.com/ethersphere/bee/issues/3522, this PR addresses goroutine leaks in hive package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3531)
> fix(hive): goroutine leak

- pkg/feeds/sequence/main_test.go
- pkg/feeds/sequence/sequence.go
As part of https://github.com/ethersphere/bee/issues/3522, this PR addresses goroutine leaks in sequence package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3529)
> fix(sequence): goroutine leak

- .github/workflows/beekeeper.yml
At the time of the PR, the storage incentives tests do not test anything.
It would be good to rewrite the test after the localstore rewrite.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3689)
> chore: disable beekeeper storage incentives test

- .github/workflows/release.yaml
- Dockerfile
- Makefile
- go.mod
separate PR for go.19
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3706)
> chore: upgrade to go 1.19

- pkg/keystore/file/key.go
This change fixes incompatibility between btcec.S256() used in NewEthereumAddress by the encryptKey function and elliptic.P256() used for generating the libp2p key. The serialization is now possible and key encryption is successful.
Fix panic on node start:
```
panic: crypto/elliptic: attempted operation on invalid point
goroutine 23 [running]:
crypto/elliptic.panicIfNotOnCurve({0x102416ec0?, 0x102fb6c40?}, 0xf2?, 0x20?)
crypto/elliptic/elliptic.go:182 +0xb4
crypto/elliptic.Marshal({0x102416ec0, 0x102fb6c40}, 0x14002083070?, 0x14000cba340?)
crypto/elliptic/elliptic.go:75 +0x2c
github.com/ethersphere/bee/pkg/crypto.NewEthereumAddress({{0x102416e30?, 0x102d29a20?}, 0x14000dbe400?, 0x14000dbe420?})
github.com/ethersphere/bee/pkg/crypto/crypto.go:121 +0x7c …
```
> fix: keystore file encrypt key support multiple ec

- pkg/localstore/migration_residue.go
Fixes residue migration when `leveldb.ErrNotFound` is returned for retrieval data index.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3713)
> fix: residue migration

- pkg/pusher/pusher_test.go
Using a larger timeout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3716)
> fix: increase timeout on flaky test

- pkg/localstorev2/internal/stampindex/export_test.go
- pkg/localstorev2/internal/stampindex/stampindex.go
- pkg/localstorev2/internal/stampindex/stampindex_test.go
- pkg/swarm/swarm.go
Closes #3704
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3701)
> feat: add stamp index

- pkg/localstorev2/internal/cache/cache.go
- pkg/localstorev2/internal/cache/cache_test.go
- pkg/localstorev2/internal/chunkstore/chunkstore.go
- pkg/localstorev2/internal/chunkstore/chunkstore_test.go
- pkg/localstorev2/internal/pinning/pinning.go
- pkg/localstorev2/internal/pinning/pinning_test.go
- pkg/localstorev2/internal/stampindex/export_test.go
- pkg/localstorev2/internal/stampindex/stampindex.go
- pkg/localstorev2/internal/stampindex/stampindex_test.go
- pkg/localstorev2/internal/upload/uploadstore.go
- pkg/localstorev2/internal/upload/uploadstore_test.go
- pkg/postage/stamp.go
- pkg/storagev2/inmemstore/transaction.go
- pkg/storagev2/leveldbstore/transaction.go
- pkg/storagev2/migration/index.go
- pkg/storagev2/migration/migration.go
- pkg/storagev2/migration/migration_test.go
- pkg/storagev2/repository.go
- pkg/storagev2/storage.go
- pkg/storagev2/storagetest/storage.go
- pkg/storagev2/storagetest/transaction.go
- pkg/swarm/swarm.go
Closes #3705
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3708)
> fix: transaction put logic

- pkg/localstorev2/internal/chunkstore/chunkstore.go
- pkg/localstorev2/internal/internal.go
- pkg/localstorev2/internal/upload/uploadstore_test.go
- pkg/storagev2/chunkstore.go
- pkg/storagev2/inmemchunkstore/inmemchunkstore.go
- pkg/storagev2/storagetest/chunkstore.go
Closes: #3695
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3707)
> chore: multiple stamps per chunk

- pkg/storagev2/storagetest/chunkstore.go
- pkg/storagev2/storagetest/transaction.go
Fix broken tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3719)
> fix(localstorev2): broken tests

- pkg/storagev2/chunkstore.go
- pkg/storagev2/inmemchunkstore/inmemchunkstore.go
- pkg/storagev2/inmemchunkstore/transaction.go
- pkg/storagev2/inmemstore/transaction.go
- pkg/storagev2/leveldbstore/transaction.go
- pkg/storagev2/transaction.go
- pkg/storagev2/transaction_test.go
Improve transaction `Done` call API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3720)
> refactor: improve transaction Done call API

- pkg/localstorev2/internal/pinning/export_test.go
- pkg/localstorev2/internal/pinning/pinning.go
- pkg/storagev2/inmemstore/inmemstore.go
- pkg/storagev2/leveldbstore/store.go
- pkg/storagev2/migration/index_test.go
- pkg/storagev2/migration/steps_chain_test.go
- pkg/storagev2/storage.go
- pkg/storagev2/storagetest/batch.go
- pkg/storagev2/storagetest/storage.go
Add iteration by prefix and skip first item option for index store query.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3725)
> feat: add iteration by prefix and skip first item

- pkg/localstorev2/internal/stampindex/stampindex.go
- pkg/localstorev2/internal/upload/export_test.go
- pkg/localstorev2/internal/upload/uploadstore.go
- pkg/localstorev2/internal/upload/uploadstore_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3727)
> fix: check for existing stamp index on upload

- pkg/localstorev2/export_test.go
- pkg/localstorev2/internal/cache/cache.go
- pkg/localstorev2/internal/cache/cache_test.go
- pkg/localstorev2/internal/internal.go
- pkg/localstorev2/internal/pinning/export_test.go
- pkg/localstorev2/internal/pinning/pinning.go
- pkg/localstorev2/internal/pinning/pinning_test.go
- pkg/localstorev2/internal/stampindex/stampindex.go
- pkg/localstorev2/internal/stampindex/stampindex_test.go
- pkg/localstorev2/internal/upload/export_test.go
- pkg/localstorev2/internal/upload/uploadstore.go
- pkg/localstorev2/internal/upload/uploadstore_test.go
- pkg/localstorev2/localstore.go
- pkg/localstorev2/localstore_test.go
- pkg/storagev2/repository.go
Initial skeleton for the localstore container class. This PR includes the high-level interfaces that localstore will expose for Upload and Pinning related functionality. Also tests to cover all the changes. These interfaces will eventually be used in the API and Pinning service implementations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3741)
> feat(localstorev2): localstore container implementation

- pkg/storagev2/inmemstore/inmemstore.go
- pkg/storagev2/leveldbstore/store.go
- pkg/storagev2/storage.go
- pkg/storagev2/storagetest/storage.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3745)
> feat: iterate to start at a prefix and continue until the end of the namespace

- pkg/localstorev2/export_test.go
- pkg/localstorev2/internal/cache/cache.go
- pkg/localstorev2/internal/cache/cache_test.go
- pkg/localstorev2/localstore.go
- pkg/localstorev2/localstore_test.go
- pkg/storagev2/repository.go
Cache-related interfaces in the localstore container. The difference between Cache and other components is that the cache is instantiated once and its size can be configured. Each Get and Put operation needs to be guarded by a transaction as these may include a few cache-related updates.
Also added tests to cover some error cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3755)
> feat: localstore container cache interfaces

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/deploy.go
- cmd/bee/cmd/start.go
- packaging/bee.yaml
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
- pkg/node/node.go
Closes #3258  
#3260 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3765)
> fix: remove block hash and transaction

- pkg/api/api_test.go
- pkg/storageincentives/agent.go
- pkg/storageincentives/agent_test.go
- pkg/storageincentives/redistributionstate.go
- pkg/storageincentives/redistributionstate_test.go
- pkg/storageincentives/staking/contract.go
- pkg/storageincentives/staking/mock/contract.go
IsFrozen is calling the wrong function on the contract side, and we check is frozen more frequently than before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3768)
> fix: is frozen checks wrong function

- pkg/accounting/accounting.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3771)
> chore(accounting): lower ALL loggers

- pkg/node/node.go
- pkg/puller/puller.go
- pkg/puller/puller_test.go
- pkg/pullsync/pullsync_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3774)
> feat(puller): blocklist peers on sync interval timeout

- pkg/node/node.go
- pkg/puller/puller.go
- pkg/pullsync/pullsync.go
- pkg/topology/depthmonitor/depthmonitor.go
- pkg/topology/depthmonitor/depthmonitor_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3772)
> revert(depthmonitor): use rate of chunks as signal

- pkg/traversal/traversal.go
- pkg/traversal/traversal_test.go
This PR builds on the changes in the file pkg. 
go test ./pkg/traversal/...
ok  	github.com/ethersphere/bee/pkg/traversal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3788)
> feat(traversal): use new storage interfaces

- cmd/bee/cmd/start.go
- pkg/crypto/crypto.go
- pkg/crypto/crypto_test.go
- pkg/crypto/edg.go
- pkg/keystore/file/key.go
- pkg/keystore/file/service.go
- pkg/keystore/keystore.go
- pkg/keystore/mem/service.go
- pkg/keystore/test/test.go
This change will make switching between `secp` revisions very easy, and would make reverting of the libp2p functionality less painful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3797)
> feat: modular key handling

- pkg/feeds/epochs/finder.go
- pkg/feeds/epochs/lookup_benchmark_test.go
- pkg/feeds/epochs/lookup_test.go
- pkg/feeds/epochs/updater.go
- pkg/feeds/factory/factory.go
- pkg/feeds/getter.go
- pkg/feeds/putter.go
- pkg/feeds/sequence/lookup_benchmark_test.go
- pkg/feeds/sequence/lookup_test.go
- pkg/feeds/sequence/sequence.go
- pkg/feeds/testing/lookup.go
Feeds pkg
go test ./pkg/feeds/...
?   	github.com/ethersphere/bee/pkg/feeds	[no test files]
ok  	github.com/ethersphere/bee/pkg/feeds/epochs	(cached)
?   	github.com/ethersphere/bee/pkg/feeds/factory	[no test files]
ok  	github.com/ethersphere/bee/pkg/feeds/sequence	(cached)
?   	github.com/ethersphere/bee/pkg/feeds/testing	[no test files]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3789)
> feat(feeds): use new storage interfaces

- pkg/localstorev2/internal/chunkstore/chunkstore.go
- pkg/localstorev2/internal/pinning/pinning.go
- pkg/localstorev2/internal/upload/uploadstore.go
- pkg/storagev2/inmemchunkstore/transaction.go
- pkg/storagev2/inmemstore/transaction.go
- pkg/storagev2/leveldbstore/transaction.go
- pkg/storagev2/migration/index.go
- pkg/storagev2/migration/migration.go
- pkg/storagev2/migration/migration_test.go
- pkg/storagev2/storage.go
- pkg/storagev2/storagetest/storage.go
- pkg/storagev2/storagetest/transaction.go
- pkg/storagev2/transaction.go
Abstract common logic for tracking the reverse tx operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3793)
> refactor: cleanup tx revert operation tracking

- pkg/localstorev2/migration/all_steps.go
- pkg/localstorev2/migration/all_steps_test.go
- pkg/localstorev2/migration/export_test.go
- pkg/localstorev2/migration/step_01.go
- pkg/localstorev2/migration/step_01_test.go
- pkg/localstorev2/storer.go
- pkg/localstorev2/storer_test.go
- pkg/storagev2/migration/export_test.go
- pkg/storagev2/migration/migration.go
- pkg/storagev2/migration/migration_test.go
Migration part of #3750 issue.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3791)
> feat(localstorev2): migration

- pkg/api/pss.go
Fixes goleak issue reported In this [CI run](https://github.com/ethersphere/bee/actions/runs/4203093077/attempts/1). 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3805)
> fix(api): end pss handler when context is canceled

- pkg/swarm/utilities.go
- pkg/swarm/utilities_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3803)
> feat(swarm): add new utility functions

- pkg/bzz/utilities_test.go
- pkg/encryption/encryption_test.go
- pkg/file/buffer_test.go
- pkg/localstore/gc_test.go
- pkg/localstore/migration_test.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/pullsync/pullstorage/pullstorage_test.go
- pkg/storageincentives/redistribution/redistribution_test.go
- pkg/swarm/utilities_test.go
- pkg/util/testutil/helpers.go
- pkg/util/testutil/helpers_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3813)
> chore: add RandBytes utility to read random bytes

- pkg/localstorev2/cachestore_test.go
- pkg/localstorev2/internal/chunkstore/chunkstore.go
- pkg/localstorev2/internal/chunkstore/helpers.go
- pkg/localstorev2/internal/chunkstore/helpers_test.go
- pkg/localstorev2/netstore_test.go
- pkg/localstorev2/pinstore_test.go
- pkg/localstorev2/recover.go
- pkg/localstorev2/storer.go
- pkg/localstorev2/storer_test.go
- pkg/localstorev2/uploadstore_test.go
- pkg/swarm/utilities_test.go
Sharky recovery part for #3750 issue.
Closes: #3750
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3794)
> feat(localstorev2): sharky recovery

- .github/workflows/go.yml
- go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3817)
> feat(ci): go.mod file tidy check

- pkg/localstorev2/internal/upload/uploadstore.go
- pkg/localstorev2/internal/upload/uploadstore_test.go
- pkg/localstorev2/storer.go
- pkg/localstorev2/uploadstore.go
Intermediate PR for iterate functionality
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3826)
> fix: upload store iterator

- pkg/localstorev2/internal/chunkstamp/chunkstamp.go
- pkg/localstorev2/internal/chunkstamp/chunkstamp_test.go
- pkg/localstorev2/internal/chunkstamp/export_test.go
- pkg/localstorev2/internal/chunkstore/chunkstore.go
- pkg/localstorev2/internal/chunkstore/chunkstore_test.go
- pkg/localstorev2/internal/chunkstore/export_test.go
- pkg/localstorev2/internal/chunkstore/txchunkstore.go
- pkg/localstorev2/internal/chunkstore/txchunkstore_test.go
- pkg/storagev2/chunkstore.go
- pkg/storagev2/inmemchunkstore/inmemchunkstore.go
- pkg/storagev2/storagetest/chunkstore.go
- pkg/storagev2/storagetest/storage.go
Move the chunk stamp index from the chunk store into a separate package.
Closes #3783
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3820)
> refactor: move out chunk stamp index from chunk store

- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/statestore/leveldb/migration.go
Clearing old overlays from the address book
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3837)
> feat(libp2p): migrate address book

- pkg/postage/batchservice/batchservice_test.go
Setting `TestBatchServiceCreate` as flaky. Issue tracking flaky test fix #3846
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3849)
> chore(postage): set TestBatchServiceCreate as flaky

- pkg/localstorev2/internal/chunkstamp/chunkstamp.go
- pkg/localstorev2/internal/chunkstore/chunkstore.go
- pkg/localstorev2/internal/pinning/pinning.go
- pkg/localstorev2/internal/stampindex/stampindex.go
- pkg/localstorev2/internal/upload/uploadstore.go
- pkg/storagev2/migration/migration.go
- pkg/storagev2/migration/migration_test.go
- pkg/storagev2/storagetest/storage.go
- pkg/storagev2/storagetest/transaction.go
- pkg/storagev2/storageutil/storageutil.go
Closes #3852
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethersphere/bee/3855)
> fix: escape slash separator character

- pkg/pullsync/pullstorage/main_test.go
Fix `TestMain` in `pullstorage` package
> fix(pullstorage): main test

- .github/workflows/release.yaml
Fix release pipeline downloading go1.2
> ci: fix release pipeline

- pkg/node/node.go
- pkg/topology/kademlia/kademlia.go
Increased kademlia ping poll time to 5 minutes
removed chainsync from registered protocols
> perf: increase kademlia ping interval and remove chainsyncer

- pkg/localstorev2/internal/reserve/reserve.go
- pkg/localstorev2/internal/reserve/reserve_test.go
- pkg/localstorev2/reserve.go
> feat(reserve): cache evicted chunks

- pkg/localstore/subscription_push.go
- pkg/localstorev2/internal/upload/uploadstore.go
- pkg/localstorev2/storer.go
- pkg/localstorev2/subscribe_push.go
- pkg/localstorev2/subscribe_push_test.go
- pkg/localstorev2/uploadstore.go
> feat: push subscribe

- pkg/storagev2/metrics.go
- pkg/storagev2/repository.go
Add metrics for the new storage.
Part of #3749
> feat: add metrics for the new storage

- pkg/api/bytes.go
> chore: timeout increase

- pkg/storageincentives/agent.go
- pkg/storageincentives/agent_test.go
> fix: agent uses correct args

- pkg/localstorev2/cachestore.go
- pkg/localstorev2/metrics.go
- pkg/localstorev2/netstore.go
- pkg/localstorev2/pinstore.go
- pkg/localstorev2/reserve.go
- pkg/localstorev2/storer.go
- pkg/localstorev2/uploadstore.go
Add metrics for the new localstore components.
Closes #3749
> feat: add localstore components metrics

- pkg/topology/kademlia/export_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/topology.go
> cleanup(kademlia): remove unused code

- pkg/retrieval/metrics.go
- pkg/retrieval/retrieval.go
Adding metrics as part of  #3876.
> feat: more retrieval metrics

- pkg/api/tag.go
- pkg/api/tag_test.go
- pkg/localstorev2/internal/upload/uploadstore.go
- pkg/localstorev2/internal/upload/uploadstore_test.go
- pkg/localstorev2/mock/mockstorer.go
- pkg/localstorev2/mock/mockstorer_test.go
- pkg/localstorev2/storer.go
- pkg/localstorev2/storer_test.go
- pkg/localstorev2/uploadstore.go
- pkg/storagev2/storage.go
> feat: implement storer ListSessions and DeleteSession

- pkg/node/node.go
> fix: panic in registry

- pkg/chainsyncer/chainsyncer.go
- pkg/chainsyncer/chainsyncer_test.go
- pkg/chainsyncer/main_test.go
- pkg/chainsyncer/metrics.go
- pkg/node/node.go
- pkg/topology/kademlia/kademlia.go
> revert: chainsync removal

- pkg/bmt/bmt.go
- pkg/bmt/proof.go
- pkg/bmt/proof_test.go
- pkg/bmt/trhasher.go
- pkg/swarm/hasher.go
- pkg/swarm/hasher_test.go
- pkg/swarm/swarm.go
This PR adds `NewTrHasher` from  #3823
> feat(bmt): add TrHasher

- pkg/pushsync/metrics.go
- pkg/pushsync/pushsync.go
> chore: cleanup pushsync metrics

- pkg/p2p/libp2p/libp2p.go
> fix(libp2p): set network status to unknow only when the node starts

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/configurateoptions.go
> feat: add comment hints to printconfig

- pkg/bmt/benchmark_test.go
- pkg/bmt/bmt_test.go
- pkg/encryption/encryption_test.go
- pkg/file/joiner/joiner_test.go
- pkg/util/testutil/helpers.go
- pkg/util/testutil/helpers_test.go
This PR adds common `RandBytesWithSeed` utility.
> chore(testutil): add RandBytesWithSeed

- pkg/puller/puller.go
- pkg/puller/puller_test.go
- pkg/pullsync/pullsync.go
- pkg/pullsync/pullsync_test.go
> fix: pullsync returns invalid err to backoff next retry

- pkg/storageincentives/agent.go
- pkg/storageincentives/agent_test.go
> chore(storageincentives): increase min balance

- pkg/postage/service.go
- pkg/postage/service_test.go
> fix: save stamp issuers with the batchID

- pkg/storage/repository.go
- pkg/storer/storer.go
> Fix metrics

- pkg/pullsync/pullstorage/pullstorage_test.go
> chore: mark test `TestIntervalChunks_IteratorShareContextCancellation` as flaky

- pkg/storageincentives/agent.go
- ~~removed optimization because there is no need for optimization as this handled is quite trivial. additionally, this optimization had a flaw because it could actually reduce phase length (potentially this could make issues when playing the game).~~
- adding context to doWork for gracefully handling cancellation
-  doWork called manually when starting in order to set initial data
> fix(storageincentives): agent improvements

- pkg/postage/stamp.go
- pkg/postage/stamp_test.go
- pkg/pullsync/pullsync.go
- pkg/pullsync/pullsync_test.go
- pkg/pusher/pusher.go
- pkg/pusher/pusher_test.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
> perf: validate chunk stamps directly

- pkg/retrieval/retrieval.go
- pkg/swarm/swarm.go
- pkg/swarm/swarm_test.go
We see a lot of retrieval requests with zero address which is causing a lot of failed activity on the mainnet. This PR checks for this and prevents unnecessary retrieval requests.
> fix(retrieval): dont retrieve zero value chunks

- pkg/api/api.go
- pkg/api/debugstorage.go
- pkg/api/debugstorage_test.go
- pkg/api/router.go
- pkg/auth/auth.go
- pkg/storage/inmemstore/inmemstore.go
- pkg/storage/leveldbstore/store.go
- pkg/storer/debug.go
- pkg/storer/debug_test.go
- pkg/storer/internal/cache/cache.go
- pkg/storer/internal/chunkstore/chunkstore.go
- pkg/storer/internal/chunkstore/chunkstore_test.go
- pkg/storer/internal/pinning/pinning.go
- pkg/storer/internal/pinning/pinning_test.go
- pkg/storer/internal/upload/uploadstore.go
- pkg/storer/internal/upload/uploadstore_test.go
- pkg/storer/mock/mockstorer.go
- pkg/storer/storer.go
Add debug information for storer. Add new API to show the information.
> feat(storer): add debug information for storer

- pkg/pullsync/pullsync.go
- pkg/pullsync/pullsync_test.go
- pkg/storage/storage.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/mock/mockreserve.go
- pkg/storer/storer.go
> fix: pullsync ignore overwrite error

- pkg/storageincentives/agent.go
- pkg/storageincentives/events.go
- pkg/storageincentives/events_test.go
- pkg/storageincentives/redistributionstate.go
Since previous phase value is not need in callback anymore, callback func signature was simplified.
> chore(storageincentives): simplify events callback

- pkg/status/status.go
fixed a panic (reading nil pointer)
also made status requests parallel
> fix(status): panic reading snapshot field on error

- pkg/api/router.go
Fix status endpoint panic on node startup before debug endpoints are available.
> fix(api): status endpoint panic on node start

- pkg/node/node.go
> fix(metrics): register chainsyncer

- pkg/jsonhttp/jsonhttptest/jsonhttptest.go
- pkg/jsonhttp/jsonhttptest/jsonhttptest_test.go
- pkg/jsonhttp/jsonhttptest/testing_mock_test.go
- Add option factory for asserting response header values with `WithExpectedResponseHeader`
- Improved internal helper function `assert` to assert multiple errors; and not just last one
> feat(jsonhttp): add options for checking response headers

- pkg/storageincentives/agent.go
- pkg/storageincentives/events.go
- pkg/storageincentives/events_test.go
- pkg/storageincentives/redistributionstate.go
This PR is not making any changes to agent logic. The only scope of this change is to introduce better naming and code organization of agent handlers.
> chore(storageincentives): agent event handler improvements

- openapi/SwarmCommon.yaml
- pkg/api/redistribution.go
- pkg/storageincentives/agent.go
> feat(storageincentives): return min required funds

- pkg/puller/puller.go
Do not exit on statestore err.
> fix(puller): continue and retry on statestore error

- pkg/retrieval/retrieval.go
- pkg/swarm/swarm.go
- pkg/swarm/swarm_test.go
> fix(retrieval): reject invalid length chunk address

- pkg/pullsync/pullsync.go
> fix: reduce logs

- pkg/traversal/traversal.go
The traversal package was broken as we did not handle encrypted references. This was recently changed to handle SOC chunks that failed traversal. This broke the encrypted reference handling.
> fix(traversal): handle encrypted references

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
- pkg/p2p/libp2p/internal/handshake/handshake.go
> chore: bump openapi and handshake version for release

- pkg/config/chain.go
- Fixed token names for mainnet
- default branch of GetByChainID func will return Testnet config - it's unnecessary to recreate it here
> chore(chain-config): fix token names

- pkg/storageincentives/agent.go
- pkg/storageincentives/redistributionstate.go
- pkg/storageincentives/redistributionstate_test.go
This PR adds mechanism for purging stale round data from redistribution state.
> feat(storageincentives): purge round data

- .github/workflows/beekeeper.yml
bee clef is marked as deprecated so this removes the ci clef integration tests
> chore: remove clef tests

- pkg/puller/puller.go
- pkg/pullsync/pullsync.go
- pkg/storage/storage.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/storer.go
> fix: merge

- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
> feat(kademlia): allow light nodes to be picked in oversaturated bins

- pkg/api/status.go
> fix(status): include batch total amount

- pkg/node/node.go
- pkg/pushsync/pushsync.go
- pkg/pushsync/pushsync_test.go
- pkg/skippeers/skippeers_test.go
> fix(pushsync): best attempt to find next peer

- openapi/SwarmCommon.yaml
- pkg/api/peer.go
- pkg/p2p/libp2p/connections_test.go
- pkg/p2p/libp2p/internal/blocklist/blocklist.go
- pkg/p2p/libp2p/internal/blocklist/blocklist_test.go
- pkg/p2p/libp2p/libp2p.go
- pkg/p2p/p2p.go
> fix(blocklist): duration and full node fix

- pkg/api/api.go
Add debug log message on put chunk failure.
#4036
> feat: log error on put chunk failure

- pkg/pushsync/pushsync.go
- pkg/topology/kademlia/kademlia.go
Add more logging to improve debugging.
> feat: add log messages

- pkg/storage/testing/chunk.go
- pkg/storer/internal/reserve/items.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/internal/reserve/reserve_test.go
- pkg/swarm/swarm.go
Adding information about type of chunks. 
Closes: #4017
Note: Tests and lint steps are failing because localstorev2 branch has issues.
> feat: add chunk type information to reserve

- pkg/retrieval/retrieval.go
> fix(retrieval): select peer before go routine push attempt

- pkg/topology/kademlia/kademlia.go
> fix(kad): race cond

- pkg/storageincentives/agent.go
Fix for race condition in commit event handler.
> fix: race condition in commit event handler

- pkg/storageincentives/agent.go
- pkg/storageincentives/agent_test.go
- pkg/storageincentives/export_test.go
- pkg/storageincentives/proof.go
- pkg/storageincentives/proof_test.go
- pkg/storer/mock/mockreserve.go
- pkg/storer/reserve.go
- pkg/storer/reserve_test.go
- pkg/swarm/swarm.go
These changes are needed by PR https://github.com/ethersphere/bee/pull/4040. They are made in individual PR in order to prevent future merge conflicts on https://github.com/ethersphere/bee/pull/4040.
> chore(reserve): sample data improvements

- pkg/storageincentives/agent.go
> fix: last played round

- pkg/api/api_test.go
- pkg/node/node.go
- pkg/storageincentives/agent.go
- pkg/storageincentives/agent_test.go
- pkg/storageincentives/proof_test.go
- pkg/storageincentives/redistributionstate.go
- pkg/storageincentives/redistributionstate_test.go
- pkg/storer/mock/mockreserve.go
- pkg/storer/reserve.go
- pkg/storer/reserve_test.go
- pkg/storer/storer.go
Exclude batches from sample with low balance.
> feat(sample): exclude batches with low balance

- pkg/postage/stampissuer.go
Fix marshal/unmarshal for the stamp issuer.
> Fix stamp issuer marshal

- pkg/statestore/test/store.go
- pkg/storage/statestore.go
Fix the state store adapter iterator.
> fix: state store adapter iterator

- pkg/pusher/metrics.go
- pkg/pusher/pusher.go
- pkg/retrieval/retrieval.go
- pkg/salud/salud.go
- pkg/status/status.go
includes a panic fix in status protocol.
fix for retrieval goroutine leak
> fix(pusher, retrieval, salud):  panic and leak fix

- pkg/storage/inmemchunkstore/transaction.go
- pkg/storage/inmemstore/transaction.go
- pkg/storage/leveldbstore/transaction.go
- pkg/storage/transaction.go
Fixes the memory leak on the transaction bookeeping.
> fix: transaction bookeeping memory leak

- .github/workflows/release.yaml
- .goreleaser.yml
upgrade actions and fix soon to deprecated gorelaser options
> ci: upgrade actions and fix soon to deprecated gorelaser options

- pkg/storer/cachestore.go
- pkg/storer/internal/stampindex/stampindex.go
- pkg/storer/metrics.go
- pkg/storer/reserve.go
- pkg/storer/storer.go
Adding more metrics. Pretty self-descriptive.
> chore(storer): add more metrics

- pkg/storage/storagetest/benchmark.go
- pkg/storer/cachestore_test.go
- pkg/storer/internal/cache/cache.go
Add benchmark for Cache putter. Also fix logic in benchmark suite. Moving mutex to avoid duplicate chunks in the cache.
> chore: add benchmark for cache putter

- pkg/skippeers/skippeers.go
Under heavy uploads, the skippeers is still taking up a lot of unnecessary CPU. so we simply the whole thing by relying on a ticker to cleanup the items.
> perf(skippers): further optimizations

- pkg/api/api.go
- pkg/api/auth_test.go
- pkg/api/bytes.go
- pkg/api/bytes_test.go
- pkg/api/bzz.go
- pkg/api/bzz_test.go
- pkg/api/chequebook_test.go
- pkg/api/chunk.go
- pkg/api/chunk_stream_test.go
- pkg/api/cors_test.go
- pkg/api/dirs.go
- pkg/api/dirs_test.go
- pkg/api/export_test.go
- pkg/api/pin_test.go
- pkg/api/postage_test.go
- pkg/api/redistribution_test.go
- pkg/api/staking_test.go
- pkg/api/subdomain_test.go
- pkg/api/tag_test.go
- pkg/api/topology.go
- add header constants
- improved headers listed in "Access-Control-Allow-Headers"
Closes: #4079
> chore(api): headers cleanup

- pkg/storer/reserve.go
Panic on eviction in lightnode and bootnodes. Should be a noop.
> fix(storer): handle eviction on light and bootnodes

- pkg/storage/transaction.go
Transaction methods now return a `contex.Canceled` error if the parent context was canceled before marking the transaction as completed.
> fix: transaction return a contex.Canceled error when the parent context is canceled

- pkg/hive/hive.go
> fix(hive): do not gossip private CIDRs unless explicitly allowed

- pkg/storage/inmemstore/inmemstore.go
- pkg/storage/leveldbstore/store.go
- pkg/storage/leveldbstore/transaction.go
- pkg/storage/repository.go
- pkg/storer/cachestore.go
- pkg/storer/internal/chunkstamp/chunkstamp.go
- pkg/storer/internal/chunkstore/chunkstore.go
- pkg/storer/internal/internal.go
- pkg/storer/pinstore.go
- pkg/storer/reporter.go
- pkg/storer/reserve.go
- pkg/storer/storer.go
- pkg/storer/uploadstore.go
> refactor: improve errors

- pkg/storer/internal/reserve/reserve.go
From the dashboards, it seems like ReserveHas is the slowest operation. This is a minor change to improve that.
> perf: improve ReserveHas

- openapi/SwarmCommon.yaml
- pkg/api/redistribution.go
- pkg/storageincentives/agent.go
- pkg/storageincentives/redistributionstate.go
- pkg/storageincentives/redistributionstate_test.go
> chore(agent): show sample duration in endpoint, cleanup, reduce required min funds slightly

- cmd/bee/cmd/db.go
- cmd/bee/cmd/db_test.go
- pkg/statestore/mock/store.go
- pkg/storage/statestore.go
Add `db nuke` and `db info` commands
#3907
> feat: add db nuke and db info cmd

- pkg/storageincentives/proof.go
- pkg/storer/export_test.go
- pkg/storer/reserve.go
localstorev2 branch had some changes related to ph4 sampling. In this PR this logic is temporally commented out and appropriate logic for ph3 is added.
> feat: ph3 sample

- pkg/bmt/bmt.go
- pkg/postage/export_test.go
- pkg/postage/stamp.go
- pkg/postage/stamp_test.go
- pkg/postage/stampissuer.go
- pkg/soc/export_test.go
- pkg/soc/soc.go
- pkg/soc/validator.go
This PR  exports various method which are used for ph4 logic.
> chore: export methods 

- pkg/storer/reserve.go
- pkg/storer/sample.go
- pkg/storer/sample_test.go
- removed `SampleStats.String()` - this struct could be easily formatted using `"%+v"` pattern
- adding more information to stats
- added SampleStats to Sample struct - this enables tests to additionally assert sampling logic
> chore(sampling): stats improvements

- pkg/storageincentives/agent.go
> fix(agent): check frozen status before neighborhood selection and remove some logs

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
- pkg/api/api_test.go
- pkg/api/chunk_stream.go
- pkg/api/chunk_stream_test.go
- pkg/api/chunk_test.go
- pkg/api/router.go
- pkg/api/soc.go
- pkg/api/soc_test.go
- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/topology/kademlia/kademlia.go
Updated the openapi spec. During the update I found some small issues which are now fixed. Also bump of versions and revert of temporary fix for reachability.
> chore(openapi): update and bump versions

- pkg/statestore/storeadapter/migration.go
Temporary migration for unblocking testnet testing.
> chore: temp migration for testnet

- pkg/puller/puller.go
- pkg/statestore/storeadapter/migration.go
> fix(puller): histsync timeout should be higher than makeoffer

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/bytes.go
- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/chunk_stream.go
- pkg/api/feed.go
- pkg/api/postage.go
- pkg/api/postage_test.go
- pkg/api/soc.go
- pkg/api/soc_test.go
- pkg/node/node.go
- pkg/node/statestore.go
- pkg/node/statestore_test.go
- pkg/postage/batchservice/batchservice.go
- pkg/postage/batchservice/batchservice_test.go
- pkg/postage/batchstore/store.go
- pkg/postage/interface.go
- pkg/postage/mock/service.go
- pkg/postage/service.go
- pkg/postage/service_test.go
- pkg/postage/stampissuer.go
- pkg/postage/stampissuer_test.go
Move stamperIssuer data from statestore to stamperstore
#4129
> feat: move stamp issuer to stamperstore

- pkg/postage/service.go
Ignore the not found entries for expiry event.
> fix: ignore not found entries for expiry event

- pkg/storer/metrics.go
> fix(storer): metric fix

- pkg/api/api.go
- pkg/api/postage.go
- pkg/api/pss.go
- pkg/api/stewardship.go
- pkg/postage/export_test.go
- pkg/postage/mock/service.go
- pkg/postage/service.go
- pkg/postage/service_test.go
- pkg/pusher/pusher.go
Fixes:
1. Batch in use was not being cleared on error.
2. During direct upload respond with success for Put if there is an inflight op already for the chunk.
> fix: issues with direct upload and stamper cleanup

- pkg/statestore/leveldb/leveldb.go
- pkg/statestore/leveldb/migration.go
- pkg/statestore/storeadapter/storeadapter.go
- pkg/storage/inmemchunkstore/transaction.go
- pkg/storage/inmemstore/inmemstore.go
- pkg/storage/inmemstore/transaction.go
- pkg/storage/leveldbstore/batch.go
- pkg/storage/leveldbstore/recovery.go
- pkg/storage/leveldbstore/recovery_test.go
- pkg/storage/leveldbstore/store.go
- pkg/storage/leveldbstore/transaction.go
- pkg/storage/storage.go
- pkg/storage/transaction.go
- pkg/storer/epoch_migration.go
- pkg/storer/internal/chunkstore/chunkstore.go
- pkg/storer/internal/chunkstore/recovery.go
- pkg/storer/internal/chunkstore/recovery_test.go
- pkg/storer/internal/chunkstore/transaction.go
- pkg/storer/internal/chunkstore/transaction_test.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/sample_test.go
- pkg/storer/storer.go
In-progress transaction recovery mechanism on node crash. 
Closes #4085
> feat: tx crash recovery mechanism

- pkg/node/statestore.go
- pkg/storage/cache/cache.go
- pkg/storage/cache/cache_test.go
- pkg/storage/cache/metrics.go
Improvements and cleanups for storage cache.
> refactor(cache): cleanup

- pkg/storage/leveldbstore/transaction.go
Removes LevelDB sync true option in order to speed up operations.
> perf: remove leveldb sync true option

- pkg/storer/internal/chunkstamp/chunkstamp.go
Handle not found while deleting stamp. Swallow the error.
> fix: best effort cleanup bug

- cmd/bee/cmd/cmd.go
> perf(leveldb): disable seek compaction

- pkg/storer/reserve.go
- pkg/storer/sample.go
proof of concept: periodic cleanup of expired chunks from the reserve.
during bootup, in a reserve of 2M chunks, the process took 11 seconds on the testnet.
> feat: periodic cleanup of expired chunks from the reserve

- pkg/pullsync/pullsync.go
> fix: metrics

- cmd/bee/cmd/cmd.go
- pkg/postage/batchstore/mock/store.go
- pkg/storage/metrics.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/metrics.go
- pkg/storer/reserve.go
> fix(reserve): optimizing the cleanup worker

- Makefile
- pkg/api/api.go
- pkg/api/bytes.go
- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/chunk_stream.go
- pkg/api/feed.go
- pkg/api/postage.go
- pkg/api/pss.go
- pkg/api/soc.go
- pkg/api/stewardship.go
- pkg/node/node.go
- pkg/postage/mock/service.go
- pkg/postage/postagecontract/contract_test.go
- pkg/postage/service.go
- pkg/postage/service_test.go
- pkg/pullsync/pullsync.go
- pkg/pusher/pusher.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/metrics.go
- pkg/storer/reserve.go
- pkg/storer/reserve_test.go
- pkg/storer/storer.go
- pkg/storer/subscribe_push.go
- Allow uploads to wait till we have batch available to use
- Simplify eviction flow. Also, revert the expiration handling to old way.
- Multiple parallel deferred uploads cause SubscribePush to fail
- Puller has to reiterate intervals on failures
> fix: issues from public testnet testing

- pkg/storage/leveldbstore/store.go
- pkg/storer/internal/internal.go
- pkg/storer/internal/pinning/pinning.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/internal/upload/uploadstore.go
- pkg/storer/pinstore.go
- pkg/storer/reserve.go
- pkg/storer/storer.go
- pkg/storer/uploadstore.go
Removes unnecessary RWLock operations on LevelDB and introduces some cleanup
> refactor(leveldbstore): remove unnecessary rw-lock

- pkg/storer/metrics.go
- pkg/storer/storer.go
Introduces LevelDB stats for fine-tuning.
> feat(storer): introduce LevelDB stats

- pkg/storage/leveldbstore/transaction.go
Enhancements to the LevelDB Put and Delete transactional store calls when no transaction exists.
> perf: improve leveldb tx store calls when no transaction exists

- pkg/storage/storagetest/batch.go
Closes store at the end of batched store test.
> fix(storagetest): close store at the end of batched store test

- pkg/node/statestore.go
- pkg/storage/leveldbstore/store.go
- pkg/storer/storer.go
Contains several LevelDB settings to improve performance according to the following recommendations: https://github.com/google/leveldb/blob/main/doc/index.md#performance
> perf: levelDB options tuning

- pkg/node/statestore.go
Fixes current broken build on master: https://github.com/ethersphere/bee/actions/runs/5530530019/jobs/10090040507
> fix(node): remove unused import

- pkg/pullsync/pullsync.go
Closes:
https://github.com/ethersphere/bee/issues/4210
https://github.com/ethersphere/bee/issues/4209
> fix: pullsync error log and reader initialization

- openapi/Swarm.yaml
Added clarification for description of /chunk and /stewardship endpoints. Corrected inconsistent capitalization of "chunk". Removed non-relevant sample 200 response for HEAD /chunks.
> chore: added clarification to openapi spec descriptions

- pkg/storer/reserve.go
> fix: evict log

- pkg/storer/epoch_migration.go
- pkg/storer/internal/internal.go
- pkg/storer/internal/pinning/pinning.go
- pkg/storer/internal/pinning/pinning_test.go
- pkg/storer/internal/upload/uploadstore.go
- pkg/storer/internal/upload/uploadstore_test.go
- pkg/storer/pinstore.go
- pkg/storer/uploadstore.go
> feat: uploadstore uses batches

- cmd/bee/cmd/db_test.go
- pkg/storer/epoch_migration_test.go
> chore: tag flaky tests

- pkg/statestore/storeadapter/migration.go
> fix(migration): reset puller intervals

- pkg/storage/repository.go
- pkg/storer/storer.go
On testing, we found some issues with uploader nodes missing some chunks. We found that there could be races in the chunkstore when multiple components use it simultaneously. So there is a need for chunk level lock to ensure refcnts work as expected.
> fix: synchronize chunkstore ops

- pkg/statestore/storeadapter/migration.go
- pkg/statestore/storeadapter/storeadapter.go
- pkg/storage/cache/cache.go
- pkg/storage/leveldbstore/transaction.go
- pkg/storage/migration/index.go
- pkg/storage/migration/migration.go
- pkg/storage/migration/migration_test.go
- pkg/storage/migration/steps_chain.go
- pkg/storage/migration/steps_chain_test.go
- pkg/storer/internal/chunkstore/chunkstore.go
- pkg/storer/internal/chunkstore/export_test.go
- pkg/storer/internal/chunkstore/helpers.go
- pkg/storer/internal/reserve/export_test.go
- pkg/storer/internal/reserve/items.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/migration/all_steps.go
- pkg/storer/migration/all_steps_test.go
- pkg/storer/migration/export_test.go
- pkg/storer/migration/step_01.go
- pkg/storer/migration/step_02.go
- pkg/storer/migration/step_03.go
- pkg/storer/migration/step_03_test.go
- pkg/storer/reserve.go
- pkg/storer/storer.go
- pkg/storer/storer_test.go
> fix(reserve): reconstruct binIDs

- openapi/SwarmCommon.yaml
- openapi/SwarmDebug.yaml
Bump the minor version of debug and common API specs.
> docs: bump api version

- pkg/statestore/storeadapter/migration.go
> chore(puller): reset sync intervals post 1.17.2 migration release

- packaging/docker/README.md
- packaging/docker/docker-compose.yml
- packaging/docker/env
Removed all clef occurrences from bee' docker-compose
> feat: remove all clef from docker-compose

- pkg/retrieval/retrieval.go
Should boost retrieval success rate and performance.
> feat(retrieval): use healthy peers for requests

- .goreleaser.yml
- packaging/homebrew-amd64/bee-get-addr
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee-get-addr
- packaging/homebrew-arm64/bee.yaml
- brew itself deprecated using `plist` for managing services
- removed clef from post install script and config file
> ci: fix publishing and installing from brew

- openapi/SwarmCommon.yaml
- pkg/pushsync/pushsync.go
- pkg/storer/internal/reserve/reserve.go
> fix(openapi): default upload method is now direct

- pkg/transaction/transaction.go
Logs confirmation of pending transaction in info level.
Closes #3346
> chore: log pending transaction confirmation in info level

- pkg/storer/internal/chunkstore/chunkstore.go
- pkg/storer/migration/all_steps.go
- pkg/storer/migration/export_test.go
- pkg/storer/migration/step_05.go
- pkg/storer/migration/step_05_test.go
> fix(chunkstore): increase refCnt capacity

- pkg/node/node.go
> chore(mining): logging improvements

- pkg/puller/puller.go
> fix(puller): cleanup log messages

- openapi/SwarmDebug.yaml
- pkg/api/postage.go
- pkg/api/postage_test.go
> feat(postage): default batch type is now immutable

- pkg/node/devnode.go
- pkg/storageincentives/staking/mock/contract.go
Fixes panic on staking API in the dev mode.
Closes #4022
> fix: panic on staking API in the dev mode

- cmd/bee/cmd/start.go
> fix: default bootnode address for the testnet

- pkg/bmt/bmt.go
- pkg/bmt/proof.go
- pkg/bmt/proof_test.go
- pkg/bmt/trhasher.go
- pkg/storer/sample.go
- pkg/swarm/hasher.go
- pkg/swarm/hasher_test.go
> revert: 1f84ef4 ph4 bmt

- pkg/storer/metrics.go
- pkg/storer/reserve.go
> feat(reserve): new worker and metric for reserve size within radius

- pkg/storageincentives/agent.go
- pkg/transaction/transaction.go
- pkg/transaction/transaction_test.go
> fix(transaction): swallow estimate gas error

- pkg/pusher/metrics.go
- pkg/pushsync/metrics.go
> chore: metrics clean up

- go.mod
- go.sum
- pkg/pusher/pusher.go
> chore: update si

- pkg/storage/leveldbstore/recovery.go
- pkg/storer/internal/chunkstore/recovery.go
Enriches the transaction store and transaction chunkstore `Recovery` methods with logging.
Closes #4363
> feat: add logs to the txstore and txchunkstore recovery method

- pkg/pusher/pusher.go
- pkg/sharky/shard.go
> chore(pusher): logging address of shallow receipt

- pkg/storer/compact.go
- pkg/storer/compact_test.go
> fix(compact): mark already used slots

- pkg/storer/compact_test.go
> chore: extra unit test for compaction

- .github/patches/postage_api.patch
- pkg/api/postage.go
- pkg/api/postage_test.go
> chore: lower min depth

- CODING.md
Adds logger API usage section.
> doc: add logger API usage section

- pkg/node/node.go
- pkg/topology/kademlia/export_test.go
- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
- pkg/topology/topology.go
closes https://github.com/ethersphere/bee/issues/4409
> fix: kademlia to use storage radius as neighborhood depth

- pkg/node/node.go
- pkg/node/statestore.go
- pkg/postage/service.go
- pkg/postage/service_test.go
> fix: delete expired stamp issuers

- pkg/retrieval/retrieval.go
- pkg/storer/compact_test.go
- pkg/storer/internal/cache/cache.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/internal/reserve/reserve_test.go
> fix: make cache ops independent of parent context

- pkg/storer/reserve.go
> fix(worker): evicts batch only once

- .github/patches/retrieval.patch
- .github/workflows/beekeeper.yml
- pkg/postage/export_test.go
- pkg/postage/service.go
- pkg/postage/service_test.go
- pkg/postage/stamper.go
- pkg/postage/stampissuer.go
- pkg/retrieval/retrieval.go
- retrieval.patch
> fix(stamperstore): remove stamps belonging to expired batches

- pkg/postage/listener/listener.go
log the sleep duration only when the next window in not paged
> fix(listener): log sleep duration more accurately

- cmd/bee/cmd/db.go
- pkg/puller/metrics.go
- pkg/puller/puller.go
- pkg/storer/reserve.go
closes #4442
also fixes the nuke cmd to not remove the root folder.
> fix(puller): start syncing of peers in parallel

- pkg/statestore/leveldb/migration.go
This migration cleansup batchstore for the batch migration from Goerli to Sepolia.
> feat: batchstore cleanup for sepolia migration

- pkg/replicas/export_test.go
- pkg/replicas/getter.go
- pkg/replicas/getter_test.go
- pkg/replicas/putter.go
- pkg/replicas/putter_test.go
- pkg/replicas/replica_test.go
- pkg/replicas/replicas.go
TO BE REBASED ON #4448 AND MERGED TO ERASURE FEATURE BRANCH 
implementation of dispersed replicas as per BOS sec 5.1.3 Incomplete chunks and dispersed replicas p160
> feat(replicas): new replicas pkg for redundancy by dispersed replicas

- .github/patches/minradius.patch
- .github/patches/postagecontract.patch
- .github/patches/postagereserve_gc.patch
- .github/patches/postageservice.patch
- .github/workflows/beekeeper.yml
- pkg/node/node.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/internal/reserve/reserve_test.go
- pkg/storer/storer.go
- pkg/storer/storer_test.go
> fix: unit tests and integration tests after patch

- pkg/statestore/storeadapter/migration.go
> chore: resync intervals after release

- .github/patches/minradius.patch
- .github/workflows/beekeeper.yml
- pkg/node/node.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/internal/reserve/reserve_test.go
- pkg/storer/reserve.go
- pkg/storer/storer.go
- pkg/storer/storer_test.go
> chore: removed min storage radius threshold

- pkg/puller/puller.go
> fix: missing puller metric

- pkg/puller/puller.go
> fix(puller): rate limit hist sync only

- pkg/file/joiner/joiner.go
- pkg/file/joiner/joiner_test.go
- pkg/file/pipeline/builder/builder.go
- pkg/file/pipeline/hashtrie/hashtrie.go
- pkg/file/pipeline/hashtrie/hashtrie_test.go
- pkg/file/redundancy/getter/getter.go
- pkg/file/redundancy/level.go
- pkg/file/redundancy/redundancy.go
- pkg/file/utils.go
- pkg/replicas/export_test.go
- pkg/replicas/getter.go
- pkg/replicas/getter_test.go
- pkg/replicas/putter.go
- pkg/replicas/putter_test.go
- pkg/replicas/replicas.go
> feat: replicas integration

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- pkg/api/api.go
- pkg/api/bzz.go
- pkg/api/dirs.go
- pkg/file/joiner/joiner_test.go
- pkg/file/redundancy/getter/getter.go
- pkg/file/redundancy/getter/strategies.go
API support and headers integration for redundancy decoder parameters
> feat(redundancy): api headers integration

- pkg/storer/reserve.go
> fix: radius metric

- pkg/postage/service_test.go
- pkg/postage/stampissuer_test.go
- pkg/storer/reserve_test.go
> fix(postage_service): unit test

- pkg/storer/debug.go
> fix: panic on debugstore endpoint in light/ultralight mode

- cmd/bee/cmd/split.go
- pkg/storer/cachestore.go
- pkg/storer/storer.go
> chore: use the regular split pipeline

- Dockerfile
- Dockerfile.goreleaser
- Dockerfile.scratch
> chore: update docker base image

- pkg/storer/internal/cache/cache.go
> fix(cache): added mutex protection at chunk and eviction levels

- pkg/postage/stamper.go
- pkg/postage/stamper_test.go
- pkg/postage/stampissuer.go
Updated stamper index assignment rules
Closes #4539
> feat: stamper index assignment rule update

- pkg/storer/internal/cache/cache.go
- pkg/storer/internal/cache/cache_test.go
- pkg/storer/internal/cache/export_test.go
- pkg/topology/kademlia/kademlia_test.go
RemoveOldest is decrementing the wrong amount from the cache size.
> fix: cache size fix

- CODINGSTYLE.md
Fix broken table and some minor changes.
> fix(doc): minor additions

- pkg/api/bytes.go
- pkg/api/bzz.go
- pkg/file/joiner/joiner_test.go
- pkg/file/redundancy/getter/strategies.go
- pkg/retrieval/retrieval.go
Fixed strategy timeout using the wrong context key.
improved headers parsing.
> fix: strategy and fetch timeout parsing

- .github/workflows/codeql.yml
This PR adds CodeQL to the repo.
To enable this, go to repo settings -> Security : Code security and analysis -> Code scanning: Enable
Please not that it requires the following actions: 
```
actions/*,
github/codeql-action/*,
```
Which can be found in Settings -> Code and automation  -> Actions -> General -> Allow specific actions and reusable workflows
https://github.com/ethersphere/bee/issues/4324
> feat: add codeql.yml

- openapi/SwarmCommon.yaml
The 200 response was missing in the SwarmCommon.yaml file.
> fix: missing 200 response

- pkg/api/bzz_test.go
> fix(redundancy): bzz unit test

- pkg/file/joiner/joiner_test.go
- pkg/node/node.go
- pkg/p2p/libp2p/internal/handshake/handshake.go
- pkg/postage/batchstore/store_test.go
- pkg/storer/sample.go
- pkg/topology/kademlia/kademlia.go
> chore: remove repetitive words

- cmd/bee/cmd/start.go
Use neighborhood suggester option only on mainnet
> fix: use neighborhood suggester only on mainnet

- .goreleaser.yml
- Makefile
> fix: missing v2 in the makefile and goreleaser

- .github/workflows/release.yaml
- .goreleaser.yml
> chore: upgrade release actions and remove deprecated goreleaser options

- go.mod
- go.sum
> chore: update abi testnet

- cmd/bee/cmd/db.go
closes https://github.com/ethersphere/bee/issues/4668
> chore: added extra logs before sleeping after db cmd

- .github/workflows/release.yaml
- .goreleaser.yml
> chore: bump goreleaser to v2

- pkg/hive/hive_test.go
[Issue](https://github.com/ethersphere/bee/issues/3397)
> fix: Investigate TestBroadcastPeers failing flaky test

- pkg/storageincentives/staking/contract_test.go
Fix for contract failing tests.
> fix: added back missing gas limit boolean values in contract constructor

- pkg/storageincentives/staking/contract.go
- pkg/storageincentives/staking/contract_test.go
> fix: is node frozen check

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- packaging/bee.yaml
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
- pkg/node/node.go
Making possible to set in the config file the minimum radius storage.
> feat: minimum radius storage treshold configurable option

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start_dev.go
- packaging/bee.yaml
- packaging/docker/env
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
Update default `api-addr`
closes #4731
> fix: update default api-addr

- pkg/pullsync/pullsync.go
Add stamphash to `wantChunks` ID
#4738
> fix: add stamphash to wantchunks id

- pkg/node/node.go
> fix: mine new overlay log fix

- CODING.md
- packaging/bee.yaml
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
Fixes [#4691](https://github.com/ethersphere/bee/issues/4691)
> fix: consistent quotation in config files

- pkg/puller/puller.go
- pkg/pullsync/pullsync.go
> opt: reduce unnecessary pullsyncing 

- pkg/topology/kademlia/kademlia.go
> fix(kademlia): tweak saturation count

- pkg/topology/kademlia/kademlia.go
- pkg/topology/kademlia/kademlia_test.go
> fix(prune): prune func does not count peers correctly

- pkg/node/node.go
- pkg/storageincentives/redistribution/redistribution.go
- pkg/storageincentives/redistribution/redistribution_test.go
There is no claim tx happening in the redistribution game, this PR intended to fix that problem.
> fix: passing is winner param

- pkg/p2p/libp2p/internal/reacher/reacher_test.go
> fix: reacher aggresive retry duration

- openapi/SwarmCommon.yaml
> docs: typo

- openapi/SwarmCommon.yaml
Update API doc enums to match API return values
#4620
> docs: fix API doc enums

- pkg/file/redundancy/getter/getter.go
resolves flakiness of redundancy get
> fix(redundancy): getter flakiness

- pkg/p2p/libp2p/internal/handshake/handshake.go
Bump handshake protocol to version 12.0.0.
> chore: bump handshake protocol version to v12.0.0

- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/start.go
- packaging/bee.yaml
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
- pkg/node/node.go
- pkg/storer/storer.go
Rename "reserve-minimum-radius" to "minimum-storage-radius"
> chore: rename reserve minimum radius to minimum storage radius

- pkg/node/node.go
- pkg/postage/listener/listener.go
> fix: paused topic added to topics

- pkg/statestore/storeadapter/migration.go
> chore: reset sync interval

- pkg/storer/internal/reserve/reserve.go
- pkg/storer/internal/reserve/reserve_test.go
Overwrite same chunk only with same batchID
> Fix overwrite same chunk only with same batchid

- pkg/storer/internal/reserve/reserve.go
- pkg/storer/internal/stampindex/stampindex.go
- pkg/storer/internal/stampindex/stampindex_test.go
- pkg/storer/migration/step_06.go
Added an extra check at the end of the migration.
Added DeleteWithStamp to stampIndex store.
Made sure Deletes are added to the transaction before the store to avoid any accidental overwrites of batch operations.
Also, no overwrite error should be returned if the
> chore: extra checks in step 6 migration and small changes to transaction op steps

- pkg/storer/internal/upload/uploadstore.go
Fixes issue [4632](https://github.com/ethersphere/bee/issues/4632)
> fix: print batch id in failed to read upload item log

- pkg/api/readiness.go
- pkg/api/readiness_test.go
> fix: add payload to readiness endpoint

- pkg/storer/internal/reserve/reserve.go
- pkg/storer/internal/reserve/reserve_test.go
- pkg/storer/migration/step_06.go
Reserve reset should also remove binID items
> fix(reserve): reset binIDs as well

- pkg/node/node.go
- pkg/storer/storer.go
> fix(node): close localstore if migration errors out

- pkg/node/node.go
Fixes [#4840](https://github.com/ethersphere/bee/issues/4840)
> fix: add overlay to api service so it shows earlier in the api request

- pkg/api/router.go
- pkg/node/node.go
Fixes [#4821](https://github.com/ethersphere/bee/issues/4821)
> fix: get wallet endpoint available if swap not enabled

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
- pkg/api/rchash.go
Fixes [#4838](https://github.com/ethersphere/bee/issues/4838)
> fix: show rchash duration response in seconds

- pkg/api/api_test.go
- pkg/node/node.go
- pkg/salud/salud.go
- pkg/salud/salud_test.go
- pkg/storageincentives/agent.go
- pkg/storageincentives/agent_test.go
- pkg/storer/mock/mockreserve.go
- pkg/storer/reserve.go
- pkg/storer/sample.go
- pkg/storer/sample_test.go
part 9 of https://github.com/ethersphere/bee/issues/4842
> fix(redistribution): reveal with correct depth, swip21

- pkg/transaction/backend.go
Fixes [#4851](https://github.com/ethersphere/bee/issues/4851)
> fix: rename ethereum in log

- pkg/settlement/swap/chequebook/chequebook.go
fix some function names in comment
> chore(pkg): fix some function names in comment

- .golangci.yml
- pkg/statestore/leveldb/leveldb_test.go
- pkg/statestore/mock/store_test.go
- pkg/storage/storage_test.go
Starting from [3831](https://github.com/ethersphere/bee/issues/3831) enabled more paralel tests lint check
> fix: enable more paralel tests lint check

- pkg/log/httpaccess/http_access.go
Closes [#4845](https://github.com/ethersphere/bee/issues/4845)
> fix: change api access log level to debug

- pkg/api/router.go
- pkg/api/router_test.go
- pkg/node/node.go
reverts https://github.com/ethersphere/bee/pull/4859
> Reverts "get wallet endpoint available if swap not enabled"

- .github/CODEOWNERS
> feat: adds @istae and @acha-bill as required approvers for commits

- .github/workflows/beekeeper.yml
- pkg/feeds/getter_test.go
- pkg/storage/inmemchunkstore/inmemchunkstore.go
> fix: add TestGetWrappedChunk

- cmd/bee/main.go
- openapi/Swarm.yaml
> fix: update openapi spec

- openapi/SwarmCommon.yaml
- [x ] I have read the [coding guide](https://github.com/ethersphere/bee/blob/master/CODING.md).
- [x ] My change requires a documentation update, and I have done it.
- [x ] I have added tests to cover my changes.
- [ x] I have filled out the description and linked the related issues.
Fix default value for swarm-deferred-upload
> docs: update default value for swarm-deferred-upload

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
…neighborhoods
fix openapi spec for `/status/neighborhoods` and `/status/peers`
[Wrong OpenAPI response sample for /status/peers and /status/neighborhoods #4961 ](https://github.com/ethersphere/bee/issues/4961)
> fix(openapi): correct OpenAPI response

- go.mod
- go.sum
- pkg/api/router.go
adds fgprof which enabled off and on cpu profling.
> feat: fgprof off-cpu profiling

- pkg/storer/internal/upload/uploadstore.go
- pkg/storer/internal/upload/uploadstore_test.go
Fixes [4980](https://github.com/ethersphere/bee/issues/4980)
> fix: delete tag from chunck if tag deleted or not found

- pkg/node/node.go
Use `maxAllowedDoubling` variable in error message
fixes #5014
> refactor: max allowed doubling

- pkg/storer/internal/upload/uploadstore.go
> fix: continue pushing chunks if tag deleted

- pkg/crypto/crypto.go
use a more direct and less error-prone return value
> refactor: use a more direct and less error-prone return value

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
Removed out of date auth related entries from OpenAPI specs
> docs: remove outdated auth related entries

- .github/workflows/beekeeper.yml
- cmd/bee/cmd/cmd.go
- cmd/bee/cmd/deploy.go
- cmd/bee/cmd/start.go
- packaging/bee.yaml
- packaging/homebrew-amd64/bee.yaml
- packaging/homebrew-arm64/bee.yaml
- packaging/scoop/bee.yaml
- pkg/node/chain.go
- pkg/node/node.go
> chore: remove deprecated swap-endpoint and swap-deployment-gas-price

- pkg/accounting/accounting.go
- pkg/file/splitter/splitter_test.go
- pkg/postage/postagecontract/mock/contract.go
- pkg/retrieval/retrieval_test.go
- pkg/storageincentives/staking/mock/contract.go
> chore: fix some comments

- .github/CODEOWNERS
> feat: remove code owners

- pkg/storageincentives/agent.go
- pkg/storer/internal/reserve/reserve.go
- pkg/storer/sample.go
> chore: fix some typos in comment

- go.mod
- go.sum
- pkg/settlement/swap/chequebook/cashout_test.go
- pkg/settlement/swap/chequebook/chequebook.go
- pkg/settlement/swap/priceoracle/priceoracle.go
- pkg/settlement/swap/priceoracle/priceoracle_test.go
> chore: update abis

- pkg/node/node.go
- pkg/node/snapshot.go
- pkg/node/snapshot_test.go
- pkg/postage/listener/listener.go
Added tests for postage snapshot
> test: postage snapshot

- openapi/Swarm.yaml
- openapi/SwarmCommon.yaml
Set the acceptable values for `coin` param in `wallet/withdraw/:coin` endpoint.
closes #5125
> docs: fix acceptable values for coin param in wallet withdrawal

- pkg/accounting/accounting.go
- pkg/transaction/backendsimulation/backend.go
There is a [new function](https://pkg.go.dev/maps@go1.21.1#Copy) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: use maps.Copy for cleaner map handling

- pkg/api/util.go
Try to use better api reflect.TypeFor instead of reflect.TypeOf when we have known the type.
More info https://github.com/golang/go/issues/60088
> refactor: using reflect.TypeFor

- README.md
> fix(docs): update install instructions link
